### ISSUE TITLE
API returns no diffs when CLI shows file was added

### ISSUE THREAD

**Issue by tsykes-2020** [treeverse/lakeFS#1009]
version: 0.20.0

### Steps to reproduce
```
lakectl repo create lakefs://repo2 s3://my-bucket/repo2 -d master
lakectl branch create lakefs://repo2@b1 -s lakefs://repo2@master
lakectl fs upload lakefs://repo2@b1/test.jpg -s .\test.jpg
lakectl commit lakefs://repo2@b1 -m "added test file"
lakectl diff lakefs://repo2@b1 lakefs://repo2@master
 + added test.jpg

curl -u $ACCESS_KEY:$SECRET_KEY http://localhost:8000/api/v1/repositories/repo2/refs/b1/diff/master
```
### Expected result
one diff indicating test.jpg was added
### Actual result
`{"pagination":{"has_more":true,"max_per_page":1000,"results":0},"results":[]}`

The same result is obtained if the refs `b1` and `master` are reversed in the API query

**Comment by tsykes-2020** [comment]
Oh, I missed the result value `has_more: true`.
It looks like even though the `amount` parameter to `/repositories/{repository}/refs/{leftRef}/diff/{rightRef}` is optional, it defaults to zero.

`curl -u $ACCESS_KEY:$SECRET_KEY http://localhost:8000/api/v1/repositories/repo2/refs/b1/diff/master?amount=100` includes the added file as expected.

Should the `amount` parameter default to something other than zero if it is optional?

**Comment by itaiad200** [comment]
Thanks @tsykes-2020 - very nice catch!
Indeed the default value of the amount is set to zero.

Opening PR for the fix.

**Comment by itaiad200** [comment]
Hey @tsykes-2020 , version 0.21.0 contains the fix. Feel free to test it and reopen this issue if needed.
