### ISSUE TITLE
Documentation for import command should have an example for `docker run`

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1027]
It's somewhat different from other commands as needed arguments differ.

**Comment by nopcoder** [comment]
@itaiad200 this is not the case of running something like the following?

```shell
docker run --rm -it treeverse/lakectl ingest --from s3://bucket/optional/prefix/ --to lakefs://my-repo/ingest-branch/optional/path/
```

**Comment by itaiad200** [comment]
Not really since you need to use configuration for lakectl and that's missing here.
For `lakeFS import` the configuration is even more trickier for `docker run`.

**Comment by johnnyaug** [comment]
No more import command
