### ISSUE TITLE
UI is not loaded for `objects` tab when url ends with `/tree`

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1028]
Need to understand if it's only when we switch tabs or some other behaviour.

**Comment by arielshaqed** [comment]
Unable to reproduce: I can successfully move from "Objects" to "Changes" and back: by clicking "Objects", or by browser history buttons (backwards/forewards), or by re-typing the `tree` suffix.  All work.

Please re-open if it still happens, with more detailed instructions.
