### ISSUE TITLE
Add configuration through environment variables to lakectl

### ISSUE THREAD

**Issue by OriPekelman** [treeverse/lakeFS#1034]
lakefs configuration can take the form of environment variables with `LAKEFS_BLOCKSTORE_S3_REGION` style. 

For consistency lakectl should have the same facility IE have something like `LAKECTL_CREDENTIALS_ACCESS_KEY_ID`

Even more so as this enables using a secret store such as vault to grab secret values from.

**Comment by itaiad200** [comment]
Actually, @guy-har tested it and since we're using `viper` as our flags package, it is supported out of the box.
For example, `LAKECTL_CREDENTIALS_ACCESS_KEY_ID` could be used if you export it. It also overrides the value from the `lakectl.yaml` config file.
