### ISSUE TITLE
Get Started guide on empty repo doesn't appear

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#1082]
After creating a new repository, a "getting started" guide should appear in the UI (see <GetStarted> tag).

It does not appear anymore, probably because now 2 branches are created by default with each repository (master+import branch).

**Comment by shamikakumar** [comment]
@johnnyaug I'd like to work on this issue, do assign it to me

**Comment by johnnyaug** [comment]
Hey @shamikakumar, done. Thank you
