### ISSUE TITLE
PORT

### ISSUE THREAD

**Issue by capriciousduck** [treeverse/lakeFS#1142]
How do I change the listening port in the docker version? Is it possible to use PORT variable? I am trying to run lakefs on heroku and heroku, by default, assigns  random port. So lakefs should be able to grab port values from $PORT

How do I implement it? Is it possible?

**Comment by itaiad200** [comment]
Hey @capriciousduck , you can change the listening address with the `LAKEFS_LISTEN_ADDRESS` env var. The default value is `0.0.0.0:8000`. 
Let us know if you need further assistance here or on Slack, closing the issue for now.
