### ISSUE TITLE
pebble cache ref-count exit with an error

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1177]
pebble: cache (0xc00017c820) has non-zero reference count: 1

**Comment by arielshaqed** [comment]
Can you share some previous log-lines?

**Comment by arielshaqed** [comment]
Sample one of mine:
```INFO   [2021-01-11T09:45:39+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-8eec052e-de6d-497a-b3de-fcd3a0543080  1001]" duration="230.903µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
INFO   [2021-01-11T09:45:39+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo-trunk-8eec052e-de6d-497a-b3de-fcd3a0543080  1001]" duration="252.334µs" query="SELECT key, identity, data FROM graveler_staging_kv WHERE staging_token=$1 AND key >= $2 ORDER BY key LIMIT $3" service_name=postgres_staging_manager type=query
DEBUG  [2021-01-11T09:45:39+02:00]httputil/logging.go:77 httputil.DebugLoggingMiddleware.func1 HTTP call ended                               host="localhost:8000" method=POST path=/api/v1/repositories/foo/branches/trunk/commits request_id=e3c6e5a5-1bca-4a83-bad8-8727713c103e sent_bytes=214 service_name=rest_api status_code=201 took=29.481488ms user=foo
pebble: cache (0xc00ac18f00) has non-zero reference count: 1
```

would appreciate more, to hint if we're losing some against end-of-query perhaps.

**Comment by arielshaqed** [comment]
I am somewhat able to reproduce by concurrently running `s3 ls` and stopping the lakefs process.  When I restart the lakefs process after ~1 minute, the panic tends to occur.
An upcoming fix _seems_ not fail like this.

**Comment by arielshaqed** [comment]
Instructions how to reproduce (or, at least, how _I_ reproduced it):
1. Run lakeFS.
2. Determine its PID, call it `$LAKE_PID`.
3. Run `aws s3 ls ... & kill -STOP $LAKE_PID`.  This (usually) starts listing, but then hangs the lakeFS process so everything hangs.
4. Run `sleep 60; kill -CONT $LAKE_PID`.
5. Wait... when lakefs restarts, it panics.

With #1179 it doesn't panic.

**Comment by arielshaqed** [comment]
Note #1179 might not really fix an underlying issue.  Possibly we are missing a deref call for some reader.
