### ISSUE TITLE
Pyramid | removing file fails

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1183]
I am getting the following error when running lakeFS:

```
ERRO[0034] Removing file failed                          error="remove /tmp/experiment/ranges/tmp/experiment/ranges/repo/test/ba87edb6b02b7213af0f5fd928459d3b59ecf932d75b27d1280502e5c37a0349: no such file or directory" path=/tmp/experiment/ranges/tmp/experiment/ranges/repo/test/ba87edb6b02b7213af0f5fd928459d3b59ecf932d75b27d1280502e5c37a0349
```

**Comment by itaiad200** [comment]
Is it during the initialisation of lakeFS or during a normal operation? Do you have a more detailed stack trace perhaps?
Does the issue persist if you're using a cache dir which isn't under `/tmp`?

**Comment by guy-har** [comment]
I am still receiving this error therefore I am reopening this issue

**Comment by guy-har** [comment]
@arielshaqed I am still receiving this error therefore I am reopening this issue

**Comment by arielshaqed** [comment]
I am unable to reproduce.  However, the work on #1232 might be relevant:
1. Prior to #1234 pyramid would evict large-ish files immediately, so a lot more load on this code.  
2. #1233 adds lots of *lovely _logs_*!  @guy-har if you still manage to reproduce, could you please run it with trace logs on?

Meanwhile I shall try to use (1): I will try to reproduce and look for a specific bug in removal upon immediate eviction.

**Comment by guy-har** [comment]
@arielshaqed The Error I get is 
``` 
...no such file or directory" path=/tmp/experiment/ranges/tmp/experiment/ranges/repo/test/...
```

It looks like, when trying to remove files it is accidentally using the base directory twice, In my case   `/tmp/experiment/ranges`

After the Changes you mentioned it is hard to reproduce...
I forced it to happen using a smaller value for `DefaultCommittedLocalCacheBytes`

**Comment by arielshaqed** [comment]
> After the Changes you mentioned it is hard to reproduce...
> I forced it to happen using a smaller value for `DefaultCommittedLocalCacheBytes`

Thanks, that reproduces nicely.  Hope to have a PR soon.
