### ISSUE TITLE
diffing Graveler commits returns garbage results

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1218]
diffing 2 commits results in a diff containing garbled object names (showing a deleted file with a name that doesn't exist in either commit).

attachment includes 2 meta ranges (which in turn contain 1 range each). To reproduce, create a commit from each and diff the 2 commits.

[ranges.zip](https://github.com/treeverse/lakeFS/files/5826802/ranges.zip)

**Comment by arielshaqed** [comment]
Possibly related to #1217, as merge starts by `diff`ing.  Handle this one first?

**Comment by ozkatz** [comment]
Might be important for repro: one of the commits is the other's parent (i.e. in a 3-way diff, the merge base is one of them).

I believe it shouldn't matter which one

**Comment by arielshaqed** [comment]
It's actually really hard to reproduce this (blockchain is hard).  Could you please
```sql
select * from graveler_commits where meta_range_id in ('ec52ecbce076cc7ec27c8850e4938f03df11fc270d210f6892e9b57ad7b6ca08', 'c90e0adaf90b42c3d723e6a71a68960a5453bd2cefda4d6fafff06cc3cdfb6a9');
```
on your lakefsdb?

(Also, we probably want a "create a commit from this ranges-and-metaranges archive" command.)

**Comment by ozkatz** [comment]
Sure:

```
select * from graveler_commits where meta_range_id in ('ec52ecbce076cc7ec27c8850e4938f03df11fc270d210f6892e9b57ad7b6ca08', 'c90e0adaf90b42c3d723e6a71a68960a5453bd2cefda4d6fafff06cc3cdfb6a9');
-[ RECORD 1 ]-+-------------------------------------------------------------------
repository_id | repo1
id            | 9a1ba1094f5fe1241802d2dfbcf7dc30ac9d2ee169aeabc59a48f7294b998c0d
committer     | admin
message       | first commit
creation_date | 2021-01-17 22:35:46.980036+02
meta_range_id | ec52ecbce076cc7ec27c8850e4938f03df11fc270d210f6892e9b57ad7b6ca08
metadata      | {}
parents       | 
-[ RECORD 2 ]-+-------------------------------------------------------------------
repository_id | repo1
id            | ba23f5807964506dd61b92ac957e7a4d55a88bf00c2ffc4993b6c90435cd02f6
committer     | admin
message       | commit 2
creation_date | 2021-01-17 22:36:06.288256+02
meta_range_id | c90e0adaf90b42c3d723e6a71a68960a5453bd2cefda4d6fafff06cc3cdfb6a9
metadata      | {}
parents       | {9a1ba1094f5fe1241802d2dfbcf7dc30ac9d2ee169aeabc59a48f7294b998c0d}

```

**Comment by arielshaqed** [comment]
So I'm still unable to create the commits to reproduce.  Part of the issue is that revparsing a commit ID can result in a different commit ID, it "fixes" any issues in hashing.
Can you instead give a sequence of commands to generate this diff issue?  That would also help us add a test to nessie.

**Comment by ozkatz** [comment]
create a repo called "repo1" and on the master branch add the following object names:
- `jc/JumpCloud-aws-metadata.xml`
- `logo_large.jpg`
- `logo_large.txt`

commit changes.

upload another file to master, called `jc/arch.png`

commit again

diff the two commits. it should look like this:

```
lakectl diff lakefs://repo1@{ba23f5807964506dd61b92ac957e7a4d55a88bf00c2ffc4993b6c90435cd02f6,9a1ba1094f5fe1241802d2dfbcf7dc30ac9d2ee169aeabc59a48f7294b998c0d}
- removed logo_large.
```

**Comment by ozkatz** [comment]
@guy-har @arielshaqed reopening as I am still able to reproduce using the steps above.
