### ISSUE TITLE
lakeFS tooling for working with Graveler

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1222]
Tooling that will help capture and restore lakeFS state or information related to Graveler repositories:

- Export/import specific commit. Export should capture the commit information, meta range, and ranges files. Import the commit information to an existing branch.

**Comment by ozkatz** [comment]
To clarify, we're talking about importing/exporting *metadata* and not the data represented by said commits

**Comment by ozkatz** [comment]
@nopcoder is there more work we should do here? I think refs-dump/refs-restore/cat-sst cover all the bases.. what's missing?

**Comment by nopcoder** [comment]
Agree I think with the latest plumbing commands we are covered.
