### ISSUE TITLE
Graveler | Slow commands

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1240]
When running lakeFS an EC2 instance of type `t2.xlarge` with a large dataset
I noticed that it takes too much time for some commands to run.

commit (after adding one file to the beginning) - ~3 minutes
Diff to the one file change - ~6 minutes 
Merge the change -  ~9 minutes

**Comment by ozkatz** [comment]
@guy-har does this reproduce after the cache fixes maxe by @arielshaqed?

**Comment by arielshaqed** [comment]
> @guy-har does this reproduce after the cache fixes made by @arielshaqed?

I would *not* expect these fixes to affect performance greatly.  #1244 _maybe_, but probably not by a lot.  #1245 not at all.

However I _would_ want to be sure that we are after #1234.  The numbers are about right for "no caching at all".  If we can still reproduce, can you attach logs at level TRACE?  For multi-minute operations the added slowdown should be minor.

**Comment by arielshaqed** [comment]
Closed by #1267.
