### ISSUE TITLE
Range manager exists uses cache to verify that metarange exists

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1242]
Graveler range manager calls the cache to check if 'id' exists.
We use this call to verify that a meta-range id exists while adding a commit.
My concern is that we can't assume that the data we just wrote will be available in the cache - the manager can use the cache for a quick check but still check the adapter/fs to the meta-range.
 
```go
func (m *RangeManager) Exists(ctx context.Context, ns committed.Namespace, id committed.ID) (bool, error) {
   return m.cache.Exists(ctx, string(ns), id)
}
```

**Comment by arielshaqed** [comment]
I don't believe this is actually true, it's more a matter of horrible naming (sorry).  What *really* happens is that a sstable Cache is created that directly tests "exists" on the backing store, https://github.com/treeverse/lakeFS/blob/93e8ebca846a709f22ba1134c0a4dcd1fc9e0c38/graveler/sstable/cache.go#L71.

Re-assigning in the hope you agree and we can close.  Or (even better!) suggest less confusing naming!

**Comment by nopcoder** [comment]
yes, the naming is very confusing - as cache.Exists doesn't really check the cache.
will have to align the noCache implementation to this spec and close this one.
