### ISSUE TITLE
graveler allows merge with no changes

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1251]
graveler should return error in case of merge that has no changes
same as MVCC return ErrNoDifferenceWasFound

**Comment by johnnyaug** [comment]
Also, a revert with no changes should return a similar error

**Comment by arielshaqed** [comment]
# Why is this a release blocker?

Being able to merge repeatedly causes long-term damage to the user repository.  It is an easy mistake to make, and hard to recover from.
