### ISSUE TITLE
UI: comparing commit with itself returns  error Branch not found

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1286]
![Screen Shot 2021-01-21 at 21 17 24](https://user-images.githubusercontent.com/60321938/105400786-1249a780-5c2e-11eb-9a4e-1f58683b33b2.png)

**Comment by shamikakumar** [comment]
Could I work on this issue ?

**Comment by itaiad200** [comment]
Hey @shamikakumar ! It's yours - assigning it to you. 

Some tips to get you started: A validation to the API is probably needed. Returning an empty diff list when source and target branch match. If the API validation exists and the UI error persists, then I would check the UI for the error.
