### ISSUE TITLE
Post-Merge hooks (Export) are not being triggered after revert

### ISSUE THREAD

**Issue by gilandose** [treeverse/lakeFS#1287]
Say I have commit X on master followed by Y with continuous export set up Y is exported but then I revert the commit. The export is not updated to reflect X again.

**Comment by itaiad200** [comment]
@gilandose Indeed. 
Post-Merge hooks (where the export is configured) are not being called when a commit is reverted.

I find it hard to believe this was planned, desired behaviour should be to always export the current state of master in lakeFS. We will debug further and fix during next week.

**Comment by ozkatz** [comment]
Will be handled as part of #1369 - as export is being redone on top of Apache Spark. Closing for now.
