### ISSUE TITLE
Commit Identity function isn't consisted

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1291]
The flow

```go
commitID := graveler.CommitExistingMetaRange(metarangeID)
graveler.UpdateBranch(branch, commitID)
```

is broken since UpdateBranch uses RevParse which seems to output different result for commitID.

**Comment by ozkatz** [comment]
Not sure how it have ever worked.. Initial commit id represents no parents. When adding it to a brach a parent is set, resulting in a different ID. 

We should consider changing the API to accept either a list of parents or better yet, a branch, to avoid possible races.

**Comment by itaiad200** [comment]
IIUC `UpdateBranch` isn't `AddCommitToBranch` hence change its parents.
`UpdateBranch` should simply point the branch to that commit without changing it.
The problem starts where you pass the commitID as a Ref to `UpdateBranch` and it calls `RevParse` which outputs a different commitID which doesn't exist.
