### ISSUE TITLE
rocks: TierFS should store sstables directly under `committed.block_storage_prefix`

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1293]
Per the design, sstables should be stored directly under `committed.block_storage_prefix` a-la `.git/objects` instead of the added hierarchy we currently have (with `$prefx/ranges` and `$prefix/meta-ranges`.

  #1201 was a prerequisite and is done.

**Comment by arielshaqed** [comment]
@itaiad200 I think at the time you disagreed with this?

**Comment by itaiad200** [comment]
I remember disagreeing but I don't remember having a strong argument.

Maybe just a little concern that any collisions between a `metarange` id and a `range` id will have a catastrophic consequence. But I can't come up with an example where they might collide, other than the empty table on both and that would be ok.

**Comment by arielshaqed** [comment]
> Maybe just a little concern that any collisions between a `metarange` id and a `range` id will have a catastrophic consequence. But I can't come up with an example where they might collide, other than the empty table on both and that would be ok.

Well, let's be safe not sorry!  We have metadata on each SSTable, we can read it on open and ensure we got the correct type.  Would that work for you?

**Comment by ozkatz** [comment]
In that case, perhaps add the object type to the hash. Git does this as well

**Comment by itaiad200** [comment]
@arielshaqed That won't work. When you store the second created-id in the blockstorage it will override the other one. Fetching it and validating for the type will help identify, but won't prevent overriding.

**Comment by ozkatz** [comment]
@itaiad200 @arielshaqed so by this discussion, definition of done is:
1. removal of hierarchy under `committed.block_storage_prefix`
2. sstable content address should include the object type to avoid collision of empty spaces (btw we already [do this to commits](https://github.com/treeverse/lakeFS/blob/master/graveler/graveler.go#L135))

**Comment by arielshaqed** [comment]
> @arielshaqed That won't work. When you store the second created id in the blockstorage it will override the other one. Fetching it and validating for the type will help identify, but won't prevent overriding.

If 2 different files can have the same ID then content-addressed storage won't work.  So different in-file metadata\ should be part of the digest.   As @ozkatz says:

> [...]
>     2. sstable content address should include the object type to avoid collision of empty spaces (btw we already [do this to commits](https://github.com/treeverse/lakeFS/blob/master/graveler/graveler.go#L135))

but that gives a different property than the one I was looking for.  Keeping metadata in the file is both more git-like _and_ allows better debuggability - a file cannot be mis-parsed just because its ID popped up in the wrong place.

We want *both* properties, I think.

**Comment by ozkatz** [comment]
@itaiad200 @arielshaqed I want to make the requirements explicit. Do you both agree this is the list?
1. removal of hierarchy under `committed.block_storage_prefix`
2. sstable content address should include the object type to avoid collision of empty spaces

If not please state exactly what you think needs to change so this could be worked on.

**Comment by arielshaqed** [comment]
Render onto Oz what is Oz' PR.
