### ISSUE TITLE
Merge operation should return a summary of the merge

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#1300]
In the MVCC implementation, the cataloger would return a summary of the merge. The CLI would then print this summary. The summary includes the number of added, deleted and changed files.

Decide whether this feature is needed, and if so, implement it for the Rocks catalog.

**Comment by arielshaqed** [comment]
I think it should happen, and I will do it.  Knowing what happened in a merge is really useful, particularly when something goes wrong :-)
