### ISSUE TITLE
Unifying format of lakectl sub-commands

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#1305]
### Problem
Today, lakectl sub-commands are not aligned in the way they accept lakeFS references.
For example:
- `lakectl merge` and `lakectl diff` each accept two arguments with the fully qualified lakefs uri (e.g. lakefs://example-repo@commit-ref). 
- `lakectl revert` accepts one fully qualified uri and one "bare" reference (e.g. a1b2c3)
- `lakectl reset` accepts one fully qualified uri, and one "bare" reference as a flag rather than an argument.

The argument formats should be predictable and consistent between the commands.

This problem stems from the fact that lakeFS has no concept of HEAD. In git, commands which operate in the context of a branch don’t need to accept the branch as an argument because the HEAD is already set to this branch. Similarly, commands which operate in the context of a repository (for example, creating a branch), already know which repository they’re in because git runs in the context of a directory which is the repository.

In lakeFS, the need to mention the repo and branch in every command may cause some frustration. Some commands require a fully-qualified URI, and some don’t. Also, some commands require redundant information, like the repository name twice (e.g. `lakectl diff lakefs://my-repo@master lakefs://my-repo@my-branch`).

### Suggestion
Use flags `-r` and `-b` to state the repo/branch for the context of the command (if needed).
All other arguments should be as similar to git as possible.
The `lakefs://` scheme will only be used for `lakectl fs` commands.

#### Examples
Create a repo:
```
lakectl repo create my-repo
```

Create a branch:
```
lakectl branch create -r my-repo my-branch
```
Get uncommitted changes:
```
lakectl diff -r my-repo -b my-branch
```

Changes from ref to branch (should include uncommitted):
```
lakectl diff -r my-repo -b my-branch d4e5f6
```

Diff between two refs (doesn't include uncommitted):
```
lakectl diff -r my-repo a1b2c3 d4e5f6
lakectl diff -r my-repo a1b2c3 my-branch
```

Merge branch into master:
```
lakectl merge -r my-repo -b master my-branch
```
Revert commit from branch:
```
lakectl branch revert -r my-repo -b my-branch a1b2c3
```

In the future, we may want to introduce a local HEAD which will be saved somewhere on the machine running lakectl. In case this hypothetical HEAD is set, the `-r`/`-b` flags will not need to be specified.

**Comment by johnnyaug** [comment]
@ozkatz @guy-har @itaiad200 @nopcoder, moved the document here for our discussion

**Comment by ozkatz** [comment]
This resulted in milestone https://github.com/treeverse/lakeFS/milestone/8 - closing in favor of individual tasks tracked there. Thanks!
