### ISSUE TITLE
Migrate mvcc to rocks progress

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1326]
A single commit migration from MVCC to Rocks can take a long time. For better UX we should enable progress like we do with import.

**Comment by arielshaqed** [comment]
@ozkatz not clear: are we still planning to do this after pulling #1347?  If we are, it will need to be on a side branch.

**Comment by ozkatz** [comment]
Yes, I think we talked about this - we don't have a concrete enough reason to invest in this without someone specifically requesting it. Closing for now.
