### ISSUE TITLE
Pass JWT tokens on "Authorization: Bearer" header

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1362]
We use the non-standard `X-JWT-Authorization` header to carry tokens.  We should use the `Bearer` scheme on the `Authorization` header.  Doing so will make our code more standard, easier for external readers and tools and understand and reason about, and match more examples on The Internew.

## What header to use?

The [JWT website] says:
> Whenever the user wants to access a protected route or resource, the user agent should send the JWT, typically in the Authorization header using the Bearer schema. The content of the header should look like the following:
>
>     Authorization: Bearer <token>
and the RFC has normative wording to that effect IIRC.

go-swagger has an example using "composed authorization" that includes JWT; see [`examples/composed/auth/swagger.yml:60`](
https://github.com/go-swagger/go-swagger/blob/22d967c1be3fb8d5c711ea3a46883745fb0ea728/examples/composed-auth/swagger.yml#L60).

## Why change?

1. Easier to write clients.
2. Easier to understand the server.
1. Easier for third-party tools (e.g. intercepting proxies, _sigh_) to verify stuff.  (This third is a _bad idea_, but we're a data lake tool and we shouldn't have opinions on whether internal firewalls should utterly wreck security by performing MITM attacks on internal clients...).

**Comment by arielshaqed** [comment]
:arrow_right: @nopcoder  - I think you implemented this, right?

**Comment by nopcoder** [comment]
We kept backward compatibility - so leave this one open, we can address it and remove the old header support.
