### ISSUE TITLE
General block adapter tests

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1386]
Write a single test suite that will test the block adapter.
Locally we are not connecting to real block storage and we need a way to test the capabilities we expect from our underlying storage.
Buy building a test suite that works using the block adapter interface, we can test each implementation as part of integration tests and verify that current and new block adapter works as expected.

**Comment by itaiad200** [comment]
We have it now, although it's minimal. We shall increase coverage as we go.
