### ISSUE TITLE
Disallow commit without a message

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1395]
Should block at least from the CLI/UI a commit without a message

**Comment by DataDavD** [comment]
Not sure how quick I can get this done, but I'd like to take a crack at this one my PR for Issue #2190 is complete. Is that fine?

Thanks in advance.

best,
dd

**Comment by talSofer** [comment]
Hi @DataDavD! thanks for your collaboration, we appreciate it!

@lynnro314 will be working on this issue, so unfortunately we cannot assign it to you. but please do continue commenting on issues you would want to address.

**Comment by DataDavD** [comment]
hey @talSofer no problem at all; thanks for the very fast (and detailed) response. I'm already assigned to 2 other issues anyways 😃

**Comment by Jonathan-Rosenberg** [comment]
Hey @nopcoder and all,
Just been assigned to this issue and been wondering if there should be an enforced practice of writing meaningful commits... Although I definitely agree with this practice, other users might not. 
There's a middle ground here which we can use which is adding a `--allow-empty-message` like flag that will state the intention of an empty commit. 
What do you think?

**Comment by guy-har** [comment]
Hey @Jonathan-Rosenberg,
I like your suggestion, I believe this is a case we should behave like git.
Supporting the `--allow-empty-message` sounds like a great solution
