### ISSUE TITLE
lakeFS live stage environment

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1399]
Running lakeFS stage environment, using cloud storage and postgres, loaded with close to real metadata.

The requirement is to have such an environment on a cloud provider and an easy way to deploy the current latest code to that environment.
The automated process should enable an easy way from getting the current green master branch to the running environment loaded and configured to serve.

**Comment by nopcoder** [comment]
Think we can close as having a working stage environment based on the current master we currently have on a different project.

**Comment by guy-har** [comment]
@nopcoder, can we close this?
