### ISSUE TITLE
Decide on Spark client implementation language and order of versions support

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1427]

**Comment by arielshaqed** [comment]
Draft form: https://docs.google.com/forms/d/e/1FAIpQLSd8IB2BZrq9JP0lPr78WUnvprGG-UQItmwi3CSrouocafL0qA/viewform

**Comment by guy-har** [comment]
Looks great!
Short and clear.
Maybe @YaelRiv could help with the design (not that important, but could be nice)

Do we have any way to count users that came and did not submit? If not, maybe we should redirect through our webpage. I think it might be useful.

**Comment by nopcoder** [comment]
Maybe a link to a design or the idea of the use-cases what we can do with this client, or why we suggest building such a client.

**Comment by arielshaqed** [comment]
> Maybe a link to a design or the idea of the use-cases what we can do with this client, or why we suggest building such a client.

This would be great, but I think it would take 3-4 days to write & review something like it.

> Do we have any way to count users that came and did not submit? If not, maybe we should redirect through our webpage. I think it might be useful.

It's a Google form, you cannot count.  I think it would be over-engineering -- I strongly believe we will get fewer than 10 responses in total.

**Comment by ozkatz** [comment]
> This would be great, but I think it would take 3-4 days to write & review something like it.

I think it's worth it

**Comment by arielshaqed** [comment]
No significant traction (low single-digit responses) on the form.  We are going with a Spark client written in *Scala*.  It should support Spark 2.4.7 _and_ Spark 3.0.x.
