### ISSUE TITLE
Cache GetRepository, GetCommitByPrefix and GetCommit

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1458]
All these are in the critical path of most requests and are prime candidates for caching.  Currently 50% of the time is spent on those for random reads.

To generate random read load:

`lakectl abuse random-read lakefs://repo1@a67a8fa0cfc598859a46ef652800f9d4e2d70db41a78c27f1500193118156068 --amount 1000000 --from-file ./randomfiles --parallelism $(nproc)`

While executing, generating a pprof profile using `http://<LAKEFS ADDR>/_pprof` and download a profile.

Commenting out the DB requests from these functions and returning a static repository/commit object increased throughput from ~11.5k r/s to ~18k r/s

**Comment by itaiad200** [comment]
@ozkatz Closing as I think this is done. Feel free to reopen.
