### ISSUE TITLE
Hooks: UI to list and output actions and hooks

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1480]
- [ ] Actions runs tab - listing all, branch or commit
- [ ] Each run in the Actions tab cloud be clicked and render the same information found in our ctl describe
- [ ] Commit completion - success or failure should disable the action information associated and link to the run in the Actions tab
- [ ] Merge completion - success or failure should disable the action information associated and link to the run in the Actions tab

**Comment by itaiad200** [comment]
completed with #1584
