### ISSUE TITLE
Multi-repository support for Spark/Scala code

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1481]
Decide how to share *.proto files and swagger.yml between the main lakeFS repository and client repositories.

**Comment by arielshaqed** [comment]
What do other people do?
1. https://www.bugsnag.com/blog/libraries-for-grpc-services says "just build and publish a separate library for each language" -- overkill.
2. https://medium.com/namely-labs/how-we-build-grpc-services-at-namely-52a3ae9e7c35 says to keep proto def files in a single repo and then add a bunch of tooling.
3. https://medium.com/building-ibotta/building-a-scaleable-protocol-buffers-grpc-artifact-pipeline-5265c5118c9d is already on top of a monorepo; still use e.g. lerna to manage their subdirectories there.  (Not needed by us, plus we already decided to do multirepo for reasons)

**Comment by arielshaqed** [comment]
4. https://github.com/stormcat24/protodep _is_ a "[d]ependency tool for Protocol Buffers IDL file (.proto) vendoring tool".  Looks good.  But needs 3rd-party users to depend on this tool, not very active.

**Comment by arielshaqed** [comment]
5. https://stackpulse.com/blog/grpc-in-practice-directory-structure-linting-and-more/ is single-language (Go), so protos are exported as Go modules.

**Comment by arielshaqed** [comment]
6.https://buf.build/ is "join our waitlist" status.  Trying to be npmjs-for-protos.

**Comment by arielshaqed** [comment]
7. DIY.  E.g., publish to some S3 bucket with version (or revision,, for snapshots...) identifier as part of the path.  Add handwritten tooling to publish and fetch.  This requires writing _some_ of a VCS, but hopefully one simpler than git.
8. git submodules.  While they have a bad rap, part of it is because they solve a hard problem (multi-repo integration).

**Comment by arielshaqed** [comment]
8. Do nothing, just keep on copying proto definitions from treeverse/lakeFS to treeverse/spark-client until we have a better user story.  This is actually somewhat convenient for Treeverse (can forget to update the code) _until_ a customer explicitly requests a new field.  Field discovery will also be harder for fields that never appear in the dataframe in Spark-SQL.

**Comment by arielshaqed** [comment]
Back to single repo as of #1621 .
