### ISSUE TITLE
Require running tests with secrets for external pull requests

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1484]
Branch protection on the master branch doesn't enforce "Run latest lakeFS app (rocks)" as it requires secrets. On external pull-requests, we currently don't have access to secrets.

**Comment by itaiad200** [comment]
Github limitation of secrets from fork PRs is gone:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

BUT: There still isn't a safe and easy way of allowing external PRs to run after approving by some reviewer. Allowing external PRs to run with secrets is vulnerable to malicious code that can steal them.
