### ISSUE TITLE
PORT Variable

### ISSUE THREAD

**Issue by capriciousduck** [treeverse/lakeFS#1485]
How to create a lakefs server using binary version by passing $PORT variable?

**Comment by ozkatz** [comment]
If you wish to configure the port lakeFS will listen on via an environment variable, you can use the LAKEFS_LISTEN_ADDRESS environment variable like so:

```sh
export LAKEFS_LISTEN_ADDRESS="0.0.0.0:8765"
lakefs run
```

see the [documentation reference](https://docs.lakefs.io/reference/configuration.html#reference) for for more information, as well as [how to configure lakeFS with environment variables](https://docs.lakefs.io/reference/configuration.html#using-environment-variables)

**Comment by ozkatz** [comment]
closing for now, if you encounter any issues please reopen. for help troubleshooting it is usually more effective to [reach out on Slack](https://join.slack.com/t/lakefs/shared_invite/zt-ks1fwp0w-bgD9PIekW86WF25nE_8_tw)
