### ISSUE TITLE
DirtyBranch renders as internal server error

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1547]
Returning ErrDirtyBranch, currently part of Merge and Revert rendered as HTTP status code 500 with an internal server error.
It is a UX that the end-user will have a hard time understanding the root cause.

**Comment by ozkatz** [comment]
Actually, a worse side-effect of this is that it happens in the S3 gateway as well. Things like Kafka Connect or other managed ingestion systems might not know how to handle this properly

**Comment by nopcoder** [comment]
Not sure automated tools can handle it - for merge, you will need to clean your stage or commit.
But between the status code and the error message, it is a big difference as the first log with the error should help you understand how to address the issue.

**Comment by ozkatz** [comment]
> Actually, a worse side-effect of this is that it happens in the S3 gateway as well. Things like Kafka Connect or other managed ingestion systems might not know how to handle this properly

misunderstood this issue - please disregard my comment :)
