### ISSUE TITLE
Hooks: UI for information after merge

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1571]
Successful or failed merge because of an Actions execution should enable the end-user to understand what was running and or failed from on the last merge.

**Comment by itaiad200** [comment]
When trying to merge and an hook fail:
![image](https://user-images.githubusercontent.com/9861474/126901747-a30b9124-c532-43f5-929f-6831b3c60cb7.png)

From the Actions tab:
![image](https://user-images.githubusercontent.com/9861474/126901773-a2d28459-bb3d-483f-95a5-03cad2a35206.png)

Already done.
