### ISSUE TITLE
Docs versioning

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1612]
Docs always reflect master, they are not released together with the binaries.

This has several implications, including:
1. User running an older version of lakeFS might not find the documentation she needs.
2. It is impossible to coordinate a release with its documentation.

**Comment by nopcoder** [comment]
Gathering requirements and addressing the above as part of Gitbook evaluation.

**Comment by nopcoder** [comment]
Documentation will be updated in two workflows:
1. latest - changes going into `master` branch will publish the documentation to docs-lakeFS root folder and will be served as 'Latest'
2. release - documentation of the published release will be pushed into docs-lakeFS `/<version>` folder and will update the `/versions.json` file there. Once the file is updated the dropdown will be populated with the version number and the users can switch between the Latest and the published version.
