### ISSUE TITLE
When viewing files by commit ref, Delete option should be disabled

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1622]

**Comment by shamikakumar** [comment]
Can I work on this issue ?

**Comment by itaiad200** [comment]
All yours @shamikakumar .
Adding some information: In the below image, when viewing the objects by commit ref, Delete button should not be displayed.
![image](https://user-images.githubusercontent.com/9861474/111639533-03cdd580-8804-11eb-9e5f-92f8cff03390.png)
