### ISSUE TITLE
Outdated example for the branch rollback use-case

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1637]
- The example in https://docs.lakefs.io/usecases/production.html -> Continuous Deployment -> Rollback is using the 'reset' command instead of 'revert'. 
- After changing the example to use revert the example graph needs to change to make intuitive use of the supported revert capabilities. i.e. rollback a single commit instead of multiple commits.

**Comment by johnnyaug** [comment]
Opened followup issue #2708
