### ISSUE TITLE
Entry's address to hold full path

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1650]
Entry's address has 2 possible formats:
1. Full block store address, if the item was imported.
2. Relative path to the storage namespace, in case it was created by the cataloger.

Support for the 2 formats must stay, since sstables are already written with the 2 options.
But moving forward, it's much easier to always store the full address path, so that clients can read it directly from the object store, without applying more logic to it.
Any relative address path, will simply be concatenated to the repo's storage namespace, since that was the logic when the addresses were relative.

**Comment by arielshaqed** [comment]
I think there are two distinct issues here:

* stored (DB/Rocks) format: what is actually stored inside graveler (or other DBs that are used internally).
* wire ("client") format: what clients receive over the wire, and what is presented on the API.

I believe that the second is far more valuable than the first.  Indeed you write that:

> Support for the 2 formats must stay, since sstables are already written with the 2 options.

^^ applies _only_ to the stored format.

I can see few (if any) advantages to having both options on the wire, and even fewer to presenting both to the client.  So mega-:+1: from me on that.  This is also an enormously cheaper change.

I _do_ see advantages to storing relative names internally.  E.g., consider some future "git remote"-based replication: pushing between two lakeFS instances, _where data are also replicated along_.  Allowing both pathname formats (absolute and relative) means that we preserve computed IDs; it also makes the actual push (much) simpler with many more usable tools.  So I am quite wary of _storing_ full pathnames.  We need to explore more before we decide to do *that*.

**Comment by arielshaqed** [comment]
#1651 changes "stored" format; I like it less than something that would change what the client sees.  In particular, note that it doesn't help write a simpler client unless we backfill all existing installations or tell them to throw away all of their data.

**Comment by itaiad200** [comment]
What the client "sees" depends on where it gets its information from.
If it reads sstables and tries to do something with the underlining data (ahm `export`), then presenting the full path from the API does no good. It must change on the Entry level for supporting that.

Regarding the client logic, I agree that we'll always have to handle the relative path option since sstables were already written. But the logic is fairly simple IMHO: `fullpath -> use it`, `relativePath -> do storageNS + relativepath`. 

Anything else, like objects address patterns per repo is much more expressive and it will require the client to know more as it keeps evolving, not less.

**Comment by arielshaqed** [comment]
> What the client "sees" depends on where it gets its information from.
> If it reads sstables and tries to do something with the underlining data (ahm `export`), then presenting the full path from the API does no good. It must change on the Entry level for supporting that.
> 
> Regarding the client logic, I agree that we'll always have to handle the relative path option since sstables were already written. But the logic is fairly simple IMHO: `fullpath -> use it`, `relativePath -> do storageNS + relativepath`.
> 
> Anything else, like objects address patterns per repo is much more expressive and it will require the client to know more as it keeps evolving, not less.

We seem to agree that:

1. All clients will need to handle the existing format in the foreseeable future (until we add version numbers and make a breaking change).
2. Clients should always expose full pathnames.

I think that we seem to disagree about how to support this.  I don't see how writing only full paths helps if:

> Regarding the client logic, I agree that we'll always have to handle the relative path option since sstables were already written. But the logic is fairly simple IMHO: fullpath -> use it, relativePath -> do storageNS + relativepath.

Note that the above means we _document_ what lives in files, and/or that we _expose only full paths_ from a client.  This is true regardless of whether we change the stored representation.

I think that we also disagree about the advantages of the current format, regarding moving files across installations.

**Comment by itaiad200** [comment]
> Note that the above means we document what lives in files, and/or that we expose only full paths from a client. This is true regardless of whether we change the stored representation.

Not sure I follow. What do you mean by documentation? where? And clients can expose both relative/full paths, by using the repo's storage namespace regardless of whether we change the stored representation or not.

> I think that we also disagree about the advantages of the current format, regarding moving files across installations.

I understand the tradeoff here, but haven't come with a way to get both. Using the discussed `repo-object-path-pattern` is doable. But it means that a repo will have to stick to a certain pattern (lakeFS server will have to keep supporting all possible object paths), or do a very costly migration.

**Comment by itaiad200** [comment]
Decided to stay with the current implementation.
Clients will do for the meantime `fullpath -> use it`, `relativePath -> storageNS + relativepath`.
