### ISSUE TITLE
lakectl command line testing

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1657]
Testing the functionality of lakectl using scripting will verify the client and the api functionality

**Comment by arielshaqed** [comment]
Speaking as a disinterested observer, a truly great open-source tool that helps test CLI clients with a server is https://github.com/arielshaqed/specshell.  It just gives you a shell that your test can control.  At Binaris we used it to do CLI testing.  Think of it as like Expect, but easier to use (and lets you code in JavaScript not TCL).

**Comment by nopcoder** [comment]
@itai-david can we close this one?

**Comment by itai-david** [comment]
@nopcoder - Absolutely. We got this one done, and we got open issues for specific missing prats. Closing
