### ISSUE TITLE
Spark/Hadoop FileSystem support: (optionally) support "fake directories"

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1691]
Add *minimal* support on the server side and in the Spark client to allow faking directories in Spark:

* Optional flags when creating an entry (both parts):
  - one disallows creating an entry with a path that is a suffix of another one.
  - one disallows creating an entry with a path that is a prefix of another one.
* Create a file by setting both.
* `mkdir` by setting only the second.

**Comment by johnnyaug** [comment]
@nopcoder, should this also be closed?

**Comment by nopcoder** [comment]
> @nopcoder, should this also be closed?

yes, closing. thanks

**Comment by nopcoder** [comment]
Re-open. thought this issue is about the directory support we implemented as part of Hadoop lakefs. But this one is about the lakefs server side support.

**Comment by arielshaqed** [comment]
Not worth doing compared to LakeFSOutputCommitter, especially given difficulty of ensuring compatibility with S3A semantics.
