### ISSUE TITLE
Expand Documentation on "self-hosted" Buckets

### ISSUE THREAD

**Issue by mpldr** [treeverse/lakeFS#1694]
Hello, I'd like to expand the documentation on "self-hosted" instances. But for this, it would probably be beneficial if I got it to work first.

My issue is that I cannot access it through rclone. I am pretty sure that the issue lies with my nginx-config but I can't really spot it.

LakeFS is running on docker as suggested in the example.

Here is my nginx config:
```conf
	server {
		listen 443 ssl http2;
		listen [::]:443 ssl http2;
		server_name s3.my-domain.de
		server_name ~^(?<bucket>[a-zA-Z0-9\-_]+)\.s3\.my-domain\.de$;

		# … SSL Stuff

		if ($bucket = false) {
			return 301 https://my-domain.de/s3-note;
		}
		
		location / {
			proxy_http_version     1.1;
			proxy_set_header       Host $bucket.s3.my-domain.de;
			proxy_set_header       Authorization '';
			proxy_hide_header      x-amz-id-2;
			proxy_hide_header      x-amz-request-id;
			proxy_hide_header      Set-Cookie;
			proxy_ignore_headers   "Set-Cookie";
			proxy_buffering        off;
			proxy_intercept_errors on;
			proxy_pass             http://127.0.0.1:8000/$uri;
		}
	}
```

The rclone error Message is:
```shell
$ rclone copy . storage://testbucket/master -P
2021-03-31 10:24:42 ERROR : : error reading destination directory: RequestError: send request failed
caused by: Get "/": stopped after 10 redirects
```

**Comment by poldi1405** [comment]
Unfortunately, I cannot debug further because I have no access to the request rclone executes.

**Comment by poldi1405** [comment]
I also found `/api/v1` but that does not work either.

**Comment by johnnyaug** [comment]
Hey @poldi1405, thank you for opening this issue. 
You are welcome to join our [Slack](https://join.slack.com/t/lakefs/shared_invite/zt-ks1fwp0w-bgD9PIekW86WF25nE_8_tw), we can debug further there, and update the issue here later.

Alternatively, please add the following information (omitting any sensitive information, if any):
* The lakeFS run configuration (or docker-compose file).
* The rclone configuration file.
* Logs from the lakeFS container.

**Comment by poldi1405** [comment]
<details>
<summary>docker-compose.yml</summary>
<pre>
<code>
version: '3'
services:
  lakefs:
    image: "treeverse/lakefs:latest"
    ports: ["8000:8000"]
    links: ["postgres"]
    environment:
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "some junk"
      LAKEFS_DATABASE_CONNECTION_STRING: postgres://lakefs:lakefs@postgres/postgres?sslmode=disable
      LAKEFS_BLOCKSTORE_TYPE: local
      LAKEFS_BLOCKSTORE_LOCAL_PATH: /home/lakefs
      LAKEFS_GATEWAYS_S3_DOMAIN_NAME: s3.local.lakefs.io:8000
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/lakefs", "run"]
    volumes:
      - /storage/slab1/lakefs:/home/lakefs/slab1
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
    volumes:
      - ./database:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
</code>
</pre>
</details>

<details>
<summary>rclone.conf</summary>
<pre>
<code>
[storage]
type = s3
provider = AWS
env_auth = false
access_key_id = bonk
secret_access_key = a long string
endpoint = https://s3.my-domain.de
</code>
</pre>
</details>

<details>
<summary>container-log (suspiciously empty)</summary>
<pre>
<code>
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="lakeFS run" func="pkg/logging.(*logrusEntryWrapper).Infof" file="build/pkg/logging/logger.go:115" version=0.33.1
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="connecting to the DB" func=pkg/db.ConnectDBPool file="build/pkg/db/connect.go:54" conn_max_lifetime=5m0s driver=pgx max_idle_conns=25 max_open_conns=25 uri="postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialized DB connection" func=pkg/db.ConnectDBPool file="build/pkg/db/connect.go:73" conn_max_lifetime=5m0s driver=pgx max_idle_conns=25 max_open_conns=25 uri="postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="connecting to the DB" func=pkg/db.ConnectDBPool file="build/pkg/db/connect.go:54" conn_max_lifetime=5m0s driver=pgx max_idle_conns=25 max_open_conns=25 uri="postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialized DB connection" func=pkg/db.ConnectDBPool file="build/pkg/db/connect.go:73" conn_max_lifetime=5m0s driver=pgx max_idle_conns=25 max_open_conns=25 uri="postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="connecting to the DB" func=pkg/db.ConnectDBPool file="build/pkg/db/connect.go:54" conn_max_lifetime=5m0s driver=pgx max_idle_conns=25 max_open_conns=25 uri="postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialized DB connection" func=pkg/db.ConnectDBPool file="build/pkg/db/connect.go:73" conn_max_lifetime=5m0s driver=pgx max_idle_conns=25 max_open_conns=25 uri="postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialize blockstore adapter" func=pkg/block/factory.BuildBlockAdapter file="build/pkg/block/factory/build.go:38" type=local
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialized blockstore adapter" func=pkg/block/factory.buildLocalAdapter file="build/pkg/block/factory/build.go:82" path=/home/lakefs type=local
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialize blockstore adapter" func=pkg/block/factory.BuildBlockAdapter file="build/pkg/block/factory/build.go:38" type=local
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialized blockstore adapter" func=pkg/block/factory.buildLocalAdapter file="build/pkg/block/factory/build.go:82" path=/home/lakefs type=local
lakefs_1    | time="2021-03-31T07:40:39Z" level=info msg="initialized Auth service" func=pkg/auth.NewDBAuthService file="build/pkg/auth/service.go:180"
lakefs_1    | time="2021-03-31T07:40:40Z" level=info msg="initialize OpenAPI server" func=pkg/api.Serve file="build/pkg/api/serve.go:42" service=api_gateway
lakefs_1    | time="2021-03-31T07:40:40Z" level=info msg="initialized S3 Gateway handler" func=pkg/gateway.NewHandler file="build/pkg/gateway/handler.go:121" s3_bare_domain="s3.local.lakefs.io:8000" s3_region=us-east-1
lakefs_1    | time="2021-03-31T07:40:40Z" level=info msg="starting HTTP server" func=cmd/lakefs/cmd.glob..func9 file="cmd/run.go:158" listen_address="0.0.0.0:8000"
lakefs_1    | time="2021-03-31T07:40:40Z" level=info msg="Up and running (^C to shutdown)..." func=cmd/lakefs/cmd.gracefulShutdown file="cmd/run.go:220" version=0.33.1
lakefs_1    | 
lakefs_1    | 
lakefs_1    |      ██╗      █████╗ ██╗  ██╗███████╗███████╗███████╗
lakefs_1    |      ██║     ██╔══██╗██║ ██╔╝██╔════╝██╔════╝██╔════╝
lakefs_1    |      ██║     ███████║█████╔╝ █████╗  █████╗  ███████╗
lakefs_1    |      ██║     ██╔══██║██╔═██╗ ██╔══╝  ██╔══╝  ╚════██║
lakefs_1    |      ███████╗██║  ██║██║  ██╗███████╗██║     ███████║
lakefs_1    |      ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝
lakefs_1    | 
lakefs_1    | │
lakefs_1    | │ If you're running lakeFS locally for the first time,
lakefs_1    | │     complete the setup process at http://127.0.0.1:8000/setup
lakefs_1    | │
lakefs_1    | 
lakefs_1    | │
lakefs_1    | │ For more information on how to use lakeFS,
lakefs_1    | │     check out the docs at https://docs.lakefs.io/quickstart/repository
lakefs_1    | │
lakefs_1    | 
lakefs_1    | Version 0.33.1
lakefs_1    | 
</code>
</pre>
</details>

**Comment by johnnyaug** [comment]
Thanks!
lakeFS has two APIs:
1. The metadata API (served by `/api/v1`)
2. The S3 gateway, which is S3 API-compatible.

Rclone should interact with the second one. I see that you've set the Host header to be `$bucket.s3.my-domain.de`, which is good. However in order for lakeFS to serve this request through the S3 gateway, you also need to set the `LAKEFS_GATEWAYS_S3_DOMAIN_NAME` variable to `s3.my-domain.de`. 

If that doesn't work, please set `LAKEFS_LOGGING_LEVEL` to `DEBUG` - and post the logs again.

**Comment by poldi1405** [comment]
Awesome! That worked. Now I get
```
lakefs_1    | time="2021-03-31T11:48:58Z" level=warning msg="could not find access key" func=pkg/gateway.AuthenticationHandler.func1 file="build/pkg/gateway/middleware.go:45" error="not found: no rows in result set" key=""
```
I also tried generating a new token-pair to no avail. The same message and 403.

**Comment by johnnyaug** [comment]
Hey @poldi1405, is Slack an option for you? I think I could better help you there. You can join it [here](https://join.slack.com/t/lakefs/shared_invite/zt-ks1fwp0w-bgD9PIekW86WF25nE_8_tw).

**Comment by poldi1405** [comment]
Joined it

**Comment by arielshaqed** [comment]
@mpldr @johnnyaug did we make any progress on this issue?

**Comment by mpldr** [comment]
> @mpldr @johnnyaug did we make any progress on this issue?

Unfortunately not. I got distracted and I am now at a point where I already found a solution to most of my problems in not using LakeFS. That is not to say that LakeFS is a bad project, quite the opposite. It just wasn't right for me and my usecase.

**Comment by mpldr** [comment]
Keeping this ticket open because the documentation in this regard is still non-existent.

**Comment by itaiad200** [comment]
Seems like a misconfiguration of the keys, closing until further information from the author is given.
