### ISSUE TITLE
Support multiple S3 gateway domain names

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1719]
[Requested [on Slack](https://lakefs.slack.com/archives/C016726JLJW/p1617649557038900)]

The use case is when there are _two_ ways to access lakeFS as an S3 gateway:
1. via external domain name  https://lakefs.xxx.xxx.xx  though load balancer .
2. direct access from inside k8s,  e.g. http://lakefs

**Comment by xubofei1983** [comment]
Hi @arielshaqed, thanks for this PR.  
Any estimation when would this get released?
