### ISSUE TITLE
Bug: parent order for merge commits is reversed

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1730]
Background: when merging a branch into another, the resulting merge commit will have 2 parents:
- The commit the source branch is currently pointing to
- The latest commit on the destination branch at the time of merge

When Git creates a merge commit, their order is always `[destination branch, source branch]`.
This is useful for diffing: for every commit, whether it's a merge commit or not, comparing the commit with its first parent will result in a diff of all the changes introduced from parent to child.

In lakeFS, the order is currently `[source branch, destination branch]`.
This means that when doing a diff with the first parent, we're asking what changed between a set of changes and the results of merging them to another branch. The answer is an empty diff. To get the "correct" result when diffing, we need to special-case merge commits and compare the commit with its second parent. This not only breaks compatibility with Git, it makes the developer experience cumbersome.

This is, of course, a breaking change - diffing merge commits genereted prior to making this change will incorrectly show an empty diff. I suggest doing it *now*, since it'll always be mroe painful to do it later.

**Comment by arielshaqed** [comment]
*YES* to fixing this, and *_even more yes_* to fixing it sooner rather than later.

However I am wary of breaking existing repos.  Can we mark new commits somehow?  Even better, can we do something to new commits so that old commits will stand out?  Then we can special-case it, and while the special case will never die -- its fragility will become less important over time.

Here's one way to do it without introducing a version number (there may be others).  Change `CommitData` to:
```proto
message CommitData {
  string id = 1;
  string committer = 2;
  string message = 3;
  google.protobuf.Timestamp creation_date = 4;
  string meta_range_id = 5;
  map<string,string> metadata = 6;
  repeated string old_parents = 7 [deprecated=true];   // not sure we want this tag, but also not sure it does anything
  repeated string parents = 8;
}
```

Now we should be gold: the field name has changed to be ugly, we can special-case on `old_parents` having elements, and everybody starts using `parents`.

(Other ways are possible).

**Comment by ozkatz** [comment]
thanks @arielshaqed - I agree it's possible to do it this way, but I see little benefit over adding a version number because you'd still need to:

- [ ] handle these fields when generating a content address (commits must retain their adresses forever)
- [ ] also expose `old_parents` in the API, everywhere parents are exposed (or at least know to return a reversed pair in every API that exposes parents)
- [ ] ensure any diffing/merging or other types of business logic internal to the system knows how to handle these correctly, check for their existence, etc

it's not impossible to do, but there's some non trivial cost to this

**Comment by nopcoder** [comment]
Same - yes and soon.
Assume lakeFS is the only want need to handle the information - having the lakeFS version in the file metadata can enable us to patch the information (mini migrate) while loading the file.
But processing this information by other clients can be problematic unless we document it as a known bug in old commits and if we will be required to address it - a re-write tool that will rewrite history I think is the way. (in the cost of loosing old references)
