### ISSUE TITLE
Pagination in auth is broken

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1748]
`auth.ListPaged` expectes the struct field name to match the name of the column in the database. In our case, this is never true. This means pagination in auth is essentially broken for all paginated responses.

Reproduction is easy: calling listUsers with an amount < number of users will result in `has_more: false` with `"next_offset": "<invalid Value>"`.

**Comment by arielshaqed** [comment]
Ouch.  On it.
