### ISSUE TITLE
Diff outputs objects with no changes

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#1762]
Steps to reproduce:

1. To a lakeFS repository, upload a file to the `main` branch, and commit.
2. Create a new branch `br1` from the main branch.
3. Upload the same file with the same name to the new branch, and commit.
4. Run `lakectl diff lakefs://repo@br1 lakefs://repo@master`.

Expected: no results.
Actual: file appears as modified.

Related Slack question: https://lakefs.slack.com/archives/C016726JLJW/p1618528555058400?thread_ts=1618528530.058300&cid=C016726JLJW

**Comment by johnnyaug** [comment]
Looks like in pkg/catalog/entry.go, we include the physical address in the checksum, causing an uploaded file to have a new Graveler identity, regardless of the content.

**Comment by xubofei1983** [comment]
Thanks @johnnyaug,  does it means lakeFS will stores two files separately in this case? would it merge both after fix?

**Comment by johnnyaug** [comment]
@xubofei1983, after the fix - both branches will be identical and you will see no difference between them.

Whether or not two files will be stored (i.e. whether there will be a deduplication feature) will need to be decided. Stay tuned :)

**Comment by xubofei1983** [comment]
Thanks @johnnyaug,  our use case is like this (I think pretty common):

We have a pipeline runs weekly and generates a large number files for thousands GB data.   Most of the data would not be exactly same, with few new files and some updates to old files.
We expect to create a new branch and aws sync the data, then compare the diff and merge.

We would expect the data storage would not double every week, but increase with only new data.

Would this be supported in lakeFS solution?

**Comment by talSofer** [comment]
Hi @xubofei1983, this bug fix will not address the use case you described here. This is a valid use case and we've opened https://github.com/treeverse/lakeFS/issues/1765 to track your feature request. We thought of adding an offline deduplication mechanism that will clean up objects uploaded to multiple branches.
