### ISSUE TITLE
Offline deduplication mechanism 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1765]
https://github.com/treeverse/lakeFS/issues/1762 introduced the following use-case: 
> We have a pipeline runs weekly and generates a large number files for thousands GB data. Most of the data would not be exactly same, with few new files and some updates to old files.
We expect to create a new branch and aws sync the data, then compare the diff and merge.

> We would expect the data storage would not double every week, but increase with only new data.

To support that we thought of adding an offline deduplication mechanism that will clean up objects uploaded to multiple branches.

**Comment by arielshaqed** [comment]
@treeverse/product : dedupe was an explicit goal, but we're moving away from it.  This had some customer demand and is often surprising to customers.  I would rather we could add an explicit note here than let the bot close it in silence.
