### ISSUE TITLE
Test multiple domain names in Nessie

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1770]
#1720 included a _manual_ test that multiple domain names work.  Add a Nessie test.  See #1769 for Docker features that may hinder, and how it might nonetheless be possible.  (It should still test host-based addressing, this is a subtle and important part of the feature!)

**Comment by itaiad200** [comment]
@arielshaqed is this still relevant given the changes in the subdomain logic?

**Comment by arielshaqed** [comment]
Important low, I am not aware of this in any large installation.
