### ISSUE TITLE
provide a lakeFS Airflow operator

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1771]
Provide a set of reusable building blocks for Airflow that can create branches, commit and merge. The idea here is to enhance existing pipelines that, for example, run a series of Spark jobs, with an easy way to create a lakeFS branch before starting, passing that branch as a parameter to all Spark jobs, and upon successful execution, commit and merge their output to master.

Should support the following:

- [x] A `CreateBranch` operator
- [x] A `Commit` operator
- [x] A `Merge` operator
- [x] An `OnCommit(branch)` sensor
- [x] An `OnChange(ref, directory_or_prefix)` sensor

A good starting place would be: https://github.com/astronomer/airflow-provider-sample

**Comment by pgzmnk** [comment]
This makes sense. With the core functionality defined, I'd start with creating a Hook that exposes every layer needed to accomplish the Sensor and Operator logic. The Hook will also handle authentication using Airflow connectors.

The sample repo shows a minimalist [SampleHook](https://github.com/astronomer/airflow-provider-sample/blob/main/sample_provider/hooks/sample_hook.py) that uses HTTP. A similar concept can be transposed if using a public Python library.

**Comment by pgzmnk** [comment]
Another element to keep in mind is the metadata that operators will pass to other tasks (to modules in both this and external packages) as the workflow executes. This can be, for example, resource ids.
