### ISSUE TITLE
Support creating glue table and symlinks from lakeFS path with one command

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1774]
Currently in lakeFS there is no way easy way to query `lakeFS` data using `Athena`.
The only way requires the user to already have a table in `Glue` pointing to data in `lakeFS`, only then the user could run the `lakectl create-symlink` command.
Creating such table is not possible using only `Glue` and `Athena` and would need an external client such as `Spark` `Presto` or `Hive`.

In order to make querying `lakeFS` from `Athena` more convenient we would like to add command that would allow creating such table ( and relevant symlink data ) without the need to create the table pointing to `lakeFS` first.

**Comment by arielshaqed** [comment]
Please bump if you need this!
