### ISSUE TITLE
Hadoop FileSystem: Inject of a dummy filesystem into Spark and access it 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1775]
To address the goals described in [Hadoop FileSystem for lakeFS: Design Options](https://docs.google.com/document/d/1934pMXjLoyLc-ECIvu9jFAL0Uw5Y2nOJ5HgT0yu-pxA/edit?ts=6064a4a3 ) we are planning to implement a lakeFS FileSystem that whenever it has to perform a data operation, it takes a relevant Hadoop FileSystem and uses it.

This task is part of the initial feasibility testing of the plan above. 
* Write a dummy lakefs FilySystem that does nothing, and make sure we are able to register it to Hadoop. 
* Test that the lakefs filesystem is accessible via Spark and is used by Spark workers.

**Comment by arielshaqed** [comment]
@talSofer can we close this?
