### ISSUE TITLE
Hadoop FileSystem: Write a Nessie test that runs a Spark job interacting with lakefs

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1777]
To address the goals described in [Hadoop FileSystem for lakeFS: Design Options](https://docs.google.com/document/d/1934pMXjLoyLc-ECIvu9jFAL0Uw5Y2nOJ5HgT0yu-pxA/edit?ts=6064a4a3 ) we are planning to implement a lakeFS FileSystem that whenever it has to perform a data operation, takes a relevant Hadoop FileSystem and uses that.

This task is to allow testing the overall functionality of the lakefs filesystem. 
* Write a Nessie test that runs a Spark job that interacts with lakefs. 
* The test should pass successfully after the implementation of the lakefs filesystem. 
* The test should include:

**Comment by nopcoder** [comment]
Added spark app as part of the lakeFS test flow.
The current test checks basic read/write operations from two workers on spark v3 - future tasks can enrich the tests.
