### ISSUE TITLE
Complete multipart response - wrong location field  

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1779]
The response from `Complete multipart upload` contains a Location Field.
The value returned seems invalid in two aspects:
1. `o.Repository` is used where `o.Repository.Name` should be used
2. The `FQDN` value will not always be correct (e.g when the endpoint is configured without port but the request contains port)

We should check if Location returned in the result is valid and if not, fix it so it would be as expected.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

**Comment by ozkatz** [comment]
This is partially solved by #2390 (the right repository name field is used).
The FQDN populated on `o.FQDN` will not contain the proper port if a non-default one is used.

**Comment by nopcoder** [comment]
#2456 algin the value of 'Location' in response to include: host, port, and consider path-style based on the request format.
