### ISSUE TITLE
Handle virtual hosted requests by modifying request to be path-based during route

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1780]
We currently support virtual host request and path based request in many places in our S3 Gateway.
We would like to modify the request (if it is possible) during route to be path based.

for example: the request `my-repo.my.endpoint.com/my-branch/path/to/object` should change to `my.endpoint.com/my-repo/my-branch/path/to/object`

path style request should stay the same.

There are two places where this might go wrong:
1. sigV2 - sigV2 uses the host as part of the signature, when calculating the signature, the host request is modified to path base any way https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html
2. Complete multipart upload - currently returns location based on the FQDN field, seems it is created regardless to `path-style` https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

**Comment by itaiad200** [comment]
@guy-har Is this still relevant given the recent changes we've made to the gateway?

**Comment by arielshaqed** [comment]
@guy-har is this still required?  (Please unassign yourself after response, of course!)

**Comment by guy-har** [comment]
Many things changed since the Issue was opened, don't believe this is required anymore. 
If for some reason this will be required again we will just re-open it.
