### ISSUE TITLE
Renaming the lakeFS main branch from "master" to "main"

### ISSUE THREAD

**Issue by karentamrazyan** [treeverse/lakeFS#1792]
Not a strong opinion, just an idea/suggestion. How about renaming the lakeFS main branch from "master" to "main"? This might be applied to the software itself as well as its github repo.

Here is the github's article that answers "why?": https://github.com/github/renaming

**Comment by itaiad200** [comment]
A work has been done a while ago to support **any** default branch name. It was also changed in most places to have it preconfigured to `main` instead of `master`. The UI was an exception to that an PR #1800 should fix that.

**Comment by arielshaqed** [comment]
Also personally I don't find "master" a particularly descriptive term.

Also it's _not_ like we're trampling all over the traditional terms.  The terms of art are "trunk" (e.g. as used in [Subversion](https://svn.apache.org/repos/asf/subversion/trunk/doc/user/svn-best-practices.html), CVS) and "main" (e.g. as used in [ClearCase](https://www.ibm.com/docs/en/rational-clearcase/8.0.1?topic=information-version-selector) and probably most other large systems).  By moving back to main we are restoring the old name, one that was more descriptive than this modern "master" nonsense.  This really is what we call in Hebrew <span dir="rtl">מחזירים עטרה ליושנה!</span>
