### ISSUE TITLE
Expanding repository tags

### ISSUE THREAD

**Issue by karentamrazyan** [treeverse/lakeFS#1802]
Please, consider adding some of the following relevant tags to the repository for a better discoverability:

- #data-version-control (14 repos)
- #git-for-data (2 repos)
- #version-control (634 repos)
- #versioning (771 repos)
- #dvc (50 repos)
- #git (21,895 repos)
- #big-data (2,404 repos)

Feel free to ignore the less relevant ones from the list.

**Comment by YaelRiv** [comment]
added 'data version control' and 'git for data'
