### ISSUE TITLE
Add thick (direct write) DeltaLake committer

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1804]
"Merely" supporting S3A and friends is not enough for thick support for DeltaLake, if the DeltaLake committer does not go through it.  (Even if it does, need to verify support -- it might well perform other operations than standard Spark flows.)

Some providers (e.g. DataBricks) have their own DeltaLake committers; check whether we can work with those, too.

**Comment by tahesse** [comment]
Anyone tried to directly write their delta tables to lakeFS with the deltalake (delta-rs with python bindings) package?

I think this issue is related.

**Comment by arielshaqed** [comment]
Still relevant for DeltaIO.
