### ISSUE TITLE
replace "master" with "main" in docs pictures

### ISSUE THREAD

**Issue by karentamrazyan** [treeverse/lakeFS#1809]
Kudos to the team for the great job of flawless replacements of all "master" mentions with "main" in the docs! Multiple pictures in docs still use the word "master" for the main branch. I could, as nice as I can, replace the mentions in the pictures and submit a PR. Should I try it or is there a special person in the team who takes care of the graphics?

**Comment by YaelRiv** [comment]
@karentamrazyan goof catch! I fixed the wording for all images in docs.

**Comment by YaelRiv** [comment]
fixed
