### ISSUE TITLE
build: Generated code by docker created by root user

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1815]
The project Makefile uses docker to generate files - the current user that the container is using is the docker user and not the user who performs the action.
Expected behaviour that the generated source code should have the non-root owner.

**Comment by arielshaqed** [comment]
Need it so stealing it to do it. :-\

**Comment by arielshaqed** [comment]
Solved this in #1828 (b65be0c3fe39fe20ab99c163ac84fd6135a02b31) many moons ago and forgot to close.  Sorry.
