### ISSUE TITLE
Restructure lakeFS documentation

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1822]
The sidebar at the right is somewhat messy and might not make it easiest to look things up.  Propose a more principled layout (in the sense that one can ask, "where should this page go?"). Move existing pages around.

**Comment by YaelRiv** [comment]
This is great. Thanks @arielshaqed!

I'd also suggest taking another look on the deployment section (e.g. Deploy on AWS, Deploy on Azure, On-prem, etc.). It's not very clear or user friendly atm.

**Comment by arielshaqed** [comment]
Being done by @johnnyaug & @YaelRiv in another way.  Closing in favour of _that_ approach; please re-open if you disagree.
