### ISSUE TITLE
[discovery] Should mtime be a part of object identity?

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1844]
Part of discussions triggered by #1840.

mtime is currently treated as a part of object identity in the current system, but #1840 (via #1841) would have us change that.  Discover which we want to do.

Points that we already know are important:
- Similarity to Git
- Similarity to S3
  _(This is probably different from Git!)_
- Should lakeFS object mtime be a copy of underlying storage mtime?
- How does this affect retention?

**Comment by guy-har** [comment]
@arielshaqed mtime is not currently treaded as part of the object identity in the current system.
#1841 Fixes different bug that hid that bug.

**Comment by arielshaqed** [comment]
No traction on this issue: does not (currently?) seem to matter.
