### ISSUE TITLE
Improve Hive Metastore Integration

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1846]
Currently, lakeFS supports integrating with Hive Metastore as an external `lakectl` command. It allows copying a table definition and mapping its physical address to another branch prefix. While this is a good start and in theory can support even complex branching models, it forces consumers to modify their queries to adapt to different branches (i.e. if I want to query `db.table` in different branches, I'd have to query something like `db_mybranch.table` or `db.mybranch_table` etc).

While this is theoretically possible it imposes a few limitations:
1. Tooling: notebooks and pipelines that embed the table name in a SQL query have no easy way of controlling it dynamically. Table names will not accept a placeholder like `?`. Even if possible, the resulting query would be pretty hard to understand as the table is now determined at runtime.
2. Changes in data and metastore have to be synced manually. If I modify a table (even by adding or removing partitions) in a commit, and then decide to revert it, merge it somewhere, etc - I'd have to also call the relevant `lakectl metastore` command pre-op or post-op. Aside from breaking atomicity, it introduces another place for human error. This is automatable using hooks, but places a lot of the burden on the user.

**Comment by arielshaqed** [comment]
## Controlling the client

### Loading an alternate version

There is _some_ support for loading an alternative Hive client, [documented for Spark](https://spark.apache.org/docs/latest/sql-data-sources-hive-tables.html#interacting-with-different-versions-of-hive-metastore).  So we might load our own metastore classes by pointing at a suitably modified version.

### Encoding parameters in the Hive metastore URL

Possibly we could point the [DB URL](https://github.com/apache/hive/blob/6246c47b95f6cab7ea24d1deadfd13b2b43cf876/data/conf/hive-site.xml#L101) and put parameters (notably `branch`) in there?

**Comment by itaiad200** [comment]
Extraction of user-stories for this epic:

1. Users would want to use metastores with lakeFS without having to run custom lakeFS/metastore commands when merging/committing/creating branches. 
1. Users would like to store their metadata in the same version-control they use for their data. A User should be able to use a lakeFS commit that represents both the data and the metadata and produce the same results. A diff between commits should show both the data and metadata that changed.
1. Users would like to work on metadata and data in isolation and commit any changes atomically to both.
1. Users find it hard to change the table name between branches and would like to keep a persistent name across branches.

**Comment by arielshaqed** [comment]
5. Users need metastore changes to appear in staging area (even before commit).

**Comment by nopcoder** [comment]
@itaiad200 can you explain item 4 in the user-stories? do you mean the way the end-user needs to access the actual table in case we encode the branch name as part of the schema or table name?
Removing the different names for the same table, without any modification from the user is a current limitation in our metastore support?

**Comment by itaiad200** [comment]
> @itaiad200 can you explain item 4 in the user-stories? do you mean the way the end-user needs to access the actual table in case we encode the branch name as part of the schema or table name? Removing the different names for the same table, without any modification from the user is a current limitation in our metastore support?

Item number 4 was addressing the current suggested solution we provide for metastores. Since tables should be copied when a branch is created, the user needs to interact with the new table, which means changing the table name wherever it exists.

**Comment by arielshaqed** [comment]
@ozkatz is this still a priority?  Should we keep it open, just behind Delta, Iceberg, and friends?

**Comment by ozkatz** [comment]
I will concede at this point. Closing for now.
