### ISSUE TITLE
Report the modification details on diff presentation 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1849]
### Background
In https://github.com/treeverse/lakeFS/issues/1840 a user uploaded a file that is content-identical but different in metadata to a committed file. In that issue, the user expected not to see the file in diff and thought the files to be identical. If the user could see that the files are different in metadata and the name of the different property (modification data in this case) it may prevent the confusion. 

### Required changes
Report the modification details on diff presentation in both the UI and lakectl diff command output.  

**Suggestion** 
1. Use the following definitions: 
* _modification category_: Data/Content, Metadata
* _modified field_: all the file metadata fields included in its identity. 
2. Make diff report _modification category_ and _modified field_

![Screen Shot 2021-05-02 at 12 29 15](https://user-images.githubusercontent.com/14786381/116808619-7d1a5100-ab42-11eb-8146-6b67dafca567.png)

**Comment by xubofei1983** [comment]
Nice,  but maybe provide a global level toggle would be an even better, since we may have thousands of files. Thanks.
