### ISSUE TITLE
[filesystem] Repository storage namespace - cache

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1851]
Cache repository underlying information - storage namespace - as part of the FS to access storage when needed.

**Comment by itaiad200** [comment]
@nopcoder Could you please add more details to this issue? Like what exactly are we caching, just the storage namespace? What is the "underlying information"?

**Comment by nopcoder** [comment]
When the application access lakefs fs (lakefs://repo/main/out) the filesystem needs to access the underlying data through the repository storage namespace. For example, access the s3 bucket for data on repository 'repo'. This information is stored on lakeFS as part of the repository, and our filesystem need to cache this information for operations like create, open and etc.

**Comment by nopcoder** [comment]
Not caching any lakeFS information at this point - until we get to the point that it is not efficient
