### ISSUE TITLE
[filesystem] Rename API - research what s3 does

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1857]
Implement lakeFS filesystem API

**Comment by talSofer** [comment]
s3 uses copy to rename files and directories. see https://github.com/apache/hadoop/blob/2960d83c255a00a549f8809882cd3b73a6266b6d/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/impl/RenameOperation.java#L344 for a reference.
