### ISSUE TITLE
ObjectsAPI: deleteObject not indicating whether an object deleted from staging existed 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1902]
### Steps to reproduce:
1. call objectsApi.deleteObject with details of a file not committed or in staging. 
2. No APIException will be thrown and the response won't have an error message. 

### Root cause 
The DropKey operation implemented in graveler.staging.manager does not report err when deletion from graveler_staging_kv not affected any record. 

Need to investigate whether this is the desired behavior or it is an issue.

**Comment by ozkatz** [comment]
This is desired behavior (we can of course change it, but this is intended). It is based on S3's [DeleteObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html) behavior, in which deleting objects returns 200 OK even if an object does not exist prior (i.e. will not validate its existence in any way).

Do we have a good case to change that?

**Comment by itaiad200** [comment]
Closing since behaviour is as expected.
