### ISSUE TITLE
Test and list wasabi as a supported by lakeFS cloud storage

### ISSUE THREAD

**Issue by karentamrazyan** [treeverse/lakeFS#1911]
This is just an idea that emerged after [this conversation in slack](https://lakefs.slack.com/archives/C0209QU20BU/p1620331070122500?thread_ts=1620330178.121500&cid=C0209QU20BU). Feel free to ignore & close it if not relevant.

Links:
- [Wasabi](https://wasabi.com/)

**Comment by YaelRiv** [comment]
@karentamrazyan thanks for opening an issue! We're in the process to test and be part of their partner network. I'll update as we progress.
