### ISSUE TITLE
Add youtube icon & link to the footer of the docs

### ISSUE THREAD

**Issue by karentamrazyan** [treeverse/lakeFS#1918]
Similarly to the footer of the homepage (lakefs.io) it would be great to have a [link to the youtube channel](https://lakefs.io/youtube) in the footer of the docs. Currently, the youtube icon is missing in the [assets/icons](https://github.com/treeverse/lakeFS/tree/master/docs/assets/icons) directory.

**Comment by nopcoder** [comment]
Checking where we can get or quick way to create the missing assets for this one

**Comment by karentamrazyan** [comment]
There is a SVG version available from the https://lakefs.io/wp-content/uploads/2021/03/youtbe-icos.svg location. A PNG version can be created from it (in the right color) and both can be used for the docs section. Will give it a go once I have more time on my hands. Can be assigned to me.
