### ISSUE TITLE
Expand Spark client integration tests

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1930]
We currently have an integration test (`test/spark/run-test.sh`) running with `spark 3.1.1` above `S3`
We would like to expand this test so it would run on spark client `2.4.7` and above `GCS` and `Azure blob storage`.

The required tests should run on all the combinations 

|          | `spark 2` |`spark 3`|
| -------- |:---------:| -------:|
| `S3`     |           |         |
| `GCS`    |           |         |
| `Azure`  |           |         |

**Comment by arielshaqed** [comment]
Should be Spark *2.4.7*.

**Comment by itaiad200** [comment]
To be honest, I don't see much additional value from testing all options of the matrix.
Yes we should test `S3`, `GCS` and `Azure`. Also `Spark` `3.*` and `2.*`.

I just don't think we'll gain much from testing every combination. What would `GCS` on `Spark` `2.*` give you that `Azure` didn't?

**Comment by arielshaqed** [comment]
> To be honest, I don't see much additional value from testing all options of the matrix.
> Yes we should test `S3`, `GCS` and `Azure`. Also `Spark` `3.*` and `2.*`.
> 
> I just don't think we'll gain much from testing every combination. What would `GCS` on `Spark` `2.*` give you that `Azure` didn't?

This is Spark... Which has a unique approach to how plugins such as our LakeFSFileSystem get to use other libraries.  E.g. overloading configuration options is dangerous, re-using the same library that Spark uses might fail, shadowing the library that Spark uses might also fail, etc.  Spark 2.4.7 and 3.x are very different in that regard, and small changes might affect client behaviour to the point of failure.

[![This is SPARK!](https://user-images.githubusercontent.com/7802932/117662150-ee43af00-b1a7-11eb-93b2-6df26c560b33.png)](https://imgflip.com/i/58yl96)
