### ISSUE TITLE
Gateway copy should perform a physical copy

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1935]
Currently the gateway copy operation is a metadata operation, meaning that after the copy is done both the destination and the source are represented by the same object in the underlying storage.

This behavior will cause problems with the implementation of retention.

We would like to change the copy operation to be a physical operation, 
meaning that after the copy command is over, the source and destination keys will be represented by two different objects.

**Comment by guy-har** [comment]
This issue is a requirement for #1566 and #1932 and #1933

**Comment by itaiad200** [comment]
@guy-har This slows down the copy operation significantly, which is one of the offering we have. Is there a way to keep that and still have retention?

**Comment by guy-har** [comment]
This Issue should Come together with #1933 (At least the part that handles delete commands).
The reason for that is:
When running a spark job it may create many temporary files, copy them and then remove them.
Currently there is no "Garbage" created by that process, All temporary files, are used by the final files due to meta-copy. Once We do physical copy, all the files created will exist twice (one for the temporary one for final).
In order to not create that "Garbage" we need the staging delete command to delete the physical data as well.

*Inserting physical delete before physical copy will cause bugs

**Comment by guy-har** [comment]
Currently the retention handles deduplications. Closing this issue for now.
