### ISSUE TITLE
lifecycle | Include logical path In physical address

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1943]
As part of #1566,
in order to implement lakeFS lifecycle using AWS S3 lifecycle

physical address should be in the form:
`<STORAGE_NAMESPACE>/<KEY_IN_LAKEFS>/<UUID>`

**Comment by arielshaqed** [comment]
> physical address should be in the form:
> `<STORAGE_NAMESPACE>/<KEY_IN_LAKEFS>/<UUID>`

#1566 says
> Objects’ physical address in the underlying storage will be the same path as their logical path, with a UUID added as a suffix.
> For example, the file: lakefs://repo/master/a/b/c/filename will be saved under s3://bucket/a/b/c/filename/8abb1f1d-e33b-4487-9cad-d2f86eb26b92.

This is unchanged, correct?  So KEY_IN_LAKEFS does not include branch (or bucket).

**Comment by guy-har** [comment]
Yes, It is unchanged.
KEY_IN_LAKEFS - does not Include branch or repo

**Comment by guy-har** [comment]
We decided not to Include logical path In the physical address in order to support atomic rename
