### ISSUE TITLE
lifecycle | Add lakectl commands to get and set lifecycle policy

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1945]
Add lakectl commands to get and set lifecycle policy

These commands will set lifecycle policy in underlying storage.

For example 
For a repository using the storage namespace: `s3://my-bucket/path`
```shell
 lakectl lifecycle set --repo my-repo --prefix my-data/raw --days 14
```

will set a lifecycle policy in S3 
```xml 
<LifecycleConfiguration>
  <Rule>
    <ID>[lakeFS_ID]</ID>
    <Filter>
       <Prefix>path/my-data/raw</Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Expiration>
      <Days>14</Days>
    </Expiration>
  </Rule>
</LifecycleConfiguration>
```

`lakeFS_ID = lakefs-[REPO]-[hash(prefix)]`

* lekFS Lifecycle rules apply to all branches, branch-specific lifecycle rules are not supported.

```shell lakectl lifecycle ls```
should return 

<table>
<tr>
	<td>Prefix</td>
	<td>Days</td>
<tr>
	<td>my-data/raw</td>
	<td>14</td>
<tr>
	<td>other/path</td>
	<td>300</td>
</table>

Notes:

* consider supporting Azure and GCS. This is not a requirement, Add only if it can be done as part of this issue without to much effort.
* consider returning Expiration as part of Head and Get The same way S3 does
	* In get we should set the header `expired` to be the same as we got from S3
	* Head currently does not make any request to S3 so it might not be worth adding it

**Comment by arielshaqed** [comment]
Need to see what #4015 entails to see whether this can be done.

**Comment by arielshaqed** [comment]
Closing as UGC is now implemented, _differently_.
