### ISSUE TITLE
DBT Snapshots Integration w/ lakeFS

### ISSUE THREAD

**Issue by peacing** [treeverse/lakeFS#1947]
DBT has a [Snapshots](https://docs.getdbt.com/docs/building-a-dbt-project/snapshots) functionality that let's users define a table they want to track over time.

We propose this as an inroad to integrate DBT & lakeFS. With lakeFS, the level of data duplication among snapshots can be reduced (in most cases, I assume greatly) 

This is achieved by turning snapshots into lakeFS commits, instead of full copies of the table/dataset.

**Comment by itaiad200** [comment]
@ozkatz had a different idea for the integration. Can we use this issue to track DBT integration options?
