### ISSUE TITLE
Tutorial/Suggestions inside lakeFS UI

### ISSUE THREAD

**Issue by peacing** [treeverse/lakeFS#1949]
As discussed in the risks & mitigations meeting, to increase understanding and usability, when run in local mode,  include dismissable pointers or suggestions of things you can do with lakeFS.

This idea needs to be fleshed out more, but this is the basic concept.

**Comment by nopcoder** [comment]
Currently, on a new repository, there is a getting started page.
Adding 'get started' page also in the following places:
- No repositories - getting started, create repo and link to docs.
- No actions - link to docs for more about actions.

@peacing any other places or links you can think we should add 'get started'?
