### ISSUE TITLE
Metastore | Use AWS provider chain to receive AWS Glue credentials

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1951]
Currently when running metastore commands the AWS Glue credentials are taken from the lakectl glue configurations 
We would like to add an option to use AWS provider chain as well

* We should take in consideration that the same environment might need to access both lakeFS and Glue which will have different credentials

**Comment by ozkatz** [comment]
@guy-har [this might be relevant](https://github.com/treeverse/lakeFS/blob/master/cmd/lakectl/cmd/store/s3.go#L15) - we already have code to read the default sdk config for AWS
