### ISSUE TITLE
Support atomic rename

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1955]
Spark committers require atomic rename.  While S3 does not allow this, _our_ API can do this.

**Comment by arielshaqed** [comment]
+ @talSofer should have additional insight into what e.g. Parquet probably does.

**Comment by arielshaqed** [comment]
# :warning: 
#1566 (and specifically the physical path naming that  #1935 / #1953 are moving towards) may conflict with this and we might need to design how we solve _both_ *together*

# If physical paths are uncorrelated with logical paths

Rename is a pure metadata operation; doing it atomically is fairly straightforward.

# If we base physical paths on logical paths

Rename becomes a data operation.  We need to copy from the old name to the new name, and then atomically change the link to the new link.  If we need to rename all data files in some format then for these users we can problems for essentially *all* data and metadata.  Some of the problems this causes:

1. All renamed files are written _twice_.  It's still like S3, but we need to do it and missed an easy win.
2. We greatly increase the volume of *garbage collection* activity, all files pass through it.
3. Garbage collector performance drops.  Whereas in S3 data of files is immediately deleted, now we need to allow configuration that will delete these intermediate files much more quickly.

**Comment by ozkatz** [comment]
> 2. We greatly increase the volume of _garbage collection_ activity, all files pass through it.
> 3. Garbage collector performance drops.  Whereas in S3 data of files is immediately deleted, now we need to allow configuration that will delete these intermediate files much more quickly.

@arielshaqed  Well not necessarily - it is unlikely that a branch will commit _while_ a Spark committer is running. A delete for an uncommitted change should directly call `DeleteObject` when possible. It's a form of online garbarge collection, but doesn't necessarily make the garbage collection job work any harder.

Assuming we always want to give the same or better guarantees provided by the underlying object store, I'd say atomic renames are not a requirement for S3 users. They are, however, a requirements for GCS and Azure users since not supporting this will _take away functionality for them_. 

Since I'm not sure we can support atomic renames _at all_ if we base physical paths on logical paths, this requires more discovery IMO.

**Comment by talSofer** [comment]
# Rename by S3A on Parquet writes 
This section demonstrates how s3a uses rename operation in writing Parquet files into s3. 
- Committer used: `ParquetOutputCommitter`

Below are the significant FS operations in writing Parquet files to s3: 
```
S3AStorageStatistics: op_mkdirs += 1  ->  1 - s3a://aws-repo/main/peopleS3a.parquet/_temporary/0
S3AStorageStatistics: op_create += 1  ->  1 - s3a://aws-repo/main/peopleS3a.parquet/_temporary/0/_temporary/attempt_202105131342205343125378474902589_0001_m_000000_1/part-00000-18b468cc-faa8-4968-a3ad-fa20983a2f08-c000.snappy.parquet

S3AStorageStatistics: op_rename += 1  ->  1 - DIR: after a successful write attempt; s3a://aws-repo/main/peopleS3a.parquet/_temporary/0/_temporary/attempt_202105131342205343125378474902589_0001_m_000000_1 to s3a://aws-repo/main/peopleS3a.parquet/_temporary/0/task_202105131342205343125378474902589_0001_m_000000
S3AStorageStatistics: op_rename += 1  ->  2 - FILE: after completing the task s3a://aws-repo/main/peopleS3a.parquet/_temporary/0/task_202105131342205343125378474902589_0001_m_000000/part-00000-18b468cc-faa8-4968-a3ad-fa20983a2f08-c000.snappy.parquet to s3a://aws-repo/main/peopleS3a.parquet/part-00000-18b468cc-faa8-4968-a3ad-fa20983a2f08-c000.snappy.parquet

S3AStorageStatistics: op_delete += 1  ->  1 - Delete the temporary dir after completing the task; s3a://aws-repo/main/peopleS3a.parquet/_temporary
S3AStorageStatistics: op_create += 1  ->  2 - SUCCESS FILE
S3AStorageStatistics: op_delete += 1  ->  2 - main/peopleS3a.parquet/.spark-staging-18b468cc-faa8-4968-a3ad-fa20983a2f08
```

We see two rename operations that take place (dir and file). Looking at [S3a#innerRename](https://github.com/sharvinbala/Hadoop/blob/ad06ccc9e31e6dcb405cea7e04f7a3c9b567c3b8/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L677) it's apparent that rename is implemented with copy.

**Comment by arielshaqed** [comment]
Related: #2042 is another way to do something similar.  Or this could be a step in implementing that one.

**Comment by arielshaqed** [comment]
This is probably impossible on lakeFS/KV, and we want to do it with LakeFSOutputCommitter, so closing.
