### ISSUE TITLE
Discovery - Avoid MultiPartCopy when possible

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1969]
AWS cli and probably s3a driver uses multuipart-copy when requested to copy files bigger than 5MB.
When the request reaches lakeFS it will execute it as is, meaning that an actual copy process will be performed on the data. It is better to keep the same logic we have for smaller files, where the data isn't actually copied but instead being referenced from more than a single entry.

**Comment by itaiad200** [comment]
Here's a possible design:
1. CreateMultipartUpload will continue to work as today.
2. UploadPartCopy will register the file and the range to be copied if it originated from an object in the current repo. Otherwise, perform the actual copy.
3. CompleteMultipartUpload will follow this:
- If all parts are of the same file and together assembles it entirely, then on complete the new entry will point to the existing object in the repo.
- In all other cases (single/multiple files from a different storage namespace, multiple files from the current repo, partial file from current repo), perform the delayed copy operations and complete them.

Benefits:
- We assume that the majority of copy operations copy entire files (rename or other), thus skipping the parts copying make sense.
- Even if that's not the case, then overall latency is only slightly increased because most time is spent on copying data and not lakeFS api requests.

Why this is a low priority issue:
With the upcoming lakeFS Hadoop filesystem, we can naturally support copy/rename operations without having the s3 gateway holding us back. Users will gradually switch from using s3a FS for lakeFS and will enjoy the performance boost when it comes to this specific operation.

**Comment by arielshaqed** [comment]
@itaiad200 is this priority still relevant, given that

>  With the upcoming lakeFS Hadoop filesystem, we can naturally support copy/rename operations without having the s3 gateway holding us back. Users will gradually switch from using s3a FS for lakeFS and will enjoy the performance boost when it comes to this specific operation.

no longer seems to be the case?

**Comment by arielshaqed** [comment]
Assigning @itaiad200 to respond to ^^^^ (and then unassign, of course).
