### ISSUE TITLE
[discovery] Can we support S3 Select?

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#1971]
Spark and friends can do _predicate pushdown_ right into S3 select, which means they need to fetch much less data.  Can lakeFS support that?

Refs:

- [S3 SELECT Command](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-glacier-select-sql-reference-select.html)
- [S3 Select and Glacier Select blog post](https://aws.amazon.com/blogs/aws/s3-glacier-select/).  Quote:
  > Query pushdown using S3 Select is now supported with Spark, Hive and Presto in Amazon EMR. You can use this feature to push down the computational work of filtering large data sets for processing from the EMR cluster to Amazon S3, which can improve performance and reduce the amount of data transferred between Amazon EMR and Amazon S3.

**Comment by arielshaqed** [comment]
* DataBricks say they do support it - https://docs.databricks.com/data/data-sources/aws/amazon-s3-select.html
* AWS appear to support it on emrfs: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-s3select.html
* minIO have https://min.io/resources/docs/Spark-S3Select.pdf; also for Parquet IIUC :shrug: 
* S3A would obviously prefer not to support it (they want you to use a columnar data format, S3 Select only works with CSV or JSON (row-ish) formats.

S3 Select itself is single-file, so it seems conceivable we could support it!

**Comment by talSofer** [comment]
> S3 Select itself is single-file, so it seems conceivable we could support it!

@arielshaqed what does it mean that it is a single file, is there any useful reference I could read? Thanks!

**Comment by arielshaqed** [comment]
By "single-file" I mean that S3 Select "only" speeds up access to a single object at a time.  So if I have 10_000 objects, I will still open all of them even if I use S3 Selectg.

Contrast this with things that operate across a range of objects.  For example, per-object statistics on a field can can help a query planner entirely avoid touching objects that will be relevant for a query.

**Comment by jacobdanovitch** [comment]
Are there any plans to support this? This would be super helpful to have.

**Comment by arielshaqed** [comment]
> Are there any plans to support this? This would be super helpful to have.

This is not currently on our roadmap, sorry.

**Comment by homme** [comment]
This is a blocker for my team to explore LakeFS as we make heavy use of S3 SELECT on our parquet objects.
