### ISSUE TITLE
Split "Create a Repository" page

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1977]
It starts with setup and ends with creating a repository.
Title is misleading as the content manifests two actions that are valid only for the first repository creation.

It's better to split the page to:
1. Create the first user.
2. Create a repository.

**Comment by johnnyaug** [comment]
I wouldn't split the page, not enough content for two separate pages. Maybe rename to "Create your first repository", as suggested before by @itaiad200
