### ISSUE TITLE
Allow Kafka offsets as lakeFS metadata

### ISSUE THREAD

**Issue by einato** [treeverse/lakeFS#2011]
In order to support the entire data pipeline, including analysis done on Kafka consumers/Flink/etc' , lakeFS should support Kafka offsets as part of it's metadata. Once supported, with support of calling lakeFS from the Kafka consumer/Flink/spark streaming, the user can have reproducibility of the full pipeline on a branch or a commit.

**Comment by itaiad200** [comment]
@einato @ozkatz I think this is supported by the setting the offset in the commit metadata, is something missing?

**Comment by ozkatz** [comment]
it requires integration with the actual stream processor (Kafka Connect, Flink, etc). Otherwise, how would you know which offset to put in the commit metadata?

**Comment by itaiad200** [comment]
Who is the committer? lakeFS can't commit on its own. I think the committer should have the relevant information and should set it in the metadata.
