### ISSUE TITLE
Retry DB connection on startup

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2017]
Got [this failure](https://github.com/treeverse/lakeFS/pull/2007/checks?check_run_id=2703565284#step:7:88):
```
lakefs_1    | panic: could not open DB: failed to connect to `host=postgres user=lakefs database=postgres`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
```
This looks like a race during startup, so need to retry _at least on this error_. This will also be useful for simplifying system automation.

**Comment by nopcoder** [comment]
lakeFS got more than one way to connect to the database, during `lakefs run` and `lakefs setup` the first call in case of the run goes to BuildDatabaseConnection and in case of lakeFS setup it goes using Migrate (migrate.NewWithSourceInstance).
The current retry connects works for our BuildDatabaseConnection but not for the setup process.
