### ISSUE TITLE
UI - minor bugs

### ISSUE THREAD

**Issue by LiorItzhak** [treeverse/lakeFS#2030]
* changing the base-branch changes the compared-branch (I think that each Combobox should work independently)
![image](https://user-images.githubusercontent.com/46001729/120198849-40b63f80-c22b-11eb-98a5-0c28eac56c5c.png)

* changing branch (Combobox) on the 'Objects' view resets the path 
I think that if the current path exists on the selected branch, you should keep it instead of rest into the root
![image](https://user-images.githubusercontent.com/46001729/120199647-2466d280-c22c-11eb-8ab0-244944bb60f8.png)

* We can use the URL for pasting paths - but I think it's better to have a dedicated textbox/filters

**Comment by itaiad200** [comment]
Splitting the 2 bugs into #2440 and #2441 and closing this one.
