### ISSUE TITLE
Remove gateway playback test

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2031]
The gateway test does not verify a lot, and is very hard to modify.  Relevant: #1769, #1784, #1785.  It runs pre-recorded S3 commands from some Spark run.  Now we have a live Spark run as part of Nessie.  Add whatever is missing and then get rid of the recordings.

# Known missing:

1. Multipart uploads.  See [`fs.s3a.multipart.size` and similar in hadoop-aws configuration](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html#general_configuration) for how we might induce Spark to do this.
2. Previously Spark on local gave different results than Spark on EMR.  This is _probably_ because of local vs. cluster differences.  Can we ensure coverage?

**Comment by arielshaqed** [comment]
@guy-har for any other things that we need (you _did_ tell me the above 2, do you remember any others?)

**Comment by guy-har** [comment]
We currently also have recording for Presto and AWS CLI.
* The important thing to check in AWS CLI is multipart upload. We already have a test for that using the AWS SDK, I believe it covers the AWS CLI recording (we might want to add AWS CLI tests anyway, but it shouldn't be related to this issue)
* We should check if the Presto recording is significantly different from Spark recording

**Comment by arielshaqed** [comment]
F2F with @guy-har :

* Dropped Spark/EMR playback as required: this is _not_ causing problems, #2418 is much more urgent (has more users).
* Opened #2657 to do Presto.

So, once #2657 is done... we can remove the gateway playback test!

**Comment by guy-har** [comment]
@arielshaqed, Test for Trino was added. we could now remove the gateway playback test!
