### ISSUE TITLE
Quickstart Naming Consistency

### ISSUE THREAD

**Issue by adunuthulan** [treeverse/lakeFS#2043]
The naming convention for the Repository-ID in the quick start examples should be consistent throughout to ensure the tutorial is easy to follow.

![image](https://user-images.githubusercontent.com/29340929/120405248-fd2c0600-c2fc-11eb-9105-2de87ce07eb5.png)
<img src="https://user-images.githubusercontent.com/29340929/120405282-10d76c80-c2fd-11eb-9124-cab42241efb5.png" width="500" height="400">

Consider changing all cases of the Repository-ID in the Quickstart to ```example-repo```  and all cases of the Default Branch to ```main``` to match the naming convention in the Integration tab.

- In /quickstart/repository.html (Create a Repository) change the Repository-ID in the images from ```my-repo``` to ```example-repo``` and ```master``` to ```main```
- In /quickstart/aws_cli.html (Add Data) change all cases of ```s3://example/main/``` to ```s3://example-repo/main/``` and update the images
- In /quickstart/lakefs_cli.html (Install lakeFS CLI) change all cases of ```lakefs://example``` to ```lakefs://example-repo```

**Comment by itaiad200** [comment]
+ @YaelRiv/ @ozkatz to guide on image creation.
