### ISSUE TITLE
Contributing - Maven Dependency

### ISSUE THREAD

**Issue by adunuthulan** [treeverse/lakeFS#2044]
While setting up my environment for development (macOS), Maven was required to complete make test which required certain mvn commands. 

Should Maven be added as a dependency under the #**Setting up an Environment** header in the Contributing tab?

**Comment by arielshaqed** [comment]
> Should Maven be added as a dependency under the #**Setting up an Environment** header in the Contributing tab?

Thanks for the analysis.  We should add it.  I'll do!
