### ISSUE TITLE
Parallelize rename operation for objects under the same directory 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2047]
Address the todo in https://github.com/treeverse/lakeFS/blob/bddd5ecb894fa172a651b8d1cf704171f402d45e/clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java#L312

**Comment by arielshaqed** [comment]
Partially resolved by #4266 .

**Comment by arielshaqed** [comment]
... and will become _much_ less important once we do the LakeFSOutputCommitter.

**Comment by arielshaqed** [comment]
> ... and will become _much_ less important once we do the LakeFSOutputCommitter.

Back to being important, now that we closed that project!
