### ISSUE TITLE
404 error on drill-down to a commit 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2048]
Steps to reproduce: 
1. create a branch and commit to it
2. Go to Objects -> branch drop-down -> branch name 
3. choose a commit
4. Inspect the browser and watch the Network section 

Notes: 
- The issue does not impact the user experience, but we would like to investigate the failing call to determine if the call is intentional or not. 
- We need to check if the API call should be of the form http://localhost:8000/api/v1/repositories/<>/**ref**/<> instead of http://localhost:8000/api/v1/repositories/<>/branches/<>

**Comment by ozkatz** [comment]
Not really an issue and not visible for users.
