### ISSUE TITLE
Support ldap authentication (was: Dex (OpenID) integration) 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2058]
This feature was requested over slack on: 
https://lakefs.slack.com/archives/C016726JLJW/p1622700653019000?thread_ts=1622669223.018000&cid=C016726JLJW

Requirements and feature justifications mentioned in the thread:
> We use it in our clusters to allow authentication of users via our AD. Dex can then provide signed JWT tokens. https://dexidp.io/docs/using-dex/.
> So what would be nice is if LakeFS can consume these tokens so that we may have a single point of sign on.

> Dex integration is maybe one the top thing we care about and is a bit of a blocker for full adoption.

**Comment by arielshaqed** [comment]
There are usually 2 parts to integrating a new auth system:
1. Integrate *authentication*. Make the login and relogin flows go through the API callback hoops and get a token. This is "just a small matter of programming"... 
2. Integrate *authorization*. Once a user is authenticates, we need to know what access permissions to grant them. That typically requires mapping whatever authorization is available on the provider (OpenID here) to required authorization. This is a product call, particularly when mapping dissimilar systems like OpenAPI and IAM.

**Comment by arielshaqed** [comment]
# Proposal for phase 1 system: SSO

We shall provide SSO (authentication) via Dex but continue to provide authorization using lakeFS mechanisms.  Authorizations after being authenticated by Dex:
* If the user is (additionally) defined on lakeFS then lakeFS handles authorization in the same current way.
* If the user is unknown to lakeFS but authenticated then lakeFS attaches that user to a default group.

**Comment by arielshaqed** [comment]
Taking this as part of wider discovery.
