### ISSUE TITLE
Lakectl commands don't take environment variables into account

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2097]
Any Lakectl command except for the "config" command not taking environment variables into account. 

Steps to reproduce: 
1. run lakefs locally 
2. run docker with the lakectl image and feed the config paraeters as environment variables
```
docker run -e LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE -e LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -e LAKECTL_SERVER_ENDPOINT_URL=http://127.0.0.1:8000 -it treeverse/lakectl repo list 
```
3. get error: 
```
Error executing command: Get "/api/v1/repositories?after=&amount=100": unsupported protocol scheme ""
```

**Comment by arielshaqed** [comment]
Testing with command running in the shell works nicely.  This looks very much like a Docker issue (quite possibly related to our packaging or to how we run `lakectl`).

Some investigation: Inside a container, 127.0.0.1:8000 is *not* wired to the host 127.0.0.1:8000 by default (AFAIU).  Wire it up by running `docker --network host`, at which point you can see using `nc` that the port 8000 server is indeed accessible.  But the command still does not work.

Note that the config is irrelevant here: I can reproduce with
```
docker run --network host -e LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIAsomething -e LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=some/SECRET/example/KEY treeverse/lakectl --base-uri http://127.0.0.1:8000 repo list
```
which fails with the exact same error.

I recommend trying to narrow down why we cannot connect from inside the container to a locally-running daemon.  Or write it down to the difficulties of connecting from within a Docker container to loopback.

A more typical experience might be to run `lakefs` inside one container and `lakectl` in another.  Then they should be cleanly wired together -- and if they do not, this is a very real issue.
