### ISSUE TITLE
hadoop-lakefs test app read parquet fails on databricks

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2111]
Using `test/lakefsfs` under Databricks Spark v3 the application reaches the point where it reads the 
 data from lakeFS and fails with the following exception:

[stderr](https://github.com/treeverse/lakeFS/files/6644038/stack.txt)
[log4j-active](https://github.com/treeverse/lakeFS/files/6644043/log4j-active.3.txt)

**Comment by gilandose** [comment]
tested following on databricks spark 3 here are results

Ok so ran a bit of testing here:
parquet partitioned write **faii**
parquet partitioned read **fail**
delta partitioned write **fail**
delta partitioned read  **pass**  (confused about this one ) when all the rest pass (I guess delta points directly at the files to read)
