### ISSUE TITLE
Support for s3 api copy-object across buckets

### ISSUE THREAD

**Issue by sumeshkanayi** [treeverse/lakeFS#2162]
Currently s3 api doesn't support copying objects across buckets

I am trying to copy  objects across buckets by running this using local storage  
`aws --endpoint-url http://s3.local.lakefs.io:8000 s3api copy-object --bucket demo-2 --key main/mytest7.py --copy-source demo-1/main/mytest.py`
and returns below error
`An error occurred (InvalidArgument) when calling the CopyObject operation: Copy Source must mention the source bucket and key: sourcebucket/sourcekey. ` 
I am following https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html#examples

**Comment by arielshaqed** [comment]
This is probably falling afoul of the restriction that objects cannot be shared between repositories (implemented [here][source-no-inter-repo-copy]).  We cannot share the underlying object between repositories, that would be unsafe, as either repository could decide to garbage-collect it.

However we *could* safely copy the object (using the very same corresponding S3 API).


[source-no-inter-repo-copy]: https://github.com/treeverse/lakeFS/blob/b4e8654ad2bfd49bc55c4d801e4b3d362eedf78b/pkg/gateway/operations/putobject.go#L54-L59
