### ISSUE TITLE
Automate the release stage verifying that swagger.yml in docs is up-to-date 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2166]
Automate the release step:
> Verify that swagger.yml in docs is up-to-date (or create another update PR)

https://github.com/treeverse/dev/blob/main/pages/lakefs-release.md

**Comment by N-o-Z** [comment]
@talSofer I think this issue can be closed - as this line was removed in commit b604687b0a68ff8342ae968d6b0911b5623a2f1d
