### ISSUE TITLE
Support post-merge and post-commit hooks

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2182]
This is useful in order to notify downstream systems.
In particular, this will allow systems that integrate with lakeFS using `symlink.txt` files (sometimes known as `SymlinkInputFormat`) to automatically generate these files on commit/merge, and to register them into an existing metastore such as Glue Data Catalog or a self-managed HSM.

**Comment by tvanderwal-lmco** [comment]
Additional use case for this feature would be to initiate some down stream automation such as a kubeflow pipeline after quality checks on the branch have passed.

**Comment by itaiad200** [comment]
Hey @tvanderwal-lmco , release [v0.46.0](https://github.com/treeverse/lakeFS/releases/tag/v0.46.0) introduced `post-merge` and `post-commit` events. Feel free to give it a try..
