### ISSUE TITLE
API with unknown path should return an error

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2190]
Currently lakeFS register openapi handlers and handle all specific routes.
In case of a call to `/api/v1/test`, the unknown path under the API prefix, the mux will serve the request by the UI handler and return a valid HTML (UI) page.

The expected behaviour is to return a non-2xx status code with JSON error - prefered the internal error format, so the developer will handle an error and not fail to parse the response in case of a bad API call.

**Comment by nopcoder** [comment]
The above bug also affects `hadoop-lakefs` when the lakefs api endpoint is configured currently.
Example: https://prod.lakefs.dev/api/v/
No handler registered to handle this call and it falls to the default, which is UI handler that returns html with 2xx.

**Comment by DataDavD** [comment]
Hey @nopcoder I haven't dug into the code specifics yet but I am hoping to take this up if that is fine, ok? Thanks in advance!

Best,
David D

**Comment by nopcoder** [comment]
sure, thanks!

**Comment by nopcoder** [comment]
@DataDavD let me know if you have any questions or need help in this one.

**Comment by DataDavD** [comment]
Ok great, thank you @nopcoder. I'll take a close look this weekend and return with any questions I'll probably have. 

Thanks again!!!!
David

**Comment by DataDavD** [comment]
hey @nopcoder just wanted to give you an update. I was able to take a look at the code and believe I understand the specific issue at hand. I intend to look much more closely tomorrow or the following day now that I pinpointed the code at issue; I will most likely send you some clarifying questions then. 

Thank you,
dd

**Comment by nopcoder** [comment]
thanks for the updates, here for anything that will help you get this one moving.

**Comment by DataDavD** [comment]
hey @nopcoder I am assuming the issue is centered around this line of code. I've been having a little trouble reading through the code because a number of objects/types like `HandlerFromMuxWithBaseURL` show as unresolved refs and I believe are causing my `make build` to fail with error `error generating code: error generating Go handlers for Paths: error generating inlined spec: template: inline.tmpl:5:8: executing "inline.tmpl" at <.>: range can't iterate over` . Do you know what the issue is or does this even prevent correcting it, or is just an annoyance for now?

Also to clarify, for any route past /api/v1 return json 401 error instead of UIHandler, correct?

**Comment by nopcoder** [comment]
Hi @DataDavD, make build should run `go generate` and fill the missing parts - the specific one is lakefs.gen.go which includes the openapi generated code.
Verify that you have Go 1.16 and try to run go generate command found in `serve.go` - maybe it will have more information about the source of the error.

The main issue is any route under `/api/v1` (ex: /avi/v1/unknown) will continue to fall to the UI handler and serve the UI html with status code 200. 
We would like to return the default error with 500 with `writeError` so the caller will identify there is an issue.

**Comment by DataDavD** [comment]
Ahh ok that makes sense; maybe my issue was maybe go 1.15 related, not totally sure though.

Thanks for confirming the issue; I thought that was it but want to verify before I start writing code to handle that. Thank you!!!!

**Comment by DataDavD** [comment]
hey @nopcoder took another look/try and still getting the same error for some reason. I'll try and dig in more tomorrow, but in meantime here is the full error 

For some reason it freaks out over the `swaggerSpec` in `inline.tmpl`. I'll look into why it could be doing this tomorrow as I'm still a bit green with regards to how oapi-codegen is generating the code specifically.

full error:
` error generating code: error generating Go handlers for Paths: error generating inlined spec: templateinline.tmpl:5:8: executing "inline.tmpl" at <.>: range can't iterate over {[H4sIAAAAAAAC/+x9eXPbOLL4V0Hxt1W/ZEu27CRv5q23tl5lnGO8k8PlY2e3xnkqiGxSGJMABwBtazz6 7q9w8BJBUkp0WB7/lVjE0ehudDca3eh7z2dJyihQKbyjey/FHCcggeu/TnFEKJaE0dehBK5+CkD4nKTq N+/I4yAzThGRkAiEVRskJ0SgGxxn4A08ohr9lgGfegOP4gS8I0838wae8CeQYDWmnKbqg5Cc0MibzQbV iROWUdmcecJuUYLp1M4tGTKwtE1qhqnOGkCIs1h6R4cHBwMvwXckyRL9l/qTUPPn3uEgh49QCRHwOQDf QEwS4sROkH9CmYBAwRhxlqXIZ0nCKEo5hOQOBBpPW6AuBlgYXad6zB5C2YkDdEvkpJ9gpnknCLOBx0Gk jArQjHPMaBgTX9PNZ1SCISFO05j4GtDhr0IBdl8Z9C8cQu/I+3/DkiWH5qsYvuWccTNRfWFnIFjGfUD5 lAL9rFZ1gXkE0psNvE9MvmMZDTYIyycmkZlTEYeDz2hAVKN3mMSwAUiqcyI76WzgnQO/AW56rR2GEyqB UxwjMyuyDQfeJcWZnDBOft8EKmqzzQbev3BMAj3DhvBQTpijYJZvJb1XXvs+CPETTI85BEAlwbERxZyl wCUxOwrrVqNrmI5I0Nzf5jO6hik6eaMkjQCJQqYlD8//gwhFWohxA44EIQmN9r2BB3c4SWO1p1//dPL6 5PP5u89vPn36/u2/X388/fDW0wLxA9BITryjUiLm+3/gCfA5yFEJZRNE0wRVIP0WMG//iWP+70tJ3739 eDL86fuPb95+ej8cn96dheT4Pxbun97+pw90Lbl+ywhXvPjLHJpd6/pSDMHGv4KvRcxrXwF6ltEm3cYc U3/ikJkDpXkTIi05G1+BBiNJlAC+90LGEyyVQsAS9vSvDhrADVA5Mj/fe0CV+vpFSe+Rmckb6D8S4BFU llEOwDPaBo2QmMsl4RESy0xUYQmNJNJLT2OQEDjgmKOIBWqQY7IGSxWJNQQUs3eS6wMRskmytNCmfXu+ 1Lue0YBZbMworWf7epdcMyuAxJzjaQMHFYjKaZwry+REiRAjwS7YNThYUuY/z4kQ9M+fL5D+iOQES+Sz LA7QGArrBZejA1LwgZDC6yOgmc4F7Q+aosccCmTXATX2h4sbtZp120LVqfUARXMXCMdmZzSmNmxlrbrm zrUgjxT/NzF5Sckdepsyf6JEmdCqWOGp2DaEyu9eeU3DcuC1bL8EhMARtHyTeMQxjWDU2lviAEutwnBg rAIcn9aZYr5TA1Up5vkpoWDvtl5uNtabNB9mUMFxucB53M4vr52G7WzUh7xvRc3cKvPp2kHdrtixLL8y mbOc2bKxvTS3nHm2qgPWs64tE6yC4HVQTZ2XzrWd85Do12JTLme+zVN9MXPuOONKRl0KI/7rGMnsr10U 0z3nYdMdXdO9IWHo4i7pNhvVh4aVZ1wKo+Kobkd3WXmC/A6j8VSaaebdBCkHodaC5ASQaopYqP+PgwCC oT9RkjgYBqDNNwRUalfBAuScB1kPqLk0YTfGKjSDa9Vg/Qe95qG19jS2qrhpQ/R2t7Im9cr2cHGAbdV3 cyewCeMS2c8I7tIYE0popOkLerA+dHcpt/eYj3EExyyOwbfOKKXtz4yl6MA6hxvCMjEqDx5z7JhRRALF gRjljZHI9O4Nsxi9P0a/snHtXPjdK8D48ODlXvD9i+/2XuGXL/fG/vi/9773D8av8DiEg7+Bc5VLLMc4 uprrifwRDgIOQoAYxcwvGKq+qvyLMqnVcVcde+EuVShGRX+UYv5bBhJJPI4BPUsxl9o6gQCNp8hg7Hlt 6eLl0XCYTPeEZBxHsKesX5FiH4ajGF9DKIYcpJL5jA6LeVwHt8i3J8aFVmHlg2FUxU22L/LFzZqgtzN4 nWfY+dNNRslvGSCi1V5IgKMIKHCsxJgigfaDrpKjnKdYF24HLZyz0CY7y2Joczu06ewCk6MAT6s2bpv1 VA7X6LwwkKINSlhcfrpX3xCog9y5P1p6pS0dByWszgVzlqWOU+Rmz4k9Jm+Lnathbz89LTJT18jbVbiG MH0aNx91UIXLtaIfGbt2uvmwn69lBY68CWPXbVtXf3uQjroqZIMcIeVi5vx2He45i+TtMk5O6ZUZax9Y ROgJNRRx7rT+s9YKTkSLnYA+ah/xNjwpblDONGKbAHEIgQP1W9yEWZJgPnVgWh89HMqgPIO4P1auNZtf 84NMv5JZ8ujT4mjKlzeooMFFzM/6f+dSKc5WMe9PwL8WavevzYGY5FJpZVownUwF8XGcG09uLqidd5f1 GzWmGJSoqo3diXkplsX46nG1Ln/CBohQwbiDHo2zf46+HpJsV8FUeWNlSua0Bnx9YRMsRgnjDq76BHcS pTgCRATCN5jE6tRWkmXMWAxYrzLBd6MU+Ch1Ohg+4juS4BjRLBkDVydDoJITdZoFrmfwKqE1By42pXAn RywMBTiCfvSFVnEdxUGNfQP6+EnzNTgPhSVt5lZeAKoDYAQKWUYDtbfKI63ogXneDMrRPIesQcXKrC7S SUYWE3+69fOEsdIgsbERC7H1edFjptF2YjodLnI1VM7WjpTtblpLmJXt1zMI2+4e22zABc9j1Zvxlpm3 i0q19FXiUbzJkrTdxTDqvybN/TL9LSWO+ps5XSgNQJyDtcHiXnrKBJGMb1Re5G6SjvCWVpGi/Xujwr/X hOsdiUFMhYQEXZ6d6DAhybiR8xkNgMdTQiOkLFIF+DPYj/bRVeFBHGf+NcihYAkMlVEwvPKe9zroHM6S xipdwHeTpN3ebiKw9DgmmFCXGsvjIVIsJXCFqf/9Be/9frD3ty/2370v9y8G372Y/cV9zN8S5uecvPbP vLUx3fIFPRMv/4jEHxMpU/E/fySQ/BEzH8d/SI6pIEDl86PhcP+vf+klaB77sSTFti0Ui828QtkooCM6 ovVcMH8ksCMOGmcDDnU7puumzg3gDfBOCDlQOTJGZZNnbydAEddjKN7ESAe42VuIgWZdM0Julj7TjijV NuQsQYfPEYcYS6IsSYZuJ8SfqP+kwJUgtJagGn7fKQq50eF1oFQnA4GxVFX3AYrIDVA0niKMVK8+jNUX bmZyIfAcpMv7bP1D3SFojtjT2UDfVefSZu4ehVZvUMy9CZjwTSMNfsUU9gMG/SK3mMS5Jqn4O/rQf/+k YEhj7GviU2SGQJorhBkE2djHGlMtcmptiZRjKf4tg2J0GzJnLvMkQzGh1yhLY4YDCFCxbb42Ss5i4mPF B1MHh5RORYTHLJOOydtdD/WxmpdkLMxRasOkEaNojP1rtXSjHZ7JaapwGU/R2wscPfcG3+wA0IcBtewF zhs1PrHMO1pDYFcO0TIeoPPqAartyqA9nK7jADXwIAzB+CKLkIo4ZrfabqFTd4QvLBo6aQevdCl8+u51 ajV7zGhIIocVHjP/WjNLqYhHOjCeyOkZRHDnXL6zW2FNdHfI1VePVT7XoWfOwSIr6cDP5dmJwww3lhZG ShUrswoja7WglLMbEhSy1VpaxnA6NCaWZEMzjbG16nivXt93I6Lz0vkCR0teEBZqcYGDaptauywMTuMr O50LHqn+lZt5foyNLKdZbLxYR5JnsFDAhzvea7t3uI4oti8toK/lClcNvF2T2MTSrcoY/hdwQRhtk1M3 5rMbXU3tIMDPOJHTcwWrlXRYEH+EM2NU60VoF6r6ueQCdbwxLgd2TaBorrPvzG+V1EVzVWcMhBIPKfkJ tBr49VaOCkNlDJgDf5cz3z9/vsjz9jQU+us8GGolyoZw2Fj4Gt6dox8vLk7R69MT1ZFIfZCzX8yPBda8 g/3D/QMFFEuB4pR4R97L/YP9A+ue1xgaqtUOdSakiZoynl5FBk3Bk8A78hTPvTdNBrWk1F/c3FI2GTaS IWeDJfqYRNflupjc0tmXuSTIFwcHK8suK0MpHBlmJqs01l8H3quDw7bRCvCG81lxRTJsX8dqCuGsesfq qflRlNNM4khok0Sx9pfZwEuZcNBZCy0wURpmS4OQP7BgulrMFbJx1sxVfWHwtbrJWkn01dR5dfCqv1OR 57oacmqlA4agTXrOBrV9PLzX/54EMyNEYjC6sk7sN/r3ktg1Irxqih/D13mocRn3GU93CpNmAW2YHLgF 4HuQLYg6eOLWJo4jkO0IntMfWsvaS2OrYy33elWrwtiN7TnvX1r3wDCBZGyfUOjWbh9twycdZy29bhWX QAJj4A9I1aGkoOCDYbvhfSaALy6LLRNOyGJSOSmaPy7RjJIqHjZEzYFzJEO/5dhi4KWZQ9S8DoJeIh92 ElkHq+0uiXEQLEDf9k2Vspj4eYJHpzA/zVs+SfMiVKJNnmusTr9NkG+DmyqSPy3JvX3RnwMzvDeY7ZX+ EvsTQ6J3nCWL2+SWcIEeYLdFv1oBsuvRN4EbNiDdsj+n32qkvyzpfMFaqHzYSmUsd53KZgU5lfMXuDrk f8wiYlyoTn+FjuJfk6eikSHgdFasTkK7HgtxiOpKvmVsVz8BHNjzzTnIvWPjsaxNXMZ8VP2X/8BjP4DD Fy//67u/o1MsJ/8Y/h39KGX6mcZTxx3pbPNGvnXpeke/fKkyUh4NgAskdHAQM3uxlYXUdzdhu1Cvem0T H/d1d/UvX2Y1DMUsEohlEmFk2u1V34sJdIxAB9oWsrOeTKzNmlirspg6baUOx7CNt12PvM2DeeuXSUrV rtNFXJ3VRTBDq4N+lM8/ZLdFGltfcZpTq2+PL2ylqt8rPLCwcfo43BJt+Gx3Gbfh6mDD7LtDXuN2JPdb /Su11S/T4CFJvIMnidfBOZkmVr/EU0ZPt0lzKZ4uABa4ANARpg/ClslEm7+/w5C5FDaCd/Wbuhb7s+b7 bfuwlZM6lW283gd1b8oHdeGBWD49ZxvNMktcyxTc0mfw6F3xWMwdNxLbjR03lg42yOw7ZOa0IbffyPma y6gWzh/69bciO5ViNSXhST3W34Fs05Ilfnf0akULNL9G+Q2xbLf+rjPj2vSr+1XOTkKLXYwq66TwAsJj eI/zzKWFFGon+Rx6tTLVo1GvPbuqTct2om4twu0x8btSvdsQZ+67xcqmWY0+XyCKW6nyp0juzUVyb1d1 d8R/b9TQXOg2SbHm7t0oDRoJ0CSObfUrhOMYBURIQv3y1qW8x5esTNdlHGE6RSxERIqScK4KUCYZkNyA u4BWiGMBzdeCnsKLvmEjfVt00Tq20leGFi3sy3jMkUUbPX1vPK7ITeI/VVhRuwPQ16mGQ5ugWtFHjQJ9 5jEzm1mXZwCb7hnPkxsb9nk983qNErc+kUPodkL+ddSdlSg1w9WRWknXdCJVWd+2jdJzOYCarC5cftAN bI7oOnFZT0Ntx2W+wNVibwI4lhP9iEEr6vRXUwdKWQyvT08s3hARKEsRpgHiGaXmQYQ6Jn/U4x/r8ReR /J/YsUVqMwIrX8CkMqZZBc/fyukz886qDZ/OILVnhtoMqAK5DySAiNdpmHNF7ee+O7jK40oNLpgrXRki rRmRdVdhNMYcUAUpunIqZYhQor2t9q0ftSuKx8JclrQa5yuM6NXfGjreKNtwIFT1rasuBtx4eMCrg7/1 dyoq3K7UL8qrLNrC5POyb3hf9lrAFVrbBf2yucLzj8URugiS2/2hXfg72NLm2CFn6GLI7z8X8ToZljrl tu6eoXnhSAx5Rhe0KaZnqukaId6cV8mpr4qXL3uPm3M9i5qznafL9SU31Gq8uixsZVYYeiNN7p3zE3HD ecWZ0/Bun4ao8fjw3hTsmLUyu5J4GV0zg7sGywuJLOWsWD87uVip5CL7ZPjOSWWsgF8VLw0njF33iM+M /qgb7QJfPYIDX7WkTpssFCn4JCS+5mNDwl0UiRb0lfLy8L5S3Gg2ZJm0XtEOkalQ/tk03BEmdwxUr+m0 LlHMfAlyT0gOOKnzdPGK3phQU+qmkSE4cNSMVGAjS6WdM5Dn4F+ekatV9Vol8A95oyeHmClG0CYbDTZ3 9CpxXFI556KyjuFaz1ndrrgf8mPFOlxbZvBvc2tJuJPDiUzi+rT90qeoxLV5r9WSPLZFN1dxqnQw5WKy bXhv/reAw6vCa33OLrvXH4ujqwvN7Q6uNnytVNq2S9qdU9jdWN6w5TeuCtZvu+PXdSPWKqjrlSkWktNO D7UAWdmrO8VABvgVysOiNnb1YjfloN9gyJmh8SCFVZlFWe2vNQkfauaEXlhr0oS5u4tZtHuhxQXoJs7I MMH+FX1T0PwIcUhj7JvK6zGLLJXVXykWgtDIdkNKhiAsEIfwquoNyllqd+SZ2/TMPdLrkGVm8G3dpdql tTL3Dlijhy/Wnzl6yvX7/LoYCHqna1zbygoYpRz27HbSx28TUAsBwijEJM44PF9xDkzOjs1ttqzMD0gY tp7235AwXL9Np2ZpE7AKPMTCXMxk1KxUmdim7vFueRr1cpay+jZ0gbdWz80biElCcvAeotxfdteYQg6i /wT5Oa+i1G+M2lJJj+UEWRavslye42w3TIGWq2k77gpMiktdaKvgDxdG5ua20bHHuk5ND+x11jrOOAcq 4ykSWZoyLgViNJ6iK++vV54uIBTH7NbW/qoXQ9PtSIgYBRQwEPT/SwR3REg0BVkr0PjXPG7NPPFXwn0S 7n1iFPY+YjkXD1Ap3nh15SzM2BnClmSxJCnmchgynuzlNbsq488Vxy161tHzuV6kTDKLiWotntZbhGZx l7U+o1Gr/d3Ul5ZqRQmzXTHeujtUjS9je32TrGpIpIF3t1c+DbIHd36cBbA31iynoytnLZ6Oc4mjqpBf /emgIHgE2zoiPDaeW4GSE4oepZi88kSx/qKypS3ZOW/tlXpwWavD1AK1dU139ShtSrau2TlYqwr79d5B Nczuugc1s6zEMWjLVw5t7c6u8IVTWxz1ta2Nutasorn6nY5kTgsNsqVa9d7Mi69iDngHw60aa8I00FWB dRZvUVH2lpPCCtcmTVmDO08oK3kjr0/657PNM4c9eBJq+a1s5Zjo1GeF00SZryD0J98Y1PU6vgOEhWA+ wdJUPbe4x7rLFW3QTSeC1CZSK9i/olf0s5wAvyUCBsr2zmeZYIHGABSVThBFezWEAVE1gLtUrX5QpHXr bLqY+PKKqtYTQnWJY64LDmv3bhVayZDkU4QjTOg+Qsc4joEjMWFZHCCfpdP5xmppFG7dbHl6eWGGKher 2tbQto/Qs08MUTBJ5krGIBaGgysqJ0QgIlCQmeLITHucdVFtBbUeWJhHo2lOEeuHK+TS/vOrZu7jB0Kv XYJq9apovgLz4u9ntj3nHU91lehcCj00O6smvYpIgU3J+5zVDbvhspI7nyLF8qvK4S32ec7JjCLNre5N burzOuVttyq2ft3hvfnPSXe0deWWYq23YX2XBTt3C/YwLqxyGq/SdRn5w5RDijmMKre7m4/dOjVAvMd8 rBPB4xh0SGJ5b7yWAp7z01kwzsxcay/p2Tq9mdBpsWI5EUrbWUWmtIaA3dpYAt+AjnoUiIU6UeYGtDlg bRO7NmONRwZJyC+wVMvuUlTQtcVnvYzOs7gjcvU9yAY9znSPdb7Y5J7R9XyTjxT8uxIs6iLQNmJCzzup ugGJUiHoV7gYBEjHBtCcIHbtBmj5PZt7zPR/RhzTCIb35f87bR1lUZ+pVht4t+Ty7MS1ZRWkexpSpFrU ahsVRqrDqxQQbg9P5y8773Fmu+Vv0sfNy7MTfaGEKtgJSVx1NhSO4i3YWCV3rdLKKhjZ8nA/+26ZdZ+4 toVrHxzDrpxXOYRiGGRJuvaDgOu+7E2WpGcQrvUlZDW+mqclyUIgvfo/wy2VwkL16Rm9+meKrQe5DT4o En2eqx1gHXtCMg41OzzsvzfQnMXB9N0Gc52ZuQv+WsfNUpW1vsKPpylQd+YxHDxUZ96K2dHSZwmO1JHJ 38yT5T3WNIkJvd6NG9RGFI8aMX+GVeJxDNo50PJaVJyr8m9ItTs36HpntOHa5HW3qZIvxD6oFezgm/UC WcbThoVAPuOmc2AuQSrRAsbKqj9xUzE/FmH2GEJ5BqEJ7R3ecxJN9N+dUb5unbzBGN8xyFsAqgXC7oX0 Frmboimg1msyzj0nUkKCnvn6zm4MCIicAEc4j6JmvLgaQSdvnucSpA6SZaMtwGO9nynmxR2fG8SctR/o o0ibjqme0wB64V9xja4YetToXOwUT044wChgOvqTZolidXnL7C/l1y+Drzqa3HMlu5qpaI3Es6eUs11P OeN6625UXDoHC1d+vjZMXMkSaPMDteUHbOzNE1aLfa67g+zTuntviNDrI/Nc3IyFzrt8ABrJSQt0hMrv XpXAESohAsMwby9w1DfHByzk3kcWkJAoet0/CF/Uq8MNlC+0xLLXaCvcmQ0u2HTSxtrMGL68ebCa2LJl pcSwp67dZ0uJNSqeSpx3m/axjBLrOiHR7r1qY5FtoiERtqeu1Bhgf262f2hWcd3CXdqYXn4DConbX2ZT u+JrlPX6My02qN2c0ESMAno2ziRKMdcvmheZEAmeKg7GN5jEeByvLA26orIKXDzprC3orDKo/LSWatda d9fVfp11eIv5zM6qzNq/vRCjrqj5XTt12VWVuZAt63raQJvZQIJl3AftoU2ARzC8D0BZU5q/fyifJtsc 5g1E9jjumKeA+NumqSyz+myMe84GTlYTL/ZRYfyESrbWBDQ9izu69GC1k5zZR6Nd0UlcB5UlqX5PYGce FdwEbvzK04QbeT0mrb4eEzZfjzHEWvPjMWaSrquKbvFlGnccUS9Ug0fnju144FXiaEdfd5WGVDn99b/b fNX1AkdrksUXONpemaKwhWuennjteN1Kal6YY81+0TS8lzha4FHXnNX6YrPV5n4sj/E4Udr+jqsTRQcb 2xc7dLhqQeyGr7BkIT2XOKcIkFk6ivG10v3qvNGWYJGl60qO1WMvHkq3mtvVsqT+z0ROzsHn4FTuupay DTpyCIANXPeMcYB4nqq2WgO5dU7NFegWC4RjDjiYIh/H3/rgTr0uZyVRTE9mC5ZiGpRFE0PCbTlrr6US qf7WlQxrEsLdBYZXyE6VaVqYyHUTbrPVW2r/1lF27/16K0c6V14hUMmAMRbEH+nm9hefsWsC5U8Kz5oK riKVtWq2CGiQMqKv/TIee0feEKdkeHPozb7M/i8AAP//8GNnXeXpAAA=] map[]}
serve.go:3: running "oapi-codegen": exit status 1`

**Comment by nopcoder** [comment]
@DataDavD looks from the output that you get a newer version of the `oapi-codegen`.
As part of the root project we got 'tools.go' that reference the oapi-codegen in order to lock the specific version.
Verify that you didn't `go get -u` by checking if your `go.mod` and `go.sum` are unmodified.
Running `make gen` on the root project should try to install the specifc versions and generate the code.
I'll check what changed in the oapi-codegen and maybe it is time to update and update the templates.

**Comment by nopcoder** [comment]
@DataDavD any luck build the generated code with the specific oapi-codegen library?

**Comment by DataDavD** [comment]
hey @nopcoder sorry for the delayed response. Was very busy over weekend so didn't get to touch/look at the code, but I should tonight. I'll let ya know how it goes. 

Thanks again for helping me debug!

**Comment by DataDavD** [comment]
Hey @nopcoder, I feel dumb as I realized for some reason my Go version tried to update the oapi-codegen library when I must have done a run a bit ago. Your suggested fixed the issue and now everything appears fine. 

I will start working on this issue now that I'm in a non-buggy state in my local repo. 

I can't thank you enough for being patient and very helpful. Thanks again for allowing me to contribute.

best,
dd

**Comment by nopcoder** [comment]
Hi dd, did you had any progress with this issue? would like to have this bug fix for the next release if possible. Will it be possible to frame it for the following week or two?

**Comment by DataDavD** [comment]
hey @nopcoder sorry for the delayed response. I thought I had messaged you prior about being out of town last week. I actually just got back in so I should be able to get this complete or at least a good place within the next week or two. If I have any further issues or think that it won't be doable by EOD Wednesday I'll let ya know and seek your guidance.

Thanks again for your help; and sorry for the delay.

best,
dd

**Comment by nopcoder** [comment]
Appreciate it, thank you! I can post a test code that will break that you can use if it will help.

**Comment by DataDavD** [comment]
Yea sure anything will help. Currently, I have something of the sorts, but I'm not too sure the specific place to put it although I believe it should be placed in `api.NewHandlerWithDefault`
`if r.URL.Path != BaseURL + "/" {
			writeError(w, http.StatusInternalServerError, err)
			return
		}`

**Comment by DataDavD** [comment]
hey @nopcoder I was wondering if you saw my last message. I'm still having a little trouble, but am hoping/wanting to finish this before the end of the weekend although I'm a bit unsure of myself, so if this is holding y'all up please tell me as I don't want to do that. In the meantime I will carry on trying to get something working, properly. 

Thank you.

Best,
dd

**Comment by nopcoder** [comment]
@DataDavD yea, I missed your previous message - sorry about that.
When we set up the routes we have the API's base URL - if you register a handler on that point it will handle all the calls that are not handled by the registered handlers of the open-api. So without any 'if' it will handle this specific case.

Regarding test code - hope this one helps:

// part of serve_test.go
```go
func TestInvalidRoute(t *testing.T) {
	handler, _ := setupHandler(t, "")
	server := setupServer(t, handler)
	clt := setupClientByEndpoint(t, server.URL, "", "")
	cred := createDefaultAdminUser(t, clt)

	// setup client with invalid endpoint base url
	basicAuthProvider, err := securityprovider.NewSecurityProviderBasicAuth(cred.AccessKeyID, cred.SecretAccessKey)
	if err != nil {
		t.Fatal("basic auth security provider", err)
	}
	clt, err = api.NewClientWithResponses(server.URL+api.BaseURL+"//", api.WithRequestEditorFn(basicAuthProvider.Intercept))
	if err != nil {
		t.Fatal("failed to create api client:", err)
	}

	ctx := context.Background()
	resp, err := clt.ListRepositoriesWithResponse(ctx, &api.ListRepositoriesParams{})
	if err != nil {
		t.Fatalf("failed to get lakefs server version")
	}
	if resp.JSONDefault == nil {
		t.Fatalf("client api call expected default error, got nil")
	}
	expectedErrMsg := api.ErrInvalidAPIEndpoint.Error()
	errMsg := resp.JSONDefault.Message
	if errMsg != expectedErrMsg {
		t.Fatalf("client response error message: %s, expected: %s", errMsg, expectedErrMsg)
	}
}
```

// part of serve.go
```go
var ErrInvalidAPIEndpoint = errors.New("invalid API endpoint")
```

**Comment by DataDavD** [comment]
Thank you for the info and help @nopcoder !!! I'll try and get this finalized tonight/tomorrow. If I still don't have something PR ready I'll hold off to avoid delaying this getting in the next release.

Thanks again!!

dd

**Comment by DataDavD** [comment]
Hey @nopcoder I believe I have (at least close to) what is required for the issue fix, but for some reason I have 2 tests failing. One f the failed tests is `TestInvalidRoute` you provided me but it is failing on the api client call (i.e. the line with `if resp.JSONDefault == nil`), and for more details the second failed tests is the TestLocalLoad. Am I forgetting to set some auth configs or something?

Last, here is my existing code for this issue fix https://github.com/DataDavD/lakeFS/commit/dfc3b78bff7b77da2ef9eca2a3a5306f1823f4bd

**Comment by DataDavD** [comment]
@nopcoder FYI I submitted a PR (https://github.com/treeverse/lakeFS/pull/2382). The tests passed, but I still had one test, `TestLocalLoad` that still wouldn't pass for some reason. However, I created the PR so we have a good place to review and maybe can also discuss why I'm getting an issue with that particular "local" test.

Thank you for your patience on this and letting me contribute.

Best,
dd

**Comment by nopcoder** [comment]
@DataDavD thanks! looking into the PR and I'll add my comments there.
Regarding the failed test - I wanted the error format to match our current default error format, so when the invalid API route fails, all the clients that use the same definition will parse an error as described in the swagger.
