### ISSUE TITLE
Serialization errors with export on Databricks

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2200]
A workaround was applied to solve issue #1847 using [init scripts](https://docs.databricks.com/clusters/init-scripts.html).
However new errors arose when calling the export:
It seems that Databricks use a custom HadoopConfiguration `GlobalHadoopConfiguration` that isn't serializable. We use `SerializableWritable` to pass the configuration to the workers for the FS discovery and copy.
```
Caused by: NotSerializableException: org.apache.spark.util.GlobalHadoopConfiguration
Serialization stack:
	- object not serializable class: org.apache.spark.util.GlobalHadoopConfiguration
	- object (class $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw$$iw, $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw$$iw@58ef2bea)
	- field (class: $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw, name: $iw, type: class $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw$$iw)
	- object (class $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw, $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw@68305186)
	- field (class: $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw, name: $iw, type: class $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw$$iw)
	- object (class $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw, $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw@2ff5b5ed)
	- field (class: $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw, name: $iw, type: class $line1866b642d1ac4207a239f3c39765385627.$read$$iw$$iw$$iw$$iw)
	- object 
```

**Comment by arielshaqed** [comment]
> We use `SerializableWritable` to pass the configuration to the workers for the FS discovery and copy.

Hmmm... but why do we need to do this?  Could we "just" extract the necessary parameters from `hadoopConfiguration` into our operators?  Because it seems truly strange that we need the entire configuration to perform some operation, it should either already be on every worker or we should care about only a few fields from it.

@johnnyaug and/or @guy-har do you have more info?

**Comment by arielshaqed** [comment]
> We use `SerializableWritable` to pass the configuration to the workers for the FS discovery and copy.

Hmmm... but why do we need to do this?  So I had a look, and this is in order to create a FileSystem (which needs a configuration).  This is obviously problematic.

@johnnyaug and/or @guy-har do you have more info?

**Comment by nopcoder** [comment]
Not reproducible
