### ISSUE TITLE
lakectl --help output

### ISSUE THREAD

**Issue by karentamrazyan** [treeverse/lakeFS#2204]
running `lakectl --help` of the current lakefs version returns the following output:

```
Available Commands:
  actions         Manage Actions commands
  auth            manage authentication and authorization
  branch          create and manage branches within a repository
  commit          commit changes on a given branch
  completion      Generate completion script
  config          create/update local lakeFS configuration
  diff            diff between commits/hashes
  gc              manage garbage collection configuration
  help            Help about any command
  ingest          Ingest objects from an external source into a lakeFS branch (without actually copying them)
  log             show log of commits for the given branch
  merge           merge
  metastore       manage metastore commands
  repo            manage and explore repos
  show            See detailed information about an entity by ID (commit, user, etc)
  tag             create and manage tags within a repository
```

A few remarks to this output:

1. it seems like not all available tier 1 commands are listed in this list. E.g. "fs" is not in the list.
2. Some descriptions of the commands start with a capital letter ("Generate completion script"), some with a lowercase letter ("manage metastore commands"). That's inconsistent. I slightly tend to think that starting with a cap letter is better.
3. The "merge" command descriptions is not very descriptive :)

**Comment by arielshaqed** [comment]
1. Decision: capitalize all short command descriptions.  Rationale: It's what the [Cobra docs](https://github.com/spf13/cobra/blob/v1.2.1/user_guide.md#example) show, consistently.
1. Verify we don't hide important commands like fs.
