### ISSUE TITLE
Support repo + bucket creation

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2206]
Some users create multiple repos on many buckets (consider e.g. repo-per-user scenarios).  If the bucket does not already exist, that's an additional configuration hurdle.  WIBNI we could prompt-to-create the bucket for a repo, based on its namespace?

## Pros

* Customer demand
* More integrated
* Streamlined repo creation

## Cons

* Less modular ("more integrated" as a con...)
* More complex basic lakeFS configuration: need to grant `s3:CreateBucket` permission to lakeFS to enable this feature; might be mitigated if we SimulatePolicy to check whether we have this permission)

**Comment by dsgibbons** [comment]
Are they any plans to implement this?

**Comment by arielshaqed** [comment]
> Are they any plans to implement this?

Sorry.  To be blunt: We've not seen much demand for this.  Unfortunately this is the kind of feature where the user journey is really important.  Right now it's just WIBNI ("wouldn't it be nice if..."), to progress we would need specific use-cases that detail:
* How to transform a repository name to a storage namespace URL
* The desired UX: I assume webUI?

This issue is the right place to provide such a user story or feature request, so we can prioritize.

**Comment by dsgibbons** [comment]
I don't need this anymore - I hadn't realised that multiple repositories could share a single bucket via different prefixes.

**Comment by arielshaqed** [comment]
> I don't need this anymore - I hadn't realised that multiple repositories
> could share a single bucket via different prefixes
>
Sorry, I definitely dropped this one; some bad timing here.

If anyone finds this issue and wants to reopen, *please do*. We'll need a
use-case in order to understand what exactly it should do.

>
