### ISSUE TITLE
LakeFS API client is sensitive to trailing slashes

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2214]
### Steps to reproduce
- Run spark with lakeFSFileSystem, and configure its lakefs endpoint to end with "/", e.g. spark.hadoop.fs.lakefs.endpoint=https://example.lakefs/api/v1/ 
- Try to use the file system to write a file
- The write will fail silently (as a result of #2190), and no objects are written to lakeFS. 

### Potential solutions
1. Handle trailing slashes on the JavaOpenAPI client by adding a custom layer as we did with the Python OpenAPI client. 
2. Make the LakeFSFileSystem sanitize the value configured for spark.hadoop.fs.lakefs.endpoint

**Comment by johnnyaug** [comment]
Went with solution #2.
To do #1, we _could_ extend the ApiClient class of the Java API client with one of our own. However, this means that all users will need to remember to use it rather than the standard ApiClient - which is essentially the same as remembering to trim the "/".
