### ISSUE TITLE
policy schema enforces small letters 

### ISSUE THREAD

**Issue by LeonardAukea** [treeverse/lakeFS#2218]
I think there is a bug in the API. Here you see that the required values need to be small letters for the  `effect` statement. whereas the documentation states and convention is  to use `"Allow"` , `"Deny"`. This should be the only accepted format in the schema: 

https://github.com/treeverse/lakeFS/blob/2c620a5db984ce96eb7b87a32209507486c57861/api/swagger.yml#L647

```
Error executing command: request failed: [400 Bad Request] request body has an error: doesn't match the schema: Error at "/statement/0/effect": value is not one of the allowed values
Schema:
  {
    "enum": [
      "allow",
      "deny"
    ],
    "type": "string"
  }

Value:
  "Allow"
```

**Comment by LeonardAukea** [comment]
This leads to you only being able to attach policies that has no "effect". As in it seems like they do not work when given In lowercase.

**Comment by itaiad200** [comment]
Thanks @LeonardAukea for reporting this!
Indeed our docs showed examples that did not work. See PR #2223 for the fixes. `effect`, `action` and `resource` should be lowercase.
