### ISSUE TITLE
Support policies to limit lakefs users to repo operations for specific buckets/blobs 

### ISSUE THREAD

**Issue by LeonardAukea** [treeverse/lakeFS#2220]
According to the documentation [Authorization](https://docs.lakefs.io/reference/authorization.html) It seems like we are not able to limit the scope for lakefs users to a specific bucket/blob. 

## Use case 

We require to set up a multi-tenant data development environment such that teams are limited to managing repositories backed by a specific blob/bucket. This includes the create, delete repo operations only for repos that reside in a given bucket x. This would enable better encapsulation for data teams and make it easier to manage the stores from the cloud providers perspective as well. 

Using AWS as an example, I believe that being able to `lakectl auth users policies attach`  a functional policy like below to a lakefs user would suffice: 

```json 
{
  "Action": [
    "fs:*"
  ],
  "Effect": "Allow",
  "Resource": ["arn:aws:s3:::<BUCKET_NAME>", "arn:aws:s3:::<BUCKET_NAME_WITH_PATH_PREFIX>/*"]
}
```

Maybe, this could be generalised by providing an `arn` for the storage namespace: `arn:lakefs:fs:::storage/mystorage/*`.  If it's so that the mapping between storage namespace and repo is not 1-1, rather One To Many.

**Comment by arielshaqed** [comment]
# Proposal

I plan to implement this following the approach outlined by @ozkatz in #2246: use a separate action and a new ARN resource type "`storage`" to match storage (namespaces).

@LeonardAukea WDYT?

# Example

## Problem

Allow users to create only repos whose name starts with `internal-${user}-` on buckets whose names start with `initech-corp-dev-${user}-`.

## Solution

Attach a policy that looks something like this:

```json
{
  "statement": [
    {
      "action": [
        "fs:CreateRepository"
      ],
      "effect": "allow",
      "resource": "arn:lakefs:fs:::repository/internal-${user}-*"
    },
    {
      "action": [
        "fs:AttachRepositoryNamespace"
      ],
      "effect": "allow",
      "resource": "arn:lakefs:fs:::storage/s3://initech-corp-${user}-*"
    }
  ]
}
```

## How does this work?

With the planned change, creating a repository is conceptually split into creating the repository (name), then attaching it to a storage namespace.  Users must have _both_ permissions.

In the above example, users get the "repository" name permission from the `fs:CreateRepository` action, and the "storage namespace" permission from the `fs:AttachRepositoryNamespace` action.  lakeFS IAM looks up each permission, and the above policy has statements allowing each, so the user is permitted to create that repository.

If a user tries to create a repository under another user's namespace, say `ariels` tries to create a repository with any name that uses storage namespace `s3://initech-corp-ozkatz-secret`, then there is no statement allowing `ariels` to `fs:AttachRepositoryNamespace` and create repository fails.
