### ISSUE TITLE
Add lakectl command verify endpoint and credentials are correctly configured

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2226]
Add a command, e.g. `lakectl doctor`, that does basic diagnosis of the configuration:
1. lakeFS API is accessible at configured endpoint.
1. authentication succeeds with lakeFS API.
1. S3 gateway is accessible at configured endpoint, also for host-based access
   * If host-based is broken but path-based works, it's better to state this and keep going, that's good enough for _some_ users!
1. authentication succeeds with S3 gateway.

Now troubleshooting many basic setup issues might be kickstarted with this command.

**BONUS:** In order to do this easily, the UI should generate a _complete_ `lakectl.yaml` config file that includes `s3_endpoint`.  While `lakectl` itself does not (currently?) use this, it means that users can verify their configuration and also have a single source for the correct S3 endpoint.

This can help setup and diagnosing on our #help channel.

**Comment by idanovo** [comment]
As discussed with @arielshaqed, I'll start by implementing a thin version of this command:

- Attempt a simple API that should always succeed.
- If it succeeds, we are all good
- If it fails, try to decode:
    - Host not found (bad host on the endpoint)
    -404 (bad path on the endpoint)
    - Unauthorized (bad auth keys)
    - 502 (bad setup between lakectl and lakefs).

**Comment by idanovo** [comment]
was done partially in #2948
