### ISSUE TITLE
Actions Feature Request: Post commit/merge hooks

### ISSUE THREAD

**Issue by tvanderwal-lmco** [treeverse/lakeFS#2227]
One feature that would be helpful is to be able to fire a webhook after a successful commit or merge event. One specific use case would be to initiate some down stream automation such as a kubeflow pipeline after quality checks on the branch have passed.

**Comment by ozkatz** [comment]
Thanks @tvanderwal-lmco - this is strong validation for #2182 but with yet another use case for why this should exist.

**Comment by tvanderwal-lmco** [comment]
No problem @ozkatz! Sorry I didn't see this was already an open issue. Do you want me to close this one and make a comment on #2182 instead?

**Comment by ozkatz** [comment]
That would be helpful! Thanks @tvanderwal-lmco :)
Closing as dup of #2182 for now
