### ISSUE TITLE
Support an `exec` hook execution driver

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2231]
Currently, lakeFS supports only Webhooks. While easy to understand, they are not always easy in terms of operations:

* They require a server to be deployed and provide an uptime SLA
* They require setting up network communication between said server and lakeFS
* Depending on security protocols, they often require some sort of authetication
* They make very simple things more complex than needed (i.e. a one-liner in bash now needs to be wrapped in a web application)
* They make it hard to experiment locally, if lakeFS is running in Docker container due to Docker networking woes (a Docker container by default cannot access network ports of the hosting machine)

To make hooks easier to get started with, lakeFS should support a simpler type of hooks - that execute some behavior directly by the lakeFS server. 

This could be calling out to a command line directly, doing `docker run` on a provided image, or integrating with existing orchestration/scheduling tools that already exist in the organization such as Kubernetes (**discovery required**)

**Comment by nopcoder** [comment]
@ozkatz can we close this one? 

https://github.com/treeverse/lakeFS/blob/0ca69c4f0f7550e8af4e513a305a6c8732ae5d3a/design/rejected/k8s-job-hook.md

**Comment by ozkatz** [comment]
Yes. As we're rethinking how to execute hooks in a better way, I suggest closing this issue in the meantime as it is unlikely to be implemented in its current form.
