### ISSUE TITLE
Link to setup on Auth Login Page

### ISSUE THREAD

**Issue by adunuthulan** [treeverse/lakeFS#2235]
When running lakeFS without easy access to the logs (like when lakeFS is deployed on the cloud), it’s not immediately clear how to reach the setup page from the initial auth ui page. Should there be a link to the setup page on this page? Should the user be redirected to the setup page on their first run of lakeFS?

![Screen Shot 2021-07-13 at 10 47 04 AM](https://user-images.githubusercontent.com/29340929/125500663-d62d4c20-aa27-4cff-b5bc-8a5d1437be79.png)

**Comment by johnnyaug** [comment]
Similar: #2388
