### ISSUE TITLE
Python Client unable to upload objects from a stream

### ISSUE THREAD

**Issue by tvanderwal-lmco** [treeverse/lakeFS#2241]
I was putting together a demo pipeline and noticed that even though content in `upload_object()` can be a file_type, it needs to be an actual file on disk in order to be uploaded to lakefs. When generating data in a stream this requires a work around to write the data to a temp file, then reread that temp file to send in the upload. 

Here is what I was expecting would work and the error as well as what the workaround for this example is. Note that the `StringIO` object is already an open file, the same error happened when trying to use a `ByteIO` streamer as well

```
from faker import Faker
import logging
import os
import io
from random import randrange
from lakefs_client import models
import lakefs_client
from lakefs_client.client import LakeFSClient

# lakeFS credentials and endpoint
configuration = lakefs_client.Configuration()
configuration.username = os.getenv("ACCESS_KEY_ID")
configuration.password = os.getenv("SECRET_ACCESS_KEY")
configuration.host = 'https://lakefs.<redacted>.lmco.com/'
configuration.ssl_ca_cert = '/etc/ssl/certs/ca-certificates.crt'

client = LakeFSClient(configuration)

fake = Faker()
path = fake.pystr()

output = io.StringIO()

for line in range(randrange(1000)):
    output.write(f"{fake.name()},{fake.zipcode()},{fake.city()},{fake.state()},{fake.pyint()}\n")
client.objects.upload_object(repository='ai-summit', branch='pipeline-demo', path=f"{path}/00001.csv", content=output)
``` 

Error: 
```
~/.local/lib/python3.6/site-packages/lakefs_client/api_client.py in files_parameters(self, files)
    549                         "for %s must be open." % param_name
    550                     )
--> 551                 filename = os.path.basename(file_instance.name)
    552                 filedata = self.get_file_data_and_close_file(file_instance)
    553                 mimetype = (mimetypes.guess_type(filename)[0] or

AttributeError: '_io.StringIO' object has no attribute 'name'
```

Workaround: 
```
with open(f"tmp.txt", 'w+') as f:
    for line in range(randrange(1000)): # fake 100 lines per file
        f.write(f"{fake.name()},{fake.zipcode()},{fake.city()},{fake.state()},{fake.pyint()}\n")
with open(f"tmp.txt", "r+") as f:
    client.objects.upload_object(repository='ai-summit', branch='pipeline-demo', path=f"{path}/00001.csv", content=f)
```

**Comment by arielshaqed** [comment]
Thanks for the the report! This file is auto-generated by openapi-generator from swagger.yml, I may have difficulty fixing it here rather than up streaming the bug. I'll have more info about this tomorrow.

Note that uploading requires knowledge of content length - but that doesn't mean the stream needs to have a filename!

**Comment by arielshaqed** [comment]
This appears like an issue with the [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator) for Python.  [The OpenAPI spec](https://swagger.io/docs/specification/2-0/file-upload/) is unclear (to me) about whether a `filename` argument is actually required on a file-upload specification.  And [RFC 7578](https://datatracker.ietf.org/doc/html/rfc7578#section-4.2) appears (to me) to recommend this behaviour (as a "SHOULD"):

>    For form data that represents the content of a file, a name for the
   file SHOULD be supplied as well, by using a "filename" parameter of
   the Content-Disposition header field.  The file name isn't mandatory
   for cases where the file name isn't available or is meaningless or
   private; this might result, for example, when selection or drag-and-
   drop is used or when the form data content is streamed directly from
   a device.

@nopcoder do you reckon we should open a bug upstream to allow file uploads with no filename?  Is it a defect in the actual OpenAPI spec?

**Comment by arielshaqed** [comment]
@tvanderwal-lmco I'm unable to put you as a reviewer on #2244, but I would of course be *very* glad if you could verify that it resolves your issue and/or review it.

**Comment by arielshaqed** [comment]
Adding @tvanderwal-lmco  for traction: I shall release a version with this fix by tomorrow (2021-07-19), and would be happy if you could TAL at it before then.

**Comment by tvanderwal-lmco** [comment]
@arielshaqed Thanks Ariel! I've been out on leave the last month but I'm back in now and will upgrade/test this. I appreciate you guys diving into it :)
