### ISSUE TITLE
Support using underlying S3 buckets in multiple regions

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2245]
Currently, the S3 block adapter is tied to a specific S3 region.
In some cases, it is desirable for a single lakeFS installation to host repositories backed by buckets in different regions.

This might be possible without adding additional configuration by probing S3 to get a bucket's region (either by directly calling some API endpoint, or by attempting to use a default region and capturing the correct region from the resulting error message if any).

**Comment by johnnyaug** [comment]
@talSofer, a thought about multi-region lakeFS: unless you're using the lakeFS HadoopFS for all heavy operations, it's probably not the best practice - cost and performance wise - to deploy lakeFS on a different region than its buckets. Our documentation should note the implication of doing that.

**Comment by talSofer** [comment]
The tasks that implement this feature: 
- https://github.com/treeverse/lakeFS/issues/2324
- https://github.com/treeverse/lakeFS/issues/2325
- https://github.com/treeverse/lakeFS/issues/2326

FYI @johnnyaug
