### ISSUE TITLE
Migrate Down runs all down migrations

### ISSUE THREAD

**Issue by adunuthulan** [treeverse/lakeFS#2270]
`lakefs migrate down` runs all the down migrations in the ddl folder, which destroys all data within postgres. As an example, you can spin up lakeFS and go through the setup to create an admin user. If you then run `lakefs migrate down`, you will be able to run the setup again to create a new admin user. 

`lakefs migrate down` runs the `MigrateDown` function, which in turn runs the golang-migrate `Down()` function. This function reads the down migration scripts until there are no more migrations, which is likely not the behavior expected for `lakefs migrate down`.

**Comment by itaiad200** [comment]
I think we should remove this command completely. Operators of lakeFS can easily use this by mistake and ruin their installation.

**Comment by nopcoder** [comment]
- we can remove the command from lakefs cli (until somebody will ask for something like that)
- for now, we can use `migrate goto --version 0` to rollback changes to the starting point
- the migrate to lower level should be added to the test
