### ISSUE TITLE
Remove default value for db_connection_string

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2302]
It is hardly usable, and it masks away errors when the config isn't loaded properly.
Better to exit if that value is missing, instead of returning a connection error which isn't always very indicative to the fact that there's no db running in the other end.

**Comment by johnnyaug** [comment]
The default value exists in order to allow the usage of [Postgres environment varaibles](https://www.postgresql.org/docs/9.3/libpq-envars.html) instead of a connection string, as requested by a user. The solution to this issue should not remove this support.

**Comment by arielshaqed** [comment]
@johnnyaug would it be OK to have a default empty value (or an invalid value such as `not-set://...`, and fail after loading configuration if the connection string is still empty?  I believe that would give us the desired failure when _no_ configuration was applied, while still allowing configuration using environment variables.

**Comment by johnnyaug** [comment]
Do you mean, that in order to use environment variables I would have to explicitly set the connection string according to some convention?

**Comment by arielshaqed** [comment]
Analysis: lakefs server code works fine with an empty DB connection string.  The only problem seems to be DB migration.  Module [golang-migrate/migrate/v4](https://pkg.go.dev/github.com/golang-migrate/migrate/v4) treats connection strings separately from the underlying database: it parses the schema to determine the name of the DB driver to use, see [this call to iurl.SchemeFromURL](https://github.com/golang-migrate/migrate/blob/b690b78e22b7aea506ef68bdcfa37b0f10994a99/migrate.go#L150).  So we have special-case handling of empty strings in _our_ [getMigrate](https://github.com/treeverse/lakeFS/blob/00a7c63610884edc783a51cd779927db80ba3394/pkg/db/migration.go#L101).  And that means envariables don't work as they should, anyway.

**Comment by arielshaqed** [comment]
Analysis: lakefs server code works fine with an empty DB connection string.  The only problem seems to be DB migration.  Module [golang-migrate/migrate/v4](https://pkg.go.dev/github.com/golang-migrate/migrate/v4) treats connection strings separately from the underlying database: it parses the schema to determine the name of the DB driver to use, see [this call to iurl.SchemeFromURL](https://github.com/golang-migrate/migrate/blob/b690b78e22b7aea506ef68bdcfa37b0f10994a99/migrate.go#L150).  So we have special-case handling of empty strings in _our_ [getMigrate](https://github.com/treeverse/lakeFS/blob/00a7c63610884edc783a51cd779927db80ba3394/pkg/db/migration.go#L101).  And that means envariables don't work as they should, anyway.

Not clear what configuration would (ever) work in an expected manner with both server migration _and_ regular ("`pgx`-style") operation.  Best I can figure out is to fix upstream.
