### ISSUE TITLE
Fix failing HadoopFS tests

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2309]
Some of the Hadoop FileSystem [contract tests](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/filesystem/testing.html) are not passing and have been commented out.

Analyze the reason for the failures, and decide whether or not a fix in lakeFS HadoopFS is needed.
It's possible that some tests are not applicable to lakeFS, or that the tests needs to be adapted to lakeFS.

The list of failing tests:
- In TestLakeFSFileSystemContract:
  - [ ] testWorkingDirectory
  - [x] testRenameFileMoveToNonExistentDirectory
  - [x] testListStatus
  - [x] testRenameDirectoryMoveToNonExistentDirectory
  - [x] testRenameFileAsExistingDirectory
  - [x] testListStatusThrowsExceptionForNonExistentFile
  - [x] testOverwrite
  - [x] testMkdirs
  - [x] testRenameFileAsExistingFile
  - [x] testRenameDirectoryAsExistingFile
  - [x] testRenameNonExistentPath
- In TestLakeFSContractRename:
  - [x] testRenameNonexistentFile
  - [x] testRenameFileNonexistentDir
- In TestLakeFSContractDelete:
  - [x] testDeleteDeepEmptyDir
- In TestLakeFSContractCreate:
  - [x] testCreateFileOverExistingFileNoOverwrite

**Comment by nopcoder** [comment]
Fixing the contract was done by aligning the lakeFS file system with s3a v2.7 implementation for the above tests.
