### ISSUE TITLE
Support s3 gateway and webui on different ports

### ISSUE THREAD

**Issue by tc-imba** [treeverse/lakeFS#2312]
In Minio, the s3 gateway and webui are setup on two different ports, which makes it possible to use the s3 gateway without a domain. 

Is it possible to have a config item so that the s3 gateway can be exposed to another port, and also do not use hostname checking when receiving s3 client requests if the extra port is configured?

This may help local development since it's not easy to setup wildcard dns records (*.s3.lakefs.example.com) locally unless a local dns server is installed, since we can not set wildcard hosts in /etc/hosts.

**Comment by arielshaqed** [comment]
Hi @tc-imba,
This is a common request that is very understandable. So I shall try to write it up here. _DNS configuration is required to support the full S3 protocol_, also if using minio. See the full thread here: minio/minio#4681.
The underlying issue is that S3 host based addressing rputs the

**Comment by arielshaqed** [comment]
# suggested action
Document the whole addressing style saga explicitly (@peacing : is this a FAQ? An "advanced"  explanation? Something else?), and close. The separate endpoints are not a solution to this afaict.

**Comment by tc-imba** [comment]
Thanks for your explanation. Now I understand why the domain is necessary in lakefs.

I'm using rclone which seems only support the sub domain style apis, so I have to setup dns. I can't find any information in the docs about how to set up dns on localhost. [dnsmasq](https://thekelleys.org.uk/dnsmasq/doc.html) can be a good choice, but the configuration is still quite complex. Instead of using it, I finally discovered that the aliases feature in docker network can simply setup dns records (which supports subdomains). In `docker-compose.yml`, we can write:

```yaml
lakefs:
  image: treeverse/lakefs:0.46.0
  container_name: lakefs
  ports:
    - "8000:8000"
  environment:
    LAKEFS_GATEWAYS_S3_DOMAIN_NAME: s3.lakefs.example.com:8000
  networks:
    default:
      aliases:
        - s3.lakefs.example.com
```

Then in other containers in the `default` network, we can access the s3 api endpoint though `http://s3.lakefs.example.com:8000` and the subdomains (*.s3.lakefs.example.com) will be automatically handled by docker network. The web gui and api endpoints can still be accesed through `http://lakefs:8000` in the containers, or through `http://localhost:8000` on the host machine.

Maybe this will be helpful to someone who also needs a devlopment server on localhost. Is it possible to include a config like this in the docs?

**Comment by arielshaqed** [comment]
> Thanks for your explanation. Now I understand why the domain is necessary in lakefs.

I know, it is unfortunate.

> I'm not purely on localhost, I'm using `rclone` in a container within the same docker network of lakefs, but it seems that `rclone` only support the sub domain style apis, so I have to setup dns. I can't find any information in the docs about how to set up dns in docker. [dnsmasq](https://thekelleys.org.uk/dnsmasq/doc.html) can be a good choice, but the configuration is still quite complex. Instead of using it, I finally discovered that the aliases feature in docker network can simply setup dns records (which supports subdomains). In `docker-compose.yml`, we can write:
> 
> ```yaml
> lakefs:
>   image: treeverse/lakefs:0.46.0
>   container_name: lakefs
>   ports:
>     - "8000:8000"
>   environment:
>     LAKEFS_GATEWAYS_S3_DOMAIN_NAME: s3.lakefs.example.com:8000
>   networks:
>     default:
>       aliases:
>         - s3.lakefs.example.com
> ```

What docker version is this, please?  When I try the same on my system I do get `s3.lakefs.example.com`, but not its subdomains.  I would obviously very much like to be able to run this...

However, note that AFAICT [`rclose` uses path-style addressing by default](https://rclone.org/s3/#s3-force-path-style).  Which means the above should just work.

> Then in other containers in the `default` network, we can access the s3 api endpoint though `http://s3.lakefs.example.com:8000` and the subdomains (*.s3.lakefs.example.com) will be automatically handled by docker network. The web gui and api endpoints can still be accesed through `http://lakefs:8000` in the containers, or through `http://localhost:8000` on the host machine.

> Maybe this will be helpful to someone who also needs a devlopment server on localhost. Is it possible to include a config like this in the docs?

Please let me know if you can ascertain that the above configuration works.  Perhaps you could disable path style, maybe try
```
export  RCLONE_S3_FORCE_PATH_STYLE=false
rclone ...
```
and see whether that still works?

**Comment by tc-imba** [comment]
> Please let me know if you can ascertain that the above configuration works. Perhaps you could disable path style, maybe try
> 
> ```
> export  RCLONE_S3_FORCE_PATH_STYLE=false
> rclone ...
> ```
> 
> and see whether that still works?

Thanks, this works.

> What docker version is this, please? When I try the same on my system I do get `s3.lakefs.example.com`, but not its subdomains. I would obviously very much like to be able to run this...

After a further test, I find out that the subdomain network doesn't work in docker. The reason why I successfully execute `rclone` in the container is that the rclone verison is v1.45 in the container while it is v1.56 on my host machine. I think the default value of `RCLONE_S3_FORCE_PATH_STYLE` has been changes in certain version of `rclone`.

Sorry for the misleading on docker subdomain network, but at least it works for path-style routing and it's enough for development usage as long as lakefs doesn't drop support for path-style.

**Comment by arielshaqed** [comment]
Cool!  AFAICS even AWS cannot drop path-style for the foreseeable future.  See the note at the top of https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/ for the latest on their progress in dropping support for this (spoiler: I am not holding my breath...).

@tc-imba can we close this issue?

**Comment by itaiad200** [comment]
With the DNS now optional and path-style support in AWS not going away soon, I'm closing this issue. @tc-imba reopen if you think this is still needed.
