### ISSUE TITLE
Links to the documentation on the webui

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2316]
Refer users to the documentation from the webui. For example, the Create-Repo dialog can link to the quickstart-create-repo doc page. Inspiration taken from Airbyte; while choosing the postgres Source:
![image](https://user-images.githubusercontent.com/9861474/127979559-625708c7-6159-4ec3-b137-aecabc4fe527.png)

**Comment by DataDavD** [comment]
I'd be happy to take complete this Issue if that is fine.

**Comment by itaiad200** [comment]
All yours @DataDavD ! Let me know if you need any assistance.

**Comment by DataDavD** [comment]
thanks @itaiad200. FYI, I will be out of town this weekend, so I will most likely start really working on this issue (as well as Issue #2415) when I return Monday next week (hopefully that isn't an issue).

Thanks again for the help and letting me contribute to lakeFS.

best,
dd

**Comment by DataDavD** [comment]
hey @itaiad200 FYI. I may get to this later than I originally anticipated as I'm only really just now getting started with #2415 (comment) (had some work/life issues that took up a large part of time last couple weeks). I'm happy to still work on this once I'm done with the other issue, but I just wanted to give you an update, just in case some knows/wants to work on this now/ASAP.

In the meantime, I'm still going to give this a more thorough look tonight since the last time I looked at the code for this issue a couple weeks ago I couldn't directly make how where the change should be centered. If I have more question I'll post those here as well as the lakeFS slack server.

Thanks again for all y'alls help

Best,
David

**Comment by DataDavD** [comment]
hey @itaiad200 I'm pretty rough in Javascript and have about 0 experience with React, but I quickly mustered up this. I am guessing this is on the right track, but I wasn't sure how to get a better button and/or link and make it look better/placed better on the Create a Repo form. 

Should I add something similar for other parts of an instance? Or should I separate such PRs as adding documentation links to one page/form per PR?

Thanks in advance for your help.

Best,
david

**Comment by itaiad200** [comment]
Hey @DataDavD , thanks for the contribution. I have viewed the PR. 
In order to support our users best (and close this issue) I think we would need more links like the one in #2506.

Some more possible places for helper text:
1. Setup page.
2. Administration auth page.
3. Branches tab (link to our [branching models](https://docs.lakefs.io/understand/branching-model.html))

**Comment by johnnyaug** [comment]
Mockups:
![image](https://user-images.githubusercontent.com/3149885/136692208-1df80c15-259c-4ff7-a120-478520598ea2.png)
![image](https://user-images.githubusercontent.com/3149885/136692216-81b78923-3422-4fd0-8f94-2c30f519893a.png)
![image](https://user-images.githubusercontent.com/3149885/136692230-eb6e3a31-62e1-4f99-87f8-3757c7a32e2b.png)
![image](https://user-images.githubusercontent.com/3149885/136692240-e52202ae-c221-47f3-b211-586427dc9309.png)
![image](https://user-images.githubusercontent.com/3149885/136692445-dfd83c44-3e58-48be-87be-4c2984adbdc5.png)
![image](https://user-images.githubusercontent.com/3149885/136692615-c111b1e1-6745-4678-965a-a0dcda23d79d.png)
![image](https://user-images.githubusercontent.com/3149885/136692576-b5d402d3-ab4b-4575-82be-b04e3fb04763.png)

**Comment by DataDavD** [comment]
@johnnyaug @itaiad200 Update: I'm finally making some actual progress. 

- Create a Repo page: currently I am getting the `<div>/<p>` style text under the Modal.Title, but for some reason I'm running into the problem where the `Modal.Title` is too far left or the `...Learn More` text is a tad too far right if I correct the Title. Also, although I got the text to be closer to the `Modal.Title` there is no more room between that and the start of the form (unlike the mocks @johnnyaug provided); do y'all have any advice on how to decrease the white space between the `...Learn more` text and the start of the form below? I will continue working on this.
![Screen Shot 2021-10-14 at 3 38 03 AM](https://user-images.githubusercontent.com/39511285/137302355-ca88b367-b890-4ca8-9793-a5b993640057.png)
- Auth/Admin pages: currently I have been able to get the `...Learn more` text under the buttons, but now I'm running into issue where the refresh button is pulled left. To be completely honest, I actually think this looks better than what already exists in lakeFS (and in the mocks); its kind of odd that the refresh button is so far right and doesn't even lien up with the first right data in the table. What are your thoughts on keeping it this way (see screen shots below). Also if you notice in pics, I'm having the same issue as Create a Repo page where now there is more room between the `..Learn more` text and the start of the table (unlike the mocks @johnnyaug provided); do y'all have any advice on how to decrease the white space between the `...Learn more` text and the start of the table below? I will continue working on this. Once the code is agreed upon I will submit my revisions so we can review the actual code. 
- 
![Screen Shot 2021-10-14 at 3 39 44 AM](https://user-images.githubusercontent.com/39511285/137303013-9c1628c1-0e64-467c-aaa6-8ca5a243fa63.png)
![Screen Shot 2021-10-14 at 3 39 41 AM](https://user-images.githubusercontent.com/39511285/137303018-e1d1c634-2a17-4582-9609-75101a4302a3.png)
![Screen Shot 2021-10-14 at 3 39 34 AM](https://user-images.githubusercontent.com/39511285/137303020-8bdd4368-e657-44e2-a12f-fc683e02502a.png)
![Screen Shot 2021-10-14 at 3 38 38 AM](https://user-images.githubusercontent.com/39511285/137303021-15be7457-a735-45f7-a864-c8743586df48.png)

Also, I 


FYI I won't be able to work on this until next Monday, but I'm getting more confident that I should be able to finalize and submit the PR by the end of next week.

Best,
David

**Comment by DataDavD** [comment]
hey @itaiad200 @johnnyaug I got my issues resolved and I should have this PR ready to review and submitted by EOD. Thanks again for your help. This was a good frontend/react/bootstrap learning experience.
