### ISSUE TITLE
Discovery: Check if we can remove the blockstore.s3.region property from config.yaml

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2328]
After this issue https://github.com/treeverse/lakeFS/issues/2245 is closed, we need to check if the blockstore.s3.region property becomes useless. 

To do that, we shall check if other parts of the system use this property. Suspicious areas are export, and garbage collection.  

**edit (@arielshaqed):** "blockstore".

**Comment by nopcoder** [comment]
Currently the s3 block adapter implementation use the configured region value when we fail to resolve the region information from the bucket.
Also, underlying storage with S3 compatible interface (like MinIO) my not support GetBucketRegion API and use the configured region fallback.
We should consider use the configured value if set or use it as different, closing this one and open specific one to address this concern.
https://github.com/treeverse/lakeFS/issues/2697
