### ISSUE TITLE
Support Hadoop direct-access FileSystem with Spark 3.1

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2336]
This may work but probably does not.  Test it on:

- [ ] EMR
- [x] DataBricks
- [ ] Default Spark download + install.

(Some versions bumped to Hadoop 3, which may be tricky).

**Comment by arielshaqed** [comment]
#2597 does part of this.

**Comment by arielshaqed** [comment]
@Jonathan-Rosenberg this should mesh into your Hadoop 3 support efforts :-)

**Comment by johnnyaug** [comment]
Tested on EMR - works.

**Comment by arielshaqed** [comment]
It actually works now, thanks @johnnyaug + @Jonathan-Rosenberg !
