### ISSUE TITLE
Add project description to lakeFS’s python package.

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#2344]
We should have some description in the [lakeFS’s python package](https://pypi.org/project/lakefs-client/) referencing the [lakeFS docs](https://docs.lakefs.io/integrations/python.html) and the [lakeFS pydocs](https://pydocs.lakefs.io/).

**Comment by vaibhavk1992** [comment]
Hi Team,
I am planning to work on this issue.Please tag me to it. I will be touch over slack for further communication.
