### ISSUE TITLE
Improved streaming support for Apache Kafka

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2358]
Committing (along with attaching useful information on the commit) makes a lot of sense for batch workloads: run a job or a pipeline on a separate branch, and then commit once the pipeline has completed successfully, recording metadata such as the git hash of the code executed, the versions of frameworks used, and information about the data artifacts generated by the run.

For streaming however, this is currently less clear: There's no obvious point in time to commit, as things never actually "finish successfully".
[The recommended pattern](https://docs.lakefs.io/usecases/production.html#example-1-rollback---data-ingested-from-a-kafka-stream) would be to ingest from a stream on a separate branch, periodically committing - storing not only the data added since last commit but also capturing the offset read from the stream, for reproducibility.
These commits can then be merged into a main branch given they pass all relevant quality checks and other validations using hooks, exposing consumers to validated, clean data.

In practice, implementing such a workflow is a little challenging. Users need to:

1. Orchestrate the commits and merge operations.
1. figure out how to attach the correct offset read from the stream broker
1. Handle writes coming in while the commit is taking place

Ideally, lakeFS should provide the tools to automate this, with native support for [Apache Kafka](https://kafka.apache.org/).

**Comment by arielshaqed** [comment]
This would _also_ require being able to support commits at a reasonably high-frequency.
