### ISSUE TITLE
[deployment] Automated rollback

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2362]
* Need to determine the desired schema from the *intended* version (metadata or invocation), then use the *existing* version to migrate there -- the intended version doesn't know what its future holds.
* If no DB schema change required then this is _safe_ and should happen with no user interaction.
* If the DB schema does change, better get some confirmation.

**Comment by johnnyaug** [comment]
Related: #2350

**Comment by guy-har** [comment]
Closing because it's not needed now in the KV implementation
