### ISSUE TITLE
Dump configuration and details on startup with errors

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2364]
Define a "startup phase" and/or "warmup period" for the lakeFS daemon.  If errors (certainly _fatal_ errors) occur during that time, dump *all* configuration.  Also dump its sources, if #2354 lets us do that.

Possible definitions:
* _Startup phase_: Right until all web services start.
* _Warmup period_: first 60 (?) seconds after startup.

**Comment by edmondo1984** [comment]
Isn't there the risk to expose secret in logs with this solution? I imagine that if there is a process tailing logs, this could create a problem

**Comment by itaiad200** [comment]
Good observation @edmondo1984! The dump should mask all potential secret information.

**Comment by itaiad200** [comment]
I think you're right @edmondo1984, it looks odd. It's not clear to me why we're not panicking on that error too. Maybe @nopcoder sees something that we're missing?

**Comment by nopcoder** [comment]
Also, agree it looks strange, and we need to address it.
But I'll try to explain the reason I think it is written this way. TL;DR - Startup database connection retries and migrate driver.

- This code verify that current db schema level match the version embedded
- We no longer migrate, so we enable a startup without db schema
- The migration connects to the database with its own driver / connection
- At some point, we added database connect retry on startup, it doesn't include to migrate driver
- In case the schema version check will exist on all errors - it probably will exit on fail to connect and there will be no retries.

**Comment by arielshaqed** [comment]
Thanks for your work on this!

> Isn't there the risk to expose secret in logs with this solution? I imagine that if there is a process tailing logs, this could create a problem

I think that we are set up to handle this correctly.  Specifically, the config template [defines a type `SecureString`](https://github.com/treeverse/lakeFS/blob/234018be2d7e6f95db9cdbfad74bb3ab2bba29b5/pkg/config/template.go#L32) to use for secrets in configuration.  I opened #3074 to change the definition of its `String` method, making it _very_ hard to spill these secrets to the log.

**Comment by itaiad200** [comment]
> Also, agree it looks strange, and we need to address it. But I'll try to explain the reason I think it is written this way. TL;DR - Startup database connection retries and migrate driver.
> 
> * This code verify that current db schema level match the version embedded
> * We no longer migrate, so we enable a startup without db schema
> * The migration connects to the database with its own driver / connection
> * At some point, we added database connect retry on startup, it doesn't include to migrate driver
> * In case the schema version check will exist on all errors - it probably will exit on fail to connect and there will be no retries.

The retries do happen before the migrate, so we should panic on that error.

**Comment by edmondo1984** [comment]
> Thanks for your work on this!
> 
> > Isn't there the risk to expose secret in logs with this solution? I imagine that if there is a process tailing logs, this could create a problem
> 
> I think that we are set up to handle this correctly. Specifically, the config template [defines a type `SecureString`](https://github.com/treeverse/lakeFS/blob/234018be2d7e6f95db9cdbfad74bb3ab2bba29b5/pkg/config/template.go#L32) to use for secrets in configuration. I opened #3074 to change the definition of its `String` method, making it _very_ hard to spill these secrets to the log.

Yes, you are right. As a side question, is there a view on which type of testing pattern to follow? I see a side test package, while I would have been tempted to add my test side-by-side the new code. WDT?
