### ISSUE TITLE
Support [fork]

### ISSUE THREAD

**Issue by Janus-Xu** [treeverse/lakeFS#2373]
the shared or read-only data can be forked to others count, 
this behavior will copy all repo data,  like all tags、branchs、commits，and also record the connected with original repo

**Comment by ozkatz** [comment]
Thanks @Janus-Xu ! There's currently a [`lakectl ref-dump`](https://docs.lakefs.io/reference/commands.html#lakectl-refs-dump) and accompanying [`lakectl refs-restore`](https://docs.lakefs.io/reference/commands.html#lakectl-refs-restore) that allow you to do this. 

Is this what you were looking for?

**Comment by Janus-Xu** [comment]
> Thanks @Janus-Xu ! There's currently a [`lakectl ref-dump`](https://docs.lakefs.io/reference/commands.html#lakectl-refs-dump) and accompanying [`lakectl refs-restore`](https://docs.lakefs.io/reference/commands.html#lakectl-refs-restore) commands that allow you to achieve this behavior.
> 
> Is this what you were looking for?

yep! that what i want , dump + restore same as fork func , thanks a lot!

**Comment by itaiad200** [comment]
@Janus-Xu Closing since fork is supported with `ref-dump` and `refs-restore`. Feel free to reopen if it's not working as expected.
