### ISSUE TITLE
Support [pulsar]

### ISSUE THREAD

**Issue by Janus-Xu** [treeverse/lakeFS#2374]
as Apache’s incubation process ‘s top-level project， pulsar become more and more popular, so many company upgrade from kafka to pulsar
also，pulsar use Apache jclouds to support Amazon S3 and same others for long term storage. may the integration with lakefs is simple and fast

**Comment by ozkatz** [comment]
Hi @Janus-Xu ! This makes perfect sense. From skimming the Pulsar docs, this seems to be doable without any modification to lakeFS or Pulsar, using the [S3 Offloader](https://pulsar.apache.org/docs/en/cookbooks-tiered-storage/#configuring-the-offload-driver):

> There is a third driver type, s3, which is identical to aws-s3, though it requires that you specify an endpoint url using s3ManagedLedgerOffloadServiceEndpoint. This is useful if using a S3 compatible data store, other than AWS. 

So it seems that setting `s3ManagedLedgerOffloadServiceEndpoint` to the lakeFS S3 domain name should do the trick, but requires some testing. If it works I'll gladly add it to our documentation. 

@Janus-Xu Would you be willing to help test this?

**Comment by talSofer** [comment]
Requires testing and documentation of testing outcome.
