### ISSUE TITLE
Move DB-Schema-Version code from workflow into lakeFS

### ISSUE THREAD

**Issue by adunuthulan** [treeverse/lakeFS#2379]
Currently the functionality to determine the lakefs db-schema-version (by reading the highest version of the upward migration files #2366) is within the Github workflows that push the lakeFS docker images to ECR. It would be ideal if this could be more baked into the lakeFS application, such as within the Makefile.

**Comment by N-o-Z** [comment]
With the introduction of KV Store based database this issue will soon be obsolete

**Comment by N-o-Z** [comment]
Closing as obsolete
