### ISSUE TITLE
[metadata client] Implement a BlockReadable on top of hadoop FSDataInputStream and use that

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2403]
Current metadata client fetches an entire SSTable file to read it.  However there is no real need to do so: Hadoop `FileSystem`s return FSDataInputStream, which is seekable.  (There is no such choice when using rocksdbjni to open SSTables, as they do not provide the required `FileSystem`-like API).

Avoiding this copy makes for slightly simpler ops (no need to create temp files) and may be somewhat faster _once we implement seeking **and** (additionally) support small InputFileFormat splits.

_Originally posted by @itaiad200 in https://github.com/treeverse/lakeFS/pull/2335#r694747395_

**Comment by johnnyaug** [comment]
@arielshaqed, I think we should consider promoting this (depending on the expected cost). This can be an alternative to #4588: it will allow me (I think, correct me if wrong) to read only the metadata section of the SSTable, and check its type without downloading everything.

**Comment by arielshaqed** [comment]
> @arielshaqed, I think we should consider promoting this (depending on the expected cost). This can be an alternative to #4588: it will allow me (I think, correct me if wrong) to read only the metadata section of the SSTable, and check its type without downloading everything.

Yes! But...

1. Why/how would you ever access a range if you didn't go through its metarange?
2. Ranges greatly outnumber metaranges in a medium or a large installation. Not sure this would save much.
3. If you need random access, that is not yet written for jpebble.
