### ISSUE TITLE
lakectl | tags command are not clear

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#2409]
Using lakectl, It is not clear how to create a tag.
The message in help is
```shell
Usage:
  lakectl tag create <tag uri> <commit ref> [flags]

```

The command expects `tag uri` to be a full URI
And `commit ref` to be only the commit ref with out the uri 
A valid command would be 
```shell
lakectl tag create lakefs://example1/my-tag 2397cc9a9d04c20a4e5739b42c1dd3d8ba655c0b3a3b974850895a13d8bf9917
```

First of all to make this command clear we should add an example in the command help

Second, we should make commit ref a full URI, weather the tag should be a full URI is debatable (the user I talked to expected the tag to be without a full URI).

**Comment by mishraprafful** [comment]
@guy-har I've created a PR adding the example, about the second change mentioned in the issue description, I think it makes sense to keep the command the way it is (from my perspective as a user). 

Adding the full URI to the `commit ref`, gives me a sense of hope that I can specify commit ref for a different repo,  which clearly doesn't seem right.

But I would love to know your thoughts about it.

**Comment by guy-har** [comment]
@mishraprafful, my problem here is that this behavior breaks the convention we currently have.
The other commands we have (such as merge and diff) receive two full URIs regardless of the fact that you can't specify refs from different repos. 
Your claim makes perfect sense, but I'm afraid that having both practices could cause confusion.
