### ISSUE TITLE
hadoop-lakefs integration tests to run over Databricks

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2418]
Currently, we run an integration test using docker on Spark cluster 2.x and 3.x.
Running the same on Databricks will help us catch more cases and issues before publishing a new package.

**Comment by johnnyaug** [comment]
In our integration tests we start lakeFS in a docker-compose in GitHub actions.
If we use the same way here, we need to somehow give Databricks access to this installation.
I tried to solve this with an ngrok tunnel, but in the end found out that they have a limit of 1 online process at a time (2 in the Business plan) so it's not a suitable solution for us.
