### ISSUE TITLE
Support Trino AVRO format access via S3 gateway

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2429]
Currently #2296 causes this to fail -- it expects a particular Content-Type to be returned _when detecting an AVRO subtree_.

**Comment by itaiad200** [comment]
@nopcoder make sure to test this one as well.

**Comment by nopcoder** [comment]
move back to in-progress until we verify this one is fix and there are not followup issues we need to open.

**Comment by nopcoder** [comment]
table creation, insert and select using AVRO format using Trino works.
