### ISSUE TITLE
Clarify spark dependency for Garbage collection in the documentation

### ISSUE THREAD

**Issue by mattew** [treeverse/lakeFS#2477]
The documentation for the Garbage collection job is a bit unclear that there is a dependency on spark to run it.
It's implied since you run `spark-submit`  but it could be more explicit that you need a external spark environment to run the job. 

It could be mentioned both in the introduction of the article and the section about running the job itself.

**Comment by johnnyaug** [comment]
Hey @mattew, thank you for opening this issue! Please see the PR #2502.
