### ISSUE TITLE
Incorrect exception thrown while passing a non-sst file to lakeFS's SST parser

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2508]
The parser fails with IlligalArgumentException on getting a non-sst file instead of failing with BadFileFormatException in this case. 

After fixing this bug, we need to enable the unit test described as "with non-sst file of size 0" which is currently ignored. This unit-test is implemented under BlockParserSpec.scala.

**Comment by arielshaqed** [comment]
Currently this test fails for a completely different reason:
```
Could not find the file /local/empty.sfile in container 729128b84926af8a669678bc59d57f9680809716da66e13e9128d5a2e1e5eadb
```

**Comment by talSofer** [comment]
@arielshaqed yes, there is a typo in line 
https://github.com/treeverse/lakeFS/blob/ebcfe98af7a2593df785242d9c87ae193a7bc9c8/clients/spark/core/src/test/scala/io/treeverse/jpebble/BlockParserSpec.scala#L382
should be "empty.file"
