### ISSUE TITLE
[performance] BlockParser is not backed by an accessible byte array

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2511]
The line https://github.com/treeverse/lakeFS/blob/69828df0fe7c4ec0fa2deaa1f2d53025951137cb/clients/spark/core/src/main/scala/io/treeverse/jpebble/BlockParser.scala#L125 never hits, which means that the buffer the block parser uses is not backed by an array. 

The buffer is created in https://github.com/treeverse/lakeFS/blob/69828df0fe7c4ec0fa2deaa1f2d53025951137cb/clients/spark/core/src/main/scala/io/treeverse/jpebble/BlockReadable.scala#L32 and is of type `MappedByteBuffer`, which is not using a byteArray. 

Impact:
1. Every byte of the file is read, potentially multiple times - depends on the actual implementation of MappedByteBuffer.
1. Checksumming occurs by individual bytes, which is much slower.

**Comment by arielshaqed** [comment]
Pretty much made irrelevant by #4194 -- BlockParser is now backed by a simple `Array[Byte]`.
