### ISSUE TITLE
lakectl: support an ignore file for recursive uploads

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2518]
Allow reading a line-delimited list of file names or [patterns](https://git-scm.com/docs/gitignore#_pattern_format) that will be skipped by recursive uploads. This should behave similarly to Git (and possibly even allow using `.gitignore` directly?)

**Comment by arielshaqed** [comment]
Workarounds can be to use other clients:

* If [using RClone](https://docs.lakefs.io/integrations/rclone.html), you can use its extensive [filtering capabilities](https://rclone.org/filtering/#exclude-exclude-files-matching-pattern).
* [`aws s3 cp`](https://docs.aws.amazon.com/cli/latest/reference/s3/index.html#use-of-exclude-and-include-filters) supports some simpler exclude patterns.
