### ISSUE TITLE
Oracle Object Storage S3 compatibility fail to put object

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2527]
Oracle Object Storage enables Amazon S3 Compatibility API - https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

We identified an issue while creating a repository - dummy file put failed with: `STREAMING-AWS4-HMAC-SHA256-PAYLOAD is not supported`.
Based on https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm - the API compatibility doesn't support chunked request that we use by default to upload object or part.

**Comment by arielshaqed** [comment]
https://www.oracle.com/in/cloud/free/ may be helpful in testing.  AFAICT object storage is included in their free tier.
