### ISSUE TITLE
Running integration tests on Windows

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2543]
There were couple issues that we identified while running lakeFS on Windows platform (specific windows 10).
Running our current integration test on this platform will help us identify this issues early - before our users.

**Comment by arielshaqed** [comment]
Working on #2740 shows this is rather hard on current-day GitHub actions: a Windows GitHub action cannot run a Linux Docker container (see e.g. https://github.com/actions/virtual-environments/issues/1143#issuecomment-973003871).

Closing for now, meaning we do not officially support lakeFS-on-Windows.  (No reason it shouldn't work, but untested generally means unsupported).

@ozkatz: we need level of support for lakeFS-on-Windows, I guess.

**Comment by arielshaqed** [comment]
I got as far as #2740, and put diffs there.
