### ISSUE TITLE
[Feature request] Configuration-based provisioning

### ISSUE THREAD

**Issue by politician** [treeverse/lakeFS#2545]
## Context

I am currently working on a Kubernetes-based stack that I will open-source by the end of the year. This stack is based on IaC (Terraform) and GitOps (Flux) to allow for easily reproducible stacks.
Currently, everything in the cluster can be deployed automatically without human intervention, which means it can be used to setup long-lived dev/stage/prod clusters as well as temporary clusters (to be used in CI) automatically.
The stack uses S3 as the de-facto data destination. The S3 buckets are provisioned automatically for long-lived environments. 

If I was to introduce LakeFS in the middle, I'd need manual steps to setup the admin credentials and each repository.

## Problem

**LakeFS cannot easily be provisioned automatically using GitOps.**

## Solution

**[LakeFS configuration](https://docs.lakefs.io/reference/configuration.html) needs to support more options.**

As far as I understand LakeFS and how it works, here are, at the absolute minimum, the areas that need to be worked on for this to happen:

### Deploy LakeFS

~~It is nearly there, just need https://github.com/treeverse/charts/issues/95 to be worked on (ideally the generic option)~~
Ok

### Setup admin credentials

LakeFS needs a way to setup the admin credentials statically. For security reasons, this could be enabled via environment variables and/or maybe through a separate configuration file.

Additionally, for the specific k8s use case, it could be that LakeFS generates and exports a k8s secret which is even better than having to manually specify credentials. [Here's a tutorial for Helm](https://wanderingdeveloper.medium.com/reusing-auto-generated-helm-secrets-a7426403d4bb)

### Setup repositories

In Grafana, you can configure data sources and dashboards either [in the UI](https://grafana.com/docs/grafana/latest/datasources/add-a-data-source/), either [via configuration at deployment time](https://grafana.com/docs/grafana/latest/administration/provisioning/). Data sources and dashboards provisioned at deployment time are not editable in the UI so there cannot be any conflicts.

Replace _data sources and dashboards_ by _repositories_ and you have a solution for LakeFS which I think is the best way forward.

**Comment by ozkatz** [comment]
@politician Thanks for taking the time to describe this in detail! Just to make sure I get it right, as it stands, this could be broken down into 2 independent issues:

## Allow setting up a new lakeFS installation with admin credentials

From what you're describing, this could be done in one of two ways:

1. At the Docker image level, by supporting static credentials passed as environment variables (similar to the way the [PostgreSQL docker image](https://hub.docker.com/_/postgres) works, where users can specify `POSTGRES_USER` and `POSTGRES_PASSWORD`
2. At the helm chart level, by generating random credentials and exposing them as k8s secrets

## Declaratively configure repositories using configuration files

Where lakeFS, when initialized with these configuration files will ensure the specified repositories are configured (and thus can only be managed via static config


@politician If I understood both correctly, may I ask that you open these 2 issues and close this one in favor of them? 
This will allow prioritizing them separately as they are indeed not coupled or dependent.
