### ISSUE TITLE
S3 block adapter incorrectly looks up buckets on AWS

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2592]
Bucket detection invariably runs and uses the default endpoint to query buckets.  I configured lakeFS to use the S3 block adapter connected to minIO.  The first time I used a bucket:

```
DEBUG  [2021-10-24T14:54:20+03:00]pkg/block/s3/client_cache.go:66 pkg/block/s3.(*ClientCache).getBucketRegion requesting region for bucket                  bucket=minfoo host="localhost:8000" matched_host=false method=PUT path=man ref=main repository=min request_id=9da530e4-2ac6-4cbe-b5d7-4f32199c819d service_name=s3_gateway user=yoo
DEBUG  [2021-10-24T14:54:20+03:00]pkg/logging/aws.go:8 pkg/logging.(*AWSAdapter).Log DEBUG: Request s3/HeadBucket Details:
---[ REQUEST POST-SIGN ]-----------------------------
HEAD /minfoo HTTP/1.1
Host: localhost:9000
User-Agent: aws-sdk-go/1.37.26 (go1.17.2; linux; amd64)


-----------------------------------------------------  sdk=aws
DEBUG  [2021-10-24T14:54:20+03:00]pkg/logging/aws.go:8 pkg/logging.(*AWSAdapter).Log DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Sun, 24 Oct 2021 11:54:20 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16B0F560D244A918
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
Content-Length: 0


-----------------------------------------------------  sdk=aws
DEBUG  [2021-10-24T14:54:20+03:00]pkg/logging/aws.go:8 pkg/logging.(*AWSAdapter).Log DEBUG: Validate Response s3/HeadBucket failed, attempt 0/5, error Forbidden: Forbidden
        status code: 403, request id: 16B0F560D244A918, host id:   sdk=aws
ERROR  [2021-10-24T14:54:20+03:00]pkg/block/s3/client_cache.go:69 pkg/block/s3.(*ClientCache).getBucketRegion failed to get region for bucket, falling back to default region  error="Forbidden: Forbidden\n\tstatus code: 403, request id: 16B0F560D244A918, host id: " host="localhost:8000" matched_host=false method=PUT path=man ref=main repository=min request_id=9da530e4-2ac6-4cbe-b5d7-4f32199c819d service_name=s3_gateway user=yoo
```

(forbidden because `GetBucketRegion` is called on the AWS endpoint not the minIO endpoint.)

Then it decides to use the default region, which is `us-east-1`, which is also the default region for minIO.  So it works, but kinda by accident, and leaking details of the minIO bucket name to an AWS endpoint.  If our minIO were configured for another region it would fail.

Other S3 compatible block stores may fare even less well.

Allow not performing block storage bucket region detection, e.g. by allowing explicit configuration.  (Note that this is the **opposite** of what #2328 wants us to do!)

**Comment by arielshaqed** [comment]
> > If our minIO were configured for another region it would fail.
> 
> @arielshaqed have you tested this? I had a thought that if I'm using Minio over AWS, the get-bucket-location call may work. that is, we won't use the default region in that case.

I think I don't understand what "tested" means here.  So here is what I did: The logs above are from a working installation.  I believe that the same thing will happen even if I put MinIO over on AWS: It would *still* not have an endpoint for calling get-bucket-location, and the existing code would try to look up a MinIO bucket name on the AWS endpoint.

In particular, the bucket name leaks over to AWS.

> If this really doesn't work, I think that @nopcoder's suggestion to separate Minio to another adapter is a good way to go.

I am confused how this would solve issues when accessing non-MinIO object stores.  E.g. if a user routes their govcloud S3 endpoint to outside of govcloud, this could be an unpleasant surprise.  Or if a user creates and wants to use an internal S3 endpoint.

**Comment by nopcoder** [comment]
@arielshaqed #2705 can close this one?

**Comment by arielshaqed** [comment]
Yes, #2705 fixes this.

Thanks!

**Comment by arielshaqed** [comment]
> Yes, #2705 fixes this.
> 
> Thanks!
