### ISSUE TITLE
Pandas/Boto: co-existing with existing underlying object store

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2624]
## Why

Existing code bases where paths are scattered throughout the codebase (which is rather common for DE/DS code) have a hard time incorporating the lakeFS S3 gateway for several reasons:

1. Clients (namely, **boto3** and **pandas**) don't support multiple S3 endpoints with differing credentials. This makes it hard to change only a subset of the data to be in lakeFS because the client, once initialized, can talk to either lakeFS or S3 but not both.
2. Once data is migrated from S3 to lakeFS, even if the repo has the same name as the previous bucket, it's still not a drop-in replacement, because in lakeFS you'd also need to specify the version ref (branch/commit/tag) you're using, as a prefix.

Solving 1 is hard because it requires a big infrastructure change: instead of using a single initialized client (sometimes it's a default or global one), now multiple clients need to be introduced (one for S3, one for lakeFS) with custom logic for when to use which one.

Solving 2 is hard because it involves changing many paths scattered throughout the code base: some are dynamically generated by the code, some come from env vars or configuration files - it's not always easy to ensure coverage.

## For Who

Data Engineering and Data Science teams that use Python and are introducing lakeFS into their stack, without fully replacing it.

## Boto / Pandas s3 Usage:

```python
1. s3 = boto3.client('s3', config=Config(signature_version='s3v4'))

2. from pyarrow import parquet as pq 
filesystem = s3fs.S3FileSystem()
pq.write_table(table, path, filesystem=filesystem)

3. s3 = boto3.resource('s3')
```

## What

A wrapper/monkey patch/utility library that makes it easy to create mappings. A mapping consists of 2 logical parts:

#### endpoints

An endpoint is a set of S3 configurations: url (optional, defaults to S3's), credentials or profile name (optional, defaults to [AWS SDK's resolution](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)) and region (optional, defaults to [AWS SDK resolution](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-the-config-object)).

One endpoint should be set as **default**, meanning any call that doesn't match a configured mapping, will use that endpoint.

#### mappings

A mapping is a pair of matching rule and destination.

**matching rules** define a bucket or combination of bucket and prefix. Any call to S3 that matches the bucket and prefix will go to the configured destination instead.

**destinations** are a 3-tuple of **endpoint**, **bucket** and **prefix**. Here's some pseudo code for inspiration:

```python
import lakefs
import boto3

# globally defining the mapping
lakefs.bootstrap_overrides(boto3, {
    "endpoints": {
        "lakefs": {
            "url": "https://lakefs.example.com",
            "region": "us-east-1",
            "credentials": {
                "aws_access_key_id": "...",
                "aws_secret_access_key": "..."
            }
        },
        "s3": {
            # omitting any of the above will result in whatever
            # boto's resultion order decides
            "default": True, # means this will be used for any bucket not explictly set with an override!
        }
    },
    "mapping": {
        "bucket-a": {
            "endpoint": "lakefs", 
            "bucket": "my-repo",
            "prefix": "dev/"
        },
        "bucket-b/foo": {
            "endpoint": "lakefs",
            "bucket": "bucket-b",
            "prefix": "master/"
        }
    }
})

# Then, using it in either monkey patch, alternative client or utility function:

# monkey patch:

lakefs.patch(boto3) # no need to change anything else! we altered boto to use the mapping! scary!


# alternative client:

# import boto3
from lakefs.boto import boto3  # our wrapper around boto, requires chaning the imports everywhere, but a little less intrusive


# utility function:
# probably harder to accomplish since there are different ways to interact with S3 using boto
# but this the least scary option (no magic), but requires adding this everywhere..
client, path = lakefs.resolve_mapping_uri("s3://bucket/prefix") 
```

**Comment by johnnyaug** [comment]
@ozkatz , this issue requires further explanation.
There are multiple ways to use boto s3, and multiple meanings to "co-existing".

**Comment by lynnro314** [comment]
This issue is done botwo.
