### ISSUE TITLE
Check lakeFS Hadoop Filesystem with Hadoop CLI

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2629]
There seems to be some missing functionality in the filesystem to support hadoop cli. A common error between `cp` and `mv` commands:

```
hadoop fs \
> -D fs.lakefs.access.key=<key> \
> -D fs.lakefs.secret.key=<secret> \
> -D fs.lakefs.endpoint=<endpoint>/api/v1 \
> -D fs.lakefs.impl=io.lakefs.LakeFSFileSystem \
> -libjars hadoop-lakefs-assembly-0.1.0.jar \
> -cp lakefs://example-repo/main/user2/yaaqov   lakefs://example-repo/main/user2/yaaqov2
cp: `tal-test': File exists
```

**Comment by itaiad200** [comment]
`rm` command fails differently:
```
hadoop fs -D fs.lakefs.access.key=<key> -D fs.lakefs.secret.key=<secret> -D fs.lakefs.endpoint=<endpoint>/api/v1 -D fs.lakefs.impl=io.lakefs.LakeFSFileSystem -libjars hadoop-lakefs-assembly-0.1.0.jar -rm -r -f lakefs://example-repo/main/user2/yaaqov
rm: statObject: Bad Request. Consider using -skipTrash option
```

**Comment by arielshaqed** [comment]
> There seems to be some missing functionality in the filesystem to support hadoop cli. A common error between `cp` and `mv` commands:
> 
> ```
> hadoop fs \
> > -D fs.lakefs.access.key=<key> \
> > -D fs.lakefs.secret.key=<secret> \
> > -D fs.lakefs.endpoint=<endpoint>/api/v1 \
> > -D fs.lakefs.impl=io.lakefs.LakeFSFileSystem \
> > -libjars hadoop-lakefs-assembly-0.1.0.jar \
> > -cp lakefs://example-repo/main/user2/yaaqov   lakefs://example-repo/main/user2/yaaqov2
> ```

Perhaps the error message is missing here?

**Comment by itaiad200** [comment]
Right, edited above.
