### ISSUE TITLE
lakectl fs cat to support recursive download

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2649]
Recursive uploads are supported with `lakectl fs upload <path> <path> --recursive`. We should allow the same functionality with downloads as well. For reference, `aws s3 cp` used both for uploads and downloads has the recursive flag for both.

**Comment by arielshaqed** [comment]
As a workaround for this (essentially) requested `lakectl fs download` command, you could use `aws s3 cp --recursive` or go full-power with [RClone](https://docs.lakefs.io/integrations/rclone.html) or something similar.

**Comment by mishraprafful** [comment]
What do you think about the pagination on this one?

Two potential options I see are: 
* All the files are downloaded no matter the number until no pages are left. 
* First page is downloaded and an extra flag is added if the user wishes to download all the pages?
