### ISSUE TITLE
docs: add details to REST API uploadObject endpoint

### ISSUE THREAD

**Issue by prat0088** [treeverse/lakeFS#2652]
I'm a new user.  I'm writing a prototype and I wanted to share that the new user experience is a little rough, particularly in one area: getting data into lakeFS via the REST API.  I had to read source code to figure out how to use the API.  

https://docs.lakefs.io/reference/api.html#/objects/uploadObject

Details that would help future users: 

1. _Only_ multipart uploads appear to be supported.
2. One file per upload.  Named content.  If you do not name your file content you get the unfriendly error message in the trace logs "http: no such file".  I figured this out after poking around the source code.  
3. path is relative to the branch (obvious, but stating the obvious in api docs would help confusion and the sense of being lost).

Thanks for lakeFS!

**Comment by itaiad200** [comment]
Thanks @prat0088 , these sorts of inputs help us improve. I've opened #2654 to improve our swagger around that and add a more descriptive error for missing content key.
