### ISSUE TITLE
CLI: Provide a way to view the latest change made to an object or prefix

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2659]
### What

being able to take a data object (or prefix, like a partition or collection) and get back the commits that added/modified its content.

### Why

This is valuable lineage information that is currently available in lakeFS but not exposed easily, and mimics the behavior of `git blame`

### How

Given the lakeFS API already supports listing the log of commits for an object or prefix (🎉), this could be a `lakectl` addition that  simply takes the first change from the list.

Additionally, `blame` could be used as an internal alias for those who really want to stick with Git's taxonomy - I would suggest something more positive like `origin`, e.g.:

```
# lakectl origin --prefix lakefs://repo/branch/collection/

lakefs://repo/branch/collection/date=2021/  2021-12-31  7c3cded Spark added 2021 partition (through Airflow)
lakefs://repo/branch/collection/date=2020/  2020-12-31  82ba1e8 Perfromed a rerun for 2020, manually
lakefs://repo/branch/collection/date=2019/  2019-12-31  91f6ab7 Spark added 2019 partition (using cronjob)
```

**Comment by ozkatz** [comment]
Following @lynnro314's awesome work on prefix/object-scoped commit log :)

**Comment by arielshaqed** [comment]
1. The historical synonyms for "blame" are "praise" and "annotate"; see e.g the [SVN manual](https://svnbook.red-bean.com/en/1.7/svn.ref.svn.c.blame.html).
2. This is *not* "blame".  The purpose of that command is to annotate the lines of a file; we cannot do that without assuming some structure.
3. What remains is not very different from `log --amount 1`:
    ```sh
    ariels@redqueen:~/dev/lakeFS$ ./lakectl log lakefs://moo/main --amount 1
    
    ID:            509fb9245f255a75d8d9aded5f1ab7fea029adce0c357cdc0eab30e2f91b35dd
    Author:        yoo
    Date:          2021-10-21 12:52:41 +0300 IDT

            stop and go
```

**Comment by ozkatz** [comment]
I feel SVN has moved beyond relevance, so I prefer not to stick with its terminology, especially when "annotate" is somewhat overloaded when it comes to data. Not sure how I feel about "praise" in the context of (possibly) machine generated commits..

> this could be a lakectl addition that simply takes the first change from the list.

As for 2,3 - that is correct. Which is why I suggest to add this to the CLI only.

**Comment by ozkatz** [comment]
For reference, updated the description to reflect a more useful variant (previously, this refered to the ability to get only the latest commit, also for a prefix, instead of the the commit that last modified each of its children)
