### ISSUE TITLE
Upgrade to AWS Go SDK v2

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2684]
This is now supported
https://docs.aws.amazon.com/sdkref/latest/guide/version-support-matrix.html.

[Developer guide](https://aws.github.io/aws-sdk-go-v2/docs/) has a section
on [migrating](https://aws.github.io/aws-sdk-go-v2/docs/migrating/); it
appears most of the work will be in client creation.

A significant change for us right now is the addition of a [`ContextLogger`
interface](https://pkg.go.dev/github.com/aws/smithy-go/logging#ContextLogger).
We can use that to help with #2682.

**Comment by nopcoder** [comment]
In favor to upgrade, more information about v2: https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/

**Comment by arielshaqed** [comment]
Against the upgrade is that the new version might remove some capabilities in a bid to simplify the interface.  Specifically it will be hard to write `s3Uploader`, which is a chunked uploader.

Also...
## :warning: BEWARE OF USING `manager.Uploader` :warning: 

This is dangerous.  It was dangerous, but it still is. aws/aws-sdk-go-v2#1040 is that files large enough to need multipart uploads _do not have their digests checked_.

Now it might seem the if you access S3 only via https then TLS checks everything for you.  But (of course) that reduces the issue but does not eliminate it.  If gremlins reside after the TLS endpoint and modify the data, it is entirely unchecked.  This is a significant path along multiple machines in the data centre, so is not safe.

**Comment by arielshaqed** [comment]
Unassigning myself and keeping it on the backlog: no current plans for this because the v1 SDK still works for us.  Keeping open because I _still_ want my ContextLogger, it can greatly improve debugging in some cases with heavy load.
