### ISSUE TITLE
Block adapter dependency on s3 aws

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2694]
Block adapter generic interface re-use s3 multipart complete struct.
```go
type MultipartUploadCompletion struct{ Part []*s3.CompletedPart }
```
It is a nice way for code reuse, but generate dependency with specific with specific underlying implementation.

**Comment by arielshaqed** [comment]
Thanks!  This will be really useful and clean things up.

Please handle only **after** #2684 is done: it will change type `s3.CompletedPart` to `types.CompletedPart`, and also moves pointers around a bit.  And part numbers will change from insane `int64` to sane(r) `int32`.

**Comment by nopcoder** [comment]
No problem I'll wait for a good rebase

**Comment by arielshaqed** [comment]
Don't wait,  fixed.
