### ISSUE TITLE
Configure S3 block adapter to disable region discovery

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2697]
Current block adapter try to discover the bucket region by calling GetBucketRegion API.
Not all S3 compatible storage system supports this API - example: MinIO.

In order not to keep trying to get the region and fill the log with errors, we should enable an option to disable it and guide these underlying systems to disable this feature.

There current S3 block configuration holds property for 'region' that will be used.

**Comment by arielshaqed** [comment]
Log appears roughly once per repo (possibly more when the first access to the repo is concurrent).  (But I _really_ like and want this!)
