### ISSUE TITLE
lakectl merge does not provide good information in case of conflict 

### ISSUE THREAD

**Issue by sthiriet** [treeverse/lakeFS#2699]
Hello,

I have seen that in case of conflict, lakectl is not very helpful : the count is not accurate and no error message or return code != 0 is provided to the user :

```shell
$ lakectl merge lakefs://test-lakefs/modify-lb1 lakefs://test-lakefs/main 
Source: lakefs://test-lakefs/modify-lb1
Destination: lakefs://test-lakefs/main
Conflicts: 0
$ echo $?
0
```

The UI is more helpful :
![image](https://user-images.githubusercontent.com/12430903/141657690-ad889723-c020-4c7d-bd74-fc05474bcb7f.png)

It could be annoying for automations.

**Comment by nopcoder** [comment]
lakectl will print "Conflict found." and exit code will be 1.

**Comment by sthiriet** [comment]
Perfect! Thank you.
