### ISSUE TITLE
Merge optimization by fast forwarding ranges

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#2710]
The merge operation receives two metaranges `source-metarange` `destination-metarange`  and finds the `base-metarange`.
The merge operation creates a new metarange which is done by a three-way diff.

The merge operation is currently optimized by skipping ranges that are identical in source and destination

## Example
Let's consider the following metaranges:

`base-metarange`
range_id  |  min_key | max_key  |  count
---------|----------|-----------|----------
1              | path_a/  |  path_a/z   |   50
2              | path_b/  |  path_b/z   |   50
3              | path_c/  |  path_c/z   |   50

`destination-metarange`
range_id  |  min_key | max_key  |  count
---------|----------|-----------|----------
1              | path_a/  |  path_a/z   |   50
4              | path_b/  |  path_b/z   |   50
3              | path_c/  |  path_c/z   |   50

`source-metarange`
range_id  |  min_key | max_key  |  count
---------|----------|-----------|----------
1              | path_a/  |  path_a/z   |   50
5              | path_b/  |  path_b/z   |   55
6              | path_c/  |  path_c/z   |   55

When creating the `merge-metarange`
1. The merge operation will write `range 1` to `merge-metarange` without the need to read and compare
2. The merge operation will read `range 2`, `range 4` and `range 5` and create a new range (or ranges)  containing the merged objects
3. The merge operation will read `range 3` and `range 6` and create a new range (or ranges)  containing the merged objects

Step 1 is optimized.

## Suggestion

Currently the optimization works only when `source-metarange` and `destination-metarange` have the same range ID.
We could also optimize the following cases:
-  `source-metarange` and `base-metarange` have the same `range_id`, `max_key` and `min_key` -> use the range in `source-metarange`
-  `destination-metarange` and `base-metarange` have the same `range_id`, `max_key` and `min_key` -> use the range in `source-metarange`

In the example we would optimize step 3 by writing `range 6` with the need to read the ranges

**Comment by guy-har** [comment]
This issue should fix many cases of #2690

**Comment by nopcoder** [comment]
1. Compare the range_id - source/base or destination/base should be enough as it the hash of the content, right?
2. In case of the new optimization (source/base matched) in order to use the destination we still need to match the min/max with the destination? do we need to continue taking ranges from destination until we reach to the min/max which is out of the source range?

**Comment by guy-har** [comment]
@nopcoder, both points are true.
In order to make this issue less complex, the optimization would work only for ranges with the same `max_key` and `min_key`. It could be optimized even more as you suggest in 2. 
Given the fact that most of our ranges tend to break at fixed locations, I think we should start with the simple case.
