### ISSUE TITLE
Update the glue/hive documentation around the Athena section

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2728]
It is somewhat unclear what is possible and what isn't with lakeFS and Athena.

**Comment by ozkatz** [comment]
+1 on this - I think it also requires a bit of explanation about what symlinks are in the Hadoop sense. 

A reference to look at is the [Delta Lake documentation](https://docs.delta.io/latest/presto-integration.html), since their integration is kind of similar to lakeFS's

**Comment by ozkatz** [comment]
This is also a good place to show the power of lakeFS hooks (i.e. creating a post-commit/merge hook that automatically maintains the symlinks as a recipe).
