### ISSUE TITLE
Hadoop Filesystem to support per-bucket configuration

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2731]
Currently, lakeFS Hadoop Filesystem depends on the library `hadoop-aws:2.7.7`, which does not support per-bucket configuration.

The reason for depending on this version is described in [this comment](https://github.com/treeverse/lakeFS/pull/2721#issuecomment-972711972).

The filesystem needs to support per-bucket configuration.

**Comment by arielshaqed** [comment]
Do you use lakeFSFS and require this?  **Please** let us know here!

**Comment by johnnyaug** [comment]
Since hadoop-aws is now a _provided_ dependency for the lakeFS Hadoop FileSystem, per-bucket configuration is now supported.
