### ISSUE TITLE
The repository can't be parsed by another docker container

### ISSUE THREAD

**Issue by zpwenjh** [treeverse/lakeFS#2748]
I create a docker container as follows:
![image](https://user-images.githubusercontent.com/63989327/143158574-fd893255-042d-4301-8c0c-fc87f5be5bea.png)

 And I create a repository in the container. Then I delete the container and recreate it again, but there is no repository exists.
![image](https://user-images.githubusercontent.com/63989327/143158860-261bd240-7d2a-45d9-952e-f32be69acfc9.png)

I dont't know why. I have clearly created a repository in the "D://xxxx//lakefs".

**Comment by nopcoder** [comment]
Although lakeFS's local adapter location points to the container's /home/lakefs (LAKEFS_BLOCKSTORE_LOCAL_PATH) there is additional information inside Postgres.
In order to keep the data persistence in this case you will also need to mount the postgres service data.

**Comment by nopcoder** [comment]
For reference, these are the changes I've applied to get persist between docker-compose up/down while working with local adapter.

```shell
$ mkdir -p data/pg data/lfs
$ chmod 777 data/pg data/lfs
```

Added the following to lakefs service:
```yaml
    volumes:
      - ./data/lfs:/home/lakefs
```

Added the following to postgres service:
```yaml
    volumes:
      - ./data/pg:/var/lib/postgresql/data
```

Hope its helps - for Windows you may not be required to create the folders with the right permissions, depends on the credentials your docker daemon holds.

**Comment by zpwenjh** [comment]
@nopcoder Thank you very much.

**Comment by zpwenjh** [comment]
@nopcoder Can I add a directory to the repository? If it's possible, how can I use lakectl to do that?

**Comment by nopcoder** [comment]
Specify the path your like in the lakectl fs upload. Same in the UI the upload path can be set after you select the file.
