### ISSUE TITLE
Add Jupyter to the everything bagel

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2758]
configured against the Spark container

**Comment by ozkatz** [comment]
@adipolak if you have specific versions/configurations in mind, this is a good place to put them, as this is currently planned :)

**Comment by nopcoder** [comment]
pyspark based on the current image version we have in the compose is enough? any specific stuff or references will be helpful?

**Comment by adipolak** [comment]
thanks! pyspark 3.1.2 is possible. if that is not supported yet. 3.1 would work great too.
