### ISSUE TITLE
Same content upload should not apperar as a change

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2767]
Uploading the same content to lakeFS currently marked as a change as it updates the timestamp.
From retention point of view, timestamp update is relevant and required.
An example of such a case is uploading and committing the same object twice. We expect the second upload to skip the update and the commit to fail as no changes should be applied.

**Comment by sthiriet** [comment]
In our use case, we are using lakefs to store configuration data. This data is generated and pushed into lakefs by automated services and it may happen that the resulting data does not change from the existing data. Our goal is to track configuration changes through commits. Not making a commit if the content has not changed is therefore important to us.
