### ISSUE TITLE
Delete multiple objects using lakeFS API

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2768]
Having to delete a large number of objects requires multiple calls to the server.
Currently alternatives will be to use the client side implementation using lakectl recursive delete or the S3 gateway delete-objects request.
Our open API is missing the use-case of deleting a large set of specific objects.

The API should enable the same functionality as the s3 delete-objects.
When all objects are delete it will return 204 No Content to indicate that all objects where deleted.
In case there is an error 200 OK will be return with a list of responses where the caller can identify which object failed to delete.
The operation is not atomic and in case of any error all objects that were deleted will not be restored as part of the request.

**Comment by ozkatz** [comment]
for reference, the documentation of S3's bulk delete API: [DeleteObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html).

A few notes about it:
1. it always returns a successful response. Errors, if any exist in the response body, so it must be parsed.
2. it supports a "quiet" mode, in which successful deletions are not returned in the response body - only errors are returned.
3. the default mode is "verbose" in which all keys are returned, regardless of their success/error status
4. just like deleting a single object, a successful deletion does not indicate the object existed at the time of deletion.

**Comment by adijesori** [comment]
It would also be nice to add support for query option called “failFast” that will cause the request to return immediately when one of the object deletions were failed.
