### ISSUE TITLE
Insufficient check for Distinguished Name login (ldap authentication)

### ISSUE THREAD

**Issue by roman-komac** [treeverse/lakeFS#2773]
While testing LakeFS I have discovered that the LDAP authentication fails with error="create backing user for LDAP user..." 
This comes as a result of a regular expression check that seems to be too strict, as a distinguished name can contain almost any character ([with the exception of some that have to be escaped](https://ldapwiki.com/wiki/DN%20Escape%20Values)).
The validation check therefore fails when any whitespace character is present, e.g.
CN=Name Surname,OU=ResearchAndDev,OU=Users,DC=company,DC=com
as the current implementation does a rudimentary RegEx evaluation against
https://github.com/treeverse/lakeFS/blob/df12f179ad4c595c97ffdfd739f6d500e4faf2c0/pkg/auth/model/validation.go#L15

On the subject of distinguished names:
While case-sensitivity for distinguished names is [implementation dependent](https://ldapwiki.com/wiki/Distinguished%20Name%20Case%20Sensitivity), most implementations treat them as case insensitive,
meaning that the following should be regarded as equal:
CN=Name Surname,DC=company,DC=com
cn=Name Surname,Dc=company,dC=com
Furthermore the corresponding relative distinguished names only have to appear
in the [same order relative to each other](https://ldapwiki.com/wiki/DistinguishedNameMatch). If I understood the ldap wiki entry correctly this example should also pass equality:
CN=Name Surname,OU=ResearchAndDev,OU=Users,DC=company,DC=com
CN=Name Surname,DC=company,DC=com,OU=ResearchAndDev,OU=Users

Please consider changing the distinguished name validation rules to at least include all permitted characters.

**Comment by arielshaqed** [comment]
Thanks, @roman-komac! Clear oversights on my part 😞.

I would rank validation as more urgent (and,  thankfully, easier...) than equality. There is no workaround for not being able to log in; meanwhile (I _expect_, but with no empirical backing) that most LDAP lookups will return DNs in some fixed ordering.

Would you agree?

**Comment by roman-komac** [comment]
@arielshaqed  Thank you for addressing this bug and apologies for the late reply, I somehow overlooked the mail notification over the weekend.
I would agree that validation should have much higher priority. The only edge case that I can really think of is if the Ldap directory was rebuilt from scratch. In that case the ordering might change.

Kudos also to @nopcoder, I am pleasantly surprised by how quickly this issue was resolved 😃

**Comment by arielshaqed** [comment]
> @arielshaqed Thank you for addressing this bug and apologies for the late reply, I somehow overlooked the mail notification over the weekend. I would agree that validation should have much higher priority. The only edge case that I can really think of is if the Ldap directory was rebuilt from scratch. In that case the ordering might change.
> 
> Kudos also to @nopcoder, I am pleasantly surprised by how quickly this issue was resolved smiley

We probably closed this entire issue by mistake after #2774.  So I opened #2781 with the remaining items.

Thanks for discovering, investigating, and reporting it!
