### ISSUE TITLE
[metastore] discover metastore solution on top of lakeFS

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2789]
One of the major high level design decisions we need to take to implement a metastore, is whether the implementation is part of lakeFS service itself or external to lakeFS.

Having lakeFS as the storage and versioning for the metastore, implementing a metastore above lakeFS.
Listing the pros and cons by mapping the challenges by going this route.

**Comment by Jonathan-Rosenberg** [comment]
Do together with #2790

**Comment by itaiad200** [comment]
Closing, we broke it down to various metastores issues.
