### ISSUE TITLE
[metastore] discover solution as part of lakeFS

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2790]
One of the major high level design decisions we need to take to implement a metastore, is whether the implementation is part of lakeFS service itself or external to lakeFS.

Implementing a metastore as part of lakeFS, using gravler as the main engine to track/store/fetch the information.
Listing the pros and cons by mapping the challenges by going this route.

**Comment by Jonathan-Rosenberg** [comment]
Do together with #2789

**Comment by rupurt** [comment]
If it helps project Nessie includes a metastore https://projectnessie.org/develop/
