### ISSUE TITLE
Support "presigned URLs" as in AWS

### ISSUE THREAD

**Issue by tc-imba** [treeverse/lakeFS#2792]
In AWS, we can create a presigned URL to an object, and give read/write access to the URL with an expiration time.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html

In lakeFS, currently I can only achieve a similar effect by creating a lakeFS user for each real user in my DB and creating a policy to one resource (on repository/branch level) if the user requests it and my own auth logic allows the user to access the resource. 

One problem is that the policies don't have expiration time, so it's not easy if I want to cancel the access of one user some time later (a possible solution is to implement a LRU based data structure and register timer events to remove the expired policies). And I'm not sure whether creating too many policies will degrade the performance of lakeFS.

If presigned URL is supported, I don't need any user and policy, any client with the generated URL can visit the resource in a period of time.

Possible related: #1428

**Comment by arielshaqed** [comment]
Hi @tc-imba,

Thanks for this feature request. I edited the title to be imperative, I hope that's OK.  I understand why managing policies externally to lakeFS would be operationally hard.

There is no hard limit on the number of policies, and generally I would expect that but to scale quite well. However managing so many policies will probably end up being prohibitive. 

On the subject of S3, have you considered using iam policies with a date conditional? We don't support those either,  I'm just mapping options for now.

In the meantime, if you can model your authorization logic in iam you will have a much easier time.

**Comment by tc-imba** [comment]
I have a quick view on iam, seems it's quite similar to the policies defined in lakeFS? But it doesn't fit all applications. For example, suppose we are going to build a service like github repos with collaboraters, we have to build one more layer on it.

Anyway, policies with a date is a good idea, it should simplify everything a lot. Hope that we can have this in the future.

**Comment by arielshaqed** [comment]
Note that this is *NOT* the use of presigned S3 URLs by lakeFSFS and other client!  In that, lakeFS and its clients _consume_ presigned URLs from the blockstore.  Here we're talking about lakeFS _producing_ presigned URLs for its clients.
