### ISSUE TITLE
Document which OutputCommitter to use with Spark

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2798]
lakeFS Spark integration docs should recommend which OutputCommitter to use, as well as how to configure it.
The docs should probably take into account questions like:

- is the native HadoopFS being used, or the S3 Gateway?
- What is the underlying object store used?
- is it possible for multiple jobs/clusters to write to the same collections on the same branch?
- can we assume failed jobs will be followed by a "reset" action in lakeFS?

It's possible not all of these actually have any impact, but are worth considering.

**Comment by arielshaqed** [comment]
Note that "the" FileOutputCommitter (sort-of default) actually has _two_ available versions, the old v1 and the newer v2 which is recommended **NOT** to be used -- but popular with some users.  So nontrivial recommendation.

**Comment by johnnyaug** [comment]
@arielshaqed can we close this?
