### ISSUE TITLE
Docs point to stale HadoopFS and not the latest version

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2802]
[Docs](https://docs.lakefs.io/integrations/spark.html#load-the-filesystem-jars) currently point to 0.1.3 as the latest version, although 0.1.4 is the latest.

**Comment by arielshaqed** [comment]
0.1.6 is latest; fixing...

**Comment by arielshaqed** [comment]
Opening a separate issue to automate this.
