### ISSUE TITLE
lakectl diff fails when diff is big

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2817]
`lakectl diff` uses exponentially growing page sizes, starting from 50 and doubling on every page.

The server doesn't allow page size > 1000, so when there are enough records in the diff to get to an amount bigger than 1000, the server returns an error.

I suggested #2811 as a fix, in which the client will limit itself - but after discussing with @arielshaqed, we decided that it makes sense to cap the page size on the server side instead of returning an error. That is, if the amount received by the server is greater than 1000, return at most a 1000 records.

**Comment by ozkatz** [comment]
I suggest returning an error instead of truncating the response to the allowed limit. A pattern that is (unfortunately) pretty common when working with paginated responses, is to assume that if `amount of results received for current page < amount I request per page`, I don't have to go check the pagination fields, I can just assume there are no more results to return. 

If we truncate at 1000, a user requesting 1100 can assume there were only 1000 results and no further pages exist. This is of course an anti-pattern, and likely a wrong assumption - but I believe good DX means making it easy to build **a correct system**.

**Comment by johnnyaug** [comment]
@ozkatz, I see your point - I'm find with both solutions (in your suggestion the client needs to limit the page size to the one allowed by server)

**Comment by arielshaqed** [comment]
> I suggest returning an error instead of truncating the response to the allowed limit. A pattern that is (unfortunately) pretty common when working with paginated responses, is to assume that if `amount of results received for current page < amount I request per page`, I don't have to go check the pagination fields, I can just assume there are no more results to return.
> 
> If we truncate at 1000, a user requesting 1100 can assume there were only 1000 results and no further pages exist. This is of course an anti-pattern, and likely a wrong assumption - but I believe good DX means making it easy to build **a correct system**.

OTOH, AWS do exactly the truncation behaviour that you do not like.  In fact this caller bug (anti-pattern suggests bad practice that yields correct results) inhibits many optimizations that we may wish to add in future.  In exchange, it is also immediately less efficient -- always adds another API call to get to the correct value.

As an alternative that avoids tying us to unjustified behaviour, the paginator could (probably) use the [`max_per_page` field](https://github.com/treeverse/lakeFS/blob/acc7116d9dbb8f7a28e52c20d1b8ae46daf29f40/api/swagger.yml#L120) on pagination.

**Comment by ozkatz** [comment]
@arielshaqed I see your point. 

I agree we need to allow clients to pass their preference even if it's larger than the max size, and let the server return a smaller response if it goes over the max allowed per page. This will indeed allow clients to negotiate a desired payload size more efficiently and reduce the coupling between client and server.
