### ISSUE TITLE
UI: E2E tests implementation 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2827]
This issue follows the decisions made in https://github.com/treeverse/lakeFS/pull/2805. 

Below is a suggested tasks breakdown,  1-3 can be parallelized, and 4 is the final task: 
1. Define the main UI workflows to be tested
2. Configure Jest & Puppeteer
3. Figure out how to use [testcontainers](https://www.npmjs.com/package/testcontainers) to set up lakeFS test servers and decide when to instantiate test containers. 
4. Implement the tests

**Comment by ortz** [comment]
@eladlachmi relates to cypress?

**Comment by eladlachmi** [comment]
@ortz Yes, it's related.

1. I can take up with @ozkatz 
2. I'm leaning more towards Cypress for E2E tests. In any case, Jest + Puppeteer are probably not the most recommended tools for E2E tests
3. I think this can be covered by @Isan-Rivkin 's current "deployment per-PR" effort
4. Meh. That's the easy part 😅

I'll assign it to myself, if you don't mind.
