### ISSUE TITLE
UI: Improve Create new repo input

### ISSUE THREAD

**Issue by peacing** [treeverse/lakeFS#2838]
**Context:** When creating a new repo in lakeFS you are asked to input the storage namespace. It is slightly annoying that as soon as you type in that text box the helpful suggested input disappears. 

![Screen Shot 2021-12-27 at 11 39 11 AM](https://user-images.githubusercontent.com/11055355/147506790-2a2e454e-317c-4f73-841f-e11f4f7222ae.png)

It would be nice if it only disappeared once you deviate from the suggested input! (which is `local://example-bucket/` for docker based environments by the way. The suggestion is correct, but just pointing out it's not as simple as always remembering it starts with `s3://`)

![Screen Shot 2021-12-27 at 11 39 17 AM](https://user-images.githubusercontent.com/11055355/147506938-68e5b50e-5024-46f8-be8b-8e45cc572891.png)

**EDIT** Also for the first input text box I would suggest "Repository Name" instead of "ID"

**Comment by johnnyaug** [comment]
Related:
* Issue: #2955 
* Change: #2952 (added an option for admin to set a default storage namespace, and also an Info button linking to the documentation).
