### ISSUE TITLE
UI: Missing error while creating a branch with invalid name

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2839]
While trying to create a branch with invalid name, lakeFS' openAPI returns an error but the UI does not show it. 

![Screen Shot 2021-12-28 at 9 45 39](https://user-images.githubusercontent.com/14786381/147541853-50d46f21-925b-4868-a3ec-1f33a14b6306.png)
![Screen Shot 2021-12-28 at 9 45 27](https://user-images.githubusercontent.com/14786381/147541855-5691bfb6-4e0a-4a43-8797-409ecd34254d.png)

### Steps to reproduce
From the lakeFS UI, try to create a branch with invalid name (i.e. name that containers characters different than words or dashs e.g. new-name%)

**Comment by itaiad200** [comment]
Hey @vinodhini8694 - are you working on this?
