### ISSUE TITLE
Docs: document the existence of $LAKECTL_BASE_URI

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2847]
It's a very handy environment variable that isn't documented anywhere. For example, [this suggestion on the lakeFS Slack space](https://lakefs.slack.com/archives/C01678929QT/p1640820012014500) could be solved quite nicely using it:

```bash
$ export LAKECTL_BASE_URI="lakefs://my-repo/my-branch"
# Once set, use relative lakefs uri's:
$ lakectl ingest --from s3://bucket/prefix --to /path
$ lakectl fs ls /path
```

**Comment by nopcoder** [comment]
Note that this based on the fact that our configuration map all the keys to environment names.
So maybe explaining how we read configuration and than the fact that there is a flag 'base-uri' that gets the default based on this configuration.

**Comment by ozkatz** [comment]
@nopcoder for some reason we explicitly call `os.GetEnv` for this [specific configuration](https://github.com/treeverse/lakeFS/blob/master/cmd/lakectl/cmd/root.go#L149) not sure why.

In any case, we should definitely explain how to use env vars for lakectl in general, 
but at least for this specific flag, also explain the use case since the flag is hard to use/understand without using it as an env var or command alias:

```bash
$ lakectl --base-uri lakefs://lakefs://my-repo/my-branch fs ls /path
```

I think we can agree this is not very intuitive.

**Comment by nopcoder** [comment]
@ozkatz the flag was there to keep the option to be explicit
