### ISSUE TITLE
Delete default branch should be blocked

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2850]
Currently it is possible to delete all branches from the repository, including the default branch which is used to create other branch.
In order not to keep a repository in unused condition we should block at least the delete of the repository default branch.
 
Example of how to reproduce

```sh
lakectl repo create lakefs://example s3://bucket
lakectl branch delete --yes main
```

**Comment by arielshaqed** [comment]
Not sure I agree. First, the repository will still be usable if you have a HEAD digest - just create a new branch from that ref.

In fact,  a friend regularly deletes their git trunk as a way of getting out of stone forms of trouble - especially in new repos.

I would be happier if we just by default protected the trunk from deletion (branch protection style). WDYT?

**Comment by nopcoder** [comment]
> Not sure I agree. First, the repository will still be usable if you have a HEAD digest - just create a new branch from that ref.
> 
> In fact, a friend regularly deletes their git trunk as a way of getting out of stone forms of trouble - especially in new repos.
> 
> I would be happier if we just by default protected the trunk from deletion (branch protection style). WDYT?

Hi @arielshaqed missed this one - can follow-up with a fix, but I wish to understand if you mean we need to enable another branch production or check something else?
Another reason I wanted to prevent default branch was out default when we create a new one.
As part of having a repository (not like git) we create a default branch.

**Comment by arielshaqed** [comment]
Not sure that this feature is desirable, particularly if there is no way to override it.  There are valid reasons for wanting to delete the default branch of a repo.  (Git also has a default branch, it merely does not have an initial commit.)

One common flow that ends in deleting `main` is that you want to change the default branch.  So you create a *new* branch, make the changes that you need, test it under this different name, and then *delete* `main` and *rename* the new branch to `main`.  Not everybody does this, but I know people who do just this (on Git).  I believe this is not a good place to be opinionated, so we should allow it.

As for making it harder to do by mistake (e.g. by some variant of branch protection), or easier to fix after you make a mistake (e.g. by implementing a reflog as per #2321) -- sure!  Just keep some way of doing it if possible.

**Comment by nopcoder** [comment]
Git enables it, but I think we modeled it more like GitHub:

```
If the branch you want to delete is the repository's default branch, you must choose a new default branch before deleting the branch. For more information, see "Changing the default branch."
```

Change default branch is a valid option I think we should enable it as github does. (we used to have it)
Also branch protection option to prevent branch delete should be a good feature.
