### ISSUE TITLE
lakectl tests - replace usage of 'script' with golang pty support

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#2855]
lakectl command line testing (#1657 ) introduced the use of linux's 'script' command to emulate a tty (#2763 )
While this works on linux systems, it required nessie to install util-linux on alpine based container (which is currently used)
More over, for development over non linux systems, this might impose a problem

Need to remove this dependency and use golang support of pty instead - https://github.com/creack/pty

**Comment by nopcoder** [comment]
We should consider just adding a global flag that controls lakectl color/tty. Assume that the flag does work we can test the output without adding any command line or test dependency.
Must command line that supports conditional output, like 'ls' also holds a flag that forces the behavior.

**Comment by itai-david** [comment]
We should also consider to ditch the usage of /bin/sh as this (potentially) prevents windows users from running nessie locally.
Maybe we can use ```lakectl``` as the command for ```exec.Command``` and send the rest of the string, divided, as argument list

**Comment by nopcoder** [comment]
Closing this one as it was fixed by using LAKECTL_INTERACTIVE env vars that controls the output.
