### ISSUE TITLE
Discovery: Test whether Azcopy works with lakeFS

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2862]
[AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-configuration-settings?toc=/azure/storage/blobs/toc.json
) is a command-line utility that you can use to copy blobs or files to or from a storage account. 

This issue is a discovery task to test whether it works with lakeFS. it uses the following configuration variables that we probably try to tune first:
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AZCOPY_ACTIVE_DIRECTORY_ENDPOINT

**Comment by guy-har** [comment]
Unfortunately, Azcopy has no way to set AWS S3 endpoints.
Azcopy has an open issue for this https://github.com/Azure/azure-storage-azcopy/issues/832
