### ISSUE TITLE
Testing for fs cat, after changes have been done.

### ISSUE THREAD

**Issue by shimi9276** [treeverse/lakeFS#2864]
As a continuation to issue #2825. We should add testing to the new functionality. Especially use PR #1657 to achieve this.

**Comment by arielshaqed** [comment]
In particular these tests should be sufficient to have detected [this](https://github.com/treeverse/lakeFS/pull/2852#discussion_r777337582) in #2852.  So they must test both a client-side error (say, connecting to a bad endpoint URL) _and_ (especially) an HTTP error (say, `lakectl fs cat lakefs://repo/main/path/does/not/exist/on/repo/and/branch/that/do/exist`).
