### ISSUE TITLE
Large commits take long time to complete

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#2874]
* Large commits are taking a long time (> 60 seconds) 
* Users with configured timeout in a network component on the way to lakeFS (such as load balancer) fail to commit due to timeout

**Comment by eden-ohana** [comment]
# Current status

## What's Done
* We seem to be re-using existing ranges properly. That is, we do not write existing ranges again during the commit.
* TierFS/Pyramid does not seem to cause the slowness - similar performance was measured when using the native filesystem.
* CPU profiling suggests that a substantial time of the commit is spent calculating SHA256 hashes. Changing the hash to MD5 (faster calculation) didn't seem to decrease the run time.
* CPU profiling suggests we spent time waiting for a response from Postgres. We tried to increase Postgres RDS size in order to get more i/o operation. It didn't change the results.
* Separate the merge and commit operation.
* Mutex profile stack traces of holders of contended mutexes hasn't suggested we spent significant time waiting for unlock.

## In progress
* Keep-alive on request for long operations - reject for now. #2710
* Parallelization by breaking the ranges on fixed points. Estimated time - one month. #2875

## Next steps 
* In case we'll see the parallelization will decrease the time complexity significantly (< 1 min) we will implement it completely.

**Comment by arielshaqed** [comment]
Pyramid should be *speeding things up*, not slowing down.  (It uses CPU but saves time...).

Have we tried boosting the local cache size to be e.g. 100GiB, and seen that it still happens?

**Comment by guy-har** [comment]
@arielshaqed 
Boosting the cache size did improve the commit time.
for a large commit that took 2:40 boosting the cache reduced the time to 1:37

**Comment by talSofer** [comment]
Considering the latest feedback we got from users, saying that commits take < 60 sec to complete, I'd like to close this issue for now and re-open it when needed.
This means that we shall park https://github.com/treeverse/lakeFS/pull/2921 until users experience this pain. The reasons are: this change requires a lot of work to verify that nothing breaks, and although the implementation is almost done there is still more work to do there. 

@guy-har @eden-ohana @itaiad200 are you ok with this?
