### ISSUE TITLE
Evaluate parallel commit optimization

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#2875]
Currently, the commit is taking a long time (more than 1 min) which causes commits to fail due to timeout.
We would like to evaluate how much time could be reduced by parallelizing the commit.

**Comment by guy-har** [comment]
To evaluate what and if we could gain from optimizing our commit 

I created a commit case which:
- has 500,000 objects in staging
- The commit spans over ranges with a summarized size of 2.6GB ( the summarized size of the complete metadata is much more)
- The commit takes 2:40 on an `m5.xlarge` machine with lakeFS with default configurations (cache size 1GB)

Tested three cases:
- Default configurations 
- Large cache - enough to contain the relevant data for the commit, and force the relevant ranges to be in the cache
- Parallel - By breaking into chunks, running the commit action on each chunk (without creating the metarange). at the end collecting all the ranges and creating a metarange

The results were as follows:

on an `m5.xlarge` machine ( 4 vCPUs):
Default configurations : 2:47
Large cache -  1:37
Parallel - 0:47

on an  `m5d.4xlarge` machine (16 vCPUs):
Large cache -  1:30
Parallel - 0:30

**Comment by arielshaqed** [comment]
Apologies for any and all of these you may already have done.

I think it would be very helpful to collect and use and possibly add observability to the system that allow understanding this case.  They will allow us to understand what is taking time.

For instance:
* All existing profiling endpoints: mutex contention (`_pprof/block`) might be interesting, especially in the parallel case.
* Pyramid swap-in and swap-out counters.  These already exist as Prometheus counters in `pkg/pyramid/metrics.go`, we should check their values.  Note however that "Miss" slightly overcounts: it includes both the initial access that fetches the object _and_ the concurrent accesses that wait for it to show up.  We might split it up into "Miss" and "Wait" -- the latter is still bad news for time spent waiting for objects, but good news for number of S3 accesses.
* Add metrics to our iterators, counting regular `Next` and `NextRange` operations.  We could put a "usage" field onto these metrics by passing one to the iterator constructor, e.g. "commit_base", "commit_diffs", "merge_destination" etc.
* Can we discover whether S3 is rate-limiting us somehow?  CloudWatch might have relevant metrics, or we might see the distinctive "quiet periods" pattern of rate limits.
* Continue to look at traces.  E.g. in the parallel case: what happens during a fetch from S3, or even file opens on the machine?  If parallel fetches compete with each other, then we should remove that.

Pyramid metrics, specifically hit and miss rates, should tell us how effective it is in the current case -- but I am not sure they are enough to tell us what to improve.

Current numbers show parallelization helping.  I **assume** these were parallel with a larger cache -- parallel ops will use that larger cache even more than regular.  That would suggest we can get a boost (with or without parallelization) merely by prefetching the _next_ block or two from every iterator on the second `Next()` call in a range (i.e. an operation entered a range).  The existing Pyramid counters should already teach us a lot about whether we still have to wait for that block to show up during a fetch.
