### ISSUE TITLE
Allow setting creation date for commits, objects, etc. to import commit history from other tools

### ISSUE THREAD

**Issue by Aloisius** [treeverse/lakeFS#2877]
We have a data repository structured as git-like immutable content addressable store with several years worth of historical data in it that we'd like to import into lakefs. Unfortunately, the lakefs API doesn't appear to allow setting creation date for operations like upload or commit, so information about when a particular commit happened would be lost.

Ideally, I'd be able to set CreationDate when creating a repo, uploading an object and creating a commit via the API. With that I'd be able to transfer our history into lakefs without much issue.

**Comment by guy-har** [comment]
@Aloisius, there currently is a way to add objects with a set creation date.
This is done by using the [stage operation](https://docs.lakefs.io/reference/api.html#/objects/stageObject).
The stage operation is a plumbing operation that supports staging a reference to an existing object.
Using the `stage` command you will not even need copy the data into lakeFS, you could just reference their current location in your object store.
Note that you will need to supply additional data such as checksum and size.

Example  using the lakectl command - `stage` :
running `lakectl fs stage lakefs://my-repo/my-branch/path/to/object --location s3://my-bucket/path/to/orig --size 23300000 --mtime 1642598716 --checksum 12324567`

will stage add the object to lakeFS under  repository `my-repo` branch `my-branch` with key `path/to/object`
The object would be linked to `s3://my-bucket/path/to/orig `
And will hold the meta-data 
```
size: 23.3MB
created date: Wednesday, January 19, 2022 1:25:16 PM
checksum: 12324567
```

**Comment by guy-har** [comment]
According to the commit, I understand the need and we will add a way to create a commit with a set date.

**Comment by Aloisius** [comment]
Commit dates are far more important to us since that that allows for testing on data as of a certain date.

The stage operation would work for referencing existing data though I had planned to transfer the data to the lakefs repo bucket itself, so I wanted it structured in the same way lakefs structures the rest of the files in a bucket just for consistency. I could just reproduce the file layout myself, but ideally the upload API would allow it.

**Comment by JJRTaylor** [comment]
> @Aloisius, there currently is a way to add objects with a set creation date. This is done by using the [stage operation](https://docs.lakefs.io/reference/api.html#/objects/stageObject). The stage operation is a plumbing operation that supports staging a reference to an existing object. Using the `stage` command you will not even need copy the data into lakeFS, you could just reference their current location in your object store. Note that you will need to supply additional data such as checksum and size.
> 
> Example using the lakectl command - `stage` : running `lakectl fs stage lakefs://my-repo/my-branch/path/to/object --location s3://my-bucket/path/to/orig --size 23300000 --mtime 1642598716 --checksum 12324567`
> 
> will stage add the object to lakeFS under repository `my-repo` branch `my-branch` with key `path/to/object` The object would be linked to `s3://my-bucket/path/to/orig ` And will hold the meta-data
> 
> ```
> size: 23.3MB
> created date: Wednesday, January 19, 2022 1:25:16 PM
> checksum: 12324567
> ```

Aloisius (Jordan Mendelson) is a child molestor. I’m his brother and he molested me for years and refuses to now face me.

**Comment by JJRTaylor** [comment]
> According to the commit, I understand the need and we will add a way to create a commit with a set date.

Aloisius (Jordan Mendelson) is a child molestor. I’m his brother and he molested me for years and refuses to now face me.
