### ISSUE TITLE
BUG : Upload directory path not parsed correctly

### ISSUE THREAD

**Issue by mishraprafful** [treeverse/lakeFS#2880]
**Description**
When uploading from a windows machine using the command line. The directory structure is not preserved. All the files are named as files with the directory names prepended to it.

Maybe, as the source machine is windows the path for files are not separated by `/` instead are separated by `\`, which leads to such behavior.

**Steps to Reproduce**
* Have a recursive directory structure you wish to upload like
```
|-README.md
|-cleaned
  |-.gitkeep
|-data
  |-.gitkeep
  |-data2
    |-.gitkeep
```
* Use poewrshell to run the upload command `lfs fs upload ls lakefs://repository/branch/ --recursive --source .\data\`

**Expected Behaviour**
The files get uploaded with the directory structure preserved. 

**Observed Behaviour**

![Screenshot 2022-01-21 at 15 49 42](https://user-images.githubusercontent.com/32913433/150547387-2851c2b1-879d-4291-b7ec-0796b6521acd.png)

**Comment by itai-david** [comment]
Hi @mishraprafful.
Just wanted to keep you in the loop - a fix for this bug is under review and hopefully will be merged shortly.
I also opened another issue, #2931, to add automatic tests, as a follow-up to 
Thank you for pointing this issue out
