### ISSUE TITLE
Get object metadata error in lakeFSFS

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#2891]
When using Databricks (and possibly not only Databricks) with lakeFSFS assembly jar, some of the processes are aborted with IOException - "failed to get object metadata using underlying s3 client". 
This error is flaky and its cause is unclear. 
We should check the cause and resolve it. 

** This bug was found while setting up Yotpo's environment.

**Comment by guy-har** [comment]
Fixed by #2896
