### ISSUE TITLE
BUG: `lakectl annotate` should default to non-recursive listing

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2897]
currently, `lakectl annotate` will list objects recursively (which is a default behavior for an object store but not so much for data systems). This is less useful: As most data systems are usually directory or prefix based, seeing the last change per prefix (for example table or partition) is much more useful than seeing it per data object.

this will also make `lakectl annotate` consistent in behavior with `lakectl fs ls` and `aws s3 ls` which default to non-recursive listing. The current behavior can be preserved under a `--recursive` flag.

**Comment by Jonathan-Rosenberg** [comment]
Hi @ozkatz 
As for the prefix listing, do you expect the tool to receive a prefix as an argument and present the latest modified commit that occurred under that prefix?

**Comment by ozkatz** [comment]
no :)
the `lakectl annotate` command already receives a path URI that may include a prefix, this part actually works as expected.
The problem is that currently, the command will recursively show all objects nested anywhere under that prefix, instead of "folding" the results into common prefixes.

I'll illustrate with an example:

Given the following set of keys:

```
a/b/c
a/b/d
a/c/a
a/c/b
a/d
```

currently, `annotate` will do the following:

```shell
$ lakectl annotate lakefs://repo/main/a/

a/b/c <last commit to modify a/b/c>
a/b/d <last commit to modify a/b/d>
a/c/a <last commit to modify a/c/a>
a/c/b <last commit to modify a/c/b>
a/d <last commit to modify a/d>
```

While the desired output should be:

```shell
$ lakectl annotate lakefs://repo/main/a/

a/b/ <last commit to modify anything under a/b/>
a/c/ <last commit to modify anything under a/c/>
a/d <last commit to modify a/d>
```

Nice to have: retain the current behavior but with an optional `--recursive` flag
This will be consistent with `lakectl fs ls` as well as the aws cli.

**Comment by Jonathan-Rosenberg** [comment]
Sounds good
Thanks for the clarification!

**Comment by itai-david** [comment]
@ozkatz - question regarding the desired example above:
`
While the desired output should be:

$ lakectl annotate lakefs://repo/main/a/

a/b/ <last commit to modify anything under a/b/>
a/c/ <last commit to modify anything under a/c/>
a/d <last commit to modify a/d>
`

The output missing an entry to the requested path itself, i.e.:
`a/ <last commit to modify anything under a/>`
Is that intentional? Should we include this (I think we should)?

**Comment by ozkatz** [comment]
@itai-david good question - while I see why this makes some sense, it means breaking consistency with `lakefs fs ls`. 
Users can always do `lakectl log lakefs://repo/ref --amount 1 --prefixes a/ ` to get the last modification to the root prefix.
WDYT?

**Comment by itai-david** [comment]
@ozkatz - agrred. I was just looking at `lakectl fs ls` and was getting to the same conclusion my self.
Thanks

**Comment by itaiad200** [comment]
@itai-david `aws s3 ls` behaviour for prefixes is better IMO. Copying it to `annotate` will look like:
```shell
$ lakectl annotate lakefs://repo/main/a/

a/b/ <last commit to modify anything under a/b/>
a/c/ <last commit to modify anything under a/c/>
a/d <last commit to modify a/d>

$ lakectl annotate lakefs://repo/main/a

a/ <last commit to modify anything under a/>
```
