### ISSUE TITLE
Stream content in UploadObject

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2905]
[`api.Controller.UploadObject`](https://github.com/treeverse/lakeFS/blob/0cb453004eae50665d8ea32e680e091ae1260f5b/pkg/api/controller.go#L1839) reads multipart uploads using `http.Request.FormFile` -- which can use up to 32MiB of memory _and_ create temporary files.

We probably don't need any of that (unless OpenAPI has already used `ParseMultipart` for us, in which case we're doomed...), because we know exactly what parts to expect.  Just use `MultipartReader()`, and stream the relevant part in with minimal use of memory.

**Comment by arielshaqed** [comment]
@nopcoder OpenAPI doesn't touch the multipart portion of the request, right?  Asking it has only path parameters, but it also sets `x-validation-exclude-body: false` and I don't know what that does.

**Comment by nopcoder** [comment]
the x attribute is for the validation middle not to check.

**Comment by arielshaqed** [comment]
> the x attribute is for the validation middle not to check. it doesn't touch it.

I read it the opposite way: we call `ValidateRequest` from our `validateRequest`.  We do _not_ set `ExcludeRequestBody` on the options, because the extension is `false`.  Now we call `openapi3filter.ValidateRequest`, passing options with `ExcludeRequestBody: false`.  That sees a non-empty request body, and `!options.ExcludeRequestBody` is `true`, so it calls `ValidateRequestBody`.  And _that_ reads the entire body in.

That's why I opened #2907 as well -- that option makes validation _read_ the body.  (This is why I hate negative option names like `ExcludeX` -- you need them in Go because there are no constructors, but the negative name makes it hard to think about things).
