### ISSUE TITLE
Nessie tests should be ignored for docs/UI only changes

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2912]
To save time, Pull Requests containing only changes under `docs/` or `webui/` can be ignored.

However, since Nessie tests are rightly marked as required in the `master` branch protection rules - we can't just add them to the ignored paths of the jobs. This is why #2911 removed these paths from the ignored paths.

Need to find some workaround to allow ignoring these paths while still making the tests required for other PRs.
Note that there is a [suggested workaround by GitHub](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) but it may be annoying to maintain.

**Comment by arielshaqed** [comment]
Fixed by #3036 :-) IIUC. :-)
