### ISSUE TITLE
Add support for dbt 1.x.x

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#2957]
Currently we support version 0.21.x.
dbt 1.0.0 introduced some breaking changes that should be handled.
The breaking changes can be found [here](https://github.com/dbt-labs/dbt-core/blob/1.0.latest/CHANGELOG.md) and [here](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0#breaking-changes).

**Comment by arielshaqed** [comment]
Seems resolved by  #3851 and/or earlier.

Please re-open if this is still broken.
