### ISSUE TITLE
Redo architecture page 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2958]
Make the [Architecture](https://docs.lakefs.io/understand/architecture.html) page represent the current state of lakeFS: 
- Include available SDKs
- Include Spark client
- List supported storage adapters
- Dedicate a section to Graveler with links to data model
- Redo the diagram

Specifically handle: 
- https://github.com/treeverse/lakeFS/issues/1640
- https://github.com/treeverse/lakeFS/issues/2858

**Comment by itaiad200** [comment]
Done with #3015
