### ISSUE TITLE
Provide a lakeFS Grafana dashboard 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2960]
lakeFS already exposes Prometheus metrics to <lakefs_url>/metrics. 
As part of the work on https://demo.lakefs.io/ we are creating our own grafana dashboards for these metrics. This issue suggests the following action items after creating the dashboard:
* Publically share it on Grafana.  
* Enrich everything Bagel by adding a  grafana container and a Prometheus backend that will collect the metrics and make them available to grafana.

**Comment by ortz** [comment]
Grafana docker image: https://hub.docker.com/r/grafana/grafana
Prometheus docker image: https://hub.docker.com/r/prom/prometheus
Docker-compose with Grafana, Prometheus, cAdvisor, NodeExporter and Alertmanager for reference: https://github.com/Einsteinish/Docker-Compose-Prometheus-and-Grafana/blob/master/docker-compose.yml
