### ISSUE TITLE
webui - Create A New Repository declares repo ID should be atleast 2 chars but does not allow less than 3

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#2967]
![image](https://user-images.githubusercontent.com/90712874/155600334-6b118495-312d-4c1f-b709-d36f4c1663fa.png)

The regex at webui/src/lib/components/repositoryCreateForm.jsx, line 18 actually requires 3-63 chars
```const repoValidityRegex = /^[a-z0-9][a-z0-9-]{2,62}$/;```
while the warning at line 77 states `Min 2 characters`

Should fix either one

**Comment by DataDavD** [comment]
Hello, not sure if this is assigned to anyone yet, but this seems like a simple enough fix that I can do in my limited spare time this week. Is that fine if I take ownership of this issue?

Thanks in advance

Best,
david

**Comment by itai-david** [comment]
Hello @DataDavD 
You are right and this issue is not assigned on anyone yet.
Not only it is OK if you claim the ownership, it will be highly appreciated.
Please feel free to contact me over this thread, or on our [slack](https://join.slack.com/t/lakefs/shared_invite/zt-ks1fwp0w-bgD9PIekW86WF25nE_8_tw) if you need any assitance

Thank you :pray:

**Comment by DataDavD** [comment]
Sounds good. I work on it this week. Thank you!
