### ISSUE TITLE
Accelerate FindMergeBase by caching commits 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2981]
This is a copy of @arielshaqed 's [comment](https://github.com/treeverse/lakeFS/issues/2962#issuecomment-1053289874)

https://github.com/treeverse/lakeFS/pull/2968 is very nice :-)

But it still performs many GetCommit calls, these are unnecessarily slow and in fact may be cached so are probably unnecessary.
### GetCommit is slow
This is intentional: this call is batched. This batching makes sense when performing other operations (see @tzahij's [blog post](https://lakefs.io/improving-postgres-performance-tenfold-using-go-concurrency/)) because they involve concurrency at load. For instance, when a large-scale Spark job starts reading from lakeFS, it performs multiple concurrent reads, and each fetches the same HEAD commit. Batching means responses arrive later than they might.

But batching does not make sense in FindMergeBase: this function sequentially fetches commits, so if we batch the commits we slow each iteration down. One speedup might be to pass this function an unbatched CommitGetter.

But we can do even better...

### GetCommit should be cached
There can be many thousands of commits. However, a quick inspection of graveler.go suggests that the relation graveler_commits is never updated other than by FillGenerations / LoadCommits. Commits are immutable.

So we can cache commits. Every call to GetCommit should go through a cache. The cache can (easily) have size 10_000, and will hold all relevant commits in memory. FillGenerations can simply invalidate the cache :-) , it is anyway only used by restore-refs. And, if we use our cache.Cache then we don't even need to batch: concurrent GetCommit operations only call out once to the database, and the result is cached for later operations.

**Comment by arielshaqed** [comment]
Just "versioning". You lot get to have all the fun on this one.

**Comment by arielshaqed** [comment]
This has actually been the case for a while, now. :-)
