### ISSUE TITLE
Screenshots of lakeFS UI in the docs should take up less screen space

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2990]
![image](https://user-images.githubusercontent.com/3149885/156027500-25b1aee5-b3da-4cf7-afb7-1b6136110af7.png)

As seen above, there is a lot of extra space around some screenshots in the docs.

We can still use the cool tool that adds the window-style border and controls (although you can also choose to remove it), but the extra space is hard on the eyes and makes the page read less fluently.

Scan the docs for such places and fix them.

**Comment by Harsh3363** [comment]
Hey can you specify in which file to make changes and can you assign this to me

**Comment by guy-har** [comment]
@johnnyaug can I close this?
