### ISSUE TITLE
Documentation - Fix statik package installation procedure in contributing page

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#2998]
The procedure to install statik (go get) was deprecated since go 1.17:

> % go get github.com/rakyll/statik                                                                                                                                                                   
go: downloading github.com/rakyll/statik v0.1.7
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

For go 1.17 and above use:

> go install github.com/rakyll/statik@&lt;version&gt;

**Comment by nopcoder** [comment]
- Should also be handled inside our makefile - make go-install
- Consider update the documentation to use the make step.
- Should consider upgrade to go 1.17 and have one set of instructions (if needed)

**Comment by N-o-Z** [comment]
@nopcoder go-install target uses install command but going over the makefile there are several places that use 'go get'. Do you suggest refactoring all of them? Also should the make file provided multiple go version support?

**Comment by nopcoder** [comment]
we keep tools.go file with all the main dependencies, if it is possible to install based on the content of the file. this is the best option. less maintenance and a way to lock the versions we use.
