### ISSUE TITLE
Architecture page has incorrect info for S3 gateway implementation

### ISSUE THREAD

**Issue by baolsen** [treeverse/lakeFS#3005]
The LakeFS documentation suggests that the S3A endpoint service runs on a different host / port whereas this is not the case.

Quote from here: https://docs.lakefs.io/understand/architecture.html#s3-gateway
"To achieve this, the gateway exposes an HTTP listener on a dedicated host and port."

However I have the LakeFS UI running here: `http://${aws_instance.server.public_ip}:8000`

And I successfully connect to the S3 gateway from Spark with 
`fs.s3a.endpoint` set to `http://${aws_instance.server.public_ip}:8000` 
This is the same endpoint as the UI, rather than a listener running on a different host / port as described.

**Comment by talSofer** [comment]
fixed by https://github.com/treeverse/lakeFS/pull/3015
