### ISSUE TITLE
Add a new flag `--include-staging` for `refs-dump`/`refs-restore` commands

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#3009]
Currently, when a user runs the `refs-dump` command (followed by a `refs-restore` command), we won't dump and restore for him the staging date. This might be painful when trying to debug an issue a user has with committing staging data for example. While it does make sense to not have the staging changes being dumped by default (since the staging data might be huge sometimes), we do want to have this capability for users that need it.

**Comment by arielshaqed** [comment]
Re-assigning to @treeverse/versioning-engine .
