### ISSUE TITLE
Support long running commit/merge operations

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3019]
The ability to run merge and commit operations that take longer than the HTTP request timeout setting.
(this will also make use as the infrastructure for long running hooks operations)

**Comment by Jonathan-Rosenberg** [comment]
@ozkatz can yo add the requirements for this issue?

**Comment by arielshaqed** [comment]
> The ability to run merge and commit operations that take longer than the HTTP request timeout setting. (this will also make use as the infrastructure for long running hooks operations)

Please, let's not tie this to long-running hooks. That is an entirely different issue - I claim that we should follow and enhance the GitHub model instead: commits have properties that are required to merge, some operations cause an external action to ru n (push to a branch, commit to  branch planned to merge, externally triggered - doesn't matter),  the action sets a property on the commit (or, more likely, adds an empty commit with that property). 

So I would not like the decision on actions (which includes never-ending waits!) to block a decision on long-running commits (which are guaranteed either to progress or to fail).
