### ISSUE TITLE
Support long running hooks / Branch status

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3020]
The ability to support hooks that run for a long period of time (hours instead of seconds) and to do so without blocking branches for writes.

**Comment by GalBachar** [comment]
Hey @Jonathan-Rosenberg and @nopcoder, is there a release date estimation for this issue?

P.S. I've noticed that it's possible to poll the DAG's state to support this implementation.
![Screen Shot 2022-04-25 at 12 01 11](https://user-images.githubusercontent.com/72210230/165056642-c5c3254b-dad0-4551-b51d-5184e8732cbf.png)
?

**Comment by nopcoder** [comment]
@GalBachar currently there it is on our near future roadmap, will update here the est by next week.

**Comment by itaiad200** [comment]
Need to gather requirements and user stories first.
@ortz @ozkatz

**Comment by nopcoder** [comment]
Close by https://github.com/treeverse/lakeFS/pull/5152
