### ISSUE TITLE
Remove `FillGenerations` func call from `LoadCommits`

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#3022]
On more advanced versions of LakeFS (probably > = v1.0.0), we would like to remove the logic that tries to fill the generation field in DB when loading old dumps. It means we will no longer support loading dump that made with a version lower than v0.61.0.

**Comment by tshradheya** [comment]
Hi,

So if the lakeFS version >1.0.0 we dont want to fill the generation for the commits.

How does the lakectl version come into play here?

**Comment by idanovo** [comment]
> Hi,
> 
> So if the lakeFS version >1.0.0 we dont want to fill the generation for the commits.
> 
> How does the lakectl version come into play here?

Hi @tshradheya,

Thanks for your question!

For commit dumps created using LakeFS versions greater than v0.60.1, we should have the generation field so we don't have to calculate them when trying to restore them. This is why we won't need FillGenerations func.

This ticket aims to remove the logic that handles a case where we are missing the generation field in the dump.

Since users that are trying to restore dumps that created LakeFS versions that are lower than v0.61.0 still need this logic, we currently keep it, but in future versions, we will remove it, which means we won't longer support restore for dumps that were created using those versions.

Does it make sense?

**Comment by idanovo** [comment]
Hi @tshradheya,

You are partially right, we want to remove the whole logic that fills the generation.

As you mentioned, we still need it if the dump was created using LakeFS version lower than v0.61.0 so we still remain this logic, but from a future version of LakeFS we won't longer support dumps that created LakeFS versions lower than v0.61.0.

This shouldn't be a problem for the users because they can easily create new dumps with later versions of LakeFS.

**Comment by Jonathan-Rosenberg** [comment]
Done
