### ISSUE TITLE
Build spark 3.2 support matrix

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#3027]
What does this mean that lakeFSFS supports a Spark version
- Nessie tests that check how HadoopFS pass for different Spark and Hadoop aws versions.
- FS contract tests pass for the supported Hadoop versions.
    Challenge: We will need to publish multiple Hadoop file systems, we may be able to provide hadoop-aws to avoid conflicts.
What does this mean that the metadata client supports a Spark version
This Needs a discovery, because it’s been a while since we’ve worked on it.
Action items:
- Metadata client: Can we compile the existing metadata client for Spark 3.2
- Metadata client: Map metadata client to Spark versions
- Metadata client: Discovery of tools that enable better exceptions translation to identify incorrect client versions being used.
- Metadata client: Discovery what automated tests do we have right now, and what tests should we add.
- HadoopFS: Discover the Spark-Hadoop combinations we need to support. Look at the combinations that EMR and Databricks support.
- HadoopFS: Test how our current Nessie tests work with the support Matrix
- Support Matrix: create the current matrix and publish it to lakeFS docs (Dimensions: Spark, Hadoop, Scala, Metadata client/HadoopFS)

**Comment by idanovo** [comment]
Things we should think about- tools we integrate with like Databricks, Spark jobs we have like the garbage collector...

**Comment by talSofer** [comment]
@arielshaqed I added a milestone link, feel free to close in case it's a dup
