### ISSUE TITLE
Test lakeFS with seaweedfs

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3033]
Test lakeFS with https://github.com/chrislusf/seaweedfs 

Came up from a user Slack question https://lakefs.slack.com/archives/C016726JLJW/p1646966529522249

**Comment by melon-gg** [comment]
![1P85YGzzll](https://user-images.githubusercontent.com/33046811/157818895-07440a13-cb0c-4a48-8e35-65d84881e751.png)
write small files(4MB) speed 100MB/s

**Comment by nopcoder** [comment]
@talSofer this is for adding more compatibility tests with different storage system. Or to investigate if our compatibility works with seaweedfs?

**Comment by talSofer** [comment]
@nopcoder the latter. I think that we can close this for now because according to @melon-gg seaweedfs works with lakeFS and so far no problems observed.

**Comment by nopcoder** [comment]
Thanks, @talSofer, closing this one
