### ISSUE TITLE
Test lakeFS with s3fs

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3034]
This ask came up in the following Slack thread 
https://lakefs.slack.com/archives/C016726JLJW/p1646984960662079

https://linux.die.net/man/1/s3fs#:~:text=s3fs%20is%20a%20FUSE%20filesystem,as%20a%20local%20file%20system.

**Comment by melon-gg** [comment]
through aws s3 ls can see lakefs bucket , but s3fs mount lakefs s3 bucket failed

**aws s3 --profile lakefs --endpoint-url http://192.168.0.65:8000 ls s3://lake/main/**
```
                           PRE DAVIS-2017-trainval-Full-Resolution-RAW/
2022-03-11 15:41:59         57 mount.txt
```
**s3fs lake lakefs-mnt -o url=http://192.168.0.65:8000 -o endpoint=cn -f -o passwd_file=/home/pai/.passwd-s3fs -o use_path_request_style -o sigv2**
```
[INF] s3fs.cpp:s3fs_init(3493): init v1.86(commit:unknown) with GnuTLS(gcrypt)
[CRT] s3fs.cpp:s3fs_check_service(3895): Bad Request(host=http://192.168.0.65:8000) - result of checking service****
```

**Comment by talSofer** [comment]
@melon-gg can you please try to run the same command with `-d` flag and share the logs output? this may help us understand why `cpp:s3fs_check_service` fails. 

I'm able to mount a lakeFS repo with the following command 
`s3fs my-repo mntPath -o passwd_file=$HOME/.passwd-s3fs -f -o allow_other -o url='my_url' -o use_path_request_style`

**Comment by talSofer** [comment]
Another question - did you add your lakeFS credentials into `.passwd-s3fs `?

**Comment by talSofer** [comment]
Tested lakeFS with s3fs and it worked, closing this issue
