### ISSUE TITLE
Decide which Spark/Hadoop combinations lakeFSFS should support

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#3056]
* What combinations that EMR and Databricks support?
* What do our users and our community use?

**Comment by johnnyaug** [comment]
At the moment, the lakeFS Hadoop FileSystem is agnostic to Hadoop/Spark versions.
It is tested with the latest Bitnami images:
* Spark 2 (Hadoop 2.7.4)
* Spark 3 (Hadoop 3.3.2)
