### ISSUE TITLE
RouterFS Documentation & Logs

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3062]
Things to think of while documenting RouterFS:
- Documenting RouterFS under its use case may work better than documenting it under its name. That is, as a user the title "using lakeFS and s3 without changing spark application code" means something to me, while "Route FileSystem" does not. 
- Document the LakeFSFS client version that'll work with RouterFS (it should include the solution that we will come up with in https://github.com/treeverse/hadoop-router-fs/issues/11)
- non-lakeFS users should be able to understand how to use RouterFS for their use cases (e.g. accessing s3 and gcs from the same Spark application)

### Definition of done 
Docs are available at https://docs.lakefs.io/ and as part of a client README

**Comment by talSofer** [comment]
@Jonathan-Rosenberg we are good to close this issue right?

**Comment by Jonathan-Rosenberg** [comment]
definitly
