### ISSUE TITLE
hook library: automate metastore operations

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3069]

**Comment by ozkatz** [comment]
# Metastore hooks - requirements

## Goals

Allow lakeFS users that query and manipulate data using Hive Metastore to automate the integration between both components:

1. Creating a branch/tag with a predefined naming convention will result in automatic creation of metastore tables (for a predefined set of table names)
1. Deleting a branch/tag with a predefined naming convention will result in automatic deletion of metastore tables (for a predefined set of table names)
1. Merging a branch into another branch will result in metastore changes between branches being applied to the metastore for modified tables defined on the destination branch

## Non-goals

1. Provide any sort of atomicity or consistency guarantees between Metastore and lakeFS (this is "best effort")


## User journey

This feature will requires combining 2 existing building blocks in lakeFS:

1. Lifecycle hooks: namely pre-merge, [pre-create-branch, pre-create-tag, post-delete-branch and post-delete-tag](https://github.com/treeverse/lakeFS/issues/3066).
1. lakeFS metastore integration API (issue TBD)

The flow would consist of the following steps:

1. user runs a hook library server (see below) that exposes a set of hooks matching the lifecycle event above.
1. user adds a `_lakefs_actions/metastore.yaml` file (copy-pasted-modified from our documentation or hook library repo)
1. user configures in that yaml file the following:
    1. a metastore address and connection details
    1. a list of tables to be copied and merged
    1. a naming convention(s) to branches and tags this applies to (i.e. `["dev_*", "experiment_*", "main"]`)
1. Once committed to main, branches and tags derived from main will automatically have tables created/deleted for them, and merges will apply metastore changes.

### Hook library server

We resurrect the lakeFS-Hooks repo - revamping it completely. It will be a consumer of the lakeFS Python SDK and provide 2 things:

1. A set of hook functions whose signature matches the parameters passed to every hook type. These should be documented importable by users who wish to expose said hooks via any hook execution mechanism they see fit (or extend the functionality).
1. A web server that wraps these hook functions and provides them as webhooks
1. A docker image, published to DockerHub that is built and published on every release of the library to pypi, to allow running it easily
1. A dedicated section in the lakeFS docs that has simple instructions on how to run and configure metastore integration
1. A Helm chart wrapping the docker image to allow running a hooks server easily on K8s (nice to have)

For the hook library, we will define a `metastore/` package with the relevant functions to create tables and merge them using the lakeFS Python SDK, as well as as a `/hooks/metastore/*` set of URLs that webhooks can trigger

### UI (lower priority)

I suggest Adding a Metastore section to the lakeFS UI to ease the automation:

![metastore](https://user-images.githubusercontent.com/205955/160125911-ce9cc941-765f-43d3-9304-43222a602054.png)

**Comment by ozkatz** [comment]
Thinking about it some more, I'm not sure there's any value in having the metastore integration logic inside lakeFS. 

Perhaps this logic belongs only inside the hook library? It has no dependency on anything internal (nor should it!)
