### ISSUE TITLE
Fail repository creation when its storage namespace is already used by another repository

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3077]
lakeFS repositories must be created with a unique storage namespace. that is, two repositories cannot share the same storage namespaces. 

#### Why 
It is a prerequisite for some advanced lakeFS features such as Garbage collection.

**Comment by itaiad200** [comment]
What if 2 different lakeFS installations use the same storage namespace?

**Comment by talSofer** [comment]
I think that it is reasonable to document a prerequisite that two distinct installations cannot use the same storage namespace, from a use case perspective I don't expect different installations to use the same storage namespace. The implementation however should allow to horizontally scale a single lakeFS installation. We can address both concerns by leaving a marker file on repository creation success and searching for it.

**Comment by itaiad200** [comment]
Not sure I understand the requirements here. The most simplified version of it would be:

User tries to create a `example` repo under `scheme://path/to/storage/namespace/` storageNamespace.
If a single file exists under `scheme://path/to/storage/namespace/_lakefs/`, fail the operation.

Is the above enough? Maybe @ozkatz can share more details?

**Comment by ozkatz** [comment]
@itaiad200 creating a new repository doesn't place anything under the `_lakefs/` prefix. 
Actually, even writing to a repository doesn't create this prefix. It only gets created once a commit has been done.

If we decide to create the `_lakefs/` prefix on repository creation, then yes, checking for its existence would probably be sufficient (even if there's a very small potential race condition here, I think the general case is covered and that should be enough).
