### ISSUE TITLE
gateway should identify wrong endpoints requests and return a friendly error

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3082]
Users often set the gateway endpoint in the clients with `/api/v1/` which is the openAPI endpoint. The return error in such cases isn't very informative:
```
java.nio.file.AccessDeniedException: s3a://<my-repo>/<my-branch>/<path-to-file>: getFileStatus on s3a://<my-repo>/<my-branch>/<path-to-file>: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 4442587FB7D0A2F9; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden
```

We should try and identify those cases and return a more informative error.

**Comment by N-o-Z** [comment]
> I believe we should return 501

Originally I thought the problem was that we return Forbidden on endpoints that don't exist in the S3GW. I wonder if that's still the case.

**Comment by itaigilo** [comment]
> > I believe we should return 501
> 
> Originally I thought the problem was that we return Forbidden on endpoints that don't exist in the S3GW. I wonder if that's still the case.

I still think it should be 404: 
Since practically it's not found - but with a possible explanation.
