### ISSUE TITLE
lakectl ingest adds multiple excess "/" to object name

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#3085]
Steps to reproduce:
1. Ingest into an empty repository:
   ```
   lakectl ingest  --from s3://treeverse-clients-us-east/logstore --to lakefs://example-repo/main/
   ```

2. List the objects:
   ```
   lakectl fs ls lakefs://example-repo/main/ --recursive
   ```

Expected list:
```
init_script.sh
lakefs-logstore-0.1-SNAPSHOT-jar-with-dependencies.jar
logstore-0.1-SNAPSHOT-jar-with-dependencies.jar
```

Got list:
```
//init_script.sh
//lakefs-logstore-0.1-SNAPSHOT-jar-with-dependencies.jar
//logstore-0.1-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by johnnyaug** [comment]
Thanks @tshradheya for finding this issue!

**Comment by itai-david** [comment]
@itaiad200 - No. It has nothing to do with the recent `walk` fix.
I will take it

**Comment by itai-david** [comment]
In case the `--to` path does not end with a `"/"` we add it automatically.
When the `--to` path does not contain any other path besides the repoisitory and branch, (i.e. `lakefs://<repo>/<branch>/`) the last `"/"` is parsed with the branch name, and we identify the rest of the path as empty and so we add a `"/"` which is redundant. I want to modify this behavior and avoid the additional `"/"` in that case.
@ozkatz - can you please confirm that this will be the correct behavior? Thanks

**Comment by itai-david** [comment]
The second redundant `"/"` is due the a wrong trim, and will bfixed regardless the above

**Comment by itai-david** [comment]
Just to be aligned with aws behavior (`aws s3 ls` command):
the result of  listing after the following `ingest` command:
`lakectl ingest --from s3://mybucket/myobjs --to lakefs://myrepo/mybranch/`
should be:
```
lakectl fs ls lakefs://myrepo/mybranch/ --recursive
myobjs/object1
myobjs/object2
myobjs/object3
```

While the result of listing afdter the following `ingest` command (`from` parameter is terminated by a `"/"`):
`lakectl ingest --from s3://mybucket/myobjs/ --to lakefs://myrepo/mybranch/`
should be:
```
lakectl fs ls lakefs://myrepo/mybranch/ --recursive
object1
object2
object3
```

This aligned the output of the sequence `lakectl ingest` + `lakectl fs ls` with that of `aws s3 ls`
@johnnyaug / @itaiad200 - can any of you confirm that?

**Comment by itaiad200** [comment]
I believe this is the desired behaviour, especially if `aws s3 ls` behaves the same. You can either keep/discard the last part of the path, and you also push it to any path in lakeFS with `--to lakefs://myrepo/mybranch/any/path/`
