### ISSUE TITLE
Docker build not working in v0.61.0

### ISSUE THREAD

**Issue by dakotah-jones-techngs** [treeverse/lakeFS#3115]
When building the docker container from source the build fails with the following error:
`
Step 8/30 : RUN go build -ldflags "-X github.com/treeverse/lakefs/pkg/version.Version=${VERSION}" -o lakefs ./cmd/lakefs
 ---> Running in b383faa96159
pkg/db/migration.go:17:2: no required module provides package github.com/treeverse/lakefs/pkg/ddl; to add it:
	go get github.com/treeverse/lakefs/pkg/ddl
pkg/api/ui_handler.go:18:2: no required module provides package github.com/treeverse/lakefs/pkg/webui; to add it:
	go get github.com/treeverse/lakefs/pkg/webui
`

**Comment by itaiad200** [comment]
Hey @dakotah-jones-techngs , how did you try to build the container?
Try running `make build-docker`.

**Comment by arielshaqed** [comment]
Hey @dakotah-jones-techngs -- there are non-Dockerized steps in the build, so you should try `make build-docker`.  If it still doesn't work _**PLEASE**_ re-open!
