### ISSUE TITLE
lakectl tests sanitation logic

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3116]
Redefine the esti lakectl tests' sanitation behavior. 
Make it more controllable such that it will not sanitize parts of the commands result we wish to test.

**Comment by itaiad200** [comment]
@Jonathan-Rosenberg Would you mind sharing an example?

**Comment by Jonathan-Rosenberg** [comment]
Example - `lakectl log`:
Currently when running the `RunCmdAndVerifySuccessWithFile` test util (that runs lakectl commands and verifies that the output is equal to a given golden file) with the `lakectl log ...` command, it's first sanitizing the result, meaning that the following possible result:
```
ID:            be2a067e9f444589a99244816cb3d7fd
Author:        nessie
Date:          2022-03-27 05:03:70 +0200 IST

	some commit message
```
is transformed to:
```
ID:            <COMMIT_ID>
Author:        nessie
Date:          <DATE> <TIME> <TZ>

	some commit message
```
If we want to test the commit id or date it's not possible currently, because each result's date and id is automatically sanitized.
We need to configure which parts should be sanitized and which don't.
So if we need to test the ids of the returning `lakectl log...` command, it would look like this:
```
ID:            be2a067e9f444589a99244816cb3d7fd
Author:        nessie
Date:          <DATE> <TIME> <TZ>

	some commit message
```
