### ISSUE TITLE
Bug: commit dates are saved according to local time

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3121]
Currently commits are saved with a date corresponding to the local time of the committing lakeFS server (due to the use of `time.Now()` function or `time.Unix(...)` function if a date is passed).
Commits should be saved with a unified date, probably UTC.

**Comment by itaiad200** [comment]
@Jonathan-Rosenberg Was this fixed or simply invalid?

**Comment by Jonathan-Rosenberg** [comment]
@itaiad200 this was invalid although an explicit use of UTC should be used when applying date to commits.
