### ISSUE TITLE
Define behavior for listing in RouterFS

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#3132]
This may not be trivial: when listing, the files in the result may belong to more than one underlying filesystem.

**Comment by arielshaqed** [comment]
I believe that in [boto-s3-router](https://github.com/treeverse/boto-s3-router) explicitly refuses to support this.  IIRC it applies routing to the provided prefix, and then lists (only) on that prefix.  Given the cost of listing and merging from multiple buckets, as well as the potential lack of utility, it might be worth continuing with this refusal.

In any case I would argue against including it in the first release: RouterFS is useful for a great many things, and usually you do _not_ need to traverse between prefixes.

**Comment by arielshaqed** [comment]
Please comment below if this is important to you!
