### ISSUE TITLE
Import: ingest bucket/path from UI

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3137]
For managed lakeFS, you can't use import from the lakeFS binary, so there should be an option from the UI.

**Comment by itaiad200** [comment]
@ozkatz:

cc @johnnyaug for onboarding

Worked with @eden-ohana  on requirements and API for this:

# Client side multipart ingestion

## Required API operations

We're adding a few plumbing API operations to lakeFS:

### range creation API

range API can create (and later possibly get?) range files

`POST /api/v1/repositories/{repo}/ranges?fromSourceURI={storageURI}&after={keyToStartAfter}&prepend={prependToRangeKey}`

Returns 201 on success with the following body structure:

```yaml
# based on "graveler/committed/committed.proto"
id: string           # Hex of the range ID that got created
min_key: string      # First key in range
max_key: string      # last key in range
count: int           # number of records in range
estimated_size: int  # estimated size in bytes
```

Example:

```json
// POST /api/v1/repositories/my-repo/ranges?fromSourceURI=s3://my-bucket/production/collections/&after=production/collections/some/file.parquet&prepend=collections/
{
    "id": "a99241ed0732ab450f036110d89ab2d85ee1727a0fcf283f27341c5c3fe956d0",
    "min_key": "production/collections/some/file2.parquet",
    "max_key": "production/collections/some/file29348209.parquet",
    "count": 12983232,
    "estimated_size": 32940
}
```

### meta-range creation API

API to create meta-ranges from a set of non-overlapping ranges

`POST /api/v1/repositories/{repo}/metaranges`

This operation expects a POST-ed body in the schema:

```yaml
ranges: array[#range]  # a list of range entries as listed above
```

and returns a metarange with a range structure as listed above
Example:

```json
// POST /api/v1/repositories/my-repo/metaranges
{
    "ranges": [
        {
            "id": "a99241ed0732ab450f036110d89ab2d85ee1727a0fcf283f27341c5c3fe956d0",
            "min_key": "production/collections/some/file2.parquet",
            "max_key": "production/collections/some/file29348209.parquet",
            "count": 12983232,
            "estimated_size": 32940
        },
        {
            "id": "f0829e4626f7fa25d574189e5b75b208729707c56ebac493c8881bb29a1fd9d2",
            "min_key": "production/collections/some/file29348209.parquet",
            "max_key": "production/collections/some/file73489343.parquet",
            "count": 347834822,
            "estimated_size": 129023
        },
    ]
}

// returns 201 CREATED with the following body:
{
    "id": "b21f58f6b6bc4bfc6e2621edd4076e51c73c707a96479922eb8722450543094e",
    "min_key": "production/collections/some/file2.parquet",
    "max_key": "production/collections/some/file73489343.parquet",
    "count": 360818054,
    "estimated_size": 16320
}
```

### committing an arbitrary meta-range API

This allows committing a (clean) branch with a changeset that is an arbitrary meta-range (instead of staged changes):

`POST /api/v1/repositories/{repo}/branches/{branch}/commits?source_metarange={metarange ID}`

With the same body payload as existing commits (i.e. commit message and additional properties)

Example:
```json
// POST /api/v1/repositories/my-repo/branches/main/commits?source_metarange=b21f58f6b6bc4bfc6e2621edd4076e51c73c707a96479922eb8722450543094e
// returns 201 CREATED with the following body:
{
    "id": "commit id",
    "parents": ["..."],
    "committer": "...",
    "meta_range_id": "5c28cf666316e6cd35d49718ce5ad2ea4422afdca4e8f13ffaf90f6b088d6932" // result of merging lastest commit on main with source_metarange
}
```

## Usage by lakeFS client(s)

## UI

![wireframes](https://user-images.githubusercontent.com/205955/159944714-7e890904-819a-44f9-a31a-fedd6d48c12a.png)

**Comment by itaiad200** [comment]
@ozkatz :

An important note raised by @itaiad200 - re-importing the same path again should update and show a diff of what changed (i.e. if I import path a/ and then delete a/1 on the source and then re-import, a/1 should be removed, and looking at the diff for the second commit should show that deletion.

For this to work I believe setting a proper merge-base is important but probably not enough (requires discovery)

**Comment by itaiad200** [comment]
@nopcoder:

@ozkatz @eden-ohana just verify and question regarding the above:
- The example uses relative path - but in our case the underlying storage will work with full path to the storage, right?
- Why `prepend={prependToRangeKey}` is needed?
- The UI (mock) button say - Import from S3 - we can import from any supported adapter, right?
- Committing a clean branch - means that we block such operation on branch with uncommitted data?

**Comment by itaiad200** [comment]
@ozkatz:

> @ozkatz @eden-ohana just verify and question regarding the above:
> 
> * The example uses relative path - but in our case the underlying storage will work with full path to the storage, right?

You mean the physical path as it will in the generated range files? anything else would probably result in a broken reference, no?

> * Why `prepend={prependToRangeKey}` is needed?

Good question, it is not explained anywhere here :) the value passed to `prepend` will be prepended to the graveler **key**, i.e. this would allow importing data from some location into a specific directory in your lakeFS repository.

> * The UI (mock) button say - Import from S3 - we can import from any supported adapter, right?

Yes, we should probably have this value taken from the configuration of the lakeFS installation, or the storage namespace used for the current repository..

> * Committing a clean branch - means that we block such operation on branch with uncommitted data?

Yes, this is conceptually a merge operation where we introduce data that wasn't staged.. I suggest doing this in the same manner and abide by the same rules (i.e. even allow it on protected branches)

**Comment by itaiad200** [comment]
@nopcoder:

@ozkatz 
- Yes. The implementation will have to use the full path to the original storage URI, so the physical path in the range will have to be a full path too.
- So it is the destination?! The import UI will probably accept just this part, as we don't have control over the full destination URI.
- merge: can you elaborate about this one? In the previous import, we had an 'import' branch with the latest import state, each import reflected the source bucket state, and we merged the data to the main branch. We plan to do the same flow using the UI? Assume that the above triggered by UI, it will be like:
  1. Create to use branch `<branch>-import`
  2. Create metarange based on ranges created by the above flow/api
  3. Commit the data to the `<branch>-import` (like force push) - fail in case there is data in stage
  4. Merge commit from `<branch>-import` to `<branch>`

**Comment by ozkatz** [comment]
These are the fields that appear in the range model

**Comment by itaiad200** [comment]
Followed up f2f, we can keep the MetaRange create response to a minimum of just the `id`.

**Comment by itaiad200** [comment]
@ozkatz , @nopcoder , I would like to document the expected behaviour for the `commit` operation when the `metarange` is given. 
I'll use examples for the expected behaviours. The examples always assume that the following API is being called: 
`
// POST /api/v1/repositories/my-repo/branches/my-branch/commits?source_metarange={metarange_ID}&metarangePrefix={prefixToConsider}
`

1.  `my-branch` HEAD objects (key/id):
```
processed/file_1.parquet <ID1>
processed/file_2.parquet <ID2>
imported/collections/stam/file_3.parquet <ID3>
imported/collections/stam/file_4.parquet <ID4>
imported/collections/stam/file_5.parquet <ID5>
```

`metarange` objects (key/id):
```
processed/file_1.parquet <ID11>
processed/file_2.parquet <ID2>
processed/file_7.parquet <ID7>
imported/collections/stam/file_3.parquet <ID33>
imported/collections/stam/file_5.parquet <ID5>
imported/collections/stam/file_6.parquet <ID6>
some/random/path/file_8.parquet <ID8>
```

`metarangePrefix=imported/`

Result: 
```
processed/file_1.parquet <ID1>
processed/file_2.parquet <ID2>
imported/collections/stam/file_3.parquet <ID33>
imported/collections/stam/file_5.parquet <ID5>
imported/collections/stam/file_6.parquet <ID6>
```

2.  `my-branch` HEAD objects (key/id):
```
processed/file_1.parquet <ID1>
processed/file_2.parquet <ID2>
imported/collections/stam/file_3.parquet <ID3>
imported/collections/stam/file_4.parquet <ID4>
imported/collections/stam/file_5.parquet <ID5>
```

`metarange` objects (key/id):
```
processed/file_1.parquet <ID11>
processed/file_2.parquet <ID2>
processed/file_7.parquet <ID7>
imported/collections/stam/file_3.parquet <ID33>
imported/collections/stam/file_5.parquet <ID5>
imported/collections/stam/file_6.parquet <ID6>
some/random/path/file_8.parquet <ID8>
```

`metarangePrefix=`

Result: 
```
processed/file_1.parquet <ID11>
processed/file_2.parquet <ID2>
processed/file_7.parquet <ID7>
imported/collections/stam/file_3.parquet <ID33>
imported/collections/stam/file_4.parquet <ID4>
imported/collections/stam/file_5.parquet <ID5>
imported/collections/stam/file_6.parquet <ID6>
some/random/path/file_8.parquet <ID8>
```

**Comment by itaiad200** [comment]
Another interesting topic - should we run pre/post commit hooks for this plumbing operation?
I think not since the data isn't really reachable (it's a dangling metarange id when committing) hench there's no much validation that can be done. Also, as a plumbing command I think it's not expected to run the hooks.

**Comment by nopcoder** [comment]
1. It is not like the current behavior, apply the new changes and not sync new changes. If we commit the new data into a different branch (import or <branch name>-import) and merge the changes into the branch, we should get the same "sync" operation + all the hooks.
2. Not related to the above. The import button is side by side with add object - it communicates the same behavior, which is, import the bucket files into the stage environment.

**Comment by itaiad200** [comment]
> 1. It is not like the current behavior, apply the new changes and not sync new changes. If we commit the new data into a different branch (import or -import) and merge the changes into the branch, we should get the same "sync" operation + all the hooks.
> 2. Not related to the above. The import button is side by side with add object - it communicates the same behavior, which is, import the bucket files into the stage environment.

1. Coming to think about it, I understand now why we choose the current import behaviour. Simply apply the metarange to a designated branch where all imports reside. You will be able to see the diff from the previous import. You can either merge automatically or not, based on your preferences. We would get the following (intuitive IMO) behaviour after the merge:
- If a file was changed only in the imported part you would see the newly imported version.
- If a file was changed only in the destination branch you would see the lakeFS changed version.
- If a file was changed in both -> conflict. 

2. Yeah I agree, the button should look different if it behaves differently.

**Comment by itaiad200** [comment]
Synced f2f with @ozkatz.

1. First we'll create the ranges and metaranges as before.
2. When applying import to a branch `my-branch` the new imported metarange will be committed as is to the HEAD of the branch `my-branch-imported` (if the branch doesn't exist, it will first be created from `my-branch`).
3.  Then, the user will be routed to the diff ui page, where the destination is `my-branch` and the source `my-branch-imported`. After reviewing the changes, the user can perform the merge.

**Comment by itaiad200** [comment]
Azure Blob API doesn't have the option to continue the listing from a specific key. It uses a Marker which is Opaque to the client and should be sent to get the next page of entries. [Azure Blob API](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#uri-parameters). To support it, we need to expand the CreateRange API to pass additional values:

### range creation API

range API can create (and later possibly get?) range files

`POST /api/v1/repositories/{repo}/ranges?fromSourceURI={storageURI}&after={keyToStartAfter}&prepend={prependToRangeKey}&continuation_token={continuation_token}`

Returns 201 on success with the following body structure:

```yaml
# based on "graveler/committed/committed.proto"
id: string           # Hex of the range ID that got created
min_key: string      # First key in range
max_key: string      # last key in range
count: int           # number of records in range
estimated_size: int  # estimated size in bytes

has_more: bool # indicates if there are more items in `fromSourceURI` that aren't included in the range
continuation_token: string # Opaque to the client, used to continue the block-store listing efficiently
```

Example:

```json
// POST /api/v1/repositories/my-repo/ranges?fromSourceURI=s3://my-bucket/production/collections/&after=production/collections/some/file.parquet&prepend=collections/&continuation_token=some_opaque_value_1
{
     "range": {
	      "id": "a99241ed0732ab450f036110d89ab2d85ee1727a0fcf283f27341c5c3fe956d0",
	      "min_key": "production/collections/some/file2.parquet",
	      "max_key": "production/collections/some/file29348209.parquet",
	      "count": 12983232,
	      "estimated_size": 32940
	},
    "pagination": {
		  "has_more": true,
		  "continuation_token": "some_opaque_value_2"
	}
}
```
