### ISSUE TITLE
Direct-access FileSystem to be credential-free

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#3160]
When using the the lakeFS Hadoop Filesystem, I need to configure the `fs.s3a.access_key` and `fs.s3a.secret_key`.

Use the fact that lakeFS already authenticates with AWS to remove the need for these configurations.

Handle the authentication by means of:

## Option 1: assume role on lakeFS server side

Add a lakeFS server configuration ("role_to_assume" in the same place where AWS credentials are given).
Then return session credentials and use them in the lakeFS filesystem.

The credentials given to lakeFS are expected to be allowed to assume this role.
 
## Option 2: Pre-signed URLs
Use the lakeFS server to sign the URLs returned to the lakeFS filesystem.
The credentials given to lakeFS are expected to be allowed to sign URLs.

**Comment by arielshaqed** [comment]
This is a really important feature!  There is no real reason for this.

But I suspect that documentation is a bit misleading here.  lakeFSFS uses S3A as-is to connect.  And S3A _can_ use any way to authenticate; the property `fs.s3a.aws.credentials.provider` is used to select a credentials provider.  So I could e.g. use EC2 instance role credentials to authenticate (if my Spark instances run on EC2 and can access these), or any other AWS IAM role provided to my Spark instances.  So lakeFSFS _does_ need you to configure Spark to authenticate itself both to lakeFS and to S3, but it can authenticate to S3 in any way that S3A supports.

Option 1 would be _very_ convenient for users -- at the price of making lakeFS harder to set up.  So it is a great option to provide -- but we would still need to keep other authentication methods.

In the longer run, the lakeFS daemon could provide presigned URLs to the client (option 2).  Doing that however would require _not_ using S3A (AFAIR).  And we _do_ want to use S3A, it has many useful optimizations.

**Comment by arielshaqed** [comment]
#3985 is a possible solution.

**Comment by arielshaqed** [comment]
@johnnyaug does this work?  Can we close it???  (If not, just say it's not and unassign yourself, of course)

**Comment by johnnyaug** [comment]
@arielshaqed sorry - apparently I'm not getting notifications when I'm tagged.
