### ISSUE TITLE
Add extra regex validation on Repo ID creation according to config.blockstore_type

### ISSUE THREAD

**Issue by DataDavD** [treeverse/lakeFS#3164]
Currently, the Repo ID creation regex accounts for existing blockstore type (basic) naming requirements (i.e. 3-63 characters, consist only of lowercase letters, numbers, dots (.), and hyphens (-), etc). However, there are a few blockstore type bucket naming rules lakeFS currently does not check. For example, for S3 specifically, lakeFS code does not currently check that
- Bucket names must begin and end with a letter or number. Existing RegEx does not check if Repo ID ends in `-`.
- Bucket names must not be formatted as an IP address (for example, 192.168.5.4). 
- Bucket names must not start with the prefix xn--.
- Bucket names must not end with the suffix -s3alias. This suffix is reserved for access point alias names. For more information, see [Using a bucket-style alias for your access point](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-points-alias.html).

I am wondering if there should be blockstore type specific regexes that can be used during Repo Creation to ensure that the Repo ID conforms to the corresponding blockstore type's naming specifications? lakeFS already makes use of `config` in `repositoryCreationForm.jsx`; [see code for reference](https://github.com/treeverse/lakeFS/blob/bd562b3cb23493c150549cea0ddac751bf94b41c/webui/src/lib/components/repositoryCreateForm.jsx#L53), so I think we could use that to add this _relatively_ easily.

What are the lakeFS contributors' and maintainers' thoughts on this change/addition? I'm happy to look into adding this if the lakeFS maintainers think this is worthwhile. 

Thanks in advance for your opinions and thoughts!!

**Comment by arielshaqed** [comment]
Hi @DataDavD ,

Thanks for digging this one up!  After asking around about this, I'd like to explain a bit further.

*Generally* lakeFS uses the same naming rules as S3.  However S3 is also (indeed, historically _primarily_) intended to serve files to browsers over HTTP.  When used in this manner, bucket names end up being used as part of the host component of the URL.  As such there are additional limitations.

Let's go over the restrictions you listed:
> * Bucket names must begin and end with a letter or number. Existing RegEx does not check if Repo ID ends in -.

This is probably needed: in virtual host-based addressing, the bucket/repo name is used as a domain name component, and that rule applies there.

> * Bucket names must not be formatted as an IP address (for example, 192.168.5.4).

I am not sure this is needed for lakeFS.

> * Bucket names must not start with the prefix xn--.

I think this is for [Punycode IDNs](https://en.wikipedia.org/wiki/Internationalized_domain_name), to prevent strange displays.  Not relevant for lakeFS.

> Bucket names must not end with the suffix -s3alias. This suffix is reserved for access point alias names. For more information, see [Using a bucket-style alias for your access point](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-points-alias.html).

Not needed for lakeFS.

So the only possibly important case is repo names ending with a minus sign.  I am closing this issue, but we might want to revisit just the decision and open an issue to disallow the regexp pattern `-$`.

**Comment by DataDavD** [comment]
Sounds good to me. Thanks for the clarification. I'll go through the lakeFS docs/code better. I'm still a bit confused between the linking between naming/etc and block store type. Your explanation is very helpful though. Thanks again!!
