### ISSUE TITLE
GC: Handle no addresses case

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3169]
In case that there are no files to delete while running the GC spark job, GC will throw the following exception:
`Exception in thread "main" org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.`

We need to catch the exception, or validate that the addresses location (the path in which the addresses to be removed should be at) is not empty and return a descriptive message.

**Update:** The issue encountered in Spark 3.0.3, it is not reproducible on Spark 3.1.1

**Comment by arielshaqed** [comment]
Could we instead specify the schema, to be able to write an empty Parquet file?
Otherwise users (including us...) need to handle the "nothing to do" case specially.

**Comment by Jonathan-Rosenberg** [comment]
This will need further discovery but it sounds like a good solution 👍

**Comment by talSofer** [comment]
@Jonathan-Rosenberg I tried the following steps to reproduce the issue without success:
1. setup a repo with gc rules and make sure that there are no objects that should expire and therefore GCed 
2. Run GC on that repo
Result: no exception thrown. 

What steps did you take to reproduce it?

**Comment by Jonathan-Rosenberg** [comment]
Can you share the execution's logs?

**Comment by talSofer** [comment]
Sure, shared it privately.

**Comment by talSofer** [comment]
Working with @Jonathan-Rosenberg we've concluded that this bug is not reproducible while running GC on Spark 3.0.3, therefore I'm closing this issue.
