### ISSUE TITLE
Feature: Use AWS S3 Object Versions

### ISSUE THREAD

**Issue by clintonmonk** [treeverse/lakeFS#3171]
# Feature Request

Add support for LakeFS to use a specific version of an S3 object. LakeFS would capture the current version of each S3 object when the object is staged or committed (one or the other). Later, after the data is committed, retrieving the physical address would return the S3 path with the version. This would guarantee that clients are reading the same files that were staged or committed.

# Motivation

We want to ensure that the underlying physical data in S3 cannot be overwritten or deleted.

We plan to use LakeFS on S3. We plan to use the LakeFS-specific Hadoop Filesystem to read from and write to S3 directly from Spark. This means that our Spark cluster needs write access to the S3 bucket. In our setup, the Spark cluster that accesses LakeFS and its S3 bucket is also the same cluster that is used by everyone within the company to do their work (technically, the same IAM role, not the same cluster). This means that everyone has permissions to modify the underlying S3 files.

AWS S3 permissions do not seem capable of preventing writing over an existing file. However, while we cannot prevent those changes, we can use [S3 object versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) to ensure that the original version remains intact. We can additionally use [S3 object locks](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html) to prevent an S3 object's version from being deleted.

It would be nice if we could configure LakeFS to use a specific version of an S3 object rather than the current implementation where the latest version of an S3 object is used. It could also prove beneficial to place a lock on the version that is captured.

**Comment by arielshaqed** [comment]
Object versioning can really be painful:

1. Version IDs on S3 are really large and incompressible.  So this greatly increases sizes of range objects.
1. Can diminish the range of backing stores we can support.  But S3, Azure blobstore and Google Cloud Store all seem to support it, so it could be an optional feature.

That said, I can see it would help some lakeFSFS users.  #3160 might give other ways to do this... but at a potential performance cost.

@nopcoder: do you reckon we could support this, as an option?

**Comment by clintonmonk** [comment]
Thanks! 

I hadn't seen #3160. I was planning to create another issue to request supporting pre-signed URLs as an alternative to preventing writes: the pre-signed URLs would expire, after which the files would no longer be writable by the clients (e.g. Spark) and only be writable by LakeFS (via an IAM policy). However, unlike the approach described above, the expiration would not be connected to the stage/commit operations. I wasn't aware though that pre-signed URLs are not compatible with S3a. I'll see if I can find some details to learn more.

**Comment by nopcoder** [comment]
Reference a specific object version help stage API to guard the original reference in case the bucket support versioning.
Didn't test this option @arielshaqed. Regarding commit - changes that are though the lakeFS API/Gateway already produce different objects per write. If the above suggestion is supporting a different way to address the implementation in case the underlying bucket support versioning - it is interesting. It will make the working with versioning (which is not supported on object store) the way to address different version of the object, but conflict between branches. As serve the latest version per branch.
Adding the additional property (version) per object can help stage implement this feature, but the s3 schema missing support - a way to have a link directly to the old version can add complexly of how external code like our Hadoop file system access this information.
