### ISSUE TITLE
Garbage Collection: Add wildcard support

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3215]
We should consider adding wildcard/regex support to the branch naming section in the retention policy such that if users want to hard-delete all of the deleted files from branches with names starting with `sensitive/*`, it would be possible.

**Comment by talSofer** [comment]
@johnnyaug I have a vague memory that you considered it and made an informed decision not to do that. is this correct?

**Comment by johnnyaug** [comment]
@talSofer I think we didn't consider it at the time. I don't know of a reason not to do it

**Comment by talSofer** [comment]
Thanks @johnnyaug. @Jonathan-Rosenberg If we don't see a use case for it, let's close this issue.

**Comment by Jonathan-Rosenberg** [comment]
@talSofer I think that there might be a use case for that but it needs some discovery

**Comment by talSofer** [comment]
IMHO it's better to get a signal from users that they need it as opposed to keeping this issue open, but it's up to you @Jonathan-Rosenberg
