### ISSUE TITLE
Cannot use Azure blob as storage

### ISSUE THREAD

**Issue by aletc1** [treeverse/lakeFS#3234]
When I try to write an Iceberg table manifest (throught Hive [HMS]) I receive the following error:

```
time="2022-04-18T19:40:31Z" level=error msg="could not write request body to block adapter" func=pkg/gateway/operations.handlePut file="build/pkg/gateway/operations/putobject.go:304" error="-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.14.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=InvalidHeaderValue) =====\nDescription=The value for one of the HTTP headers is not in the correct format.\nRequestId:06b30986-401e-0062-685c-535655000000\nTime:2022-04-18T19:40:31.5298004Z, Details: \n   Code: InvalidHeaderValue\n   HeaderName: x-ms-access-tier\n   HeaderValue: STANDARD\n   PUT https://[REDACTED].blob.core.windows.net/weather/5564deddb2ea425aa1ab85c498c86ceb?comp=blocklist&timeout=601\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [Azure-Storage/0.14 (go1.17.8; linux)]\n   X-Ms-Access-Tier: [STANDARD]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: []\n   X-Ms-Client-Request-Id: [f198a7af-ccdd-4059-7bd8-31e6326e7be0]\n   X-Ms-Date: [Mon, 18 Apr 2022 19:40:31 GMT]\n   X-Ms-Version: [2020-04-08]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 400 The value for one of the HTTP headers is not in the correct format.\n   Content-Length: [330]\n   Content-Type: [application/xml]\n   Date: [Mon, 18 Apr 2022 19:40:31 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [f198a7af-ccdd-4059-7bd8-31e6326e7be0]\n   X-Ms-Error-Code: [InvalidHeaderValue]\n   X-Ms-Request-Id: [06b30986-401e-0062-685c-535655000000]\n   X-Ms-Version: [2020-04-08]\n\n\n" host=lakefs matched_host=false method=PUT path=tables/other/metadata/snap-1129234574157815126-1-0b374c6a-4edf-4a8a-bf14-c4406bb982f3.avro ref=main repository=weather request_id=2b8d2b4b-84ad-4e1e-b425-d5ab02da4f2f service_name=s3_gateway user=admin
```
It seems that ```STANDARD``` value is invalid for ```X-Ms-Access-Tier``` header.

I tested it with a brand new vanilla Storage Account with LRS replication using access-key authentication. Shouldnt access tier be either ```Hot``` or ```Cold```?

If not all Azure Storage Accounts are supported, what would be the required configuration? I havent found anything about it in the documentation.

P.S: The same code works with LakeFS using local:// backend.

**Comment by arielshaqed** [comment]
Hi @aletc1,
 I'm sorry you're having trouble using Azure with HMS. To help narrow things down, could you share some details of your configuration, please:

* Can your lakeFS instance write objects using the S3 gateway,  writing directly without going through HMS?
* Can it write using the lakeFS API? That is, does `echo test | lakectl fs upload -s - lakefs://REPO/main/test-object` work for your repo?
* What are your lakeFS block adapter configuration (without secret fields, of course)?
* If the first 2 worked and the issue is specific to using HMS, what is your HMS configuration?

Thanks!

**Comment by aletc1** [comment]
Hi @arielshaqed, thanks for the quick reply!

The problem is when writing through s3 gateway (not related to the HMS). I just tested with s3cmd and received a 500. When I checked the lakefs console, had the same error line.
If I upload an object throught lakefs web UI it works and I see the object created in the azure blob storage (with the name hashed). But if I use the s3 gateway (with whatever client, s3cmd, HMS/Trino, etc), then cannot write.

My guess would be that there is a BUG in the adapter part, either using a configuration for a different Azure Storage Tier (maybe premium?) or using an old API (this is just a big conjecture).

I am testing lakefs using Kubernetes (helm chart), just following the tutorial on the web. My config is:
```
secrets:
    databaseConnectionString: [connectionString]
    authEncryptSecretKey: [password]
lakefsConfig: |
    blockstore:
      type: azure
      azure:
        auth_method: access-key
        storage_account: [accountName]
        storage_access_key: [accountPassword]
```
(I redacted the access keys and connection string)

Everything else is vanilla.

Thanks again.

**Comment by arielshaqed** [comment]
Thanks, @aletc1!

@nopcoder, this one looks like an issue on the bottom half of the s3 gateway, along with the Azure adapter. Can we talk on Wednesday?

**Comment by nopcoder** [comment]
> Thanks, @aletc1!
> 
> @nopcoder, this one looks like an issue on the bottom half of the s3 gateway, along with the Azure adapter. Can we talk on Wednesday? 

Sure @arielshaqed, from the above it looks like Azure block adapter related.
@aletc1 any information about the storage account type you are using will be helpful (ex: Blob storage "Standard general-purpose v2")

**Comment by itaiad200** [comment]
I'm able to reproduce this issue with Azure block adapter and using `aws` cli.

I have a `StorageV2 (general purpose v2)` storage account configured and I'm able to write to it successfully using the UI and the aws cli. BUT when passing a `--storage-class=STANDARD` to the `aws` cli, it fails with the same error in the lakeFS server side.

The gateway maps the giving S3's `x-amz-storage-class` header to Azure's `x-ms-access-tier`. Since `STANDARD` isn't a valid option for Azure storage classes, the request fails. @aletc1 , do you have logs in the s3 client side that can validate my assumptions? If you're able to control the `x-amz-storage-class` header's value that is sent from your S3 client, try turning it off as a quick mitigation.

**Comment by aletc1** [comment]
Hi @itaiad200,

I can totally validate your statement. In Azure there is no Standard access tier and that is the problem. According Microsoft documentation [Set Blob Tier](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tier) the only valid options are: ```Hot```/```Cool```/```Archive```, therefore you either "translate" s3 tier to the corresponding azure compatible tier, or ignore this header. Setting --storage-class=Hot is not an option (although help testing) since you cannot control third-party clients (like Hive, etc) that uses the s3a endpoint. Hence, if a s3 client ask for Standard tier you should translate this accordingly (best solution) or ignore it (will work, but might loose functionality and having different tiers will be cost effective in some use cases). 

Thanks.

**Comment by itaiad200** [comment]
Thanks @aletc1 for the validation. #3235 PR ignores unknown tier types. Decided not to use translation for unknown types since it doesn't map nicely. Also the Azure storage has a default tier so a user can configure the desired behaviour for unknown cases.
