### ISSUE TITLE
Make users easily understand what lakeFS' GC does and how to use it 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3248]
The current UI is confusing for a few reasons: 
* Language is ambiguous: we use both the terms retention and garbage collection. 
* We need to re-think the terminology we use: once the name GC is borrowed from git, lakeFS' GC is more similar to java GC (a much more known GC). so we need to think of a term that resonates with our users.   
* Users think of GC as a storage lifecycle feature, in the sense that you don't immediately understand that GC hard deletes things that were soft deleted. The reason for that may be the use of the term "retention". 

While the current docs explain that GC hard deletes soft-deleted objects, it is still not clear to users. 

This issue has two sides:
- Improve the UX of creating GC rules from the UI.
- Improve GC docs so that it is clear what's provided by the feature.

**Comment by arielshaqed** [comment]
No such confusion is currently apparent 🥳
