### ISSUE TITLE
test lakefs kv delete while iteration

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#3262]
We should probably add tests for concurrent iteration on one prefix and Delete on another prefix -- in all possible orders:

* ```
  iteration
               deletion
  ```
* ```
  iteration
        deletion
  ```
* ```
  iiiiiiiiiiteration
      deletion
  ```
* ```
    iteration
  deleeeeeeeetion
  ```
* ```
      iteration
  deletion
  ```
* ```
             iteration
  deletion
  ```

_Originally posted by @arielshaqed in https://github.com/treeverse/lakeFS/pull/3251#discussion_r858312105_

**Comment by itai-david** [comment]
@nopcoder @arielshaqed - how can I force start/end of one operation, in the middle of another?
For example, if I'm looking at this order:
`  iteration
deleeeeeeeetion`
How can I guarantee a deletion that `iteration` starts and ends before `deletion` is ended?
Same goes for all examples of overlapping actions above
Thanks

**Comment by nopcoder** [comment]
One way to do it is calling the requested operations in the order you like to test - Calling Next, Value, Delete, Next, Value and etc.
Second way is to have them run in parallel using goroutine and wait on channel close/message. The main test code will close/post a message on the right channel to control the flow.

**Comment by itai-david** [comment]
> One way to do it is calling the requested operations in the order you like to test - Calling Next, Value, Delete, Next, Value and etc. Second way is to have them run in parallel using goroutine and wait on channel close/message. The main test code will close/post a message on the right channel to control the flow.

2 very interesting suggestions. Thanks @nopcoder

**Comment by itai-david** [comment]
We are dividing this issue for 2 cases:
(Note: `Scan` below refers to **Scan&Read** while `Delete` refers to **Scan&Delete**)
1. `Scan` and `Delete` operate on 2 distinct prefixes. The behavior for this case is well defined and the results are straight forward - `Scan` should pass through **all** the entries under the first prefix, while delete should delete **all** the entries under the second prefix. As there is no intersection between the prefixes no entries outside the `prefix-to-scan` should be accessed (by `Scan`), while no entries the are not under `prefix-to-delete` ahould be deleted
2. 'Scan` and `Delete` operates on the same prefix or, one prefix is contained by the other - for the case we will guarantee (only) the following:
  * All the entries reflected by the `Scan` are under the `prefix-to-scan`. `Scan` should not pass through entries that are not under this prefix
  * All updates that were **completed** before the `Scan` **started** (and were not overriden) will be reflected by the `Scan`
