### ISSUE TITLE
Feature: Add Merge Strategy to the UI

### ISSUE THREAD

**Issue by GalBachar** [treeverse/lakeFS#3266]
Upon conflict, it would be great if we could select "accept source" or "accept dest".

**Comment by GalBachar** [comment]
I find it impossible to merge conflicting objects **via the UI**.
The only way to do it without _lakectl_ is to go over to "master" and upload the exact same files as "outmaster" (please find attached pic).
I imagine that "source wins" / "dest wins" button per conflicting object would make this merge very convenient.

![Screen Shot 2022-05-23 at 16 31 13](https://user-images.githubusercontent.com/72210230/169831330-e866a7dd-c897-43ea-91c0-36bfb61505c3.png)

**Comment by GalBachar** [comment]
Hey @johnnyaug,
Are there any plans to address this issue soon?

**Comment by itaiad200** [comment]
Hey @GalBachar - thanks for raising this feature request, I can see it helping to many lakeFS users.

The current merge strategies options allow you to choose between `source-wins` and `destination-wins` in an all-or-nothing approach for the entire conflicting objects during the merge. 
The option to choose a merge strategy per-object  is currently not supported. lakeFS merges can be pretty big and adding a long list of per-object policies to that single request is something we need to think about carefully.  

As for adding the current merge strategies to the UI, it's relatively easy to support. Does that help your use-case?

**Comment by GalBachar** [comment]
Hey @itaiad200,

Thanks for the elaboration.

I believe the all-or-nothing strategy is an OK compromise for now (since we usually select `source-wins`), but not ideal for the long run.

I'm happy to hear that it's relatively easy to support. Can it be scheduled to Q3?

Regarding per-object strategy, please update if you consider supporting it.

**Comment by itaiad200** [comment]
Q3 sounds like a reasonable estimate. We'll update here on the progress.
