### ISSUE TITLE
Simple text file content conflict comparison under "Compare" tab

### ISSUE THREAD

**Issue by GalBachar** [treeverse/lakeFS#3269]
It seems like "show changes" is allowed only when there's no conflict.
Seeing the diff would be extremely viable for conflicts..

**Comment by GalBachar** [comment]
Having this feature work for Book5.txt and Book5.csv would be awesome.
It's hard to determine if source should win or dest w/o any diff..

@itai-david @GalBachar Any chance it's work-in-progress?

![Screen Shot 2022-05-23 at 16 27 47](https://user-images.githubusercontent.com/72210230/169830054-2cb8f445-c1c6-4b6a-85df-5bd7143bb18e.png)

**Comment by itaiad200** [comment]
@talSofer (who implemented the UI diff viewer) - was there any limitation to add it to conflicted files as well?

**Comment by talSofer** [comment]
I implemented it. The reason for not adding it to conflicting objects was that the content diff in this case is a 2-way diff.

**Comment by itaiad200** [comment]
Github behaviour is to show the diff between the destination & the base (?!)
![image](https://user-images.githubusercontent.com/9861474/169969196-174241c3-81b5-4917-a71c-5363503c201d.png)

**Comment by itaiad200** [comment]
@GalBachar from your previous comments I understand that is not what you expect to see, right? You rather have the diff between the destination and the source, not the base.

For example:

Base file:
```
first line
second line
```

Source file:
```
first line
third line
```

Destination file:
```
first line
3rd line
```

Then when merging from Source to Destination, the second line is ignored by the diff:
Diff (Source -> Destination):
```
--- 3rd line
+++ third line
```

**Comment by GalBachar** [comment]
```
--- 3rd line
+++ third line
```

@itaiad200  This seems about right!
"second line" is irrelevant if it's no longer part of "source" or "dest" branches.

**Comment by GalBachar** [comment]
GitHub does show the diff between "source" and "base"
![Screen Shot 2022-05-29 at 14 57 40](https://user-images.githubusercontent.com/72210230/170866945-e7ca7547-a625-43c7-82ad-f654d78d769c.png)

But then you get an opportunity to resolve the conflicts as well (and the diff is visible via the UI)
![Screen Shot 2022-05-29 at 14 59 41](https://user-images.githubusercontent.com/72210230/170867035-d18c6725-6268-4818-ab24-ed664d095d89.png)

![Screen Shot 2022-05-29 at 14 59 06](https://user-images.githubusercontent.com/72210230/170867032-ae870fe6-847c-4d71-a52c-4e0704ed5eb0.png)

**Comment by GalBachar** [comment]
Hey @itai-david,
Please let me know what the future plans are for this issue..

**Comment by itai-david** [comment]
Hi @GalBachar
This issue was classified as a new feature request and is scheduled to Q3
We will update here with any further advancement or related decision

**Comment by GalBachar** [comment]
Thanks @itai-david
