### ISSUE TITLE
Esti system test for DB migration to KV Store

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3310]
* Esti system test to verify a system wide migration to KV, for correctness
  * Can also be used to cover the migration from the performance aspect by (currently manually) checking the time it takes
  * As the migration process will increase over time, as we transfer more parts to KV, the time to migrate cannot be well defined
  * We will use this to identify "unreasonable" migration time

* The main idea is to have a system running on SQL DB, performing various lakefs actions [TBD] and bringing lakefs to a certain state. Then lakefs is stopped, a migration to KV takes place and lakefs is restarted with KV enabled. The testing flow should continue at this point, seamlessly
* **Note**: Currently, Esti tests rely on lakefs being up and running prior to the test itself. This task needs to add support for stopping/starting lakefs as part of the test
* The time of the migration process should be "benchmarked" as part of this test. Initially, this can be done by manually verifying the migration time
* What is the sufficient dataset prior to migration?

**Comment by itaiad200** [comment]
Maybe I missed it, but I don't see this in the testing-plan doc. I don't think Esti should be used for benchmarking.
