### ISSUE TITLE
Unit test for `pkg/gateway/multiparts` migration

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3311]
* The main purpose is to develop a general table/module independent test infrastructure.
* I'm thinking of some `getAll` function that get a `table`, a `getter` and the `key` column, then lists all keys, gets all objects and builds a list to compare
* As the `multiparts` is a very easy one to verify, it can be used as a base case to build the more general infra

* Create an initial state - several multiparts uploads in the DB - with Table DB
* Create a list of all DB entries (using the above method, I guess)
* Migrate the table
* Create another list of all DB entries - post migration
* Compare the lists

**Comment by itaiad200** [comment]
Duplicated
