### ISSUE TITLE
Benchmark comparison for `pkg/gateway/multiparts`

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3312]
Compare performance for Table DB and KV Store -> By using a common interface, i.e. `multipats.tracker`
Build for scale, i.e. 1000s entries
Run the same benchmark on both Table DB and KV Store and compare

**Comment by itaiad200** [comment]
Please add a DoD for this issue.

**Comment by itai-david** [comment]
DoD:
A set of benchmarks running on SQL DB and KV Store and results are printed tfor comparison (manual).
What I have in mind is a set of benchmarks (bmCreate, bmGet, bmDelete, bmMix) that will be executed on both DBs (i.e. bmCreate(SQL), bmCreate(KV), etc...)
