### ISSUE TITLE
Implement RouterFS's file system operations

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3313]
After adding a [mapping capability](https://github.com/treeverse/hadoop-router-fs/blob/main/src/main/java/io/lakefs/routerfs/PathMapper.java)  RouerFS can use, this task is to implement RouterFS filesystem operations using the Path mapper. 

### Definition of done
- RouteFS translates paths into their desired form 
- RouteFS fetches the correct file system for the translated path at runtime. (correct = configured for the relevant `fromSchema`)
- RouterFS uses the relevant filesystem to invoke filesystem operations. 
- Spark users that build RouterFS locally can access lakeFS (via s3 gateway) and s3 from a spark application that does not include lakeFS-style paths. 
- The bullet above holds for any underlying object store supported by lakeFS, and for any combination of underlying stores. 
- RouterFS's code is unit-tested

**Comment by arielshaqed** [comment]
First part is in #3327.
