### ISSUE TITLE
[Proposal] Using mapstructure to model hooks properties

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#3322]
### What problem are you trying to solve?

Custom code to parse hook specific properties have partial data support, for each new property we need to extract and parse the data.

### Why should we solve it?

- Misalign in the way we parse properties in different hooks properties
- Fewer potential bugs when we use and tested code to parse the information

### How do you propose to solve it?

The [mapstructure](https://github.com/mitchellh/mapstructure) package which is a well-known page can help parse the current `map[string]interface{}` structure to the specific Hook properties structure.
It will reduce the code we currently have per hook implementation and supply a good support for types like boolean which can be parsed in different ways (ex: boolean and/or string "true"/"false")

**Comment by arielshaqed** [comment]
Yay!

However note that weak typing of YAML (but not JSON!) means that boolean-ish values of string values can be poorly converted.  See #3253 for how badly things go with weak typing enabled -- but note that Viper forces this on us, and here we can (and should) just opt-out of weak typing!

**Comment by N-o-Z** [comment]
Package looks very cool! 

- This can help us with #3144

**Comment by nopcoder** [comment]
Agree about the weak typing for numbers. For boolean, we can support `"true"` and `true` - as long as we keep the meaningful value relevant to the property we set.
