### ISSUE TITLE
Swagger API semantic error - DELETE operations cannot have a request body

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#3357]
Our API definition using Swagger for `/repositories/{repository}/branch_protection` with DELETE operation defines _requestBody_.
While using swagger tool, https://editor.swagger.io, which parse and produce client code, we fail to process our current definition with the following error:

```
Semantic error at paths./repositories/{repository}/branch_protection.delete.requestBody
DELETE operations cannot have a requestBody.
```

We should enable delete without posting body in the request, an identity should be associated to the resource we like to delete, or it should delete the configuration completely.

**Comment by itaiad200** [comment]
@nopcoder Any reason why this wasn't labeled with ve team?

**Comment by nopcoder** [comment]
API so I kept it for the triage
