### ISSUE TITLE
Docs: contribution guide should explain how to run a local server

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#3363]
Currently the [contribution guide](https://docs.lakefs.io/contributing.html) explains how to build and how to run automated tests, without explaining how to run a local dev server.

**Comment by itaiad200** [comment]
For the future assignee, notice the contribution guide links to [running system tests locally](https://github.com/treeverse/lakeFS/blob/master/esti/docs/README.md) which has that explanation. We need it in this guide for general purposes.
