### ISSUE TITLE
UI: replace the usage of our custom method for parsing query parameters with the query-string library

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#3367]
webui/src/lib/api/index.js

**Comment by talSofer** [comment]
@eden-ohana can you please add more details to the issue? it will be great if you can add the following details: 
- A link to the library we should use
- add more context to this issue. Why are we doing it? 
- is some part of our code already using the query-string library? if so please reference it

**Comment by eden-ohana** [comment]
The library you should use- "query-string". It is already used in the commit api.
https://github.com/treeverse/lakeFS/blob/f7bb5ea87d2973b06e85659c7b07eb394e0ffda1/webui/src/lib/api/index.js#L6
currently all the other operation is using this method  https://github.com/treeverse/lakeFS/blob/f7bb5ea87d2973b06e85659c7b07eb394e0ffda1/webui/src/lib/api/index.js#L35
