### ISSUE TITLE
Import branches should be created from the repo root commit

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3375]
**Actual**

The import branch is created from the HEAD of the given branch. When merging the import branch to the origin branch, it will delete all entries that existed when the import branch was created, due to the nature of 3-way merge.

**Desired**

Entries that existed before the import are not deleted. This can be achieved if the import branch is created from the repository root commit.

**Comment by N-o-Z** [comment]
The solution suggested was to use the repository's "root commit" as the base for the import's merge action.
Finding the root commit is easy as it is the only commit in the repo with generation ID = 1.
This is a backwards and forwards compatible solution that is pretty straightforward to implement, only 2 downsides to it:
1. As previously discussed, there might be a performance impact on the merge using the root commit as the base commit as this can create a very merge tree.
2. Since the code to create the import branch and perform the merge is in the UI, we will require to create a specific external API to get the root commit

@eden-ohana @itaiad200 thoughts?

**Comment by eden-ohana** [comment]
Do you mean that the root commit of the branch will be used as the source ref for creating the imported branch?

How can we use the root commit for the base of the merge operation? the merge doesn't accept base commit, he calculates it by the historical commit.

**Comment by N-o-Z** [comment]
> Do you mean that the root commit of the branch will be used as the source ref for creating the imported branch?
> 
> How can we use the root commit for the base of the merge operation? the merge doesn't accept base commit, he calculates it by the historical commit.

Current solution is to use the current working branch as the base for the import branch. The suggestion is to use the repository root commit (i.e. the first commit of the default branch) as the base for the import branch

**Comment by itaiad200** [comment]
> The solution suggested was to use the repository's "root commit" as the base for the import's merge action. Finding the root commit is easy as it is the only commit in the repo with generation ID = 1. This is a backwards and forwards compatible solution that is pretty straightforward to implement, only 2 downsides to it:
> 
> 1. As previously discussed, there might be a performance impact on the merge using the root commit as the base commit as this can create a very merge tree.
> 2. Since the code to create the import branch and perform the merge is in the UI, we will require to create a specific external API to get the root commit
> 
> @eden-ohana @itaiad200 thoughts?

1. The performance impact would be on the first merge from an import branch. I also don't think it would be that bad, only if there are tens of thousands of commits on the original branch, and even then the usability improvement is worth the wait.
2. Not necessarily. You can `logCommits` from the UI until you reach the root commit. We can introduce a new tag named `_root_commit` that will point to it for new repos (and think of a way to backfill old repos, should be a simple postgres command).

**Comment by eden-ohana** [comment]
maybe instead of creating another API command, we can add it to the log command with flag --root

```log lakefs://branch --root --show-meta-range-id```

**Comment by N-o-Z** [comment]
I think tagging can be dangerous as this might cause collision with user data (we cannot assume user has not defined the tag already)
I'll check the logCommits option but I'd like to find a more elegant solution.
@eden-ohana  As I see it, adding a flag or another API for a specific internal usecase is just the same. My problem is with the visibility of this solution
