### ISSUE TITLE
Support logical diff/merge for Iceberg tables

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#3381]
Iceberg stores metadata files ("manifests") that represent a [snapshot of a given Iceberg table](https://iceberg.apache.org/spec/#manifests).

Currently, when trying to modify an Iceberg table from 2 different branches, lakeFS would not be able to create a logical snapshot that consists of the changes applied in both references.
Users would then have to forgo one of the change sets, by either retaining the destination's branch set of changes, or the source's branch.

A much better user experience would be to allow merging snapshots into a new unified set of changes, representing changes made in both refs as a new snapshot.

**Comment by johnnyaug** [comment]
## Milestones
1. Support diff, and single-writer merges.
2. Multi-writer merges.

**Comment by code-magician323** [comment]
@johnnyaug @ozkatz addition of demos is super important as well
