### ISSUE TITLE
lakefs on KV - run benchmarks on a constant data set

### ISSUE THREAD

**Issue by itaidavid** [treeverse/lakeFS#3387]
Per @arielshaqed comments on #3377 - the KV benchmark shoulld not use b.N to control the size of the data set (should be unifrom for all values of b.N, per a given test)

**Comment by itai-david** [comment]
One of my main concerns is that benchmarks that rely on a certain dataset size, will not be able to scale with b.N, e.g. what should be the size of the dataset to allow b.N deletes?!
Discussed this wilts @nopcoder and the suggestion is to make a sampling size K to run b.N times. Each iteration (out of b.N) will create a dataset of size K, reset timers and run K operation
```
for n := 0; n < b.N; n++ {
	createDataSetOfSize(K)
	b.ResetTimer()
	deleteAllEntriesInDataSet
}
```
