### ISSUE TITLE
kv package implementation feedback

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#3395]
- [x] entry as string should not print dump as string
- [x] verify that value can be empty without null
- [x] postgres view on kv table to list keys as strings

**Comment by nopcoder** [comment]
Verified that inserting a null as inserting an empty value to bytea in postres are not the same.
We don't want to enable null for key or value.

**Comment by itaiad200** [comment]
Can we add tests for all of these cases?
