### ISSUE TITLE
Repository Template: lakeFS + Spark + Metastore

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#3411]
### User story

Data engineers new to lakeFS want to try out one of the main use cases (dev env, parallel pipelines, cross-collection consistency, etc) for their existing Spark-based stack.

### Pain

To get started using a new lakeFS installation with Spark, the following manual steps are typically required:

1. Create a repository and configure it with a storage namespace
2. Bring in existing data (whether using import, copy, ingest, upload(?), etc)
3. Connect Spark using the installation's S3 Gateway *or* configure Spark to use lakeFSFS with this installation
4. Understand how to use lakeFS structured URIs in the existing code base *or more likely* configure metastore for this indirection to have existing code run on a separate branch/commit (i.e. _I want `SELECT * FROM events;` to use the events table that exists in my `experiment-oz-temp` branch, not main or production!_)
5. Now, integrate Hive Metastore/Glue Data Catalog with lakeFS to be able to have a schema for my branch that contains all the same tables that I have in prod.

### Solution

Create a repository template that walks the user through these steps, tailored to their installation, automating as much of the process as possible.

### Repository Templates

When a user chooses to create a repository from the `Spark Quickstart` template, they get a wizard that guides them through configuring the repository, importing existing data and setting up Spark and HMS.

This will include:

1. New "empty state" for repository list screen (see dev#147)
2. New drop down button next to "Create repository" button to also show menu of templates (see dev#147).
3. The template's wizard (see below)

### lakeFS + Spark

When the user chooses this template, show them a wizard, with the steps described in [this Figma](https://www.figma.com/file/haD9y599LzW6LvsYBI2xWU/Spark-use-case?node-id=21%3A1489).

Once the user finishes the wizard and configures their Spark environment, they are redirected to a new repository with a README.md containing a summary of the things we did (or skipped..) from the wizard

1. importing data into this repository
2. connecting a spark setup to this environment

For the first deliverable, metastore commands are not automated via hooks. Instead, the README will also include:

3. instructions on which `lakectl metastore` commands to run and when.

### Considerations

* Optimize for **usability, simplicity and clarity**! One effective sentence in the README file is worth a thousand cool automations.
* Wizard steps and components should be modular and composable: we may need to reuse them in future repository types and probably also as standalone features. For example, importing data will probably be a step in multiple wizards, and is also a feature on its own.

**Comment by Jonathan-Rosenberg** [comment]
@johnnyaug @ozkatz should the README file include a sample app that writes/reads from the newly initialize lakeFS branch?

**Comment by johnnyaug** [comment]
@ozkatz, I also take issue with the name "repository templates" - since it's not really a template - in most cases the created repository is exactly a blank repository + a README. @michalwosk and I came up with the quick launch name which I think is better.

**Comment by ozkatz** [comment]
> @ozkatz, I also take issue with the name "repository templates" - since it's not really a template - in most cases the created repository is exactly a blank repository + a README. @michalwosk and I came up with the name "Quick Launch" which I think better describes what we're doing here.


@johnnyaug I disagree. I believe in most cases running a template will yield a README and set of `_lakefs_actions/` hook definitions. Similar to similar cookie cutter templates (e.g. `create-react-app` and others that yield a `webpack.json` and a few other configuration files).

This also keeps it consistent with other tools:

GitHub:

![image](https://user-images.githubusercontent.com/205955/172631381-78d827d2-7e79-4247-85bd-b26152b1a151.png)


Vercel:

![image](https://user-images.githubusercontent.com/205955/172631626-2f549dee-3920-47a2-ac83-67072f66cea2.png)

So this keeps the behavior consistent with these tools which I believe is desired
