### ISSUE TITLE
Bug: Import from UI bad behavior on branch names "*_imported*"

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3416]
There are currently 2 unexpected behaviors for these branches:
1. for Branches "x_imported_y" where "x_y" branch doesn't exist:
The imported data is being committed into branch x_imported_y and when advancing to the compare window we get an error since the ref "x_y" doesn't exist
2. for Branches "x_imported_y" where "x_y" branch exists:
The imported data is being committed into branch x_imported_y and when advancing to the compare window shows a merge from "x_imported_y" into "x_y"

Since this pattern is a valid branch naming the expected behavior should be that a new branch created called "_x_imported_y_imported" and the imported data will be committed to it and that the merge compare will suggest merging "_x_imported_y_imported" into "x_imported_y"

**Comment by N-o-Z** [comment]
1:
![image](https://user-images.githubusercontent.com/3787958/169765606-a4a19fab-f3f4-415d-8ed7-2070febe4a3b.png)



2:
![image](https://user-images.githubusercontent.com/3787958/169765625-0a964c41-a41a-4d28-8eac-6394f73dad01.png)


3:
![image](https://user-images.githubusercontent.com/3787958/169765667-fe1a7292-2c8f-4149-95ea-8469815290c4.png)

**Comment by N-o-Z** [comment]
Example compare window of no existing x_y branch:
![image](https://user-images.githubusercontent.com/3787958/169766073-fc541074-8f8f-43e9-aee9-93e56ed40e33.png)

**Comment by itaiad200** [comment]
I think that the users aren't expecting to have an import branch created from another import branch. When they are in the context of an import branch and click on the `import` button, the expected behaviour should be to use the same import branch again. We do need to fix all the edge cases which currently fail, as you rightfully mentioned.

**Comment by N-o-Z** [comment]
> I think that the users aren't expecting to have an import branch created from another import branch. When they are in the context of an import branch and click on the `import` button, the expected behaviour should be to use the same import branch again. We do need to fix all the edge cases which currently fail, as you rightfully mentioned.

I find this behavior very confusing. As a user I would not understand the flow and will in a high chance make mistakes which result in unwanted behavior
