### ISSUE TITLE
upgrade `testcontainers-scala` in spark client to the latest version

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#3421]
In https://github.com/treeverse/lakeFS/pull/3420 we upgraded `testcontainers-scala` to v.0.39.11 and not the latest one since v.0.40.0 contains a breaking change.
We should upgrade `testcontainers-scala` to the latest version with all required changes.

**Comment by talSofer** [comment]
done in https://github.com/treeverse/lakeFS/pull/3815
