### ISSUE TITLE
UI Actions - Show Partial Success

### ISSUE THREAD

**Issue by GalBachar** [treeverse/lakeFS#3433]
LakeFS v0.65.0

Run Id="20220529111458UzqJK-73" is marked as a failure, although one of its hooks has succeeded (1 success, 1 failure).

It would be nice to find a "partial success" icon instead (maybe a yellow one) + the number of successes out of number of hook runs (e.g. 1 / 2).

![Screen Shot 2022-05-29 at 14 28 48](https://user-images.githubusercontent.com/72210230/170865711-b1b5c060-5138-4bcd-ac00-9f5110f6ccb9.png)

**Comment by itaiad200** [comment]
Can definitely see how this functionality improves actions usability - thanks @GalBachar 🙏
