### ISSUE TITLE
getCommit API returns commit ref instead of ID

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#3436]
# What I tried

I fetched getCommit for my repo and a branch ref.

# What I got

I received the analogue of

```json
{
  "id": "example-branch",
  "parents": [
    "a2c6e50fd3e974108f68671b961bf5f3cd915c00945ac3a20bcb36a1e7604aaa",
    "12050b53f86a7ade577b3207eae9ec8ade6f89af0c6324c15ec07133826dcf7f"
  ],
  "committer": "foo",
  "message": "...",
  "creation_date": 1653830290,
  "meta_range_id": "fd0b8367379646fcc83464364d29dc44ca2d5cea22afee94a80f24f3b78249d1",
  "metadata": { ... }
}
```

# What I wanted to get

The dereferenced ref in field `id`, e.g.

```json
{
  "id": "c0ffeec0ffeec0ffeec0ffee",
  "parents": [
    "a2c6e50fd3e974108f68671b961bf5f3cd915c00945ac3a20bcb36a1e7604aaa",
    "12050b53f86a7ade577b3207eae9ec8ade6f89af0c6324c15ec07133826dcf7f"
  ],
  "committer": "foo",
  "message": "...",
  "creation_date": 1653830290,
  "meta_range_id": "fd0b8367379646fcc83464364d29dc44ca2d5cea22afee94a80f24f3b78249d1",
  "metadata": { ... }
}
```

# Notes

It may be difficult to change this due to backwards compatibility.  In that case I would still prefer to receive the actual commit ID under another name.

# Workaround

Ask for a log of length 1 :-/

**Comment by itaiad200** [comment]
Thanks @arielshaqed - it boils down to a bug in controller's `GetCommit` where it treats `reference` as `commitID` which isn't the case for quite some time.
