### ISSUE TITLE
DynamoDB KV Support - Migrate from postgres

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3443]
Migrate from currently used postgres SQL DB (Not KV over postgress) to DynamoDB KV

One possibilityt is to use the exported data created as part of KV over postgress/mem support and import it

DoD: A migration process from Postges SQL to KV over DynamoDB, similar to what we have for `multiparts`. This process should include all currently supported modules (multiparts, actions, auth (?)).

**Comment by itai-david** [comment]
Do we need to migrate from KV over Postgres to KV over DynamoDB?

**Comment by N-o-Z** [comment]
Closing this issue as it was decided not to support direct migration to anything other than PGSQL.
