### ISSUE TITLE
Document how lakeFS works with Iceberg

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3451]
In this task, we will configure a working lakeFS<>Iceberg setup. The task's output should be: 
- docs page for how to configure Iceberg to work with lakeFS, and the use cases. 
- Optional - should we add an Iceberg example to everything bagel? 

### EDIT (@johnnyaug)
* Document the current limitations for using lakeFS with Iceberg.

**Comment by cyofeiyue** [comment]
hi guys，what about the progress now

**Comment by talSofer** [comment]
Hi @cyofeiyue! 
Currently, lakeFS does not support Iceberg, but we have concrete plans to develop an integration as you can see in our [roadmap](https://docs.lakefs.io/understand/roadmap.html#iceberg-support-high-priority). 

Until then, we will be happy to hear about your use case. How would you like to see lakeFS working with Iceberg? any feature request will be appreciated.
