### ISSUE TITLE
Doc Pages zero-padding on sidebar

### ISSUE THREAD

**Issue by peacing** [treeverse/lakeFS#3461]
When adjusting a browser window to be smaller on any lakeFS doc page, the padding for the left sidebar will go to zero, which doesn't look great.

Ex:
![Screen Shot 2022-06-06 at 1 51 34 PM](https://user-images.githubusercontent.com/11055355/172252554-3beb9559-558b-482f-ac59-e17964f78b6b.png)

**Comment by talSofer** [comment]
I adjusted the browser to be smaller with the current docs version and it looks good, closing this one
