### ISSUE TITLE
Permission Policies: Separate Commit / Merge capabilities

### ISSUE THREAD

**Issue by GalBachar** [treeverse/lakeFS#3472]
I'm trying to create a policy which allows to create a commit, but does not allow to merge branches (or vise-versa), for all repositories and branches.

I imagined the `arn` to be something like:
`arn:lakefs:fs:::repository/*/branch/*`

How-ever, It seems like both actions are defined using `fs:CreateCommit`.
In other words, same action, same resource `arn`, different capabilities (merge vs commit).

How can I achieve my goal?

![Screen Shot 2022-06-08 at 16 43 25](https://user-images.githubusercontent.com/72210230/172638875-befb30f1-84de-409e-b36c-b2adec5b74c8.png)

**Comment by GalBachar** [comment]
@guy-har FYI

**Comment by N-o-Z** [comment]
@GalBachar Hi - to better facilitate your request, I'd like to get some context on how you plan to use it. Can you provide us with an example usecase?

**Comment by GalBachar** [comment]
Hey @N-o-Z,

At first, I planned to allow merges to "master", but not commits.
I found out (@guy-har thanks) that my use-case can use protected-branches instead.

The issue is still open since it would an interesting capability. Nothing urgent, though.

**Comment by N-o-Z** [comment]
@GalBachar Thanks, so to make the requirements clearer. You requested to have control over the commit and merge permissions for the destination branch, correct?

**Comment by GalBachar** [comment]
@N-o-Z Yes, thanks.
