### ISSUE TITLE
DynamoDB KV Support - KV Configuration

### ISSUE THREAD

**Issue by itaidavid** [treeverse/lakeFS#3474]
Currently, KV over DynamoDB is configured using a `dsn` string passed to the store's `Open` func. This string is a `json` format of the parameters, which is not ideal as it is hard to understand.
We need to figure out the correct way to pass the config params

**Comment by arielshaqed** [comment]
I think Viper can pretty much accept any JSON inside its config file.  AFAIR it easily takes a `map[string]string` type, which should be enough.

But note that this would break configuration from an environment variable, so you'd probably want to support both.  See `Strings` for how to add a Viper type that has 2 different representations.
