### ISSUE TITLE
KV Migrations Improvements

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3476]
https://github.com/treeverse/lakeFS/pull/3427#discussion_r892799808

**Comment by itaiad200** [comment]
@N-o-Z can we track each one under an issue? Otherwise it's a never ending list and this issue will remain open forever.

**Comment by itaiad200** [comment]
I think we should hold off migration optimizations until we benchmark them in #3571

**Comment by N-o-Z** [comment]
This specific optimization I agree. But I do think we need to optimize the staging migration
