### ISSUE TITLE
Feature: Support to Restrict LakeFS Access to LakeFSFS-Managed Files

### ISSUE THREAD

**Issue by clintonmonk** [treeverse/lakeFS#3489]
# Feature Request

Add support for users to restrict read and write access for LakeFS services to files that are only managed through [lakeFSFS](https://docs.lakefs.io/integrations/spark.html#access-lakefs-using-the-lakefs-specific-hadoop-filesystem).

# Motivation

We are interested in restricting permissions as much as possible. For example, we may have customer or third-party data in our system that contractually require us to limit exposure to other third-parties. 

Many of our files are only stored and retrieved using Spark via lakeFSFS in AWS S3. In this setup, it is the Spark clusters that need read/write access, not LakeFS. Are we able to restrict LakeFS permissions on these files?

There are some trade-offs:
* These files would not be available for download (or upload) through LakeFS UI and API.
* LakeFS garbage collection (GC) could not run on these files.

**Comment by clintonmonk** [comment]
From discussion in Slack:

# Proposed Solution: IAM Policy and S3 Prefixes

One way this could be done is through an AWS IAM policy. However, we need a way to distinguish between files that should and should not be accessible in LakeFS. For example, LakeFS still needs read/write access to its metadata in S3 (`_lakefs/` and any others). We may also want some files (e.g. those not uploaded through lakeFSFS) to be accessible to LakeFS. The policy should then only prevent access to some files but not all files.

We could use S3 prefixes to distinguish between the various files. This would allow users to write IAM policies that restrict access based on prefixes.

1. User chooses a prefix to use for their data.
1. User updates the LakeFS IAM policy to deny read/write access to that prefix.
1. User updates Spark cluster IAM policy to allow read/write access to that prefix.
1. User provides that prefix to lakeFSFS via Spark cluster config. When a file is written, LakeFS and lakeFSFS together use that configuration to ensure the file is written to a location in S3 that contains that prefix.

**Comment by johnnyaug** [comment]
[The documentation](https://docs.lakefs.io/deploy/aws.html#prepare-your-s3-bucket) explains how to reduce the permissions required by lakeFS (see "minimal permissions" tab).
