### ISSUE TITLE
how to configure s3 compatible storage with virtual-host-path supported

### ISSUE THREAD

**Issue by icecraft** [treeverse/lakeFS#3490]
hi, when I using aliyun oss (one s3 compatible object storage service) instead of aws s3 as block-storage.  some error occurs.

```text
time="2022-06-11T07:10:42Z" level=error msg="bad S3 PutObject response" func="pkg/block/s3.(*Adapter).streamToS3" file="build/pkg/block/s3/adapter.go:250" error="s3 error: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  
<Code>SecondLevelDomainForbidden</Code>\n  <Message>Please use virtual hosted style to access.</Message>\n  
<RequestId>62A43FF26AC3883834668994</RequestId>\n  <HostId>oss-cn-shanghai.aliyuncs.com</HostId>\n</Error>\n" 
host="127.0.0.1:2002" method=POST operation=PutObject path=/api/v1/repositories request_id=c3876296-4516-458f-8e7c-
e66d32cc574b service_name=rest_api status_code=403 url="https://oss-cn-shanghai.aliyuncs.com/shlab/lakefs/rui-test1/dummy"
```
It seems that, aliyun oss only support virutal-host-path style. but I do not know how to configure block storage use virtual-host-path. 
I need you help, please!

**Comment by arielshaqed** [comment]
Hi @icecraft,
Sorry to hear you've been having difficulties. Thanks for taking Aliyun S3 for a spin with lakeFS! There may be a few adjustments, I will try to help. 

Could you try setting `blockstore.s3.force_path_style` to true in your config file? The [configuration reference](https://docs.lakefs.io/reference/configuration.html) has a bunch of variables that can help, all under "block.s3". Good luck, and please let us know how you get along!

**Comment by arielshaqed** [comment]
Hi @icecraft,

Did setting `blockstore.s3.force_path_style` to true in your configuration resolve this issue?

Just a reminder that this issue is pending your response.  If you are unable to respond within a few days, we will close this issue.  And I will be happy for you to re-open the issue if you do try this and it does not work.

THANKS!

**Comment by arielshaqed** [comment]
Closing this issue after no response.  @icecraft please re-open if the [above configuration change](https://github.com/treeverse/lakeFS/issues/3490#issuecomment-1157349950) did not work!
