### ISSUE TITLE
KV auth service - delete expired reset password tokens

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#3500]
On the DB implementation, the function **markTokenSingleUse** of the auth service also deletes all expired tokens from the DB.
Find a way to delete all expired tokens (need to scan all tokens) and we don't want to do it on this function.

**Comment by N-o-Z** [comment]
@itaiad200, Due to our discussion, do you want to change the priority and implement it before release?
If we need to change the way we create the token, it should be prior to migration

**Comment by N-o-Z** [comment]
@nopcoder is this still relevant?

**Comment by nopcoder** [comment]
Closing. We should have an issue to remove any code left related to reset password token.
