### ISSUE TITLE
Add tests of GC report at the end of run

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#3529]
Add tests of GC report at the end of run to esti.

**Comment by arielshaqed** [comment]
@lynnro314 we did add _some_; could you please take a look and either close or say we still need it and unassign yourself?

**Comment by arielshaqed** [comment]
We have at least [GarbageCollectorJsonOutputSpec](https://github.com/treeverse/lakeFS/blob/fbef78e3b0c2c40c18448c78ae669eaf2a64eb3d/clients/spark/core/src/test/scala/io/treeverse/clients/GarbageCollectorSpec.scala#L282-L322); there may be other tests too.

**Comment by lynnro314** [comment]
I believe we still have need to complete some tests about the parquet reports (https://github.com/treeverse/lakeFS/issues/3127), so I'm leaving this open.

**Comment by N-o-Z** [comment]
There adequate coverage for the report testing in the unit tests - but we can also add a validation at the end of TestUnifiedGC in esti
