### ISSUE TITLE
TTV: Operative Templating service

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3540]
Definition of done:
Templating service is functional and returns an expanded template according to the design.

[Template Server design](https://github.com/treeverse/lakeFS/blob/master/design/open/template-server/template-server.md)
[TTV design](https://github.com/treeverse/lakeFS/blob/master/design/open/ttv-wizard-mvp.md)

**Comment by arielshaqed** [comment]
Done by #3600 and #3606.
