### ISSUE TITLE
KV Graveler Implementation - Optimistic Lock Commits

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3569]
Please refer to [Design proposal - lakeFS on KV](https://github.com/treeverse/lakeFS/blob/b3204edad00f88f8eb98524ad940fde96e02ab0a/design/open/metadata_kv/index.md#graveler-metadata---branches-and-staged-writes) and #3566 for further details

**DoD**
Working implementation of Optimistic Lock Commits over KV, with relevant tests

**Comment by itai-david** [comment]
pending completion of #3568

**Comment by arielshaqed** [comment]
Unless this is intentional, please rephrase to "lock free". AFAIK the terms used in the literature are "lock free" and "wait free". (They refer to not being locked, not to not having locks.)

**Comment by N-o-Z** [comment]
On this issue we will need to replace checkEmptyToken with another StagingAreaEmpty which needs to build the staging area from all tokens and compare the result with the committed data
