### ISSUE TITLE
make test mvn: not found

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3580]
Running unit tests on a system without mvn installed we get the following error:
```
cd clients/hadoopfs && mvn test
/bin/sh: 1: mvn: not found
make: *** [Makefile:170: test-hadoopfs] Error 127
```
We should either check for MVN and skip tests with a warning or alternatively require MVN installation

**Comment by N-o-Z** [comment]
Why should there be an error in this instance? Either we should ensure mvn installed in the make target or alternatively skip Hadoop tests

**Comment by talSofer** [comment]
@N-o-Z are you making an assumption that if someone made changes that could break hadoopfs they would have maven installed? otherwise, I wouldn't want to skip tests of any kind + agree with @yoni the error is clear

**Comment by N-o-Z** [comment]
@talSofer ,

Not making any assumption, what I'm saying is that as part of the build process (make tests) if mvn is a requirement it should be installed just like any other requirement that is being installed prior to running the tests (or perform a check and fail). If it is not a requirement then I see no reason to issue an error on it

**Comment by arielshaqed** [comment]
Not done, it says that mvn is missing.  Most required tools are _not_ installed by Makefile, and the [contributions guide](https://docs.lakefs.io/contributing.html) now documents that you'll need mvn.
