### ISSUE TITLE
KV Graveler - Cleanup Failed Repository Deletions

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3590]
Since a repository deletion starts with removing the repository entry itself and afterwards removing related partitions (partition `<REPO_NAME>-<GUID>` and staging partitions), a failure in any phase after the repository entry is deleted, leaves these repositories unreachable.
Need to miplement a garbage collector to identify these repositories and remove them.
#3566 for further details

**Comment by N-o-Z** [comment]
- Superseded by #3715
