### ISSUE TITLE
Document UserID field

### ISSUE THREAD

**Issue by ortz** [treeverse/lakeFS#3603]
After we introduced the email/password authentication, it became unclear in which circumstances we use the UserID field and which calls requires it.
In order to make things more straightforward, we should add documentation on the field and how it's being used in the different API calls.

**Comment by arielshaqed** [comment]
This should also resolve #3244 (probably is a dupe of the other).

**Comment by ortz** [comment]
> This should also resolve #3244 (probably is a dupe of the other).

it is a duplicate, I searched for userID and couldn't find this one due to the space. thanks for the heads up. I am closing this one.
