### ISSUE TITLE
KV Graveler: change type Key to string

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3608]
Post Milestone 3

**Comment by itaiad200** [comment]
Can you explain the reasoning behind it? For example, `graveler.Key` is a byte array and it will be using the `kv.Store`.

**Comment by N-o-Z** [comment]
> Can you explain the reasoning behind it? For example, `graveler.Key` is a byte array and it will be using the `kv.Store`.

Yes, in all the packages we are using the StoreMessage for KV operations. The keys types are string, so effectively what we are doing is using the graveler.Key - casting it to string passing to the StoreMessage and then casting it to []byte again. Changing it to string, we can skip the first casting

**Comment by itaiad200** [comment]
So it sounds like changing the `StoreMessage` to accept bytes is better since it will include zero castings and will not limit the store APIs.
