### ISSUE TITLE
Graveler KV Reader Flow

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3630]
Follow the reader flow described in the [kv proposal](https://github.com/treeverse/lakeFS/blob/master/design/open/metadata_kv/index.md) once the staging and branches are ported to the kv store.

**Comment by itaiad200** [comment]
Depends on completion of https://github.com/treeverse/lakeFS/issues/3595 , https://github.com/treeverse/lakeFS/issues/3592

**Comment by itaiad200** [comment]
@N-o-Z This is done, right?

**Comment by N-o-Z** [comment]
Do we want to keep it for further optimizations?

**Comment by itaiad200** [comment]
I think it deserves a new issue, please open with the next advanced steps for the reading flow. Closing this one at the basic read flow is done.

**Comment by N-o-Z** [comment]
> I think it deserves a new issue, please open with the next advanced steps for the reading flow. Closing this one at the basic read flow is done.

https://github.com/treeverse/lakeFS/issues/3690 is sufficient?

**Comment by itaiad200** [comment]
If we edit it to include the optimizations we want. As I understand, the amortized read isn't going to be the first one we choose to add
