### ISSUE TITLE
Enable TestManager_FillGenerations

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3656]
`TestManager_FillGenerations` was disabled due to `FillGeneration` dependency on `GetRepository`. Once we complete the entire transition of graveler to KV, this test needs to be enabled (end of KV3)

**Comment by arielshaqed** [comment]
@johnnyaug do you remember if we need FillGenerations for more than just backfill? I'd be happy to see it gone before 1.0... In which case maybe kv will be our chance to get rid of it!

**Comment by johnnyaug** [comment]
@arielshaqed, sorry - have a notification problem. Yes, it's only for backfill and we need to remove this. See discussion in https://github.com/treeverse/lakeFS/pull/3663#discussion_r923015713

**Comment by N-o-Z** [comment]
Removed in https://github.com/treeverse/lakeFS/pull/3663
