### ISSUE TITLE
Conflicting objects UI error is misleading

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3660]
UI error for conflict is misleading. By design that's conflict (changes to both right and left commits). I think the diff should not be visible for non-diffable objects (non csv, txt, tsv).

![image](https://user-images.githubusercontent.com/9861474/179025208-b2ad1495-adb3-4a32-a919-23e2703d71a3.png)

**Comment by N-o-Z** [comment]
2 Options I can think of:
1. Remove the 'show changes' button completely
2. Change the error to a warning message stating "Unsupported file type for diff"

@itaiad200 @ozkatz (for product perspective). Your thoughts?

**Comment by ozkatz** [comment]
I think that we should stay consistent:
non conflicting changes would show a content diff for txt,csv,... and the amount of bytes added/removed for other non-humanly-diffable formats.

We're already doing the first part for conflict, why not the second?

**Comment by ozkatz** [comment]
yes, summing the values indeed makes little sense. however showing size in bytes for source and for destination could be helpful (i.e. if `big_data.parquet` is 40bytes on source but 150MB on destination, that's useful when trying to decide which version to take)

**Comment by N-o-Z** [comment]
Sounds legit, do we want to add an informative message (as suggested above) in addition to the size change information?

**Comment by N-o-Z** [comment]
Without Diff:
![image](https://user-images.githubusercontent.com/3787958/188314179-0962a5c9-3e9f-499b-bcd3-f704703e3ef1.png)

With Diff:
![image](https://user-images.githubusercontent.com/3787958/188314197-90647d8d-1b9b-441c-804f-8c56fe4130d4.png)
