### ISSUE TITLE
lakefsfs versions are not maintained in git

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3665]
Currently, we have no way of knowing which ref a lakefsfs version is based on.
Suggest adding tags for future versions (and possible past)
Add release process documentation
Maintain a version changelist

**Comment by talSofer** [comment]
This was closed by the clients [release checklist](https://github.com/treeverse/dev/blob/main/pages/lakefs-clients-release.md) by @lynnro314
