### ISSUE TITLE
KV Graveler - testing gaps

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3668]
Repositories:

- Check all entities (branches, commits, tags and staging tokens) are removed upon delete
- Create repo with same name of deleted repo
- Check commit deleted on failed repository creation

Branches:
- Test delete branch deletes sealed tokens data
- Failure on delete branch tokens and then re-creation of branch with same name

Commits:

- Test commit data with multiple tokens
- Ensure commit deleted on AddCommitToBranchHead failure to update branch

Transactional tests
- Test creation / deletion / update of entities concurrently

Graveler 'SET' unit tests

**Comment by itaiad200** [comment]
Splited into multiple issues
