### ISSUE TITLE
Garbage Collection for Failed Graveler Entities

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3683]
As part of moving our `graveler` to run over `KV`, new challenges were introduced due to the loss of `SQL`s transactions.
This lack of transactions introduces the "ability" to fail in the mid of creation and deletion of objects, creating uncertain data statuses
#3661 tries to solve error handling during repository creation and deletion, from correctness aspect, and suggests that leftovers should be taken care of by a dedicated GC

**Note** This is about an internal clean up of **unused/unreachable/failed** graveler entities, and is not related to the current user-controlled retentiotn-related GC

**DoD**
An approved documents with detailed description of all entities/states that need a cleanup (e.g. failed repositories and their subsequent entities, patially deleted repositories(as in failed in the pocess of deletion), etc), and a suggested solution.

**Comment by N-o-Z** [comment]
- #3715
