### ISSUE TITLE
Access control credentials GUI sort

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3691]
Currently, the credentials under the GUI `Administration` tab are sorted alphabetically by their ID.
It should be possible to choose how the credentials are sorted, and the default should probably be by date.
![Screen Shot 2022-07-19 at 13 58 32](https://user-images.githubusercontent.com/96974219/179734754-b59151f7-9577-41c5-b661-954ec38f1815.png)

**Comment by rishiravikumar-tul-scm** [comment]
Hi @Jonathan-Rosenberg,
I'd like to take this up! 

Is the expectation to sort the credentials from earliest to oldest?

**Comment by itaiad200** [comment]
Hey @rishiravikumar-tul-scm , thanks for taking this one!
I agree with your suggestions, the newer creds should be on top.
