### ISSUE TITLE
Remove redundant GetRepository calls in graveler once DB implementation is deleted

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3695]
Since we don't want / can't modify or add to the current interface - we have many places where we call the GetRepo in the graveler level and fail to reuse it in ref manager.

Once DB implementation is deleted we could safely modify the interfaces to reduce the amount of GetRepo calls

**Comment by itaiad200** [comment]
Already implemented - most of Graveler interface accepts a `RepositoryRecord` now.
