### ISSUE TITLE
Support garbage collecting inactive branches

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#3698]
Extend lakeFS' [garbage collection](https://docs.lakefs.io/reference/garbage-collection.html) to handle abandoned branches. Ideally, let users set a policy on what qualifies as a GC-able branch:

1. it falls under a specific naming convention (i.e. starts with some defined prefix)
2. it had no writes/commits for a given duration of time
3. a certain amount of time has passed since its creation?
4. other criteria? (requires more discovery)

Inspired by [this thread](https://lakefs.slack.com/archives/C016726JLJW/p1658265859805779) (Thanks Clinton!)

**Comment by ortz** [comment]
### Goal
Support the capability of cleaning unused branches.

### Why
This capability supports the Dev-Test use cases where multiple branches are created without the intention of merging them back.

### Suggested Updated Configuration:
* `detach_stale_branches_after_days` (int): only branches with no new commits are a certain number of days will be eligible for detachment (and basically a GC candidate going forward). By default turned off, any number bigger than 0 is considered turned on.
* `stale_branches_filter` (array of strings): list of named branches or prefixes to filter upon, only filtered branches will be eligible for detachment with the exclusion of the configured default branch per repository. Wildcard is supported for suffix matching.
```yaml
{
  "default_retention_days": 14,
  "branches": [
    {"branch_id": "main", "retention_days": 21},
    {"branch_id": "dev", "retention_days": 7}
  ],
  "detach_stale_branches_after_days": 14,
  "stale_branches_filter": [
    "dev-test/*",
    "trash"
  ]
}
```

### Out of Scope
* Supporting per branch/prefix detach after days setting.

@itaiad200 @ozkatz I'd appreciate your thoughts & feedback on this.

**Comment by ozkatz** [comment]
Thanks @ortz! I would suggest however to structure the retention rules for branches a bit differently. Perhaps something like this:

```json
{
    "default_retention_days": 14,
    "branches": [
        {"branch_id": "main", "retention_days": 21},
        {"branch_id": "dev", "retention_days": 7}
    ],
    "branch_removal_rules": [
        {
            "pattern": "experiment-*",
            "since_event": "last_commit",
            "duration": "14d"
        },
        {
            "pattern": "*-tmp",
            "since_event": "branch_creation",
            "duration": "6h"
        },
        {
            "pattern": "no-wildcards",
            "expiry_event": "branch_creation",
            "duration": "180d"
        }
    ]
  }
```

This allows adding other event types in the future (not just since creation or since last commit, as well as to define a variable duration for different branches or patterns. WDYT?

**Comment by arielshaqed** [comment]
One thing that may be painful is that two proposed syntaxes are _very_ different from the [syntax for configuring GC](https://docs.lakefs.io/howto/garbage-collection.html#configuring-gc-rules).  I'd love for us to figure out a more consistent syntax for the different GCs.

**Comment by ortz** [comment]
@ozkatz nice... thank you.
I do like the rules of granularity and the possibility of attaching each rule to a different event.
I agree with @arielshaqed 's comment though and when I'm trying to read this configuration objectively, it's hard to tell the difference between the two sections.

@arielshaqed I'm aware this doesn't answer your syntax consistency concern, and I'm up for it to be consistent, but I'm afraid our terminology is a bit confusing (retention for branches is actually retention for objects within those branches).

Maybe we need something similar to this:
```
{
    "default_objects_retention_days": 14,
    "objects": [
        {
            "pattern": "main",
            "retention_days": 21
        },
        {
            "pattern": "dev",
            "retention_days": 7
        }
    ],
    "branches": [
        {
            "pattern": "experiment-*",
            "since_event": "last_commit",
            "duration": "14d"
        },
        {
            "pattern": "*-tmp",
            "since_event": "branch_creation",
            "duration": "6h"
        },
        {
            "pattern": "no-wildcards",
            "expiry_event": "branch_creation",
            "duration": "180d"
        }
    ]
}
```

**Comment by talSofer** [comment]
@ortz @ozkatz I'd like to suggest another way to productize the same setting. I see this as **branch settings** rather that retention settings. While retention will apply to objects on branches that will be deleted according to these settings it is only a side effect. As a user, I think that it will be clearer to separate concerns and think of my branch deletion rules and retention rules separately. 

My suggestion is to add another branch setting "called branch removal rules" (as suggested above), in addition to branch protection rules. It will be added to this section of the UI:
<img width="1479" alt="Screen Shot 2023-01-31 at 14 06 28" src="https://user-images.githubusercontent.com/14786381/215755603-6574b14c-9186-4260-a131-6e53e4ae23ba.png">

Another benefit of separating the settings is that we can use the syntax above without having to care about consistency with retention syntax. 

@ozkatz what did you mean by an "expiry_event"? I understand what "since_event" means not the first one.
