### ISSUE TITLE
Can't delete user with + sign from the UI

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#3709]
1. Create a user like 'idan+1@gmail.com'/ try to create an integration user like 'idan+demo'
2. Try to delete the user

You will get a "User not found" error

**Comment by arielshaqed** [comment]
I ran into something similar with an invited user.  That user cannot log in, cannot have groups attached (and has no groups), and cannot be deleted.

**Comment by eladlachmi** [comment]
@idanovo @arielshaqed Tried to repro this in multiple ways and couldn't. Looks like this has been resolved. See attached screen cap.  
If there's anything I've missed, please let me know.

https://user-images.githubusercontent.com/110764839/196738085-848113d2-6129-4424-a49a-05e2ad9b74c7.mov
