### ISSUE TITLE
Repository Creation and Deletion - Step 1 - Repository State and Unique Identifier

### ISSUE THREAD

**Issue by itai-david** [treeverse/lakeFS#3713]
Step 1 as described in #3661

**Comment by N-o-Z** [comment]
As part of this change, I want to change the behavior of deleting a non existing repository.
The current behavior is to return an error and I believe we should change it to return success.
I think this is the correct behavior for most flows that require deleting an object in the system, this should also enable us to implement the suggested deletion flow. @itai-david @itaiad200 @eden-ohana  @nopcoder  your thoughts?

**Comment by N-o-Z** [comment]
New view when repository is under deletion:
![image](https://user-images.githubusercontent.com/3787958/182826704-29586bbb-96f4-485d-be78-490e2c3dd111.png)
