### ISSUE TITLE
Discovery: do we want to publish the assembled Spark metadata client to Maven central

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3766]
Currently, we only publish the non-assembled Spark metadata client to Maven central. 
This task is to do some discovery and decide whether we want to publish the assembled jar too.

**Comment by arielshaqed** [comment]
We also do the _exact opposite_ on lakeFSFS: there we publish assembled and plain JARs.  At the very least we need to be consistent 😮

**Comment by arielshaqed** [comment]
In fact we publish (only) assembled metadata clients for GC (users need only add S3 / Azure hadoop plugins, depending on what they intend to use).  _Unassembled_ versions will be too hard for most users to get working.

Spark client is used almost exclusively for GC, which is generally performed by admins (or lakeFS.Cloud, of course).
