### ISSUE TITLE
Document azure support in lakeFS

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#3768]
Today lakeFS supports Azure Blob Storage, and partially supports Azure Data Lake Storage Gen2.
We should check and document our support in Azure, what are (if any) the differences in support between the storage types, and which [URIs](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/storage-connection-strings) are relevant to lakeFS.

**Comment by talSofer** [comment]
done by @treeverse/versioning-engine team
