### ISSUE TITLE
Update commit version

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#3796]
On the kv migration remove/update the commit version that was added after the parent switch bug on the merge. 

```
const (
   CommitVersionInitial CommitVersion = iota
   CommitVersionParentSwitch

   CurrentCommitVersion = CommitVersionParentSwitch
)

**Comment by N-o-Z** [comment]
@eden-ohana Do we need it for the release?

**Comment by itaiad200** [comment]
can't be done - lakeFS kv migration can't change commit IDs
