### ISSUE TITLE
Creating a new policy with the same ID as an existing policy "merges" them

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#3809]
[Reported by a user](https://app.slack.com/client/T013V60QY06/C02CV7MUV4G/thread/C02CV7MUV4G-1658946800.540749).

> I tried to create a read policy but somehow instead of a new policy, the change is merged to an existing policy.
> [...]
> Thanks, I figured it out. I used GUI. I gave a new policy name, but in the JSON I copied, I **forget to change the policy id**, then lakeFS “smartly” merge it to existing policy instead of creating a new one.

(Emphasis mine)

**Comment by eladlachmi** [comment]
This is already fixed by #4355 
Closing this issue.
