### ISSUE TITLE
Assembly jar provided dependencies

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3824]
Realize when should we mark a dependency as provided, and what is the standard regarding provided dependencies in uber/assembly jars - is it custom to set dependencies as provided in these kinds of jars?

## Definition of done
Guidelines- How and when should dependencies be marked as provided?

**Comment by arielshaqed** [comment]
Closing as we seem to be getting by without explicitly listing guidelines.  And in the meantime every case has been different :-/
