### ISSUE TITLE
CDF on Delta Lake 2.0 and LakeFS compatibility

### ISSUE THREAD

**Issue by herberton** [treeverse/lakeFS#3849]
Hi,

I've been using Delta Lake format files combined with LakeFS in my project. I'm using Delta Lake on v1.2.1 version and LakeFS with v0.6.9 version it runs fine.

I want to update the Delta Lake to v2.0.0 (most recently version) but I saw that Delta Lake have the change data feed (CDF) feature that enables versioning too, almost like LakeFS versioning but with another API.

Can you recommend use Delta Lake to v2.0.0 with LakeFS or it is not tested yet?

Thanks!

**Comment by arielshaqed** [comment]
Sorry for the time.

lakeFS now supports some Delta IO operations, with full support on our [roadmap](https://docs.lakefs.io/roadmap.html).  Meanwhile DeltaIO and lakeFS changes turn out to be very different beasts.  For instance, DeltaIO is currently much more fine-grained that lakeFS Delta-diff.  lakeFS provides cross-collection consistency, which obviously Delta cannot perform.
