### ISSUE TITLE
Align lakeFS clients publish

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#3863]
As for now, we publish lakeFS hadoopFS client jar and uber-jar to Maven central, and publish the Spark client jar to Maven, but the Spark client uber-jar to a public S3 bucket.
Both clients should be published in the same manner: 
- Non-assembly vs assembly. 
- Maven central and/or s3.

**Comment by talSofer** [comment]
duplicate of https://github.com/treeverse/lakeFS/issues/3766
