### ISSUE TITLE
KV Postgres scans are unlimited by size causing high latencies

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3888]
When the staging area is big in size (tested with 100k entries), the kv postgres implementation will fetch the entire staging area for every iteration. Requests are bounded by the users of the store (1000 default listing size for staging for example), so most data is being delivered without being used.

**Comment by nopcoder** [comment]
@itaiad200 it read the complete staging area, although the request fetches and page size using an iterator?

**Comment by itaiad200** [comment]
IIUC the postgres KV iterator doesn't use the page size.
