### ISSUE TITLE
Remove database stats collection from lakeFS

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3893]
Currently each lakeFS instance collects statistics from the database such is max connections, idle connections etc.
The current data is based on SQL statistics which are probably irrelevant in the KV world.
Also, it makes more sense to collect the DB statistics directly from the database rather than the lakeFS instances.

**Comment by N-o-Z** [comment]
@nopcoder did we remove the stats?

**Comment by nopcoder** [comment]
I think we did, as we don't have a postgres exporter.

**Comment by N-o-Z** [comment]
Closing issue
