### ISSUE TITLE
How to use Iceberg to operate lakefs

### ISSUE THREAD

**Issue by winyluo** [treeverse/lakeFS#3904]
How to use Iceberg to operate lakefs like work with hadoop?

**Comment by Jonathan-Rosenberg** [comment]
Hi @winyluo !
There is an open issue of Iceberg documentation which is currently in progress.
Please refer to #3451

**Comment by talSofer** [comment]
Hi @winyluo! Please see the updates on https://github.com/treeverse/lakeFS/issues/3451#issuecomment-1230482658. 
We will be happy to learn more about your use case. How would you like to see lakeFS working with Iceberg? any feature request will be appreciated.

**Comment by arielshaqed** [comment]
Apart from _existing_ docs as mentioned above and #4360, we are now in motion to implement Iceberg directly in lakeFS.  Current design is #5825.

So closing, but this train is arriving!
