### ISSUE TITLE
Invite user capability enabled by default even while smtp host is not configured

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3916]
### Steps to reproduce
1. Create lakefs config file not including smtp server configurations
2. Go to Administration -> Users 
3. Click "Invite user" and try to invite a user 
4. you'll see the following error
![Screen Shot 2022-08-17 at 9 19 21](https://user-images.githubusercontent.com/14786381/185048473-37f30ec5-8324-4a4b-8388-356353782473.png)

The fix should be to disable it by default. 

Impact: This bug also impacts lakefs playgrounds, where IMO the invite user capability should not be disabled.

**Comment by johnnyaug** [comment]
Does this happen when using an external authentication service? Or using the internal one?

**Comment by idanovo** [comment]
> Does this happen when using an external authentication service? Or using the internal one?

I think it's happens in OSS so probably the internal one @johnnyaug
