### ISSUE TITLE
Graveler to accept a repository object

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3934]
Currently all Graveler's operations accept just a `RepoID` which means that it would have to be fetched for every Graveler call within the same request. If Graveler was to accept a `Repository` object, many of `RefManager`s `GetRepository` calls could of been removed.

**Comment by nopcoder** [comment]
Used RepositoryRecord as the structure that captures the repository information with the repository ID.
At some point we can switch just to use just one and ignore the repository ID when needed.
