### ISSUE TITLE
Garbage Collection: add user group with permission suitable for running GC

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3954]
To run lakeFS Garbage collection, a lakeFS user needs to have the following lakeFS policy attached:
```
{
    "statement": [
        {
            "action": [
                "fs:ListObjects",
                "fs:ReadCommit",
                "fs:ReadRepository",
                "fs:ReadObject",
                "fs:ListRepositories",
                "retention:GetGarbageCollectionRules",
                "retention:PrepareGarbageCollectionCommits"
            ],
            "effect": "allow",
            "resource": "*"
        }
    ]
}
```

This issue is to add a pre-defined lakeFS GC user group with those permissions instead of letting the user figure out what permissions are required. 

DoD:
- Add a group 
- Document it GC lakeFS docs

**Comment by arielshaqed** [comment]
1. ACLs make this easy for non-Cloud users.
1. lakeFS.Cloud users get our awesome managed GC and never have to care.
