### ISSUE TITLE
Garbage Collection: document how to run spark-submit on Databricks

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3955]
GC is a Spark job and our users must use spark-submit to run it. Databricks users who usually use databricks notebooks, don't necessarily know how to run spark-submit from databricks. 
It will be helpful to mention in our docs that [databricks jobs](https://docs.databricks.com/workflows/jobs/jobs.html) are the way to do it.

**Comment by itaiad200** [comment]
Done.
