### ISSUE TITLE
lakeFSFS to Hadoop 3: add to integration tests 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#3958]

**Comment by johnnyaug** [comment]
In Esti, when we test lakeFSFS (called "direct-access client" there), we set SPARK_TAG to either 2 or 3. (See https://github.com/treeverse/lakeFS/blob/2a5b89ecdd789bc7f820adb4dea71ffe32b772fa/.github/workflows/esti.yaml#L397)

This sets the image tag of [bitnami/spark](https://hub.docker.com/r/bitnami/spark). The Spark 3 tag of this image uses Hadoop 3.3.2, so the change is tested.
