### ISSUE TITLE
Disable the cancel button on the import from UI tab when import is done

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#3992]
Gives the users the sense the cancel will cancel the operation after it's done.

![image](https://user-images.githubusercontent.com/71877898/186669005-7fcab682-30c4-4439-9618-af879265c265.png)

**Comment by itaiad200** [comment]
@N-o-Z what's the behavior for the new import?

**Comment by N-o-Z** [comment]
Obsolete
