### ISSUE TITLE
Import from UI: allow to user to not keep the tab open while import is in progress

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#3994]
Currently, the import from the UI client performs API calls to the server on every range creation.
Maybe combine it into one operation on the server/ keep state on the server to allow the user to not keep it open.

**Comment by itaiad200** [comment]
I think that's the case today with the new import, @N-o-Z ?

**Comment by N-o-Z** [comment]
We do have a state in the server, but the import dialog window remains open and if closed cancels the import operations.
IIUC this issue suggest allowing users to continue usage of UI while the import continues the progress in the background
