### ISSUE TITLE
Import failed due to writing range with wrong keys order

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#4018]
This came up from a user. 
Import data from s3 to lakeFS failed with this error:

```{"error":"writing range from entry iterator: writing record: setting key and value: pebble: keys must be added in order: #0,DEL, #0,SET","file":"lakeFS/pkg/api/controller.go:1747","func":"pkg/api.(*Controller).handleAPIError","level":"error","msg":"API call returned status internal server error","service":"api_gateway","time":"2022-08-28T15:33:00Z"}```

![image](https://user-images.githubusercontent.com/64288262/187083587-6a7e6b1b-f42e-4ef2-8e21-1177f8484afb.png)

**Comment by itaiad200** [comment]
We should block import from paths that contain the repo storage namespace.
1. It makes no sense to import lakeFS metadata and data to lakeFS.
2. It causes errors in S3 due to keys not being sorted.
