### ISSUE TITLE
Add a download capability to lakectl

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#4095]
Support lakectl download command to support single/multiple files download to local directory.

```
# single file
lakectl fs download lakefs://example-repo/example-branch/prefix/doc.md

# multiple files
lakectl fs download --recursive lakefs://example-repo/example-branch/prefix/

# select destination
lakectl fs download --recursive lakefs://example-repo/example-branch/prefix/ mydata
```

**Comment by nopcoder** [comment]
Updated issue to support `download` first instead of sync.
Currently we have upload for single / multiple files to lakeFS.
The download will enable  a single or multiple files download from lakefs to local directory.

**Comment by arielshaqed** [comment]
> Updated issue to support `download` first instead of sync. Currently we have upload for single / multiple files to lakeFS. The download will enable a single or multiple files download from lakefs to local directory.

We should probably change the title too, this is not a `sync` operation.
