### ISSUE TITLE
GC: Incremental garbage collection

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4116]
Implement incremental GC:

- [x] #5781 
- [x] #5783
- [x] #5784

**Comment by ortz** [comment]
More context: Support running the Garbage Collection Spark job incrementally: take into account commits and references scanned and collected on previous runs to avoid traversing the entire graph on each execution.

**Comment by itaiad200** [comment]
DoD: Get an estimated cost of incremental run and compare it to full GC run.
