### ISSUE TITLE
Add warning when lakefs starts with `mem` KV

### ISSUE THREAD

**Issue by itaidavid** [treeverse/lakeFS#4147]
We should warn a user on the lack of persistency, when KV is configured to "mem"
Something similar to the warning we display when the blockstore is set to "mem" or "local"

**Comment by vaibhavk1992** [comment]
@itaidavid @arielshaqed  Can you please add some more details about this issue and how to replicate it?

**Comment by itaiad200** [comment]
Hey @vaibhavk1992 ,
Do you see [this](https://github.com/treeverse/lakeFS/blob/3ae8f04ed0b9be567502c991a0fab69abc06eec0/cmd/lakefs/cmd/run.go#L154) warning? It's written when the blockstore implementation is of type memory. We need a similar warning if the database implementation is of type memory as well.
