### ISSUE TITLE
Add "Join the community on Slack" button

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#4170]
In the dropdown menu at the top-right of lakeFS, add a "Join the community on Slack" link.
Clicking this link will lead the user to the community Slack where they can ask for support and share their use-case.

It should be possible to disable this feature using a configuration flag.

**Comment by Tjs002** [comment]
@johnnyaug can you assign me this issue if its exists an can you guide me to setup as i am new
