### ISSUE TITLE
Update the container ssl certificates

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#4176]
How to configure HTTPS endpoint for Docker installation?

**Comment by nopcoder** [comment]
@kesarwam serving https and using docker are two different things. Docker is used to run lakeFS inside a container while HTTPS is a capability to listen and serve on a secure port.
- Currently lakeFS doesn't serve HTTPS. Note this is not related to Docker.
- Running lakeFS with or without Docker while serving HTTPS will require another service that will provide the https termination. It can be done using any reverse proxy or/and load balancer running with your lakeFS or provided by your cloud infrastructure.

Let me know if this answers your question/issue and I'll close this one.

**Comment by kesarwam** [comment]
Changed the issue to "Update the container ssl certificates"
