### ISSUE TITLE
Send an init event with an Installation, ID even if Stats are disabled.

### ISSUE THREAD

**Issue by einato** [treeverse/lakeFS#4181]
We would like to asses how many installations out there have stats disabled. This will help us get an idea.

- Set a fixed (24h) interval for the security events
- Associate anonymous installation_id property to the security event

**Comment by ortz** [comment]
@einato @NoyDavidson2 nowadays we're sending on a 12-hour interval security audit event, and on the other hand, we have the stats (for those who enabled them).
Calculating both metrics should give us the number of installations that didn't enable stats and make this one redundant, isn't it?

**Comment by einato** [comment]
It isn't. The security check is sent without an installation ID, and in a random time between 12-14 hours. It is therefore useless for BI purposes. We tried to cross it with IP and failed to get meaningful results. We know other OSS projects send a daily ping to server without opt out, and we may be too conservative. We can add an installation ID to the security check and send it every 24 hours, exactly 24 hours....That can be helpful.

**Comment by ortz** [comment]
> It isn't. The security check is sent without an installation ID, and in a random time between 12-14 hours. It is therefore useless for BI purposes. We tried to cross it with IP and failed to get meaningful results. We know other OSS projects send a daily ping to server without opt out, and we may be too conservative. We can add an installation ID to the security check and send it every 24 hours, exactly 24 hours....That can be helpful.

I see... thanks for the clarification. I'll check if we can change the security check to support it, and if not, we'll prioritize it as a dedicated event.

**Comment by ortz** [comment]
Verified that it doesn't violate our OSS commitment, so the required changes:

- Set a fixed (24h) interval for the security events
- Associate anonymous installation_id property to the security event

Updated in the issue description

**Comment by ortz** [comment]
@einato @NoyDavidson2 addressed in https://github.com/treeverse/lakeFS/pull/4271
