### ISSUE TITLE
lakefs run flag to configure local default parameters

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4186]
Add a flag to the `lakefs run` command that will enable default local configuration variables running with local blockstore and KV driver.
This will make it easy to use the docker run command without providing any additional parameters

**Comment by itaiad200** [comment]
What's wrong with using default flags when it's appropriate instead of passing a flag that says "set all these values for me"?

**Comment by itaiad200** [comment]
We need to be careful of doing `lakefs run --local-run` and then `lakefs run --local-db-s3-blockstore`, or `lakefs run --dyanmo-s3-blockstore-logs-to-file`
