### ISSUE TITLE
Reduce the complexity of lodaing config.NewConfig

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#4201]
Loading configuration and intialize the configuration is currently scattared between initConfig that is called once and NewConfig which one uses the use while loading, parsing and validating the configuration.
Adding defaults and the order we set them can be tricky.
We should simplify this code and enable a single entrypoint that will set the order we set the defaults, load the configuration and validate the required fields.

**Comment by itaiad200** [comment]
@nopcoder I think you fixed this this week?
