### ISSUE TITLE
Update lakeFS "architecture" docs

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4246]
https://docs.lakefs.io/understand/architecture.html says:

> lakeFS stores data in an underlying object store..., with some of its metadata stored in [PostgreSQL](https://www.postgresql.org/) (see [Versioning internals](https://docs.lakefs.io/understand/versioning-internals.html)).

That's no longer really true 🥳

**Comment by splitice** [comment]
Does this mean its now (or soon) going to be possible to go S3 object store only?

This would be great news if true.

**Comment by arielshaqed** [comment]
> Does this mean its now (or soon) going to be possible to go S3 object store only?
> 
> This would be great news if true.

Hi @splitice !

That's _almost_ true.  As #4247 is about to add, you _still_ need a data store with a bit more atomicity than is possible on S3.  But this is now PostgreSQL (used purely as a key-value) or DynamoDB.

It's still really _really_ good news, though! :-)
