### ISSUE TITLE
Extended analytics event

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#4265]
Extended analytics enables reporting more information on each event report.
Only when relevant the following values, hashed except 'client', will be reported:

1. Repository - hashed value of the repository name
2. Ref - hashed value of the tag/commit/branch name 
3. SourceRef - hashed value of source tag/commit/branch 
4. UserID - hashed value of the user ID
5. Client - user agent of the client performing the operation

This feature is turned **off** by default.

**Comment by arielshaqed** [comment]
Hashing might not do much for some of these fields.  E.g. I could download the ` md5_ascii-32-95#1-8` rainbow table from [the rainbow tables site](http://project-rainbowcrack.com/table.htm) and crack almost any repository, ref, and (non-email) userID.  (If I wanted to be more efficient, I could generate rainbow tables _once_ for the smaller character set allowed in repos and/or refs, and probably crack repo and refs of 9 or even 10 characters...).

We should probably let admins configure a salt for these hashes.
