### ISSUE TITLE
How can i upload a file with chinese name

### ISSUE THREAD

**Issue by kakasu** [treeverse/lakeFS#4279]
when i upload a file with chinese name ,it throws:
        java.lang.IllegalArgumentException: Unexpected char 0x4e2d at 37 in Content-Disposition value: form-data; name="content"; filename="中文2038_right_1654846703.jpg"

the code:
        String repository = "hanzi";
        String branch = "main";
        String path = "中文2038_right_1654846703.jpg";
        String storageClass = null;
        String ifNoneMatch = null;
        File content = new File("D:\\eyedata\\demo6\\images\\中文2038_right_1654846703.jpg");
        ObjectStats response = api.uploadObject(repository, branch, path, storageClass, ifNoneMatch, content);

**Comment by arielshaqed** [comment]
Could this be a case of OpenAPITools/openapi-generator#5117 in the upstream code generator?

@kakasu , could you try to URI-encode the path argument?  If that works, then per the upstream bug it's a pervasive issue with OpenAPI code, and IIUC the spec itself is unclear over which form to use.
