### ISSUE TITLE
lakeFS Hadoop file system to work with databricks MLflow projects

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4289]
databricks provides a managed [mlflow projects capability](https://docs.databricks.com/mlflow/projects.html). This feature does not support .jar dependencies. Since lakeFS Hadoop-specific filesystem is provided as a jar to a databricks runtime, lakeFS users can currently connect their databricks MLflow experiments to lakeFS only via the [s3 gateway](https://docs.lakefs.io/integrations/spark.html#access-lakefs-using-the-s3a-gateway). 

If databricks add support for .jar dependencies, the two will work together out-of-the-box.

**Comment by nopcoder** [comment]
@talSofer thinking on alternative based on the link you sent - we can add lakeFS Hadoop dependency/requirements into the new cluster specifications. As far as I know everything we configure as part of the application can also be done at the cluster level.

**Comment by talSofer** [comment]
@nopcoder thanks!

I tested this and unfortunately, I don't this is possible. 
I added the following into my mlflow experiment cluster spec: 
```
"libraries": [
      {
      "maven": {
        "coordinates": "io.lakefs:hadoop-lakefs-assembly:0.1.6"
      }
     }
   ]
```

After doing that, the mlflow experiment cluster startup process halts on installing the maven dependency.

**Comment by nopcoder** [comment]
Thanks Tal for checking this one.

**Comment by arielshaqed** [comment]
@talSofer is this still relevant?  Can you outline a good next step please?

**Comment by talSofer** [comment]
@arielshaqed this issue is still relevant, this issue will be resolved once databricks add support for jar dependencies. as a result, we can include the lakeFSFS jar in the experiment runtime
