### ISSUE TITLE
GUI doesn't allow scrolling or searching when attaching policies to users

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4348]
# [Reported by a user on Slack](https://lakefs.slack.com/archives/C016726JLJW/p1665418102744199)

## Steps

1. Navigate to a user or a group.
2. Click them.
3. Click to "attach policy".
4. Attempt to search for a case-sensitive substring (should either give just containing policies or _no_ policies), list does not change.

   ![search for "Full", list is unchanged](https://user-images.githubusercontent.com/7802932/194912668-a7182e56-ba05-4034-8164-5359758ea21c.png)

  Search for a case-sensitive prefix (should definitely find _something_), list does not change.

   ![search for "FS", list is unchanged](https://user-images.githubusercontent.com/7802932/194913062-9e2242ac-e560-479c-bf3b-4d8b5d80fded.png)

5. Attempt to scroll the list, list does not change.
6. Type in the exact name of a policy, list does not change... and "Attach" button remains disabled.

## Expected behaviour

It should be possible to attach a policy to a user or a group in _any_ way, and in particular:

1. It should be possible to type in the name of a policy and attach it.
2. It should be possible to type in any case-insensitive substring of a policy (e.g. "full" or "fs") to narrow the list, then select and attach it.
3. It should be possible to scroll the (narrowed!) list of policies.

## Some analysis

AFAICT (3) has not been possible for a while now, but an earlier revision let me at least narrow the list by case-sensitive prefix (but not scroll).  This is still less than the "expected behaviour" requested above, but at least it lets users attach policies!

## Workaround

Use `lakectl auth users policies attach --id USERNAME --policy POLICY`.

Reported on 0.83.2, verified on 5dc1225c1b13d406f6257d261ebdaf3f344c275d, and no relevant changes since then on webui/.

**Comment by arielshaqed** [comment]
User [report](https://lakefs.slack.com/archives/C016726JLJW/p1665419754786499?thread_ts=1665418102.744199&cid=C016726JLJW)s:
> ... it looks like the call always returns the first 5 users and is ignoring that prefix query parameter

**Comment by eladlachmi** [comment]
@arielshaqed Thank you!
Was the issue only in the BE? Does the FE already pass the paging parameters in the HTTP request or does it need to be modified respectively?
