### ISSUE TITLE
Improve server response for uncommitted changes

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#435]
DiffUncommitted should support prefix.  It will enable us getting diff by level.
The response should include flag saying if there was a change in the branch level and under the prefix return the diff by level.
It should consider add/delete in the folder level.

**Comment by ozkatz** [comment]
@itaiad200 I don't think this is relevant any more?

**Comment by itaiad200** [comment]
Yes, both committed and uncommitted support listing with delimiter ('/'). Closing.
