### ISSUE TITLE
Client cancelled request should not return 5XX response

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#4370]
If a request is terminated early due to cancellation from the client side, we should not treat that as server error. Nginx uses 499 responses for `client closed the connection`. The main incentive to change the response code is to distinguish real server errors from client cancellation. A justified reason to cancel a request is latency, which should be monitored by the appropriate metrics. 

Waiting for completion of #4291 .

**Comment by itai-david** [comment]
So, to make things clear, we want to return 499, to be aligned with nginx?

**Comment by itaiad200** [comment]
Why shouldn't we return it to the client?
I assume that a client that cancelled a request is not interested in the status code anyhow. If the request was cancelled after a long time (> 2 min / 30 sec ?), then one might suggest that it wasn't the client that initiated the cancellation, rather some other component along the way. But we don't witness many requests to lakeFS that span for so long, so trying to optimize for these is premature.

**Comment by itai-david** [comment]
No reason not to return it to the client, if the connection is still valid.
I'm just trying to figure what the phrasing should we use, as this is a custom status code. I'm thinking of a more general `Request was cancelled`. WDYT?
