### ISSUE TITLE
Support Azure Blob Storage for HadoopFS

### ISSUE THREAD

**Issue by ortz** [treeverse/lakeFS#4385]
Extend the lakeFS HadoopFilesystem to support working directly with Azure Blob Storage.

**Comment by itaiad200** [comment]
@johnnyaug don't we have it with presign?

**Comment by arielshaqed** [comment]
Assigning to @johnnyaug: please reply and close or unassign.

**Comment by johnnyaug** [comment]
Supported w/ presigned mode. Closing.
