### ISSUE TITLE
lakeFS release binaries are not signed (macOS)

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#439]
consider signing the binaries in order to have better download and execute experience on macOS .
https://goreleaser.com/customization/sign/

**Comment by arielshaqed** [comment]
Of possible relevance: the [discussion on Homebrew](https://discourse.brew.sh/t/code-signing-installed-executables/2131).

**Comment by itaiad200** [comment]
@nopcoder is this done?

**Comment by nopcoder** [comment]
nope. just added brew support.

**Comment by johnnyaug** [comment]
When I'm downloading the lakeFS binaries from GitHub, I'm able to run them without any problem. Not sure this is needed ATM. Did anyone run into problems?

**Comment by johnnyaug** [comment]
@nopcoder I suggest to close this until we prove that it's needed.
