### ISSUE TITLE
Fix or document skipped contract tests

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#4396]
In #4357, we commented out some lakeFS File System contract tests. Go over these and decide whether they need to be fixed.

If we decide that the behavior is ok as is, document it in the code where the tests are overridden (all the empty methods in [TestLakeFSFileSystemContractHadoop3.java](https://github.com/treeverse/lakeFS/pull/4357/files#diff-f74a418a887962a3f6b7da5526c90f7d37453840dbfa00f12ec1d7a00819eb93)

**Comment by arielshaqed** [comment]
@johnnyaug is htis still relevant?  please reply and close or unassign.
