### ISSUE TITLE
Perform retention queries in smaller chunks

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#440]
Retention uses single large queries.  These can hurt DB performance during retention.  Break queries up into smaller chunks to improve performance and let other transactions continue.  (It *is* a sound transformation!)

**Comment by ozkatz** [comment]
@arielshaqed @itaiad200 I vote to close this. Retention is due for a major change anyway, with the move to _lakeFS on the rocks_. WDYT?

**Comment by arielshaqed** [comment]
Closing: no current user complaints, possibly because no users yet.  And -- as you say -- will be reimplemented differently.
