### ISSUE TITLE
SQL error is shown to the user

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#441]
When trying to create a repository with a name of an existing repository, the following error is printed:

`Error executing command: error creating repository: insert repository: ERROR: duplicate key value violates unique constr
aint "catalog_repositories_name_uindex" (SQLSTATE 23505)`

This should be changed to a user-friendly error.

Example command to reproduce:
`lakectl repo create lakefs://existing-repo s3://example-bucket`

**Comment by kzuri** [comment]
I would like to take a shot at this

**Comment by ari-hacks** [comment]
👋🏾 I'd like to take this one

**Comment by YaelRiv** [comment]
Hello @ari-hacks! It's all yours. 
If you need any assistance - please join our slack channel:
https://join.slack.com/t/lakefs/shared_invite/zt-g86mkroy-186GzaxR4xOar1i1Us0bzw

**Comment by ari-hacks** [comment]
Awesome, thanks!

**Comment by avats-dev** [comment]
@ari-hacks are you working on this one or can I try?

**Comment by ari-hacks** [comment]
@avats-dev yep, still assigned. 🙂
