### ISSUE TITLE
UI: version label of web UI appears as "dev"

### ISSUE THREAD

**Issue by ortz** [treeverse/lakeFS#4415]
**What's wrong?**
UI reports it's running `dev` version.

**What was expected?**
To see the UI's explicit version.

![image](https://user-images.githubusercontent.com/1756345/196877873-4a434ce7-d4a6-43c1-aeca-419a3f404be1.png)

**Comment by nopcoder** [comment]
Thanks this one also affects the extended stats when enabled.
