### ISSUE TITLE
LinkPhysicalAddress can be used on already committed addresses

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4438]
Currently, there is no enforcement on LinkPhysicalAddress regarding the origin of the provided address or times of use.
The following scenario can occur:
1. GetPhysicalAddress returns an address issued by lakeFS
2. Perform upload to address and LinkPhysicalAddress
3. Commit data (commit-x)
4. Perform LinkPhysicalAddress using the same address on same branch
5. Commit data (commit-y)

Result - commit-x has invalid metadata for address

- The solution will be to enforce single use of addresses issued by lakeFS using GetPhysicalAddress and will be solved as part of the changes suggested in  https://github.com/treeverse/lakeFS/pull/4382

**Comment by itaiad200** [comment]
@N-o-Z Not sure I follow. The second Link will create another staging entry pointing to the same physical object? Why does that changes anything that commit-x is point to? If we were to change the actual object I would understand, but here it's a metadata operation on a new staging area.

**Comment by itaiad200** [comment]
@N-o-Z @eden-ohana That's impossible now, right?

**Comment by N-o-Z** [comment]
Yes
