### ISSUE TITLE
Interactive tool for generating a lakeFS configuration file

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#445]
The `lakefs` binary uses a yaml configuration file.

As a lakeFS user, I would like a command line utility to generate this config file interactively.

Upon running "lakefs config", the user should be asked to fill in the basic information for a lakefs server to run.
A minimal configuration file example can be found [here](https://docs.lakefs.io/deploying/install.html#docker) in the docs.

Example of information to get from the user:
1. Database connection string
2. Blockstore type.
3. If the blockstore type is S3, choose the region and authentication method (aws profile, aws key pair, or using the instance role)
4. S3 gateway domain  name

The output should be a yaml file containing the configuration. The user should be able to specify an output destination for the file. If not specified, it should be saved to the default location: $HOME/.lakefs.yaml (with override protection).

**Comment by DarthCucumber** [comment]
Hey, I'm a open source newbie. I would like to work on this issue.

**Comment by YaelRiv** [comment]
Hello DarthCucumber! 

It's all yours. Thanks for giving us a hand 💪

Feel free to join our slack channel if you have any questions. 
https://join.slack.com/t/lakefs/shared_invite/zt-g86mkroy-186GzaxR4xOar1i1Us0bzw

Many thanks, 
Yael

**Comment by johnnyaug** [comment]
Hey @DarthCucumber , should I assign you to this issue?

**Comment by DarthCucumber** [comment]
@johnnyaug yea sure I started working on it. If I face any issue can I ask on slack ?

**Comment by johnnyaug** [comment]
Of course, please do!

**Comment by johnnyaug** [comment]
Hey @DarthCucumber , still here? :slightly_smiling_face:

**Comment by DarthCucumber** [comment]
@johnnyaug yep, I'm almost done. I'll make the PR in 1-2 days
