### ISSUE TITLE
Discovery: Uncommitted garbage collection on old repositories

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4457]
As suggested in https://github.com/treeverse/lakeFS/pull/4382, the new GC process will rely on a new repository structure to optimize its execution.
This will work well for new repositories, but does not provide a solution for already existing repositories.
We need to address the following issues:

- How to run uncommitted GC on existing repositories with a flat structure in an optimal way (as much as possible, considering our limitations)
- How to incorporate this as part of the current proposal and implementation
- How to identify the first run on such repositories in order to initiate this flow

**Comment by eden-ohana** [comment]
The GC process for the old repository structure: @treeverse/versioning-engine 
* According to the proposal, there are two flows one for a clean run and one for an optimized run which uses the output of the previous run
* Old repository structure can only be included on clean run flow
* The new data will be written under /data prefix - there will not be overlapping with the new slices
* We need to address all other objects under the root

Only on clean run flow -  add to the listing objects step:
* List all the objects under the root directory
* Split them into slices by order [a-c], [d-f]
* The slices will break at fixed points (like ranges) 
* Every slice will be headed to a worker (the same workers as the one for the new repository structure)

**Comment by itaiad200** [comment]
"List all the objects under the root directory" - how do we split up this task? It has the potential of list billions of objects.

**Comment by N-o-Z** [comment]
Listing all objects just to split them - will take a very long time. Decision on where to split should be arbitrary in my opinion, according to object count or similar

**Comment by eden-ohana** [comment]
@itaiad200 @N-o-Z updated

**Comment by eden-ohana** [comment]
1. We can use max int on Java.
2. Its a statistic estimator. Every 256 bit hex string is a hex number between 0 and 2^256-1, so I can pick a uniformly distributed random number a and ask S3 for the next object b on S3 at or after a. Define the random variable X = b-a. Then EX = 2^255/N, so N=2^255/(EX).
3. If we will chose an object inside data - we can choose again.

**Comment by N-o-Z** [comment]
Since we know we use uuid to generate file names - the length is exactly 36 bytes
