### ISSUE TITLE
In the UI, make it easily possible to copy the path to an object

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#447]
In S3 web interface, the path is part of the URL so the slash separator is preserved, making the path easy to copy (see photo).

In our UI, the path is given as a query param, so slashes are escaped.
Perhaps add a copy button for the path. Need to decide which path type to copy - s3 or lakeFS, and whether it will include the repo and branch names.

![image](https://user-images.githubusercontent.com/9861474/89541046-828e7900-d806-11ea-94a8-354ccdf07c07.png)

**Comment by johnnyaug** [comment]
Apparently it can be done
