### ISSUE TITLE
GC+: Implement uncommitted GC main logic

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4488]
Pre-requirements:
1. Uncommitted format
2. Committed format 

Create logic which lists object store into DF, and performs the minus operation with the committed and uncommitted data

Opens:
1. Define clearly how to list and partition data from the object store
2. How to split the work between workers

**Comment by itaiad200** [comment]
Another prerequisite derived from our understanding of the shared GC model is the ability to split the GC client into 3 parts: the shared "infrastructure", the committed GC logic and the uncommitted GC logic. We can use this issue to track it, or split it into 2 (probably more) tasks.

**Comment by itaiad200** [comment]
Steps:
1. Call PrepareUncommitted API and read parquet files.
3. Read All committed entries
4. List all StorageNamespace objects
5. (3) -(2+1) - delete candidates.
