### ISSUE TITLE
valueEntryIterator casting Key to string

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4554]
EntryRecord is the catalog entry representation for a graveler entry.
The path field represents the logical path of the object on the object store and is of type string.
During the initialization of the struct we cast the graveler Key (byte slice with no encoding assumptions) to a string.

This will fail for objects with unsupported characters in path

**Comment by arielshaqed** [comment]
It's a bug all right, but it only actually breaks if you serialise and go communicate outside of Go. Go strings _are_ byte sequences! See https://go.dev/ref/spec#String_types.

The thing is, if you serialized it... Say to JSON... anything goes.

**Comment by nopcoder** [comment]
@N-o-Z we cast Go string to slice of bytes in UTF-8. Go string representation is UTF-8, no need assumptions as if you like to use diffrent encoding you will need different type.
