### ISSUE TITLE
Exclude based on glob pattern in GC

### ISSUE THREAD

**Issue by selvavm** [treeverse/lakeFS#4570]
First of all, thanks for LakeFS. I had a conversation on Slack and posting it here based on the suggestion there. 

Since a branch/repo contains big data, configuration files and documentations, there is not a need to delete versions of configurations or documentations. This allows time travel on those light weight data. 

To support this, it would be nice if GC can exclude certain files based on glob pattern Or have different retention policy based on glob pattern in a branch.

**Comment by arielshaqed** [comment]
In order to do this one we will need a user who can spec this out, give a use-case, etc.  Too easy for us to do the wrong thing here and make GC more complex with no gain for our users.

**Please re-open** if you can help!
