### ISSUE TITLE
Report Unsuccessful API Calls To BI

### ISSUE THREAD

**Issue by NoyDavidson2** [treeverse/lakeFS#4582]
We want to be able to understand how many of the API calls were unsuccessful.
The current state of API calls reflects all of the calls a user is trying to preform - both successful and ones who were not completed for many reasons.

Two alternatives @nopcoder and I thought about are:
1. Create a dedicated table for unsuccessful events in the 'events' table schema.
2. Add a field to 'events' table that declares whether the API call was unsuccessful or not.

Doing this will provide the ability to aggregate both successful and unsuccessful calls.
**Prior step to this - discussion of how we define unsuccessful calls report.*

**Comment by arielshaqed** [comment]
I'm curious and ignorant of the facts behind this suggestion, so sorry for the stupid question.

Why can't we go with a classic field + view scenario?

* Add a field to `events` for the status code.
* Create a view that aggregates over these fields by `status_code < 300` / `status_code >= 300` to get counts.

This should give something _correct_.  We may need to rollup / materialize the aggregates, but that's about it, no?

**Comment by NoyDavidson2** [comment]
@arielshaqed AFAIU API requests and status logs are not reported in the same time nor can be aggregated by the same time frame.
This causes the challenge of understanding - which status log belongs to which events batch sent to 'events' table.

I might have misunderstood and if so your suggestion is ideal in terms of BI.
