### ISSUE TITLE
Bulk operations in rest api

### ISSUE THREAD

**Issue by tamirFireFly** [treeverse/lakeFS#4591]
Hey, I want to mange history of large amount of documents. Can be around 10k documents and bulk reading and writing operations that will reduce amount of requests between my service and lakefs can be very helpful.

Even if I can do it in pages of x files each time is a big improvement that can help me.

**Comment by arielshaqed** [comment]
This is kind-of the converse of [supporting MinIO-style PutObjectExtract](2393).  We never decided to do that one either, but possibly MinIO can provide some inspiration for what such an API might be like.

However if you need *really* large scale, you might consider using lakeFS statObject calls or a single listObjects, and then go off and directly access the object stored on underlying storage.  That will keep lakeFS off of the data path, and should be faster.  Plus it will be much easier to parallelize.

**Comment by tamirFireFly** [comment]
You mean to access s3 directly for read operations instead of using lakefs for it?
I can do it and still have advantage of branching and accessing specific commits from my "repos history"?
How would I know the path? 
You have s3 examples maybe for it?

**Comment by eden-ohana** [comment]
you can use the [s3 getway](https://docs.lakefs.io/reference/s3.html) for read/write operations, and lakeFS for the versioning operations

**Comment by eden-ohana** [comment]
you can also use StatObject operation to lakeFS and get the actual address, e.g. s3://my-bucket/namespace/<uuid> and then get it directly from there
