### ISSUE TITLE
Receiving "[I] unmatched delete" warning messages during commit

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4593]
My app:

* Creates many objects (using the GetPhysicalAddress / linkPhysicalAddress
  API) on a path .../_temporary/...
* Stages each again on another path on the same branch using the StageObject
  API.
* Deletes the original path.
* Commits.

I see multiple "unmatched delete" messages during the commit, possibly for
each object.  You can see them on our staging org, for instance:

``` json
	
{
  "file": "build/pkg/graveler/committed/commit.go:181",
  "func": "pkg/graveler/committed.(*committer).applyNextKey",
  "host": "ecoXXX.us-east-1.lakefscloud.ninja",
  "key": "amazon-reviews-repartition-clean2.csv/_temporary/attempt_202211131610353776741523865508520_0005_m_000661_707/part-00661-8a2e50b0-e366-4a16-9266-f12187784cb1-c000.csv",
  "level": "warning",
  "method": "POST",
  "msg": "[I] unmatched delete",
  "operation_id": "Commit",
  "path": "/api/v1/repositories/test-1/branches/lakeFS-OC--1l6fxphkzwaascr80nbp2tiour6kztr3asyov0k8stzt6u1wdn-lakefs---test-1-test-clean-2-amazon-reviews-repartition-clean2-csv/commits",
  "request_id": "c4e88f51-b964-4069-83f9-f701ff75dc94",
  "service_name": "rest_api",
  "time": "2022-11-13T16:28:58Z"
}
```

The log message itself is emitted when a commit tries to delete a file that
does not exist anyway.  So it is indeed harmless (hence a warning) but
unexpected.  Pre-KV in the full SQL days it was "impossible".  Maybe it is
safe in KV, and we should just remove these messages?

**Comment by nopcoder** [comment]
Associated the fix pr - the tombstones found for non-exist entries will not log warning.
