### ISSUE TITLE
Discovery: how to efficiently list addresses of committed entries

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#4600]
For GC+, we need to list _all_ physical addresses of objects that have already been committed.

Even if we go use an optimization where we only want to go over "new" addresses, we still need to go over all ranges. This is because Graveler metadata is scattered across ranges, regardless of when they were added.

**Comment by itaiad200** [comment]
Just a thought: You can use the range, or even the metarange upload time and skip ranges that were written before.
