### ISSUE TITLE
GC+: Uncommitted objects are being marked for deletion

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#4658]
Reproduce by adding an uncommitted object and then run GC+.

**Comment by itaiad200** [comment]
Root Cause:
Uncommitted objects paths are relatives e.g: `data/gr8h115fcls5asibhqj0/cduv59tfcls5asibhqo0`. Committed and physical (data in the buckets) are absolute, e.g. `s3a://guy-repo/itai/demo/prod-2/data/gr8h8utfcls49ggqedsg/cduut2dfcls49ggqedv0`.
The `exclude` between the two will not exclude uncommitted objects.

**Comment by itaiad200** [comment]
We should also remove the schema (s3a).

**Comment by nopcoder** [comment]
Fixed by #4665
