### ISSUE TITLE
Uncommitted GC backup & restore

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#4677]

**Comment by N-o-Z** [comment]
Opened: https://github.com/treeverse/lakeFS/issues/4775

**Comment by N-o-Z** [comment]
After meeting, decided to create a temporary solution for the beta milestone which provides basic backup and restore capabilities explicitly for uncommitted garbage collection beta - and document the procedure

**Comment by nopcoder** [comment]
Adding capability to report deleted also as text. It will simplify the instructions to one-liner using rclone to backup or restore
