### ISSUE TITLE
Committed entries are marked for deletion

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#4698]
With the latest master I get:
- Committed entries:
`s3a://storagenamespace/data/gr7t8hlfcls7ethcf6k0/cdviuglfcls7ethcf6ng`
- Physical entries:
`data/gr7t8hlfcls7ethcf6k0/cdviuglfcls7ethcf6ng`
- uncommitted entries:
`data/gr57ka5fclsdflgskrhg/ce28r55fclsdflgskrj0`

So committed entries are not excluded and can be picked up by the GC.

**Comment by N-o-Z** [comment]
Long term solution will be provided by #4699 
Intermediate solution will be to transform column using substr
