### ISSUE TITLE
Authentication Integrations with WebUI

### ISSUE THREAD

**Issue by theis188** [treeverse/lakeFS#4702]
I've looked at the Auth pages for the LakeFS API, and it looks very helpful, including OIDC, LDAP, user/pass, etc. I'm also wondering about the WebUI, I'm running the demo locally and it seems login is by user/pass. Is there any support or plan to support OIDC or other delegated auth within the UI webserver? Thank you for your attention, and sorry if I missed something in the docs that addresses this.

**Comment by nopcoder** [comment]
@theis188 you can check docs for how to configure you lakeFS to use OIDC and enable you to login though the UI with your provider - https://docs.lakefs.io/reference/authentication.html#oidc-support

**Comment by theis188** [comment]
Thanks!
