### ISSUE TITLE
LakeFS and Delta symlink manifests

### ISSUE THREAD

**Issue by mng1dev** [treeverse/lakeFS#4753]
Hi,

I am trying to expose some Delta tables through Athena while using LakeFS.

LakeFS uses its own virtual file system, and the only way to expose informations "outside" is to use the `create-symlink` command. This way, each file inside each folder/partition is listed in this symlink file and users can create a table in Athena, as shown [here](https://docs.lakefs.io/integrations/athena.html).

Folders containing Delta tables contain the `_delta_log` folder, which should not be considered as part of the table data, and 
parquet files belonging to separate versions of the delta table. The LakeFS symlink exposes all of them leading to duplicated data.

Delta offers a way to [generate](https://docs.databricks.com/delta/generate-manifest.html) a symlink manifest containing the parquet files associated with the latest table version, which is also how they suggest to [integrate with Athena](https://docs.delta.io/latest/presto-integration.html#set-up-the-presto-trino-or-athena-to-delta-lake-integration-and-query-delta-tables), but even these manifests are only accessible through the lakefs virtual filesystem and don't match 'physical' S3 paths.

This could be a blocker in case Delta tables need to be accessed not only from Spark/Databricks, but also by external tools such as Athena or Snowflake.

**Comment by talSofer** [comment]
Hi @zevektor, thanks for opening this issue! 

The lakeFS-Athena integration is indeed not yet supporting open table formats. But, these days, we are [focusing an effort](https://docs.lakefs.io/roadmap.html#table-format-support) on defining and building advanced support in open table formats. We would love to hear more about how you integrate Athena with delta lake, how frequently you use that integration, and more details about your use case if you are willing to share!
