### ISSUE TITLE
GC: add tests to validate that imported data is not GCed 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4757]
Our code covers the case of imported data, and GC is designed not to collect it. However we would like to add a test that enforces that.

**Comment by arielshaqed** [comment]
Multiple ways to import data:

* S3 inventory-based.  #4876  wants to deprecate and eventually remove it -- but we still need to handle it safely!  This is "Large-Scale Imports (lakeFS inventory imports)" in [3 Ways to Add Data to LakeFS][import-blog].
* Data ingested with `lakectl ingest`.  This is "Copy Data Without Copying Data (lakectl ingest)" in [3 Ways to Add Data to LakeFS][import-blog], and also in the [reference manual][import-refman].
* GUI import, documented in the [reference manual][import-refman].

Also users can "just" randomly stage external objects.

## What do we collect?

What all these methods share is that _external objects cannot be inside the storage namespace of a repository_.  To cover all options with white-box testing, we need to test:

1. Objects with relative physical addresses _can be_ collected.
1. Objects with absolute physical addresses that have the storage namespace of the repository as their prefix _can be_ collected.  (These might be created by lakeFSFS!)
2. Objects with absolute physical addresses  that **do not** have the storage namespace of the repository as their prefix _are never_ collected.

[import-blog]: https://lakefs.io/blog/3-ways-to-add-data-to-lakefs/
[import-refman]: https://docs.lakefs.io/howto/import.html#using-the-lakectl-import-command
