### ISSUE TITLE
document the difference between our diff output vs git

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#477]

**Comment by stylesm** [comment]
Hi @nopcoder I'd like to pick this up for Hacktoberfest if possible please?

**Comment by YaelRiv** [comment]
Sure @stylesm! I have assigned you with the issue. Please reach out to us on Slack if you have any questions:
https://join.slack.com/t/lakefs/shared_invite/zt-g86mkroy-186GzaxR4xOar1i1Us0bzw

Thanks for your help!
