### ISSUE TITLE
GC backup and restore is broken since the changes to repository structure

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#4775]
Following the documentation [guide](https://docs.lakefs.io/howto/garbage-collection.html#gc-backup-and-restore)
failed to perform backup and restore with the following observations:

Currently B&R relies on a flat filesystem structure.
It reads the files list and uses the full path to access them but when saving the file it uses only the object name and saves it under the root of the designated backup path.
As an example the file:
`data/gqufd5d4fd2tgs1a98s0/ce90pbd4fd2tgs1a9900` in namespace `niro-test/gc-backup-and-restore`
is saved under `s3://niro-test/_gc-backup-restore/<user-input-provided-path>/ce90pbd4fd2tgs1a9900`

When trying to restore - we are using the same manifest which looks for the full object path - but since in the backup location the file is in the root, it fails to find it and nothing is restored.
Also, I would have expected the restore operation to copy the files to their original location on the repository namespace and not to a designated backup folder created under the namespace

In addition - it seems the the restore operation unjustifiably is spamming the repository namespace with logs which I believe should be created in the original backup folder.

**Comment by N-o-Z** [comment]
Summary of list of issues:
1. Backup and restore only considers object name and not the full path of the object - broken since https://github.com/treeverse/lakeFS/issues/4481
2. Using hadoop distCp, the copy fails on paths that contain ':' in string (same as: https://github.com/treeverse/lakeFS/issues/4766)
3. B&R creates logs and temp files on source path (repo namespace) when running restore (these files are not managed by lakefs and are in fact garbage created by the process)
4. Missing unit and integration tests

**Comment by N-o-Z** [comment]
I think @johnnyaug already fixed that?

**Comment by ozkatz** [comment]
@johnnyaug ?

**Comment by N-o-Z** [comment]
@johnnyaug can we close this?
