### ISSUE TITLE
Discovery: GC committed for MinIO

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4795]
Try out CGC with MinIO and estimate the effort of implementing it.

**Comment by arielshaqed** [comment]
Trying it out manually, it seems like anything below our Hadoop 3 Spark
assemblies will not work with MinIO.  MinIO requires me to force path style,
S3A only supports that starting Hadoop 2.8.x, and we use 2.7.7.

Going for Hadoop 3 now.

**Comment by arielshaqed** [comment]
Opened #4885 to document this.  It is somewhat tricky.
