### ISSUE TITLE
Graveler's Set IfAbsent during commit can return incorrect response

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#4796]
The issue occurs while we perform `Set` IfAbsent while `Commit` in progress.
Current implementation "retry" the operation in case of a change in the staging token (like after commit).
In this case we need to verify that the object does not exists in the latest commit.
But if a commit runs during our 'set' it means that the committed data is caused by our operation.

Scenario thanks to @arielshaqed!

**Thread A:**
Get staging token, enter setFunc, see that object does not exist, [update its value](https://github.com/treeverse/lakeFS/blob/89f8c4086afa97afbdc10d1b41cc9913c3e5008a/pkg/graveler/graveler.go#L1417), return successfully, block before reloading the staging token.

**Thread B:**
Commit successfully, object now exists on committed.

**Thread A:**
Reload staging token, see that it's changed, try again.  Enter setFunc again, find that the object on the branch (d'oh!), [return ErrPreconditionFailed](https://github.com/treeverse/lakeFS/blob/89f8c4086afa97afbdc10d1b41cc9913c3e5008a/pkg/graveler/graveler.go#L1407).

**Result:** Object did not exist, we set it, and claimed that it already existed before.

**Comment by arielshaqed** [comment]
Uncovered while working on #4770, and possibly relevant for #4722.  But neither solves or even _helps_ with this one1
