### ISSUE TITLE
Graveler's Delete race condition on branch retry can return invalid response

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#4798]
The issue is with returning 204 or 404 on DeleteObject.
The API requires us to return 204 when deleting an object, if that object exists.
A race between thread A that is deleting an object in staging and thread B that is committing. 

Scenario:

**Thread A:** Get staging token, find object it staging.
Succeed and pause right before checking whether the staging token has changed.

**Thread B:** Commit, clean staging.  Object is now deleted because the tombstone was set in staging.

**Thread A:** See that the staging token has changed, go again.  Get the staging token, find nothing in staging, find nothing in committed, return ErrNotFound - error code (404) to the caller.

**Result:** API returns 404 for a DeleteObject call when the object existed and was successfully deleted by the same call.

**Comment by arielshaqed** [comment]
#4770 is an otherwise-safe change that extends the time for losing the race.  As a result, it (almost) always loses the race and various TestDelete* tests in Esti fail.  This is **GOOD NEWS**: you can use that branch to make the race happen.  I recommend developing on top of that branch. :-)

**Comment by itaiad200** [comment]
Quick (and dirty) solution - don't retry deletes when the staging token changes.

**Comment by arielshaqed** [comment]
> Quick (and dirty) solution - don't retry deletes when the staging token changes.

This "works but...": it means that I cannot write code that depends on the return value from deleteObject for synchronization.  If I delete concurrently while committing, I cannot rely on the return value.  What do I do when I get a status code that says I was deleting concurrently with a commit?  I don't know whether I deleted it, or some other worker deleted it, or it was not deleted.

I believe that we should not provide the return value if it cannot be used for synchronization.  This is exactly what happens in S3.
