### ISSUE TITLE
Get commits, without parents error with py client 

### ISSUE THREAD

**Issue by obonyojimmy** [treeverse/lakeFS#4829]
Calling get-commits , throws when parents field is missing , which is ok for the initial commit-ids ie the commit-id of the initial branch creation. 
```
lakefs_client.exceptions.ApiTypeError: Invalid type for variable 'parents'. Required value type is list and passed type was NoneType at ['received_data']['parents']`
```

**Comment by nopcoder** [comment]
@obonyojimmy couple of questions to have more information about the error:
- Are you calling `get_commit` from the CommitsApi?
- Can you specify the python SDK version and the lakeFS versions you are using?

**Comment by kalebda** [comment]
Having same issue opened above:
answers to question:
- yes
- python SDK version: 3.8 lakefs V0.1.0
