### ISSUE TITLE
Deprecate s3-inventory-based import

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#4876]
Currently there are multiple ways to import data into lakeFS. The oldest of which (and also the most complicated) is the s3 inventory based import. 

Given we currently have more approachable ways of import data into lakeFS, I suggest deprecating and eventually removing the s3 inventory based import (docs, lakefs cmd and accompanying parts of the codebase)

**Comment by itaiad200** [comment]
@ozkatz Where do we still have it. I think I've did this some months ago, please reopen and link to any leftovers.
