### ISSUE TITLE
RocksDB-Cloud

### ISSUE THREAD

**Issue by splitice** [treeverse/lakeFS#4882]
Has anyone considered an adapter to RocksDB-Cloud ?

In theory lakefs could be entirely backed by S3 compatible data storage (and hence incredibly easy to deploy)

**Comment by talSofer** [comment]
Thanks for opening this issue @splitice! This is a cool idea, we haven't considered it, but we may in the future. Would you prefer using RocksDB cloud over DynamoDB (deployment-wise)? please do share more thoughts if you'd like :)

**Comment by splitice** [comment]
@talSofer we would certainly prefer storage to cheap low cost object storage over the introduction of a vendor specific managed service (DynamoDB).
