### ISSUE TITLE
Allow using a custom S3 endpoint as lakeFS' block storage

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#492]
In the `block` package of the lakeFS app, we currently allow connecting only to AWS S3. To be able to use other S3-compatible storage engines, e.g. Minio, allow specifying a custom endpoint through the lakeFS configuration.

**Comment by nopcoder** [comment]
under 'blockstore.s3' adding the following will allow connection to MinIO

`yaml
endpoint: http://s3.local.lakefs.io:9000
force_path_style: true
`
