### ISSUE TITLE
Define current supported underlaying storage with requirements to work with lakeFS

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#4932]
Document the underlying storage we support and related capabilities.

Each cloud provider support for each storage different properties:
- Different types/versions (ex: Azure Data Lake Storage Gen2)
- Different encryption mechanism
- Different capabilities that can effect the work of our GC - HadoopFS list order

We should define the capabilities we use and/or the current one we support, at least prevent users use configuration we currently do not support.

**Comment by N-o-Z** [comment]
Note that move to ADLS Gen2 is a one way street:
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace
> After you've enabled a hierarchical namespace on your account, you can't revert it back to a flat namespace. Therefore, consider whether it makes sense to enable a hierarchical namespace based on the nature of your object store workloads.

**Comment by N-o-Z** [comment]
For HNS when listing we basically get the same lexicographical order - only that in addition we get a zero size blob for each "directory"
ref: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list#use-a-flat-listing

> If you've enabled the hierarchical namespace feature on your account, directories are not virtual. Instead, they are concrete, independent objects. Therefore, directories appear in the list as zero-length blobs.

**Comment by N-o-Z** [comment]
Azure part done in https://github.com/treeverse/lakeFS/pull/5111
