### ISSUE TITLE
Raise validation error when trying to create a repository with incompatible storage type

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#494]
lakeFS can be started with different storage types.

This is configured using the `blockstore.type` configuration (currently supported are s3, local, mem and transient).

When creating a repository, a *storage namespace* is specified. This determines where the data will be stored. The storage namespace should be compatible with the selected blockstore type.

For example "s3://my-bucket/" is a valid storage namespace for blockstore type "s3", but invalid for all other blockstore types. Similarly, "local:///home/user/dir/" is valid only for "local" blockstore type.

Need to add a validation for this rule when creating a repository.

**Comment by avats-dev** [comment]
Hi @johnnyaug , I would like to work on this. Can you guide me how to implement this as I'm new to this codebase. Thanks:tada:

**Comment by iamRishabh07** [comment]
Hi, @johnnyaug  I would like to work on this issue

**Comment by johnnyaug** [comment]
Hi both, welcome and thank you for joining us!
Since @avats-dev was first, we'll give him the priority :slightly_smiling_face: 
@avats-dev, contact me on Slack for guidance.

@iamRishabh07, we are constantly adding issues with the `good-first-issue` label, be sure to check them out

**Comment by avats-dev** [comment]
@johnnyaug I couldn't recognise you on slack, I'm there as avats. Thanks for assigning this to me.

**Comment by johnnyaug** [comment]
@avats-dev, still here?

**Comment by arielshaqed** [comment]
@avats-dev it's been 2 months, I'd like to reassign this issue.

@Sufiyan1997 somehow I cannot assign this issue to you, will keep trying.
