### ISSUE TITLE
fix hadoopfs close twice - linking the same physical address

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#4946]
pr #4900 disable the ability to link to the same physical address twice.
when closing the hadoopfs we also link to the physical address.
hadoopfs requires closing twice to return the same result.

**Comment by talSofer** [comment]
Hi @eden-ohana! 
> hadoopfs requires closing twice to return the same result.

Can you please clarify what you mean in the sentence above? 
Also, what is the planned fix? What is the timeline for it? do you plan first to close this issue (#4946) and then close #4900? I'm trying to understand the impact of the change in #4900.

**Comment by eden-ohana** [comment]
Hi, the fix is in #4944 to merge to #4490.
Hadoopfs requires subsequent calls to close() have no effect, Hadoopfs write files and when it finishes it closes, as part of the close function it uses the lakeFS API to link the physical address.
because closing twice suppose to have no effect also linking the same physical address should have no effect (We have a test for it).
In #4490 I blocked the option to link the same physical address twice (for the uncommitted GC) so I needed to do the fix for Hadoopfs.

**Comment by talSofer** [comment]
Thanks! @arielshaqed do you see any potential issue with https://github.com/treeverse/lakeFS/pull/4944?

**Comment by arielshaqed** [comment]
> Thanks! @arielshaqed do you see any potential issue with #4944?

I think we need more context about the requirement here.  In particular, the fix works for _some_ failing cases but not for _all_ of them.  See comments on #4944.

**Comment by itaiad200** [comment]
@eden-ohana can we close this?
