### ISSUE TITLE
Discover when and how to shed load

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4957]
lakeFS has a [cascading failure](https://en.wikipedia.org/wiki/Cascading_failure) mode that causes catastrophic failure of the server under load.  I have observed this in testing, and I suspect that we have also seen it in production.  The "catastrophe" here is the loss of the lakeFS server processes, and the system cannot recover until load is removed.

We should discover how to:

* Detect the failure condition.
* Handle the detected failure.

## Description

lakeFS performance depends on KV performance.  Some lakeFS operations require _multiple_ successful KV operations on a shared key in order to succeed.  These include any mutating operation on staging:

* Upload (or link) object
* Commit
* Merge

lakeFS currently has no admission control for requests: any arriving request can be processed.  In order to finish processing, lakeFS has to modify the staging token.  Any failure leads to a retry, that can take a while even if it does not expend further KV actions.  When lakeFS is out of operational capacity on its KV it does not prioritize finishing old requests over starting new ones.  So:

* lakeFS is out of capacity on KV and is slowed down

  This might be an explicit "slow down" instruction, or it might be simply   slower operations.  It does not particularly matter.
* KV operations for old requests are _retried_.
* Retrying **increases** the load on KV.

As a bonus (or rather a malus):
* More requests might continue to arrive.
* These requests are also stuck processing.
* Memory fills up holding partially-processed requests.

## Scope

Do this on lakeFS, or figure out if we can do it on an LB in front of lakeFS.

**Comment by arielshaqed** [comment]
If no commits or merges occur during the period, we're still in some trouble: every object creation involves touching the branch key twice.

One popular KV -- DynamoDB -- throttles by returning an error, so we _still_ hit a backoff as soon as it wants us to cut back.  The metric for throttling is global, across all lakeFS instances -- so adding more instances does nothing to fix this, in fact it probably makes it somewhat worse.

**Comment by itaiad200** [comment]
One idea I had to significantly reduce the RCUs (DynamoDB measurement for read capacity) is to batch GetItem requests with [Query](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html). Unlike GetItem, or even BatchGetItems, the RCUs for Query is calculated on the total size of objects. Assuming lakeFS staging entries are roughly 200B in size, reading 20 using Query costs 1RCU (20 * 200B = 4KB), instead of 20RCU when using GetItem.

**Comment by arielshaqed** [comment]
> One idea I had to significantly reduce the RCUs (DynamoDB measurement for read capacity) is to batch GetItem requests with [Query](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html). Unlike GetItem, or even BatchGetItems, the RCUs for Query is calculated on the total size of objects. Assuming lakeFS staging entries are roughly 200B in size, reading 20 using Query costs 1RCU (20 * 200B = 4KB), instead of 20RCU when using GetItem.

**Good idea**, this can be a great speedup.  We should definitely try to achieve it -- regardless of whether we shed load or not.  I think we should make this into a separate issue: it's a speedup, whereas this is more about letting the lakeFS system continue to make progress under load.  If we manage to do this one then lakeFS progresses under load, so we can add retries (#5664) and things will continue to work only slower.  If we manage to do yours then lakeFS progresses faster _when_ it can make progress, so it can be more loaded before it stops making progress.  We need to do both :-)

**Comment by itaiad200** [comment]
We believe most of the bottlenecks are network related and that the S3GW redirect should resolve most of them: https://github.com/treeverse/lakeFS/pull/7630
