### ISSUE TITLE
GC: fix and enable Spark 3 + hadoop 2 integration tests

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4983]
In https://github.com/treeverse/lakeFS/pull/4933 we've added an integration test to validate the combination of a Spark 3 runtime with hadoop 2. this test is allowed to fail without blocking the option to merge. 

While we expected https://github.com/treeverse/lakeFS/pull/4920 to make the test pass it didn't although testing https://github.com/treeverse/lakeFS/pull/4920 on a manual setup of Spark 2.4.7 and hadoop 2.7.7 worked. 

We think that the reason for the test failure is that the docker image we build for it is using hadoop 2.4.7 rather than hadoop 2.7.7.
```
23/01/09 14:04:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.2.3
      /_/

Using Python version 3.8.16 (default, Dec  6 2022 22:22:04)
Spark context Web UI available at http://012c9f77b150:4040/
Spark context available as 'sc' (master = local[*], app id = local-1673273053775).
SparkSession available as 'spark'.
>>> sc._gateway.jvm.org.apache.hadoop.util.VersionInfo.getVersion()
'2.7.4'
```

This issue is to make the test pass, first by investigating how we can customize the image so that spark will use hadoop 2.7.7. 
see https://github.com/bitnami/bitnami-docker-spark#using-a-different-version-of-hadoop-jars for a reference

**Comment by arielshaqed** [comment]
## Directions

There is no Bitnami Spark image to run Spark (3 or even 2) with Hadoop 2.  So we created our own according to the above Bitnami instructions, and use that to build an image.

These lines [extract an ancient Hadoop version](https://github.com/treeverse/lakeFS/blob/b81e5ad50bdc7d02a1d82494ea2330c5552167fe/deployments/utils/spark3-hadoop2/Dockerfile#L20-L22).  We can/should change them to fetch 2.7.7.

To see if it works you need to push a new image that [Esti will fetch](https://github.com/treeverse/lakeFS/blob/b81e5ad50bdc7d02a1d82494ea2330c5552167fe/.github/workflows/esti.yaml#L925-L926).  So e.g.
```sh
docker build -t treeverse/bitnami-based-spark:3.2.3-with-hadoop-2.7-for-testing && \
docker push treeverse/bitnami-based-spark:3.2.3-with-hadoop-2.7-for-testing
```
You probably don't have a cookie for pushing to treeverse like this.  To speed things up you might push to some private Dockerhub repo, e.g. I used ariels9/bitnami-based-spark:3.2.3-with-hadoop-2.7-for-testing which is a repo that I control.  Once you're ready to push to the treeverse/ org, we can look for someone to give us cookies for a single push.

**Comment by talSofer** [comment]
Closing as we are not planning to do it given https://github.com/treeverse/lakeFS/issues/5107
