### ISSUE TITLE
Align config name "access_secret_key" to "secret_access_key"

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#501]
Currently, the AWS secret key is given under the key `blockstore.s3.credentials.access_secret_key` in the lakeFS configuration file.

However, in other places (for example, when logging in from the UI) this configuration is called "secret_access_key". This one is also the convention in the AWS ecosystem.

Align all `access_secret_key` appearances in our code base to `secret_access_key`.

**Comment by aaronmbos** [comment]
Hey 👋 open source newbie here! I'd like to pick this issue up for the upcoming Hacktoberfest as it seems relatively straightforward. I'll follow all the instructions in the contribution guide and reach out on the Slack channel for any questions.

**Comment by YaelRiv** [comment]
Hello Aaron! 

It's yours. Thanks for giving us a hand 💪
See you on the Slack channel. 

Yael

**Comment by iamRishabh07** [comment]
Hi, I would like to work on this issue.

**Comment by YaelRiv** [comment]
@iamRishabh07 Thanks for your offer! This is already assigned.
