### ISSUE TITLE
When creating repo from the UI, give some hint as to how the storage namespace should look like

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#502]
Also fix the documentation, where the storage namespace appears without the "s3://" prefix:
![image](https://user-images.githubusercontent.com/3149885/90635286-a94ea580-e231-11ea-9061-4c141b778c13.png)

**Comment by shamikakumar** [comment]
Hey I would like to tackle this issue for the upcoming hacktoberfest. Do assign this to me, thanks!

**Comment by YaelRiv** [comment]
Hey @shamikakumar! 

Thanks for offering your help with this one. Assigned to you - we are here to help if you have any questions:
https://join.slack.com/t/lakefs/shared_invite/zt-g86mkroy-186GzaxR4xOar1i1Us0bzw

Happy Hacktoberfest!
Yael

**Comment by shamikakumar** [comment]
Hey I see there's a placeholder for storage-namespace. How should the hint be displayed. Do I add an info button next to the input box ?

**Comment by arielshaqed** [comment]
> Hey I see there's a placeholder for storage-namespace. How should the hint be displayed. Do I add an info button next to the input box ? or do i make it a tootip ?

Can we start with a [`placeholder`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#placeholder) on the input field, and see how users feel about that?

**Comment by shamikakumar** [comment]
@arielshaqed I see that's already been implemented, and the docs are fixed too. Is it possible this issue was not closed after the fix ? would you like me to make any other change here ?
<img width="778" alt="Screenshot 2020-09-27 at 11 13 15 PM" src="https://user-images.githubusercontent.com/26432407/94665805-3fdeae00-032a-11eb-8068-97d3a0061f6d.png">

**Comment by johnnyaug** [comment]
Hi @shamikakumar, you are right. This issue is not up-to-date and I should have described better what I meant when I opened it. Thank you for pointing it out.

Since lakeFS can operate with various backing storage services, the hint should be suitable to the current storage type. For example, when running with Google as the storage service, the hint should be "gs://example-bucket/". I will update the issue to reflect that.

In any case, since our client is currently not aware of the storage type, this issue could be a bit challenging for now, and that's the reason it is not marked as a "good-first-issue". You're welcome to try it anyway and I'll be here to help. Otherwise, we are in the process of creating some more good-first-issues.

**Comment by johnnyaug** [comment]
Actually, I think it would be better to create a separate issue, since as you mentioned this one has actually been solved. I will link the two issues so that you can access it from here.
