### ISSUE TITLE
[Bug]: lakeFS client in Lua raises invalid API endpoint"

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#5076]
### What happened?

Current Behavior:
What actually happened, including error codes if applies.
        
Steps to Reproduce:
1.
2.
3.

### Expected Behavior

Expected Behavior:
How you expected thing to work.

**Comment by nopcoder** [comment]
@ozkatz can you shed more light about this one? when is this error occurs? steps, is it reproducible?

**Comment by ozkatz** [comment]
Pretty sure this is no longer relevant. Closing for now.
