### ISSUE TITLE
Discovery: tests the feasibility to connect databricks unity with lakeFS

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#5106]
This task is time-boxed in 1 week. 
So far, we didn't get a databricks Unity setup to experiment in. However, based on theoretical research, we estimate that in its current shape, we can't connect Unity with lakeFS. This take is to get a setup and try it out and see if we really can't do it. 

DOD: 
* In case the experiment succeeded - document the setup. 
* In case the experiment failed - write thoughts of what are the gaps and if there are ideas for solutions.

**Comment by itaiad200** [comment]
@arielshaqed Is this a dup?

**Comment by itaiad200** [comment]
Done.
