### ISSUE TITLE
Understanding basic differences between using lakeFS and Git

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#5138]
Sometimes users first interacting with lakeFS can't clearly understand the differences between working locally against a git repository and using lakeFS to work in isolation against the data, without copying it locally. 
Better documentation would help.

**Comment by rmoff** [comment]
See also https://github.com/treeverse/lakeFS/issues/5812

**Comment by talSofer** [comment]
Created a [task](https://trello.com/c/5lVoRegk) in the product team backlog for this item. The documentation should go to the new [Git integration docs page](https://docs.lakefs.io/integrations/git.html)
