### ISSUE TITLE
[Bug]: lakectl direct upload fails

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#5155]
### What happened?

Current Behavior:
lakectl direct upload fails. Indirect uploads (without the `-d` option works).

./lakectl fs upload -s file.txt lakefs://repo1/main/aaa/bbb/ccc/1 -d

upload to backing store: ExpiredToken: The provided token has expired.
	status code: 400, request id: GWVR9ZK1TRAHR6MK, host id: BkMTj8yfBC3uVIL4DwN6zMfGCGuvj4Q3C7e7D91CMRQIWhznCv4vCWayJaJxagE0lNeeNJDOJek=        

### lakeFS Version

master version of both lakectl and lakeFS

### Deplyoment

S3 object store

**Comment by N-o-Z** [comment]
@itaiad200 tried to reproduced with latest master:

```
± % ./lakectl -c ~/.lakectl-test.yaml fs upload -s test.go lakefs://repo1/main/aaa/bbb/ccc/1 -d                                           !10038
Path: aaa/bbb/ccc/1
Modified Time: 2023-02-01 06:43:19 +0200 IST
Size: 3384 bytes
Human Size: 3.4 kB
Physical Address: data/gpqhcqt4fd2gfakfm93g/cfcurpl4fd2gfakfm94g
Checksum: "2c149455687ef20a64065f5c77c80779"
Content-Type: application/octet-stream

```

Can you think of anything with your scenario that was exceptional?

**Comment by N-o-Z** [comment]
Looking into the error message - it seems like the error is generated from the aws sdk client and not lakeFS:
service/s3/api.go:18187
```
...
	//
	//    * Code: ExpiredToken Description: The provided token has expired. HTTP
	//    Status Code: 400 Bad Request SOAP Fault Code Prefix: Client
	//
	//    * Code: IllegalVersioningConfigurationException Description: Indicates
	//    that the versioning configuration specified in the request is invalid.
	//    HTTP Status Code: 400 Bad Request SOAP Fault Code Prefix: Client
...
```
@itaiad200  Your AWS credentials expired on that env. maybe?

**Comment by itaiad200** [comment]
@N-o-Z absolutely right, my bad.
