### ISSUE TITLE
api_client.branches.delete_branch(REPO, branch) hangs and sometimes returns 404

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#5215]
This happens when running many (1000s) delete branches in a repository.

**Comment by Jonathan-Rosenberg** [comment]
@iddoavn is this the python client?

**Comment by itaiad200** [comment]
Yes @Jonathan-Rosenberg, this happened on `v0.89.1`. I think we have solved it since then with https://github.com/treeverse/lakeFS/pull/5133 that was already released. So closing and we may open if it reoccurs.
