### ISSUE TITLE
UI: Post setup credentials page shows secret on 2 lines

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#5217]
Created on a 27' screen - the secret access key string is wrapped even though there's plenty of room

![image](https://user-images.githubusercontent.com/3787958/218302998-216aa9cc-7e4d-4ef8-849b-795cbedbf0f1.png)

**Comment by rmoff** [comment]
I see this wrapping on the latest version - is it a regression? 
<img width="913" alt="CleanShot_2023-05-05_at_12 43 04@2x" src="https://user-images.githubusercontent.com/3671582/236448958-1bb515fc-112c-4676-b377-aaabfe211c45.png">

**Comment by N-o-Z** [comment]
@rmoff This does look like regression - Can you open an issue on this please?
