### ISSUE TITLE
Bug lakectl blame hangs without output for long time

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#5224]

**Comment by itaiad200** [comment]
Tried to repro it locally. The setup:
1. 10k commits.
2. The objects I was looking for (e.g. the one I requested `blame` for) was at the first commit.
3. Every `range` retrieval was exactly 100msec to simulate object store latencies.

It took 67-70 seconds to return the correct answer. It brought 8.5k objects from the object store (some ranges were cached). Given the total amount of work lower bound (8.5k * 100msec = 14.2 min) compared to the actual time, it's safe to say that parallelism work as expected.

I'm assuming that the issue occurred in a repo with hundred of thousands of commits, where the blamed file was not recently changed. 

If we want to support an efficient search for blaming a repo of that scale, we need to come up with a non object-store information to retrieve the needed info.

Search algorithms are not applicable for this search task, as changes in commits are not linearly increasing.
