### ISSUE TITLE
Cache local copies of range and metaranges in Spark metadata client

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#5242]
If the same ranges and/or metaranges are repeatedly reopened by the Spark metadata client, they are copied each time from S3.  **Reusing a range is a performance bug and should never happen!**  But that doesn't mean that it doesn't.

* At a minimum, retain IDs of all ranges and metaranges opened, count how many times each is opened, and report numbers >1.
* Preferably, e.g. if we see >1% of ranges re-opened and it's not an obvious bug, keep a cache of the local copies on disk.  This can probably save ~25ms on each such access.

Probably more relevant following #5241, which filled up storage.

**Comment by johnnyaug** [comment]
Related: the implementation will look different if #2403 is implemented.
