### ISSUE TITLE
Map gaps and limitations for local block adapter to serve production traffic

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#5246]

**Comment by arielshaqed** [comment]
* To run a cluster, the backing store will need to be a NAS or similar.  Do we intend to support that?
* Not sure we can ever provide reasonable performance to users on local block adapter.
* In particular, GC will be "fun".

**Comment by itaiad200** [comment]
> * To run a cluster, the backing store will need to be a NAS or similar.  Do we intend to support that?

Yes - in the form of users are responsible for the management of their volumes. lakeFS will use the local storage without maintaining it.

> * Not sure we can ever provide reasonable performance to users on local block adapter.

Can you please share your concerns? The only argument I heard so far is listing performance. AFAIU we only ever list the object-store during imports and that can be documented as a known limitation. 

> * In particular, GC will be "fun".

Yap, not supported for now.
