### ISSUE TITLE
UI: Commit with empty message looks skewed

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#5250]
Commit message is used as a headline for the commit element and is also an href to the commit information.
When creating a commit with empty message it is a little skewed and looks confusing

![image](https://user-images.githubusercontent.com/3787958/219081463-20c8e1dc-773a-475c-8de9-f3fe0bc288f2.png)

**Comment by eladlachmi** [comment]
@N-o-Z I believe an empty `<a>` doesn't render at all in modern browsers. Two simple options I can think of are either to hold its place with no content or use something like `"<empty>"` to make it more obvious and less broken looking.  
WDYT?

**Comment by N-o-Z** [comment]
The `"<empty>"` option sounds better in my opinion
