### ISSUE TITLE
Misleading error when trying to list commits for nonexistent repository

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#528]
When running `lakectl log` on a nonexistent repository, a misleading message appears.

Example:
`lakectl log lakefs://notarepo@master`

Output:
`Error executing command: branch 'master' not found`

Expected:
`Error executing command: repo 'notarepo' not found`

**Comment by kzuri** [comment]
Hey @guy-har , I would like to work on this :)

**Comment by YaelRiv** [comment]
@kzuri All yours :)

**Comment by sarathsp06** [comment]
Is anyone working on this?

**Comment by guy-har** [comment]
@kzuri  do you want to proceed with this, or would you prefer that I re-assign to @sarathsp06

**Comment by kzuri** [comment]
@guy-har Sorry for inconvenience. My laptop is at repair shop so couldn't work on this issue. Ya sure go ahead and reassign @sarathsp06 on this issue

**Comment by Sufiyan1997** [comment]
If nobody is working on it, then you can assign it to me

**Comment by guy-har** [comment]
@sarathsp06 do you want me to assign it to you? or should I assign it to @Sufiyan1997 ?

**Comment by sarathsp06** [comment]
@guy-har I can work on this

**Comment by guy-har** [comment]
@sarathsp06 all yours, let me know if you need any help.

**Comment by sarathsp06** [comment]
@guy-har  had a brief look at the code, there are multiple options 

- log "executing command: 'repo/branch' not found" ( least code change )
- log "executing command: repo 'repo-name' not found" ( code change and mostly one more db/cache  read  request just for log info)

-- what would you suggest

**Comment by sarathsp06** [comment]
@sarathsp06 made a PR with the second option above please do have a look. I am not familiar with the design philosophies of the repo thus offered two approaches

**Comment by guy-har** [comment]
@sarathsp06 sounds great, I would have suggested the second option.
I will check it out soon.
Thanks for contributing 💪 .
