### ISSUE TITLE
Test import system test with different file sizes

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#5286]
When we verifying that objects have their correct length, we should use size power of 2 or a multiple of 8.
Some bugs are found when reading blocks are to read the wrong length if the length is not a multiple of 8 (prefer a length like 1357 or similar)

**Comment by Jonathan-Rosenberg** [comment]
@nopcoder is this closed?

**Comment by nopcoder** [comment]
no, it is something we would like to improve.
