### ISSUE TITLE
[Bug]: Setup UI doesn't enforce non-blank admin username, throws scary error to the user.

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5290]
### What happened?

Current Behavior:
What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Open http://localhost:8000/
2. Enter an email address and click `next`
3. On the `Initial setup` screen leave the admin username blank and click `Setup`

The UI throws an error: `Unknown: Error: Unknown at YG.lakeFS (http://localhost:8000/assets/index-6dd372f1.js:67:25600) at async http://localhost:8000/assets/index-6dd372f1.js:719:5730`

![CleanShot 2023-02-20 at 16 21 43](https://user-images.githubusercontent.com/3671582/220157687-25da68b9-b010-4cb3-af58-5ee9d042d11b.png)

### Expected Behavior

Expected Behavior:

There should be no scary error and instead some input validation that forces the user to enter a value before submitting the form

### lakeFS Version

0.93.0

### Deplyoment

Docker

**Comment by rmoff** [comment]
n.b. this will be less likely to happen if https://github.com/treeverse/lakeFS/pull/5289 is merged as the username is given a default as part of that change.

**Comment by Jonathan-Rosenberg** [comment]
hi @rmoff, can you confirm that this issue has been resolved after the #5289 merge?

**Comment by rmoff** [comment]
@Jonathan-Rosenberg it's still possible if the user deletes the default `admin` username and submits it; I guess the question is (1) is that very likely to make it worth the time to fix and (2) if so, is it fixed by handling the error nicer or enforcing validation prior to form submission  ?
