### ISSUE TITLE
Add additional label for prometheus metrics

### ISSUE THREAD

**Issue by tvanderwal-lmco** [treeverse/lakeFS#5295]
Would it be possible to add the repository name to the prometheus metrics or have additional metrics for repo interaction? We're looking to start tracking usage at the repository level and currently the only way would be to separately store and parse the application logs.

**Comment by itaiad200** [comment]
Hi @tvanderwal-lmco , I think it's a valuable addition. 2 small concerns that shouldn't block this:
1. We hear users who are struggling with the cardinality of the metrics. lakeFS doesn't limit the amount of repos in it, so adding another label with unbounded amount of values can be tricky to manage. Users can solve this by dropping this label in the scrape config.
2. I think that would be the first time in lakeFS where prometheus collects user inserted data. Imagine a user which doesn't have access to list all the repos but have access to the metrics. We can hash the values to reduce some of the concern, but not all of it (number of repos for example)
