### ISSUE TITLE
Support additional block adapters in unit tests

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#5325]
Add the following block adapters to the unit test infrastructure:
* ~~S3~~
* ~~GCS~~
* Mem

**Comment by nopcoder** [comment]
@N-o-Z  can close this one? as far as I remember you added this capability.

**Comment by N-o-Z** [comment]
Added the unit tests, but we didn't add these block adapters

**Comment by N-o-Z** [comment]
Missing mem adapted unit tests
