### ISSUE TITLE
[DX] Object page - UI suggestions

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5360]
1. ~Don't wrap the object path unless it really has to~ fixed in #5274 
2. Right-align the DuckDB note, so that the user's eye scanning down goes logically from the SQL to the `Execute` button uninterrupted
3. Add SQL syntax highlighting 

![image](https://user-images.githubusercontent.com/3671582/221843844-8fbcc99a-d2be-45b4-aafb-27caba8bbbb8.png)

**Comment by rmoff** [comment]
4. Make it clear that `Utf8` is not part of the column name (does it even need to be displayed?) 
![289c1ecc63a85706a1d7b1e87445b4d5cd345f2a6f230d00d0a0a5c772288864](https://user-images.githubusercontent.com/3671582/221845592-694ad26e-a065-4e5e-8e5f-99d4ddaba8e5.png)
5. Cmd-Enter in the SQL box should fire the `Execute` button

**Comment by rmoff** [comment]
@ozkatz IIUC https://github.com/treeverse/lakeFS/pull/5274 solves point 1 on this list, right?

**Comment by ozkatz** [comment]
indeed
