### ISSUE TITLE
[Bug]: StageObject API for local block adapter doesn't check if local import is enabled

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#5361]
### What happened?

Current Behavior:
I was able to import a single object to lakeFS running on local blockstore, but not to read it.
        
Steps to Reproduce:
1. Stage a file:
`lakectl fs stage lakefs://repo1/main/1.txt --location local:///tmp/import/bla.txt --checksum 1 --size 10`
2. Try to download it (like thru the UI) and fail.

### Expected Behavior

Expected Behavior:
If lakeFS allows me to stage an object, then I should be able to download it.
We need to make sure that both `local.import_enabled` enabled and `local.allowd_external_prefixes` contains the source when staging a local object. Right now it's not checked when staging an object. It is checked when downloading the object. 

### lakeFS Version

0.94.1

### Deplyoment

local

### Affected Clients

All

**Comment by N-o-Z** [comment]
This will be more easier to resolve once https://github.com/treeverse/lakeFS/pull/5317 is merged
