### ISSUE TITLE
[DX] Create Repository - reduce friction on storage namespace config when running locally

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5368]
As a way of reducing the friction for new users running lakeFS locally it would be good to provide a default value for the storage namespace. `Storage namespace` is not something that a new user will necessarily be familiar with so we need to make it as easy to enter. 

At the moment the form field has a placeholder but this disappears as soon as the user starts typing something which requires them to have memorized the syntax that the placeholder gave them

![CleanShot 2023-03-01 at 11 52 24](https://user-images.githubusercontent.com/3671582/222131982-4c7325fd-3e7b-495e-a895-568e55284236.gif)

Some suggestions: 

* If we're running locally then maybe we can simply default the actual contents of the field to `local://example-bucket` - does the user actually *need* to configure this unless they want to?
    * If not running locally then default the value to the storage namespace prefix?
* or maybe default the contents to the storage namespace prefix so all the user has to do is enter some path name? 
* or add a hint underneath the form box 
![CleanShot 2023-03-01 at 12 02 44](https://user-images.githubusercontent.com/3671582/222134074-49850831-6105-41a6-a8eb-084110e61e49.png)

We should also delay the validation on what's entered until they at least take focus from the box - as can be seen from the screencap above the user gets a scary red message telling them they're doing something wrong even if they're entering as-yet-still-valid text

**Comment by johnnyaug** [comment]
@rmoff, a solution can be to add the default_storage_namespace (don't remember the exact name) configuration to the bundle of default local settings. This way, this field will get field automatically

**Comment by rmoff** [comment]
`:chefkiss:` 🎉 

![create_repo](https://user-images.githubusercontent.com/3671582/223439190-f9109d3a-cce3-4831-89b0-8061435f80d8.gif)
