### ISSUE TITLE
[Docs] Simplification of Spark docs page

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#5411]
https://docs.lakefs.io/integrations/spark.html

Since there are two ways to use lakeFS with Spark (S3 compatible API vs. Hadoop FileSystem), this page is kind of messy.
We have all this before we even get to business:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/3149885/223900100-0437b292-f960-4222-b753-3dd9e53a3832.png">

Additionally, more stuff is going in there soon, namely the documentation of #5355.

Therefore, this page calls for simplification / splitting / pruning - anything really. I've opened #5401 as an SOS - but this is hardly enough.

**Comment by rmoff** [comment]
I'd add a section at the top of the page explaining each of the two options, perhaps with a ✅❌ type chart to help the user pick which to use. Other than that, not sure what else to suggest for this page.

**Comment by rmoff** [comment]
@johnnyaug I'm doing some GH issue housekeeping and came across this. 
Could you review the current page and note any suggestions/observations here please? Or if it's looking OK now then close the issue. 
thanks.
