### ISSUE TITLE
[DX] The output from `lakectl auth groups policies list` is not as easy to read as it could be

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5434]
(lakectl version 0.96.1)

This output is not particularly easy to read. 

```
$ lakectl auth groups policies list --id "Data Scientists" 
AuthManageOwnCredentials	0001-01-01 00:00:00 +0000 UTC	%!s(int=0)	arn:lakefs:auth:::user/${user}	allow	auth:CreateCredentials, auth:DeleteCredentials, auth:ListCredentials, auth:ReadCredentials
FSBlockAccessToSensitiveData	2023-03-02 10:57:48 +0000 UTC	%!s(int=0)	arn:lakefs:fs:::repository/drones03/object/sensitive*	deny	fs:*
FSBlockMergingToMain	2023-03-06 12:22:01 +0000 UTC	%!s(int=0)	arn:lakefs:fs:::repository/*/branch/main	deny	fs:CreateCommit
FSReadWriteAll	0001-01-01 00:00:00 +0000 UTC	%!s(int=0)	*	allow	fs:ListRepositories, fs:ReadRepository, fs:ReadCommit, fs:ListBranches, fs:ListTags, fs:ListObjects, fs:ReadObject, fs:WriteObject, fs:DeleteObject, fs:RevertBranch, fs:ReadBranch, fs:ReadTag, fs:CreateBranch, fs:CreateTag, fs:DeleteBranch, fs:DeleteTag, fs:CreateCommit
RepoManagementReadAll	0001-01-01 00:00:00 +0000 UTC	%!s(int=0)	*	allow	ci:Read*, retention:Get*, branches:Get*, fs:ReadConfig
```

It would be useful to do some/all the following: 

* Add column headings
* List output in aligned columns
* Offer a JSON output that could be parsed and pretty-printed by something like `jq`.

**Comment by nopcoder** [comment]
@rmoff Totally agree about the json output - I think it should a the main feature for this request.
The output in the issue description is the output when lakectl output is identified as non TTY - it uses tab (\t) to separate between fields to make the output easy to capture.
For example `lakectl auth groups policies list --id "Data Scientists"  | cut -d$'\t' -f1,5`.
 You can use LAKECTL_INTERACTIVE=1 to force the standard output and still capture it.
