### ISSUE TITLE
Mention lakeFS samples in lakeFS readme

### ISSUE THREAD

**Issue by adipolak** [treeverse/lakeFS#5462]
Mention lakeFS samples in lakeFS readme for easy discoverability

**Comment by rmoff** [comment]
@adipolak I've got a few more bits I'd like to tidy up on this page - do you want to assign this to me and I'll get a PR up today? I saw your PR but I'd probably link to the samples in a different way outside of that bullet list FWIW.

**Comment by adipolak** [comment]
@rmoff happy to, thanks!
