### ISSUE TITLE
Should we change the language when blocking a delete from a protected branch

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5497]
```
$ lakectl fs rm lakefs://drones02/main/drone-registrations/Registations-RecFlyer-Active-2015.parquet

cannot write to protected branch
```

I get that a deletion is not a read operation and so write kinda makes sense - but it also kinda doesn't. I wonder if we should adopt something more akin to what linux says:

```
$ rm /tmp/foo
rm: remove write-protected regular empty file '/tmp/foo'? y
rm: cannot remove '/tmp/foo': Operation not permitted
```

So then the lakeFS error would be something like `operation not permitted. branch is protected.`

WDYT?

**Comment by nopcoder** [comment]
The current message reports the operation you tried to perform (write in case of delete request - based on the permissions) - in the suggested message we will not know the operation. Except that minor difference I don't know a problem, but would like @ozkatz input on this one.
