### ISSUE TITLE
Remove unused code from MetaRangeManager

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#5605]

**Comment by dcode333** [comment]
@itaiad200 Can i get this issue to work on...please assign it to me

**Comment by itaiad200** [comment]
All yours @dcode333 . Feel free to reach out on [Slack](https://lakefs.io/slack) for any question.

**Comment by dcode333** [comment]
@itaiad200 Just need some Guidance...
I have searched the keyword 'metarangeManager' and In [lakeFS/blob/HEAD/pkg/graveler/committed/manager_test.go](https://github.com/treeverse/lakeFS/blob/master/pkg/graveler/committed/manager_test.go) Found this code that is commented and unused  at line no: 96 to 102. Do I have to remove this and make a PR...Please guide me on this one

**Comment by itaiad200** [comment]
@dcode333 Some of `MetaRangeManager` interface and implementations are not being used anywhere. The goal is to remove those unused functions from the interface and the implementations.

**Comment by nopcoder** [comment]
Hi @dcode333 did you had any progresss with this one?

**Comment by dcode333** [comment]
Hello @nopcoder Hope you are fine,
Still working on it ,  Can you guide a little?

**Comment by nopcoder** [comment]
I didn't look into it, but I would probably just start with finding usage of any method.

**Comment by dcode333** [comment]
@nopcoder Thank you I am on it...

**Comment by amoghrajesh** [comment]
Is anyone working on this? If not, i would like to take it up for hacktoberfest @guy-har @itaiad200
