### ISSUE TITLE
GC: "Mark" output should contain size in bytes

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#5610]
Currently, running GC in mark-only mode will output in Parquet the objects that would have been deleted. 

It would be very useful to also include object size in bytes - this makes it possible to calculate the amount of storage that will be freed if running in "sweep" mode.

**Comment by arielshaqed** [comment]
This is likely possibly "simply" by tracking the object size along with the object physical path: they appear together in the range.
