### ISSUE TITLE
Delta Diff - don't show the "You can use lakeFS to compare Delta Lake tables" note so much

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5647]
We should be more frugal with when we display the `You can use lakeFS to compare Delta Lake tables. Learn more.` note. 

![CleanShot 2023-04-06 at 11 32 34](https://user-images.githubusercontent.com/3671582/230352258-18c3b4b5-2bec-4f08-9660-b213d7c4dc60.png)

It's going to get annoying for users in several cases: 

1. They're not even using Delta
2. They are using Delta and they know already that they can diff

Ideas: 

1. Add a `X` so that it can be dismissed
2. Once the user has used the functionality once, don't show the note again
3. (maybe not worth the LOE) parse the data and only show the note if it's Delta data and the user hasn't yet used the feature

---

The note also becomes redundant once the UI is already telling the user that a diff is available: 

![CleanShot 2023-04-06 at 11 28 00](https://user-images.githubusercontent.com/3671582/230351514-b624df75-d683-4718-92fa-df8a2fac8229.png)

The same UI would be as effective:

![CleanShot 2023-04-06 at 11 29 07](https://user-images.githubusercontent.com/3671582/230351464-45bdd27f-d429-4254-862f-dfeb71113d31.png)

**Comment by rmoff** [comment]
@itaiad200 @ozkatz Coming back to this - I'm working with Iceberg data, and this note is really annoying in the UI. 

How about my idea of add a close icon to it so that it can be dismissed (and not shown again)? 

thanks

**Comment by itaiad200** [comment]
@Jonathan-Rosenberg what's the effort of this? Some kind of cookie to know that the user has disabled it?

**Comment by rmoff** [comment]
Wonderful, thanks @nopcoder !
