### ISSUE TITLE
Enhancement request: Notification on Failed Actions (Hooks)

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#5652]
In some cases, users would like to be notified of a failed Treeverse action. For example, if a data quality check failed as a part of a pre-merge hook, send an email. As opposed to writing specific code to send emails, it might be better to have generic notifications on failed actions.

**Comment by Tahasadiki** [comment]
we encountered such a case where we're trying to use hooks to maintain a parity between the data stored in LakeFS and our metastore (Unity Catalog). Given that's an important process, being alerted when it fails is going to be critical for unlocking this use case.

I would add that this is probably more important for `post-*` hooks compared to the `pre-*` hooks, given that the `pre-*` will abort the corresponding lakefs operation, and hence the caller will implicitly get notified.
