### ISSUE TITLE
[Bug]: Azure Import process creates 2 prefixes in lakeFS for every folder in ADLS

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#5670]
### What happened?

Current Behavior:
Azure Import process creates 2 prefixes in lakeFS for every folder in ADLS
        
Steps to Reproduce:
1. Run the import process from UI
![Screen Shot 2023-04-13 at 11 00 36 AM](https://user-images.githubusercontent.com/93291915/231845814-45dc562c-0903-4cd1-8282-c1a830a3a814.png)

![Screen Shot 2023-04-13 at 11 00 52 AM](https://user-images.githubusercontent.com/93291915/231845268-18582acc-4d1b-4a0a-85ca-68e157de036f.png)
8157833.png)

### Expected Behavior

Expected Behavior:
How you expected thing to work.

### lakeFS Version

0.97.5

### Deplyoment

lakeFS Cloud on Azure

### Contact Details

amit.kesarwani@treeverse.io

**Comment by N-o-Z** [comment]
I thought I took care of this already. I'll take a look ASAP

**Comment by N-o-Z** [comment]
@kesarwam I think this is fixed in 0.98.0. can you please verify with latest version?

**Comment by N-o-Z** [comment]
@kesarwam also please refer to our docs import section on how to import from an ADLS storage account
