### ISSUE TITLE
Migrate docker-compose deployments to Docker compose v2

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#5678]
## What

[docker-compose is deprecated](https://docs.docker.com/compose/compose-v2/) and users are encouraged to switch to Docker compose v2.

This may be as simple as deleting the hyphen from `docker-compose`.  Or not...

> Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can run Compose V2 by replacing the hyphen (-) with a space, using docker compose, instead of docker-compose.
>
> The compose command in the Docker CLI supports most of the docker-compose commands and flags. It is expected to be a drop-in replacement for docker-compose.

**Comment by hjain5164** [comment]
@arielshaqed I would like to work on this issue. Can I go ahead?

**Comment by N-o-Z** [comment]
@hjain5164 hi! Thanks for picking up the glove - are you still interested in taking this issue?

**Comment by hjain5164** [comment]
@N-o-Z yes I would like to work on this issue.

**Comment by N-o-Z** [comment]
@hjain5164 thank you! We greatly appreciate your contribution🙏🏽 
Please note the deprecation deadilne (end of june) and feel free to reach out if you need any help / have any questions!

**Comment by hjain5164** [comment]
@N-o-Z Sorry I am quite occupied with some other work and will be able to finish this and hence unassigning myself.

**Comment by N-o-Z** [comment]
@hjain5164 No problem, thanks for the update

**Comment by N-o-Z** [comment]
This is still relevant

**Comment by arielshaqed** [comment]
Deadline may have been delayed. Still need to do it though.
