### ISSUE TITLE
Docs: Spark integration page: SimilarWeb case study is hidden inside Databricks tab under "Hadoop FileSystem in Presigned mode" section

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#5712]
![Screen Shot 2023-04-19 at 3 22 20 PM](https://user-images.githubusercontent.com/93291915/233212658-f4d86e76-6f04-476f-acad-da19b0813eeb.png)

**Comment by rmoff** [comment]
@kesarwam can you expand on what you want changed here please?

**Comment by kesarwam** [comment]
> @kesarwam can you expand on what you want changed here please?

Case Study should be visible on main Spark integration page. Currently it is inside Databricks tab. So, it should be moved outside the tab and onto the main page.
