### ISSUE TITLE
onboarding - create entries pre-committed

### ISSUE THREAD

**Issue by tzahij** [treeverse/lakeFS#572]
When onboarding, entries are created uncommitted. then they are updated when they are committed.
committing takes about the same time as creating the entries.
I suggest that the entries will be created with a min_commit already assigned.

**Comment by johnnyaug** [comment]
A naive implementation would result in a committed corrupt state if the import fails.
Currently, with the commit happening after entry creation, it's very easy to revert the corrupt state.
Since failure is entirely possible, this case needs to be addressed.
