### ISSUE TITLE
[Bug]: Exporting Data with Docker

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#5744]
### What happened?
I am getting following error even though Export Data with Docker works and exports data:

docker run -e LAKEFS_ACCESS_KEY_ID=aaa \
-e LAKEFS_SECRET_ACCESS_KEY=aaaa \
-e LAKEFS_ENDPOINT=https://amitk04112023.us-east-1.lakefscloud.io \
-e AWS_ACCESS_KEY_ID=aaaa \
-e AWS_SECRET_ACCESS_KEY=aaaaaaa \
-it treeverse/lakefs-rclone-export:latest dev-transformed s3://amit-lakefs-cloud-dev-final/main/ --branch="main"

Traceback (most recent call last):
  File "lakefs_export.py", line 166, in <module>
    main()
  File "lakefs_export.py", line 138, in main
    process_output(local_status, check_process.stdout)
  File "lakefs_export.py", line 67, in process_output
    line = line.removesuffix('\n')
AttributeError: 'str' object has no attribute 'removesuffix'

### Expected Behavior

Expected Behavior:
How you expected thing to work.

### lakeFS Version

0.97.4

### Deplyoment

lakeFS Cloud

**Comment by arielshaqed** [comment]
Strange. Looks like an old version of Python, but Docker images were supposed to be all about _not_ failing like that.

**Comment by nopcoder** [comment]
@kesarwam can you paste the output of the follow to see the checksum of the image you are using?

```sh
docker images treeverse/lakefs-rclone-export:latest
```

Also run the following and paste the outputs as it may include more information:

```
# run a container with interactive bash
docker run -e LAKEFS_ACCESS_KEY_ID=aaa \
-e LAKEFS_SECRET_ACCESS_KEY=aaaa \
-e LAKEFS_ENDPOINT=https://amitk04112023.us-east-1.lakefscloud.io \
-e AWS_ACCESS_KEY_ID=aaaa \
-e AWS_SECRET_ACCESS_KEY=aaaaaaa \
-it --entrypoint /bin/bash treeverse/lakefs-rclone-export:latest

# (inside the container) run the export command once - it should fail the same
./lakefs_export.py dev-transformed s3://amit-lakefs-cloud-dev-final/main/ --branch="main"

# (inside the container) now that we have rclone.conf - run the following to see if we are getting more information from the check step
rclone check lakefs://dev-transformed/main/ s3://amit-lakefs-cloud-dev-final/main/ --config=rclone.conf --combined=-
```

**Comment by kesarwam** [comment]
docker images treeverse/lakefs-rclone-export:latest

REPOSITORY                       TAG       IMAGE ID       CREATED        SIZE
treeverse/lakefs-rclone-export   latest    fe641a0def00   3 months ago   159MB

**Comment by kesarwam** [comment]
rclone check lakefs://dev-transformed/main/ s3://amit-lakefs-cloud-dev-final/main/ --config=rclone.conf --combined=-

= transformed_data/_SUCCESS
= transformed_data/_c0=1/part-00000-0c7c54da-8736-47a2-b722-04fb2a97e45c.c000.csv
2023/04/25 15:50:39 NOTICE: S3 bucket amit-lakefs-cloud-dev-final path main: 0 differences found
2023/04/25 15:50:39 NOTICE: S3 bucket amit-lakefs-cloud-dev-final path main: 2 matching files

**Comment by nopcoder** [comment]
@kesarwam the latest version ID is 224be5bbe8cb.
Can you run the following first and try to export again:

```sh
docker pull treeverse/lakefs-rclone-export:latest
```

**Comment by kesarwam** [comment]
I deleted the image and pulled latest image but I am getting same version ID. And I don't see this version on Docker Hub (https://hub.docker.com/r/treeverse/lakefs-rclone-export/tags?page=1&ordering=-name). Am I doing something wrong?

ak@Amits-MacBook-Pro lakeFS % docker pull treeverse/lakefs-rclone-export:latest
latest: Pulling from treeverse/lakefs-rclone-export
b52ebda398ed: Pull complete 
5ea3b77facf9: Pull complete 
3cf88772a539: Pull complete 
58e7c3cd0452: Pull complete 
8b23ff4b1264: Pull complete 
d29b4a5e9755: Pull complete 
4a3b710ccfa3: Pull complete 
a6a641f4c908: Pull complete 
Digest: sha256:224be5bbe8cb7ed1d4d4d1db4f9136972b9f0a8e9fd6ed750510b65636e6fead
Status: Downloaded newer image for treeverse/lakefs-rclone-export:latest
docker.io/treeverse/lakefs-rclone-export:latest

ak@Amits-MacBook-Pro lakeFS % docker images treeverse/lakefs-rclone-export:latest
REPOSITORY                       TAG       IMAGE ID       CREATED        SIZE
treeverse/lakefs-rclone-export   latest    fe641a0def00   3 months ago   159MB

**Comment by kesarwam** [comment]
I see that sha265 key (224be5bbe8cb7ed1d4d4d1db4f9136972b9f0a8e9fd6ed750510b65636e6fead) matches with Docker Hub when I download latest image. So, I am using latest image.

**Comment by nopcoder** [comment]
Looks like issue is realted to the python vesion used in the export docker image.
The code uses functions found in python v3.9, while the container set to use v3.8.

**Comment by kesarwam** [comment]
Thanks, issue got resolved.
