### ISSUE TITLE
Navigation bar fixes (Logo + fonts + spaces) 

### ISSUE THREAD

**Issue by Savionadav** [treeverse/lakeFS#5795]
<img width="888" alt="Screen Shot 2023-05-03 at 15 12 50" src="https://user-images.githubusercontent.com/123975537/235912478-baea6d48-130c-4fa8-8def-bc568a7f620e.png">

**Comment by N-o-Z** [comment]
Also, might look better to horizontally align the lakeFS logo text and the other content text
