### ISSUE TITLE
Web UI - Markdown rendering improvements & issues

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5798]
1. [x] i’m going to need some CSS on the README rendering - what’s the right way to add that?

2. [x]  I already have used HTML `<a` tags but the rendering is adding a `target="_blank"` which I don’t want as it’s just to anchors - is there a way to prevent that?

3. [x]  inline code doesn't get rendered. The following code

        You'll notice that the branch is set to `main`. This is conceptually the same as your main

    Renders like this: 

    ![image](https://user-images.githubusercontent.com/3671582/235989296-7884409e-a181-43e9-bc28-4bb369b79cf8.png)

**Comment by eladlachmi** [comment]
@rmoff 
> i’m going to need some CSS on the README rendering - what’s the right way to add that?

Create the CSS you want to load. Once you're happy with it, send it to me.

**Comment by rmoff** [comment]
> @rmoff
> 
> > i’m going to need some CSS on the README rendering - what’s the right way to add that?
> 
> Create the CSS you want to load. Once you're happy with it, send it to me.

It's these bits: https://github.com/treeverse/lakeFS/blob/master/docs/_sass/custom/custom.scss#L1017-L1049

**Comment by eladlachmi** [comment]
@rmoff I recently added a fix for rendering `<code>` tags. Can you push the README.md with the issue so that I can see why it's not picking it up?

**Comment by rmoff** [comment]
> @rmoff I recently added a fix for rendering `<code>` tags. Can you push the README.md with the issue so that I can see why it's not picking it up?

https://github.com/treeverse/lakeFS/commit/69092621dd9f115ffd329391c4a27974a683efdc#diff-36bacaeb0e96cd090a48925b01852957c0eb5a2343a397f154a759ed521d3457R81

**Comment by rmoff** [comment]
inline code now works, thanks @eladlachmi 
![CleanShot_2023-05-04_at_11 03 09](https://user-images.githubusercontent.com/3671582/236173906-843e7564-4796-466f-87dd-dd4c1df02f65.png)

Do you think you'll get chance to look at the other two items today?  thanks

**Comment by eladlachmi** [comment]
> Do you think you'll get chance to look at the other two items today? thanks

Yes, I'll look into both today.

**Comment by rmoff** [comment]
re. CSS I'm not seeing it working (I do see it in the `.css` that's loaded tho)

![CleanShot_2023-05-04_at_12 24 11](https://user-images.githubusercontent.com/3671582/236190506-ea53e9c3-6c81-4bca-8a03-356ea651a5a6.png)

this needs to render as it does in the docs currently

![CleanShot_2023-05-04_at_12 24 54](https://user-images.githubusercontent.com/3671582/236190590-c2b02c53-4afe-48b5-965a-3b3c74843acc.png)
