### ISSUE TITLE
[Bug]: [WebUI] Create Repository validation for repo id length fails on len==3

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5801]
### What happened?

Current Behavior:
Repo ID not accepted if 3 chars long but requirement says "Min 3 characters". 
        
Steps to Reproduce:
1. Click "Create Repository"
2. Enter a repo id that is three chars long
3. Cry because the `Create Repository` button is still greyed out and there's no error to show why

![c0805a8a6ed0b30a4b0ae32c31ebf0f5d2d58e15fc18bfd71a86d40a6927e2c1](https://user-images.githubusercontent.com/3671582/236186192-5713c18b-9c3f-4a1b-9d02-6c5e0c7d384a.png)

### Expected Behavior

Expected Behavior:

If min is 3 then `foo` should work. If min is >3 then error should still be displayed if `foo` is not valid. 

### lakeFS Version

latest

**Comment by nopcoder** [comment]
@rmoff nice one. I think it is related to the storage namespace. if you just modity it - even revert back to the same value (change it) - it will enable the button.
