### ISSUE TITLE
[WebUI] Make collapsable sections in markdown clearer / general presentation ideas

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5805]
The `<details>  <summary>` tags are great. Can we make their rendering clearer? For example, a grey background box for the whole text area that they cover? At the moment it's not :100: obvious to the reader that they're there to be expanded

![CleanShot_2023-05-04_at_16 36 27](https://user-images.githubusercontent.com/3671582/236257551-a3468f5a-6c72-4d7b-b3a6-18036bdb8726.png)

Would be nice to combine them into tab groups too with the first instance being the default tab

**Comment by rmoff** [comment]
Added some colour and padding to make the sections stand out 

![image](https://user-images.githubusercontent.com/3671582/236314204-2ee5858b-dac6-4046-b35d-9a5720d3ceed.png)

**Comment by rmoff** [comment]
> To make one `details` block collapse when another opens, you can use JavaScript to add an event listener to each `details` element. When a `details` element is opened, you can loop through all other `details` elements and close them if they are not the one that was just opened. Here's an example:

```javascript
// JavaScript code
const detailsElements = document.querySelectorAll('details');

detailsElements.forEach(details => {
  details.addEventListener('click', () => {
    if (details.open) {
      detailsElements.forEach(otherDetails => {
        if (otherDetails !== details && otherDetails.open) {
          otherDetails.open = false;
        }
      });
    }
  });
});
```

@eladlachmi I chatgpt'd this (oops my secret is out now 🙊 ) - if you agree with it where would I put it to include it in the objects page?

**Comment by N-o-Z** [comment]
@rmoff Can this issue be closed?

**Comment by rmoff** [comment]
No, still waiting for reply from @eladlachmi to my [most recent point](https://github.com/treeverse/lakeFS/issues/5805#issuecomment-1535327842).

**Comment by N-o-Z** [comment]
Closing as this was already done
