### ISSUE TITLE
When using `lakefs run --local-settings`, pre-create a user

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5815]
* Use creds `AKIA-EXAMPLE-KEY` / `EXAMPLE-SECRET` 

Benefits: 
* reduce the time-to-first-click 
* remove the need for [ugly docker run bash gymnastics](https://github.com/treeverse/lakeFS/pull/5787/files#diff-fcccaa99bbf20c97b425af5df72bcbe82563d98d1a62b30db78f50f6a594a30bR18-R26) for a user who just wants to try the quickstart

**Comment by nopcoder** [comment]
@rmoff the command line - lakefs setup, can accept predefined key/secret.
so there will be no need to ask the user to go through the setup process.
Also, note that the initial flow was added to capture the user email for metrics.

**Comment by arielshaqed** [comment]
Also note that those are not valid AWS  access key credentials. AFAIK the secret key is Base-64 encoded binary, and the access key uses only a limited character set.
lakeFS can use anything, but using AWS -invalid access key credentials carries the risk of failing validation by some tools, and at the same time the possibility of GitHub flagging then as secrets. I'd suggest either using the same AWS "EXAMPLE" keys as always, or not starting the access key with AKIA. I prefer the former.

**Comment by johnnyaug** [comment]
Agree with @arielshaqed, and adding the reason of usability: since these credentials are used for our S3-compatible API, it makes sense for them to look like AWS credentials.
Suppose S3 clients were not important for the "local settings" use-case, we could simply use admin:admin as the user:password. However, I don't think that's the case: S3 clients is one of the prominent ways to interact with lakeFS today.

**Comment by rmoff** [comment]
@nopcoder :
>  lakefs setup can accept predefined key/secret

Right, but this then means instead of telling users to run `docker run lakefs --local-settings` (or thereabouts) it becomes `docker run lakefs --this-config --that-config --and-another -config`. Not the end of the world, but not elegant

> Also, note that the initial flow was added to capture the user email for metrics.

noted. the existing quickstart sidesteps this, and reducing user friction for a quickstart should IMO take priority over data capture. 

---

Regarding the value to use, I think we will have to agree to disagree. My two points are: 

- it makes it easier to read and grok that it's clearly sample values. I'd wager many users are not familiar with the AWS example keys at sight. The benefit of this understanding is that the user can then copy pasta and re-use statements from guides in their own environment more easily and with less friction. 
- If we're relying on users understanding the S3 compatibility parallels based on the values of a sample key then we probably need stronger efforts to emphasise this elsewhere.

**Comment by johnnyaug** [comment]
It's not that we are relying on it, it's just that people have different ways of letting things sink in. The created credentials should look like the "real" ones simply to avoid the possibility of confusion.

**Comment by nopcoder** [comment]
if we optimize for a quick start using docker we can have different entry point that will setup and start lakefs.
for non docker - we can have a different flag --quickstart that will use the default settings and configure the predefined admin or any other setup we think is relevant to our quick start.

**Comment by rmoff** [comment]
yes, I like this. I'm perhaps not following entirely though; could we just add `--quickstart` and that then work for docker and non-docker ?

**Comment by nopcoder** [comment]
yes it should
