### ISSUE TITLE
[Bug]: Actions history from deleted repo is available for repos with identical name

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#5851]
### What happened?

Current Behavior:
Very low impact, reporting for the sake of documentation. 
If you delete a Repository  and then create a new one with the same name, the action history of the old repository is associated with the new repository
Steps to Reproduce:
1. Create a repository
2. Run action scripts
3. Delete the repository
4. Create a new repository with the same name
5. View Actions tab

For example - this repository was created at 05/10/2023 11:53:28:
![image](https://github.com/treeverse/lakeFS/assets/87393827/46a02051-bcd8-4ac3-b3ee-27a576c792b4)

But there are actions from 05/08/2023 18:14:40:
![image](https://github.com/treeverse/lakeFS/assets/87393827/00e6919b-dfb0-4ce1-a51e-fc40a0e5ae23)

### Expected Behavior

Expected Behavior:

Should only show actions for the repository since it was created. 

### lakeFS Version

0.99.0

### Deplyoment

AWS

### Affected Clients

NA

**Comment by nopcoder** [comment]
@iddoavn need a better title

**Comment by N-o-Z** [comment]
We should probably save the run information using the repository uuid and not the repository name

**Comment by N-o-Z** [comment]
I think this needs to be addressed
