### ISSUE TITLE
Add "Trusted By" to repo README

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5858]

**Comment by rmoff** [comment]
@ozkatz and is [this](https://kafka.apache.org/powered-by) the kind of "wall of fame" that you're thinking of, or something more lightweight and just a list of logos?

**Comment by ozkatz** [comment]
i was thinking even simpler, like this https://github.com/apache/airflow/blob/main/INTHEWILD.md

it used to be inline in tge README but they solit it into its own file once the list got so big.. README still links to it under “Who uses Airflow”

**Comment by ozkatz** [comment]
It's currently in Hubspot I believe, I know Einat is looking to operationalize Common Room, including managing the list of users there - I would suggest syncing with her

**Comment by rmoff** [comment]
@einato please advise - do we have a list of publicly-citable users? thanks.
