### ISSUE TITLE
Import: Remove the need for an import branch

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#5875]
Investigate the option to commit directly into target branch instead of creating an intermediary branch

**Comment by N-o-Z** [comment]
Suggestion 1:
Create a dangling commit
Use cherry-pick to get it to the target branch

Advantages:
1. Removes the need for an intermediary branch
2. Allows importing to a non-empty branch
3. Doesn't require a merge commit

Disadvantages:
1. Will not work on dirty branches
2. No tracking of changes from source - i.e. every import is treated standalone
3. Will fail if we try to import paths that exist on the target branch and have changed

We could align the cherry-pick so that we will be able to overwrite existing data by passing merge strategy, which will solve no.3 and align with the requirements in https://github.com/treeverse/lakeFS/issues/5780

@ozkatz, @nopcoder, @itaiad200, @arielshaqed - will be happy to hear your input!

**Comment by nopcoder** [comment]
@N-o-Z like it better than the current solution.
Want to suggest improvement as I prefer to have the same without the `dangling commit` step.
The new import produce a local database with all the data to import.
I suggest to do a single side merge with this data into the final import commit.
This is not keep any dangling commit and should perform faster.

**Comment by N-o-Z** [comment]
> @N-o-Z like it better than the current solution. Want to suggest improvement as I prefer to have the same without the `dangling commit` step. The new import produce a local database with all the data to import. I suggest to do a single side merge with this data into the final import commit. This is not keep any dangling commit and should perform faster. So, not depending on cherry-pick feature - but more on merge capability.

Great idea, but this means we'll need to expose some merge function that allows providing an itr as source instead of metarange ID
