### ISSUE TITLE
Some endpoints are missing `LogAction` calls

### ISSUE THREAD

**Issue by eladlachmi** [treeverse/lakeFS#5905]
Several endpoints are missing `LogAction` calls. This includes `SetGarbageCollectionRules` and `CreateBranchProtectionRule`, among others.

**Comment by N-o-Z** [comment]
@eladlachmi Was this done in #5876?
Also please note that some endpoints are missing the LogAction call on purpose

**Comment by N-o-Z** [comment]
Closing this, @eladlachmi please reopen if necessary (see my previous comment)
