### ISSUE TITLE
Metadata cache load invalid keys when configured without / suffix

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#5921]
When metadata cache path is configured without '/' suffix.
While loading the current files removing the cache dir prefix from the cache key
the file path may include '/' as the prefix of the key.
When using the cache getting the key uses relative prefix without the '/' prefix.
The cache is filled with invalid keys that be evicted.

**Comment by arielshaqed** [comment]
I think we've had more than enough issues with namespace prefixes that don't end in "/".  Opening a new bug to ensure that all prefixes end in "/"!  (It will come in addition to this, but it might reduce the probability of future occurrences!)
