### ISSUE TITLE
Docs: Swagger reference is not deep-link-able

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#5940]
trying to deep link to a specific API endpoint in the Swagger documentation loads the page but does not scroll to the relevant position.

**Comment by rmoff** [comment]
Example links that don't work: 

* https://docs.lakefs.io/reference/api.html#/import
* https://docs.lakefs.io/reference/api.html#/import/importStart

**Comment by rmoff** [comment]
Example of a working link: https://docs.lakefs.io/reference/api.html#operations-tag-import

![CleanShot_2023-05-23_at_11 35 30](https://github.com/treeverse/lakeFS/assets/3671582/c2cccf67-8678-46a2-b093-721fe34b1b82)

**Comment by ozkatz** [comment]
Yep. And this also doesn't consistently work. For some reason, opening the above in a new tab redirects me to `https://docs.lakefs.io/reference/api.html#/operations-tag-import` (notice the `/` after the `#`). It still loads the page, but does not scroll.

**Comment by rmoff** [comment]
Linking within the sample Swagger UI works just fine, for example https://petstore.swagger.io/#/user/getUserByName

Reference implementation: https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html

API: https://petstore.swagger.io/v2/swagger.json

---

Noticed an error in the console for our api.html page

```
Error parsing 'integrity' attribute ('Zo9G014Djs2TRCvJGBpi0vdualARLlj1a4JNk2MyvtdrALB8R0ndaV+tewjLU2uJ'). The hash algorithm must be one of 'sha256', 'sha384', or 'sha512', followed by a '-' character.
Error parsing 'integrity' attribute ('DH0sNxIPgt9e1Nzmh5vVgyzsBd4eZAkwiec4LIqQz+sn+RkyQ9VUaZS9LvCdYl3s'). The hash algorithm must be one of 'sha256', 'sha384', or 'sha512', followed by a '-' character.
```

Source is [swagger.html](https://github.com/treeverse/lakeFS/blob/master/docs/_includes/swagger.html)

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.26.2/swagger-ui-bundle.min.js" integrity="Zo9G014Djs2TRCvJGBpi0vdualARLlj1a4JNk2MyvtdrALB8R0ndaV+tewjLU2uJ" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.26.2/swagger-ui-standalone-preset.min.js" integrity="DH0sNxIPgt9e1Nzmh5vVgyzsBd4eZAkwiec4LIqQz+sn+RkyQ9VUaZS9LvCdYl3s" crossorigin="anonymous"></script>
```

---

Next steps: 
- investigate `integrity` error, is it a redherring or cause?
- compare our Swagger UI config to the working sample one

**Comment by rmoff** [comment]
Found an issue suggesting that this is missing functionality in Swagger UI: https://github.com/swagger-api/swagger-ui/issues/3958. However, that doesn't explain why https://petstore.swagger.io/#/user/deleteUser works. 

Put together a PR to patch this, but not confident enough in my JS skills to know if it's the right fix :)

**Comment by rmoff** [comment]
Actually I just tested it again on the preview and it doesn't work e.g. https://treeverse-lakefs-preview-pr-5943.surge.sh/reference/api.html#/repositories/deleteBranchProtectionRule

Need eyes on this from someone who actually knows JS :)

**Comment by eladlachmi** [comment]
> Actually I just tested it again on the preview and it doesn't work e.g. https://treeverse-lakefs-preview-pr-5943.surge.sh/reference/api.html#/repositories/deleteBranchProtectionRule
> 
> Need eyes on this from someone who actually knows JS :)

The reason it works in the example is that the swagger-generated HTML is the top-level element in the document. In our case, it's embedded in the docs layout. The scroll-to-position functionality needs to be adapted. I can look into it if you'd like.

**Comment by rmoff** [comment]
Ah that's great to know, thanks @eladlachmi—and yes if you could fix it for us that would be tremendous :)

**Comment by eladlachmi** [comment]
@rmoff I see that there was already an attempt to fix this. I'll try to get that to work.
