### ISSUE TITLE
feat request: looking for a way to initialise lakeFS without the UI

### ISSUE THREAD

**Issue by sumz95** [treeverse/lakeFS#5947]
Hi 

Currently as I understand , we need to create the  initial credentials [manually by using the UI](https://docs.lakefs.io/quickstart/launch.html), if we deploy lakeFS with helm charts.

Is there a way to automate this process? We are deploying lakeFS in a EKS clusters, with helm. I don't think helm has the option to specify an initial user/credentials. We would be looking into something similar to passing credential when spinning up a [docker container of lakeFS](https://docs.lakefs.io/v0.100/quickstart/launch.html)

```
docker run --name lakefs \
           --rm --publish 8000:8000 \
           --entrypoint "/bin/sh" \
           --env "LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIA-EXAMPLE-KEY" \
           --env "LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=EXAMPLE-SECRET" \
           --env "LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000/" \
           treeverse/lakefs:0.100.0-duckdb -c \
           'lakefs setup --local-settings --user-name admin --access-key-id "$LAKECTL_CREDENTIALS_ACCESS_KEY_ID" 
            --secret-access-key "$LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY"; \
            lakefs run --local-settings'
```

**Comment by itaiad200** [comment]
Hi @sumz95 , welcome to the lake 👋 
I think there are 2 alternatives for programmatically initializing lakeFS. The first is using `lakefs setup ...` just like you did. I understand why this might be a little cumbersome when being used with Helm. The other is leveraging the API. Both `lakefs setup` and the UI use the `setup_lakeFS` [API call](https://docs.lakefs.io/reference/api.html#/config/setup). If you can get any simple http client to perform that call, you'll get the same results as you get from the UI/lakeFS cli. It can run as a onetime job in k8s.
