### ISSUE TITLE
Document lakeFS migration

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#5951]

**Comment by itaiad200** [comment]
Done by @N-o-Z with the 0.101.0 release

**Comment by N-o-Z** [comment]
@itaiad200 I think we still need to fix the documentation regarding migration. Also we should have an issue to create a proper design for migration

**Comment by itaiad200** [comment]
Got it, so reopening and changing the title for the documentation part. I'm not sure what needs to improve further on migration, so kindly open a ticket if you think it's needed.
