### ISSUE TITLE
Add ETag getObject with If-None-Match

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#5967]
## What

Add an optional [`If-None-Match: "ETag"`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match#syntax) header to `getObject` requests.  When an ETag is passed, if that ETag is current for the object on that path then return 304 Not Modified.

(Note that for a non-branch ref, we expect the ETag always to match!)

## Use-case

My server reads configuration from an object stored on lakeFS.  Periodically it needs to refresh the configuration.  So it calls getObject.  Ideally it would be able to avoid reading the data during a refresh.

Even better: if lakeFS versions _before_ we add this feature simply ignore the header, my server will work with them too!

**Comment by vishalsanfran** [comment]
@arielshaqed please review my PR. thanks

**Comment by itaiad200** [comment]
Reopening as there's an active PR in progress.
