### ISSUE TITLE
Add preview support for .yml files

### ISSUE THREAD

**Issue by dsgibbons** [treeverse/lakeFS#5971]
The `.yml` suffix is a common synonym for `.yaml`. When a file has the `.yaml` suffix it can be previewed in the the browser. Can this functionality be expanded to `.yml` as well? At the moment, the following error message is returned:

```lakeFS doesn't know how to render this file (extension = "yml", content-type = "application/octet-stream")```

**Comment by N-o-Z** [comment]
@eladlachmi  @itaiad200 Can we prioritize it?

**Comment by N-o-Z** [comment]
@itaiad200 prioritize as in define the priority for it

**Comment by eladlachmi** [comment]
This is minor. I'll tack it onto my next PR.
