### ISSUE TITLE
BUG: DropAsync leads to long response times

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6008]
After a branch is being deleted, we go and delete all remaining metadata from the branch asynchronically. However, this number of async operations is limited. If I want to create another one and I’ve reached the limit, the operation will wait for a spot to be freed. Hence an occasional long response from the server.

**Comment by arielshaqed** [comment]
My worry is that we are intentionally dropping wakeups.  I wonder if we can implement a better solution by stepping outside of the Goroutine / channel model.

But this kind of "sleep for event on another goroutine" is the exact use-case for events.  We could use [sync.Cond](https://pkg.go.dev/sync#Cond) or even just a [sync.WaitGroup](https://pkg.go.dev/sync#WaitGroup) of size 1 _instead_ of a channel.  We could also use an unbounded channel size.

The worry is that an async wakeup will be dropped, and then we won't do a cleanup when we should.  So another alternative is to add a periodic wakeup to the select, so we _anyway_ run once in a while.

**Comment by itaiad200** [comment]
All Cleanup async routines are identical. Ideally, the channel buffer should be of size 2: You should only wake up again if someone requested a cleanup during your current cleanup. If you wake up once or 99 times the result will be the same if no one rerequested a cleanup.

**Comment by arielshaqed** [comment]
OK, it's a bit weird to implement an event on a chan like this but it probably works.  Thanks!
