### ISSUE TITLE
[DX] Show the initial email capture even if user has already been pre-created from the CLI

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6033]
## Background

At the moment we ask users for their email address as part of the initial setup. This gives them the chance to opt-in to security updates, etc. 

![CleanShot_2023-06-07_at_09 53 59](https://github.com/treeverse/lakeFS/assets/3671582/26add979-799e-4969-ad05-89e0c52c16b3)

This is tied into the user creation process. Once the user enters their email, they get a unique set of credentials: 

![CleanShot_2023-06-07_at_09 54 42](https://github.com/treeverse/lakeFS/assets/3671582/a5e8f1b7-b552-4537-8b14-33a301904318)

However, this whole process is bypassed if the user pre-creates the admin user from the CLI: 

```
lakefs setup --local-settings  --user-name rick --access-key-id foo  --secret-access-key bar
```

## Why pre-creating a user is valuable

For a user installing lakeFS for actual use, creating an admin user with unique credentials is extremely important, and the existing workflow is a good one. 

Where it causes friction is in scenarios where we want to give users a very low-friction experience of trying out lakeFS. This includes the [quickstart](https://docs.lakefs.io/quickstart/) and [lakeFS-samples](https://github.com/treeverse/lakeFS/issues/5739#issuecomment-1574049069). 

In these cases, the user is very clearly in a sandbox/playground/not-real environment, and **having a fixed set of credentials means that documentation and notebooks can be written such that the user can just run them**. If we ask users to make a note of credentials and then each time they're needed to update them, it becomes tedious and error-prone. There are different places where they may be needed too, including: 

* logging into the web UI
* using lakectl
* authenticating to the S3 gateway

---

## Proposal

Amend the workflow so that when the user first runs lakeFS UI they are asked for their email (as currently), but skip user credential creation if a user has already been pre-created. We'd also need to hide the `Please specify the name of the first admin account to create, or leave it as the default.` box in this case. 

The benefit of this is that we can still use email capture whilst improving the developer experience of trying out lakeFS, and thus drive adoption.

**Comment by rmoff** [comment]
Currently on R&D's backlog, not a top priority.

**Comment by ozkatz** [comment]
Opened #6204 which should solve this (@rmoff please approve that it does?)

**Comment by rmoff** [comment]
Closing in favour of #6204
