### ISSUE TITLE
Running migrations before first setup fails with "Failed to get KV version: not found" error

### ISSUE THREAD

**Issue by chriswue** [treeverse/lakeFS#6053]
### What happened?

Current Behavior:
Trying to get a proper setup going on Azure Container Apps (managed k8s basically). To handle migrations I've configured an init container that runs "migrate up". The setup is brand new and nobody has ever logged in (not even an admin)
The init container fails with the message "Failed to get KV version: not found" - checking the postgresdb it seems like tables do exist, so something was created. I just suspect nothing ever entered anything into the table where the db versions are managed.
        
Steps to Reproduce:
1. Deploy a brand new lakeFS instance with postgres backend
2. Don't log in
3. Try run "migrate up"

### Expected Behavior

Expected Behavior:

I think "migrate up" should handle a blank install and just apply the first migration including all the meta data required.

### lakeFS Version

0.103.0

### Deplyoment

Azure Container Apps

**Comment by itaiad200** [comment]
I think migrations will fail before the first setup as there's nothing in the DB to indicate any status of a lakeFS installation. @N-o-Z to keep me honest.

**Comment by chriswue** [comment]
@itaiad200 Well, something in lakeFS creates all the tables and such. I don't see why this cannot be done as part of the migrate command as well?

**Comment by itaiad200** [comment]
During the initial setup the user provides some key information (email, admin username and more) upon which lakeFS can bootstrap the installation. The setup command returns the credentials for the admin user. The migration cannot setup lakeFS on its own as it rely on the user input and returns a one-time output. The tables in Postgres are created as part of lakeFS initialization and don't indicate a successful migrate/setup.

Not sure if a better user experience is to change the behavior of the migrate to succeed when the installation wasn't setup, since it's giving false indication of the status of lakeFS.

**Comment by chriswue** [comment]
Yes, that would hep since it removes the special-handling bootstrapping case. If there is nothing to migrate then migrate should not fail. Or at the very least I'd like to have an option where I can tell it to not fail in case it can't find anything to migrate

**Comment by N-o-Z** [comment]
@chriswue thanks for the suggestion.
The KV store uses a specific key to store database version, and uses it to determine whether lakeFS requires migration or not.
The existence of this key is crucial and once the migration is completed this key is written to indicate the current up-to-date version.
One instance where this key does not exist but a migration is actually required is when you're trying to upgrade lakeFS from a version prior to v0.80.0 (where KV store was introduced). In this case you are required to go through a special KV migration version and not simply ignore the fact that the DB version is missing.
This is only one example.
In general, we should be extremely cautious in the upgrade/migration flows as wrong assumptions might lead to possible corruption of lakeFS metadata which can lead to user data loss

**Comment by N-o-Z** [comment]
Well, this is exactly the scenario where lakeFS cannot know if it was setup
or not.
On this case lakeFS holds it's database in the old implementation and the
new KV driver cannot determine for certain the state of the lakeFS
installation.

**Comment by chriswue** [comment]
Hm, I still don't get it. When running lakeFS on a fresh blank install it knows that there is nothing there and it creates all the database tables. So something knows (or pretends to know). Perusing the code I found 

```
func (d *DatabaseMigrator) Migrate(ctx context.Context) error {
	kvStore, err := Open(ctx, d.params)
	if err != nil {
		return fmt.Errorf("failed to open KV store: %w", err)
	}
	defer kvStore.Close()
	version, err := GetDBSchemaVersion(ctx, kvStore)
	if err != nil && !errors.Is(err, ErrNotFound) {
		return fmt.Errorf("failed to setup KV store: %w", err)
	}
	if version < InitialMigrateVersion { // 0 In case of ErrNotFound
		return SetDBSchemaVersion(ctx, kvStore, NextSchemaVersion-1)
	}
	return nil
}
```

This is called from the `lakefs setup` command:

```
var setupCmd = &cobra.Command{
	Use:     "setup",
	Aliases: []string{"init"},
	Short:   "Setup a new lakeFS instance with initial credentials",
	Run: func(cmd *cobra.Command, args []string) {
		cfg := loadConfig()

		ctx := cmd.Context()
		kvParams, err := cfg.DatabaseParams()
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "KV params: %s\n", err)
			os.Exit(1)
		}
		migrator := kv.NewDatabaseMigrator(kvParams)

		err = migrator.Migrate(ctx)
		if err != nil {
			fmt.Printf("Failed to setup DB: %s\n", err)
			os.Exit(1)
		}
...
```

So sometimes the migrator ignores the error and at other times it doesn't?

**Comment by chriswue** [comment]
In any case for posterity - I've found a way to work-around it by overriding the container entry point to `/bin/sh` with the arguments `-c 'if ! /app/lakefs migrate up > migratelog.txt 2>&1; then cat migratelog.txt; grep "Failed to get KV version: not found" migratelog.txt || exit 1; fi'`. This is the equivalent of `err == nil || errors.Is(err, ErrNotFound)`.  Keeps an extra log around but can't be bothered to clean it up at the moment. This passes the bootstrap phase and future upgrade since I don't care about versions prior to 0.100.0.

Ideally there would be an option like `--missing-kv-version-means-clean-setup-and-it-is-ok` but for now this will do.

**Comment by chriswue** [comment]
Ok thanks, the workaround solution should be ok for now. Thanks for the background info.

**Comment by chriswue** [comment]
@N-o-Z "Closed as completed" - Does this mean an option is now available?

**Comment by N-o-Z** [comment]
@chriswue hi, this is the default close status in Github. Change to not-planned per our previous discussion and due to the possible risks this change might introduce
