### ISSUE TITLE
Update Quickstart to use DuckDB WASM so we can remove the DuckDB Docker image

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6076]
Now that https://github.com/treeverse/lakeFS/pull/6044 is merged, we should be able to update the Quickstart to use DuckDB in the browser alone, and [remove the DuckDB Docker image](https://github.com/treeverse/lakeFS/issues/6001)

**Comment by rmoff** [comment]
@ozkatz 

1. Why doesn't `ALLOW_OVERWRITE` work? Can we make it work? Would be nice if the SQL were portable

    ![CleanShot_2023-06-14_at_16 27 12](https://github.com/treeverse/lakeFS/assets/3671582/1789ed54-f197-47c6-9932-1a0f562fd512)

2. All command statements `SET` etc just show `No Rows Returned` when run - there should be something to confirm successful execution (presumably the absence of an error indicate that? but user shouldn't have to guess)

    ![CleanShot_2023-06-14_at_16 30 54](https://github.com/treeverse/lakeFS/assets/3671582/4624fff5-8afb-4503-ada1-0231aa362ce3)


4. Should we add a "Launch DuckDB" button somewhere to the UI? If we're saying now that users can manipulate their data throughout the lake using DuckDB, making them launch it by finding a compatible file in the Objects pane is a bit of a roundabout way

**Comment by ozkatz** [comment]
1. Why would you need to run those in the browser? It's already preconfigured
2. I was able to write by simply doing `COPY lakes TO 'lakefs://repo/branch/path.parquet'` - without any format or or overwrite directives.
3. Unfortunately, duckdb-wasm and regular duckdb handle IO pretty differently (and inconsistently). Another example are the S3 parameters you set in your screenshot - the s3_endpoint (which again, is preconfigured for you, so no need to set) needs to be a fully qualified URL, including the leading `https://` part. `s3_url_style` doesn't even exist in duckdb-wasm, but is implied by the existence of 'http' in the endpoint.

**Comment by ozkatz** [comment]
As for a "launch duckdb" button - yes, that makes sense, could you open an issue for it? (honestly not sure we'll be able to prioritize it any time soon but let's try)
