### ISSUE TITLE
[Bug]: JPEG object read using Spark/lakeFSFS on Azure Databricks is missing image metadata

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6098]
### What happened?

Current Behavior:
When I read an image using S3A gateway, I get correct metadata (in this case width and height of image):
```
dataPath = f"s3a://test-repo/main/Images/n02088094-Afghan_hound/n02088094_115.jpg"
df= spark.read.format("image").load(dataPath)
df.select("image.origin", "image.width", "image.height").show(truncate=False)

+---------------------------------------------------------------------------------+-----+------+
|origin                                                                           |width|height|
+---------------------------------------------------------------------------------+-----+------+
|s3a://test-repo/main/Images/n02088094-Afghan_hound/n02088094_115.jpg%7C.         |  318|500   |
+---------------------------------------------------------------------------------+-----+------+
```
But with lakeFSFS, I get -1 for width & height:
```
dataPath = f"lakefs://test-repo/main/Images/n02088094-Afghan_hound/n02088094_115.jpg"
df= spark.read.format("image").load(dataPath)
df.select("image.origin", "image.width", "image.height").show(truncate=False)

+------------------------------------------------------------------------------------+-----+------+
|origin                                                                              |width|height|
+------------------------------------------------------------------------------------+-----+------+
|lakefs://test-repo/main/Images/n02088094-Afghan_hound/n02088094_115.jpg%7Cz.        | -1  |-1    |
+------------------------------------------------------------------------------------+-----+------+
```        

my lakeFS Config:
`sudo docker run -d --restart always --pull always -p 8000:8000 -e LAKEFS_STATS_ENABLED=0 -e LAKEFS_BLOCKSTORE_TYPE='azure' -e LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCOUNT='demo' -e LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCESS_KEY='aaa'  -e LAKEFS_BLOCKSTORE_AZURE_DISABLE_PRE_SIGNED_UI=1 --name azureuser_lakefs_1 treeverse/lakefs run --local-settings`

Databricks Cluster Spark config:
```
spark.hadoop.fs.lakefs.access.mode presigned
spark.hadoop.fs.lakefs.secret.key aaa
spark.hadoop.fs.lakefs.access.key bbb
spark.hadoop.fs.lakefs.endpoint http://111.222.333.4:8000/api/v1
spark.hadoop.fs.lakefs.impl io.lakefs.LakeFSFileSystem
spark.databricks.delta.preview.enabled true
spark.databricks.delta.logStore.crossCloud.fatal false
```
Using latest io.lakefs:hadoop-lakefs-assembly:0.1.15 library for Databricks cluster.

Steps to Reproduce:
1. Please contact me. I have Azure Databricks notebook to reproduce this.

### Expected Behavior

```
Expected Behavior:
How you expected thing to work.

```

### lakeFS Version

0.102.2

### Deplyoment

Docker

### Affected Clients

hadoop-lakefs-assembly:0.1.15

### Contact Details

amit.kesarwani@treeverse.io

**Comment by itaiad200** [comment]
Tagging some folks that might know if lakeFSFS supports `.format("...")`: @Jonathan-Rosenberg @arielshaqed @johnnyaug

**Comment by kesarwam** [comment]
FYI: this works fine on Databricks on AWS. This is the issue with Azure only.

**Comment by arielshaqed** [comment]
> Tagging some folks that might know if lakeFSFS supports `.format("...")`: @Jonathan-Rosenberg @arielshaqed @johnnyaug

This is how we write in Spark. lakeFSFS lives at a much lower level. It supports this.

If I had to guess, I'd look at seeks with presigned URLs. I seem to remember jpeg stores metadata towards the end?

**Comment by arielshaqed** [comment]
> > Tagging some folks that might know if lakeFSFS supports `.format("...")`: @Jonathan-Rosenberg @arielshaqed @johnnyaug
> 
> This is how we write in Spark. lakeFSFS lives at a much lower level. It supports this.
> 
> If I had to guess, I'd look at seeks with presigned URLs. I seem to remember jpeg stores metadata towards the end?

So not at the end, but JPEGs are composed of segments - and if you're a lazy reader like Spark then you might end up seeking there.

**Comment by arielshaqed** [comment]
Name changed to clarify: it seems that the "JPEG" (EXIF) metadata is missing - _not_ what lakeFS calls the "object metadata" and returns in the statObject header.

**Comment by Isan-Rivkin** [comment]
Hi @kesarwam I don't think there's a bug. I am able to read image data on Azure Cloud. 
1. Make sure pre-signed is not disabled in the lakeFS server.  
2. Make sure the azure has the roles required to perform pre-sign requests [see issue](https://github.com/treeverse/cloud-controlplane/issues/1908)
3. Sharing an Azure Databricks Notebook with you (see email). 

I used **per-bucket** configuration for the purpose of using same spark session in a single notebook, the spark configuration I used: 

`dummy-repo` - Repository used to access with `s3a://` 
`lakefsfs-repo` - Repository used to access with `lakefs://`

```
spark.hadoop.fs.s3a.bucket.dummy-repo.path.style.access true
spark.databricks.delta.preview.enabled true
spark.hadoop.fs.lakefs.access.mode presigned
spark.hadoop.fs.s3a.bucket.lakefsfs-repo.secret.key <LAKEFS_SECRET_1>
spark.hadoop.fs.s3a.bucket.dummy-repo.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.lakefs.impl io.lakefs.LakeFSFileSystem
spark.hadoop.fs.lakefs.secret.key <LAKEFS_SECRET_1>
spark.hadoop.fs.s3a.bucket.dummy-repo.secret.key <LAKEFS_SECRET_1>
spark.hadoop.fs.s3a.bucket.lakefsfs-repo.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.bucket.lakefsfs-repo.access.key <LAKEFS_KEY_1>
spark.hadoop.fs.s3a.bucket.lakefsfs-repo.endpoint https://<lakefs-azure-url>
spark.hadoop.fs.s3a.bucket.dummy-repo.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.lakefs.access.key <LAKEFS_KEY_1>
spark.hadoop.fs.lakefs.endpoint https://<lakefs-azure-url>/api/v1
spark.hadoop.fs.s3a.bucket.dummy-repo.access.key <LAKEFS_KEY_1>
spark.hadoop.fs.s3a.bucket.dummy-repo.endpoint https://<lakefs-azure-url>
```

![Screen Shot 2023-07-03 at 10 18 24](https://github.com/treeverse/lakeFS/assets/22504565/40d5ea97-097b-4a76-af08-068c90e6ef17)

Can you please confirm with the notebook I shared with you and the information provided here that it works?

**Comment by Isan-Rivkin** [comment]
@kesarwam Hi, any update on [this](https://github.com/treeverse/lakeFS/issues/6098#issuecomment-1617512880) is it still relevant?

**Comment by kesarwam** [comment]
This is not an issue anymore. I had misconfigured lakeFS server. The LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCOUNT env var was configured with the resource group that the storage account was a part of instead of the storage account itself.

Once I fixed the misconfiguration, this issue got resolved.
