### ISSUE TITLE
Azure: Avoid redundant network roundtrips for generating pre-signed URLs

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#6165]
The current implementation of the Azure Blockstore will perform a network roundtrip to the Azure server on each generation of a pre-signed URL. This adds latency and might count towards rate limits.

Desired behavior: do the minimal amount of roundtrips to the Azure server (might be just 1 roundtrip to fetch the delegation token and cache it locally?)

**Comment by ozkatz** [comment]
cc @N-o-Z @Jonathan-Rosenberg @arielshaqed

**Comment by N-o-Z** [comment]
Closing as done
