### ISSUE TITLE
Fully automated, manually triggered, CP deployment (Design + Implementation)

### ISSUE THREAD

**Issue by eladlachmi** [treeverse/lakeFS#6166]
- Design a new process for deployment, which is manually triggered, but fully automated
- Implement the design once finalized

**Comment by Isan-Rivkin** [comment]
Hey @eladlachmi, please see this [dup ticket](https://github.com/treeverse/cloud-controlplane/issues/1859)  adding here context on ideas I had around this and closing the issue I opened. I created the ticket at the same week as you :)
