### ISSUE TITLE
hadoopfs compatibility test builds a Docker image but uses something else

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#6173]
[Discovered while running the action for #6170.]

This image says it all: _all_ tests of the action have finished, but the image is still being built.  Clearly the test does not use this built image.

![tests against all client versions have finished but Docker build is still running](https://github.com/treeverse/lakeFS/assets/7802932/892262bd-b6d3-4906-9baa-5734a4e8ed65)

**Comment by itaiad200** [comment]
I don't think there's an issue. The compatibility tests check 2 things:
1. latest lakeFS server with previous versions of lakeFSFS client.
2. latest lakeFSFS client with previous versions of lakeFS server.

The tests you see running while the server is being built are of the second type. Hence they do not need to wait for the server to be built:
<img width="824" alt="image" src="https://github.com/treeverse/lakeFS/assets/9861474/d01c804d-4784-412a-ba71-3eae2061ac0d">
