### ISSUE TITLE
MinIO adapter part of Nessie system test

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#618]
Have MinIO as an additional block adapter for lakeFS system tests

**Comment by itaiad200** [comment]
Can we close this @nopcoder ?

**Comment by nopcoder** [comment]
> Have MinIO as an additional block adapter for lakeFS system tests

no, this one was doing another adapter and not working with the a3 one

**Comment by nopcoder** [comment]
Got mix with a different issue - minio specific adapter. Closing this one as we have minio in system test.
