### ISSUE TITLE
[FEATURE REQUEST] Make the lakectl executable available via homebrew/ chocolatey

### ISSUE THREAD

**Issue by cberge908** [treeverse/lakeFS#6181]
Hi,

we're just getting started to evaluate lakeFS and were kind of surprised that you need to download the full tar package for your client to get the lakectl executable. Similar projects usually offer their custom CLIs via package managers like homebrew or chocolatey. 

Would it be an option to offer the lakectl via hombrew/ chocolatey as well? ;-)

Cheers,
cberge908

**Comment by nopcoder** [comment]
The following should work for you:

```
brew tap treeverse/lakefs
brew install lakefs
```

**Comment by nopcoder** [comment]
@cberge908 the above is the feature you wanted?

**Comment by cberge908** [comment]
Thanks @nopcoder - that was exactly what I was looking for.

Somehow I would have expected to see this over [here](https://github.com/treeverse/lakeFS/blob/master/docs/reference/cli.md) in the documentation. Or is this mentioned in another spot which I just have missed?

**Comment by nopcoder** [comment]
True, will verify we have an issue for the docs and close this one.

**Comment by nopcoder** [comment]
Another note - the brew provides the `lakefs` and `lakectl`, so it can also be used to run lakefs.
