### ISSUE TITLE
Apparent race condition in lakeFSFS compatibility test

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#6191]
See [this failure](https://github.com/treeverse/lakeFS/actions/runs/5529506117/jobs/10087722824#step:10:60).  Failure message:
```json
{
  "message": "failed to create repository: found lakeFS objects in the storage namespace(s3://esti-system-testing/compatibility/73-spark3-client/24308): lakeFS repositories can't share storage namespace"
}
```

I'd guess a test started on an S3 path that was concurrently used by another test.

**Comment by arielshaqed** [comment]
## Workaround

Re-running the test appears to succeed.

**Comment by itaiad200** [comment]
Last >20 runs didn't fail with repo creation bug, it seems like our fix handled it nicely.
