### ISSUE TITLE
[docs platform] docs feedback buttons don't work

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6198]
The 👍🏻 button can't be clicked. 
The 👎🏻 button can only be clicked on its very edge

https://github.com/treeverse/lakeFS/assets/3671582/6f01d30f-21c0-4143-95ba-27fa09c92813

Is the H1 element blocking them? 
![CleanShot_2023-07-12_at_17 01 16](https://github.com/treeverse/lakeFS/assets/3671582/f6a48602-8584-48e2-b314-387e9959cfbc)

**Comment by rmoff** [comment]
If I hack the CSS to add `z-index` 

```css
.feedback-container { position: sticky; top: 180px; z-index: 9999;}
```

then it works: 

https://github.com/treeverse/lakeFS/assets/3671582/c045a41c-241d-448f-97c2-f22a77c58b18


@eladlachmi @johnnyaug can you advise if this is the correct route, or we should be doing this another way?

**Comment by johnnyaug** [comment]
@rmoff, nice catch! I would simply add:
```
display: inline-block;
```
to the `h1` element in order for it to occupy only the needed space. But @eladlachmi is the expert.

**Comment by eladlachmi** [comment]
@johnnyaug The original sin here is that the feedback buttons have an absolute position, removing them from the flow of the document. This means their container is empty and doesn't take up space. In the natural flow of the document, `feedback-container` is a sibling of `main-header`. This design is not "responsive design friendly". But resolving that is outside the scope of this fix IMHO.

The problem with using `display: inline-block` is that it solves the issue for the initial scroll position. As you scroll the page, other elements can potentially overlap with the buttons. I think that giving them a z-index "above" the content would be the way to go.

**Comment by eladlachmi** [comment]
@rmoff I think the z-index solution is the way to go here. This probably requires a better design solution so it's more "responsive friendly", but that's outside the scope of this fix IMHO.

**Comment by rmoff** [comment]
@eladlachmi thanks, will submit a PR. How much of a "hack" is this—is this tech debt that is going to come back to bite us and needs fixing properly, or can we sweep it under the carpet vs other dev time requirements?
