### ISSUE TITLE
Support windows commands format in lakeFS docs

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#6236]

**Comment by rmoff** [comment]
Is there any more detail for this issue please? 

e.g. are we looking at supporting it from the CMD prompt, or WSL? Powershell? etc.

What are the incompatibilities that we've identified and need fixing?

**Comment by rmoff** [comment]
One approach to consider is a "Running lakeFS on Windows" docs page that outlines how to use the existing docs on Windows and can list the differences.
