### ISSUE TITLE
Document our Release cycle/process

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#625]

**Comment by arielshaqed** [comment]
Mine after yesterday's meeting.
![it's mine](https://user-images.githubusercontent.com/7802932/93863164-daf0db80-fccb-11ea-95c2-2e799ea44824.png)

**Comment by ng29** [comment]
hey @nopcoder /. @arielshaqed 

Can i pick if it is available for grabs?

**Comment by nopcoder** [comment]
> hey @nopcoder /. @arielshaqed 
> 
> Can i pick if it is available for grabs? 

already handled by @arielshaqed
