### ISSUE TITLE
OSS registration consent form

### ISSUE THREAD

**Issue by keren-lakeFS** [treeverse/lakeFS#6255]
We want to change the signup process in lakeFS open source to as follows:
### Communication Preferences:
Please provide your email below:
Email*
[name@company.com           ]

[x] I'd like to receive security, product, and feature updates
[Continue]

@eladlachmi I'll also touch base with you about this in person
@iddoavn for your reference the changes we discussed

**Comment by keren-lakeFS** [comment]
@itaiad200 any status on when this will be implemented?
thanks!

**Comment by itaiad200** [comment]
Soon :)
