### ISSUE TITLE
[Python client] Support for multipart uploads in `objects_api.upload_object`

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#6259]
Hello! I am looking at building a lakeFS IO abstraction, and one of the features is support for chunked gets and puts. But while `objects.get_object` gives a `range` argument which allows me to chunk the file, I see no such option in `objects.upload_object`.

What is the recommended way of doing multipart uploads to lakeFS using the Python client?

PS: I assume that this is possible because of the S3 API support doc here: https://docs.lakefs.io/reference/s3.html

Thanks in advance!

**Comment by idanovo** [comment]
Hi @nicholasjng, thanks for the question.

Unfortunately, currently, lakeFS doesn't support multipart uploads through its API.

What's your use case? What is the expected size of the files you want to upload and how many of them do you want to upload?

If you want to upload a couple of files in parallel, uploading each separately in a different thread will work.
If your use case is uploading one big file, currently there's no way around it since multipart upload is not supported using lakeFS API.

**Comment by itaiad200** [comment]
Hey @nicholasjng, lakeFS has 2 endpoints for objects operation: 
1. [Open API endpoint](https://docs.lakefs.io/understand/architecture.html#openapi-server) which reference you may find [here](https://docs.lakefs.io/reference/api.html). This API exposes other operations, such as branching, committing, comparing refs, CI/CD of data and other operations which are available with lakeFS. The [lakeFS python client](https://docs.lakefs.io/integrations/python.html#using-the-lakefs-sdk) interacts with the OpenAPI endpoint of lakeFS. 
2. [S3 gateway](https://docs.lakefs.io/understand/architecture.html#s3-gateway) which is S3 compatible. Any S3 client, including [python's Boto](https://docs.lakefs.io/integrations/python.html#using-boto), can be used with lakeFS.
 
At the moment, multipart uploads are only supported with S3 gateway. You can configure your Boto package for these kind of uploads, and use the lakeFS client for everything else.

**Comment by nicholasjng** [comment]
Thanks for the comments! My use case is supporting the `fsspec` API, and multipart uploads is part of that. But as far as I understand, I can also just handle single uploads and disallow multiparts explicitly.

Is multipart upload support on the OpenAPI roadmap, and how hard would it be to add?

**Comment by arielshaqed** [comment]
We have no current plans to add multipart uploads.  Uploading huge files through lakeFS servers will obviously pose some scaling issues.  This is **not** so much the code!  At the risk of stating the obvious: if the lakeFS server is on-path for data uploads, it has to consume double the client data bandwidth.

Naturally there are workarounds!

* As @itaiad200 points out above, the S3 gateway supports multipart uploads.  The lakeFS server will be on-path when you do this.  This object lifetime will be controlled by lakeFS - it is subject to GC.
* There is a [`stageObject` API](https://pydocs.lakefs.io/docs/ObjectsApi.html#stage_object).  You can upload the object to the underlying store (outside the repository storage namespace), and then "stage" it to make it appear at a given path in the repository.  You upload to the underlying storage directly and use its API -- obviously multipart uploads work there.  This object lifetime is _not_ controlled by lakeFS - it cannot be GC'ed.
* There is the [`getPhysicalAddress`](https://pydocs.lakefs.io/docs/StagingApi.html#get_physical_address) / [`linkPhysicalAddress`](https://pydocs.lakefs.io/docs/StagingApi.html#link_physical_address) API combo: you get a "physical address" inside the storage namespace, upload the object to the underling store, and then link it to make it appear at a given path in the repository.  You upload to the underlying storage directly and use its API -- obviously multipart uploads work there.  This object lifetime will be controlled by lakeFS - it is subject to GC.

As you can probably see, these are ordered by increasing client complexity.  But even the third is pretty simple!

Does this help?

**Comment by nicholasjng** [comment]
Yes, it does, thank you. My favorite is either option 1) or 3) because of GC support, with a slight edge towards 3).

I will try my luck and see how it works, just as a follow-up: I would probably also need a boto client for option 3) if I decide to talk to the storage API directly, no?

PS (if you have time): The part about "on-path" uploads was not at all obvious to me, what does it mean and why does it double the bandwidth?

**Comment by itaiad200** [comment]
Right, @nicholasjng. In the third option a boto client is required for interacting directly with the store.
Regarding the "on-path" - consider the data flow: `client->lakeFS->S3` for uploads as an example. Notice lakeFS needs to read the data from the client and upload it to S3, hence the double bandwidth. There are some lakeFS users that choose to perform all operations directly to lakeFS, depends on your scale, you can probably get away with that.

**Comment by arielshaqed** [comment]
Thanks!  I hope this helped.  I am not sure what further action we can take now, so I am closing the issue.  **Please** feel very free to reopen this issue or open a new one if you disagree.
