### ISSUE TITLE
[Python] `LakeFSClient` is missing typing information and completion

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#6262]
Due to these lines dynamically generating the API members on the client,

https://github.com/treeverse/lakeFS/blob/f5bf238a6be454af2d98bd8327e52ed9443c63b0/clients/python/lakefs_client/client.py#L39-L40 

we do not get any static name and typing information on the `LakeFSClient` class e.g. in IDE development. This confuses linters and type checkers.

To fix, I propose adding a `client.pyi` file containing the interface of the client, and packaging it together with the `lakefs_client` PyPI package. I would also be happy to contribute that if it is of interest.

**Comment by nopcoder** [comment]
Hi @nicholasjng does it means that the pyi file should include the static list of the attributes we maintain for each API package?

**Comment by nicholasjng** [comment]
No, it should only contain the API member hints of the `LakeFSClient` class - everything else shows up properly once these are in place. I have the file on hand, can quickly draft a PR if you are interested

**Comment by nopcoder** [comment]
To produce the hints means that we will need to maintain the list - so we should prefer to generate this code.
If this is the case we can just have the LakeFSClient generated and this issue will be resolved.
