### ISSUE TITLE
Build CONTRIBUTORS document for the project

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#628]
1. Add CONTRIBUTORS file to the repository
2. Update the process of when and how to update the file
3. Optional - generate code that includes these names as part of the tools

**Comment by daniloff200** [comment]
hey :)
I would like to pick this one for upcoming Hacktoberfest

I have a proposal to use https://allcontributors.org/ bot. It has cli, when you easily can collect all needed data 

https://allcontributors.org/docs/en/cli/usage#all-contributors-generate 

and it's gonna look something like this

![Selection_084](https://user-images.githubusercontent.com/13692220/93996176-997b3180-fd9a-11ea-8026-d3dc90d056f5.png)

**Comment by arielshaqed** [comment]
> hey :)
> I would like to pick this one for upcoming Hacktoberfest
> 
> I have a proposal to use https://allcontributors.org/ bot. It has cli, when you easily can collect all needed data
> 
> https://allcontributors.org/docs/en/cli/usage#all-contributors-generate

Thanks!  I was in any case unaware of this tooling.  I'm a bit unsure how the bot and the CLI interact, but obviously that should not block anything.  Please read [Contributing to lakeFS](https://docs.lakefs.io/contributing), and *do feel free to self-assign*.

Looking forward to your PR! :eyes: :telescope:

**Comment by coatest** [comment]
To make [daniloff200](https://github.com/daniloff200) life a bit easier, I have already gone ahead and created a CONTRIBUTORS.md file.
It is currently awaiting approval.

Hope this helps.
