### ISSUE TITLE
[Bug]: Unity Delta Sharing: Column comments in Delta table are not visible in Unity Catalog

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6322]
### What happened?

Current Behavior:
I used Spark (Scala) as well as Spark SQL to create Delta table with column comments but column comments don’t show up on Unity side.

I can see the comment under metadata field for column id in Delta log in lakeFS:
{"commitInfo":{"timestamp":1691101649647,"userId":"379635745759847","userName":"amit.kesarwani@treeverse.io","operation":"CREATE TABLE","operationParameters":{"isManaged":"false","description":null,"partitionBy":"[]","properties":"{}"},"notebook":{"notebookId":"2103193567248266"},"clusterId":"0207-185609-rx3dbh4v","isolationLevel":"WriteSerializable","isBlindAppend":true,"operationMetrics":{},"engineInfo":"Databricks-Runtime/12.2.x-cpu-ml-scala2.12","txnId":"9b6d35ac-111d-47d3-9373-00196c2319e1"}}
{"protocol":{"minReaderVersion":1,"minWriterVersion":2}}
{"metaData":{"id":"bf4f433e-e159-4d2f-b9bf-da71fa8af9b4","format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"nullable\":true,\"metadata\":{\"**comment**\":\"**test comment**\"}}]}","partitionColumns":[],"configuration":{},"createdTime":1691101649231}}

But I don’t see the comment on Unity side for column id:
![image](https://github.com/treeverse/lakeFS/assets/93291915/c907b9d8-a84c-4bde-b8ce-aa233f736ef2)

      
Steps to Reproduce:
This is Databricks notebook which can be used: https://dbc-8ada78b6-3a6d.cloud.databricks.com/?o=8376305627582670#notebook/2103193567248266

### Expected Behavior

Expected Behavior:
Column comments should show up on Unity side.

### lakeFS Version

0.104.0

### Deplyoment

lakeFS Cloud

### Contact Details

amit.kesarwani@treeverse.io

**Comment by talSofer** [comment]
duplicate of https://github.com/treeverse/lakeFS/issues/7302
