### ISSUE TITLE
PartitionIterator may perform N kv scans when staging area of size N

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6326]
Consider the following N uncommitted changes:
```
goo/prefix1/foo.txt
goo/prefix2/foo.txt
goo/prefix3/foo.txt
....
....
goo/prefixN/foo.txt
```
A client requests `ListEntries` of size N with prefix `goo/`.
The expected response is a list of N prefixes `goo/prefix1/, goo/prefix2/, ...., goo/prefixN/`.

The way graveler works is that it combines 2 iterators, staging area iterator and committed area iterator. It firsts tries to get a non-tombstone value from the staging area. If it exists, it will fetch from the next prefix. So it goes something like that (zooming in to the staging area iterator only, committed iterator is sub-optimal too but out of scope):
1. `Scan(start=goo\, amount=N, after = '')`.
    1. The list  `goo/prefix1/foo.txt, goo/prefix2/foo.txt, ...., goo/prefixN/foo.txt` is returned.
    2. Add `goo/prefix1/` to the result set
    3. Move to next prefix
2.  `Scan(start=goo\, amount=N, after = 'goo/prefix1/z')`. - where `z` marks the highest possible byte (in order to skip the entire `prefix1`)
    1. The list  `goo/prefix2/foo.txt, goo/prefix3/foo.txt, ...., goo/prefixN/foo.txt` is returned.
    2. Add `goo/prefix2/`  to the result set.
    3. Move to next prefix
 ....

Therefore N Scans are possible.
Explanation is simplified for readability, it's actually more complex that this.

**Comment by arielshaqed** [comment]
While we're here (but _not_ the same): #2092 is about staging areas with multiple deletes.
