### ISSUE TITLE
Return actual expiry including token expiry for presigned URLs

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#6328]
Clients can use our API to request presigned URLs to underlying storage.  The lifetime of this URL is given by the minimum of:
* The presigned expiry time, configured for the block adaptor.
* The expiry time of any authentication tokens.
For instance, when lakeFS is configured to run using AWS IAM STS, presigned URLs will expire when the current token expires.  The client has no way of knowing either of these times.  While the expiry time is static and conceivably might be configured on the client as well, lakeFS auth token expiration is dynamic and cannot be guessed by the client.

This might currently be causing isses at user sites using lakeFS Delta Sharing with Unity.

Add an expiration field to presigned responses.

**Comment by johnnyaug** [comment]
Not sure I agree with this solution. I would argue that it's within the responsibility of the lakeFS admin to make sure that lakeFS authenticates properly with the storage. Returning an expiry time which is deduced from two different expiry times seems confusing, and it's not really clear what the user is meant to do with this information.

We _could_ help in other ways. For example, we could introduce a mechanism to renew the session with the storage when it's about to expire.

@arielshaqed, could you elaborate what issue this may be causing on the user side?
