### ISSUE TITLE
[Bug]: Getting error to copy Glue metastore using lakectl

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6374]
### What happened?

Getting errors to run following commands:

`
lakectl metastore copy \
--catalog-id 11111111111 \
--from-client-type glue \
--from-schema amit_glue_hive_demo \
--from-table customers \
--to-client-type glue \
--to-schema amit_glue_hive_demo_glue_etl_branch \
--to-table customers \
--to-branch glue-etl-branch
`
Error message:
```
 InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetTableInput.CatalogId.
```

`
lakectl metastore copy-schema \
--catalog-id 1111111111 \
--from-client-type glue \
--from-schema amit_glue_hive_demo \
--to-client-type glue \
--to-schema amit_glue_hive_demo_glue_etl_branch \
--to-branch glue-etl-branch
`
```
failed to get database on copy from 'amit_glue_hive_demo': InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetDatabaseInput.CatalogId.
```    
`
lakectl metastore copy-all \
--from-client-type glue \
--from-address amit_glue_hive_demo \
--to-client-type glue \
--to-address amit_glue_hive_demo_glue_etl_branch \
--branch glue-etl-branch
`
```
InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetDatabasesInput.CatalogId.
```

### lakeFS version

0.104.0

### How lakeFS is installed

lakeFS Cloud

### Contact details

amit.kesarwani@treeverse.io

**Comment by itaiad200** [comment]
It seems like an instance of https://github.com/treeverse/lakeFS/issues/3253

**Comment by itaiad200** [comment]
Hey @kesarwam - I was able to reproduce it. The error is not very informative. Did you set `metastore.glue.catalog_id` in the .lakectl.yaml config file? Keeping this issue opened to fix the confusing error message.

**Comment by kesarwam** [comment]
@itaiad200 Yes, I had set `metastore.glue.catalog_id` in the .lakectl.yaml config file but I get following error when I do that so I removed it:
```
error unmarshal configuration: 1 error(s) decoding:

* 'Metastore.Glue' has invalid keys: catalog-id
```

**Comment by itaiad200** [comment]
I wasn't able to reproduce this issue. Can you retry with 0.106.0? It included a fix for resiliency of the catalog id value

**Comment by kesarwam** [comment]
Upgraded to 0.106.0 but still getting the same error:
```
ak@Amits-MacBook-Pro ~ % lakectl
error unmarshal configuration: 1 error(s) decoding:

* 'Metastore.Glue' has invalid keys: catalog-id
```

This is my .lakectl.yaml:
```
credentials:
  access_key_id: 111
  secret_access_key: 222
server:
  endpoint_url: https://treeverse.us-east-1.lakefscloud.io
metastore:
  type: glue
  glue:
    catalog-id: 333
    region: us-east-1
    profile: amit # implies using a credentials file
```

**Comment by kesarwam** [comment]
I think key should be `catalog_id` instead of `catalog-id` (underscore instead of dash). It is documented wrong here:
https://docs.lakefs.io/integrations/glue_hive_metastore.html

**Comment by kesarwam** [comment]
while `lakectl metastore` command uses `catalog-id`

**Comment by kesarwam** [comment]
We should use same key name everywhere

**Comment by kesarwam** [comment]
`lakectl metastore copy` command is working now after setting `metastore.glue.catalog_id` in the .lakectl.yaml config file.

But still getting error with `lakectl metastore copy-schema` and `lakectl metastore copy-all` commands:
```
ak@Amits-MacBook-Pro ~ % lakectl metastore copy-schema \
--from-client-type glue \
--from-schema amit_glue_hive_demo \
--to-client-type glue \
--to-schema amit_glue_hive_demo_glue_test_branch \
--to-branch glue_test_branch
copy amit_glue_hive_demo -> amit_glue_hive_demo_glue_test_branch
failed to replace branch name with location: 'file:/tmp/spark-warehouse/amit_glue_hive_demo.db' and branch: 'glue_test_branch': got empty schema or host wile parsing location url, location should be schema://host/path
Error executing command.
ak@Amits-MacBook-Pro ~ % lakectl metastore copy-all \
--from-client-type glue \
--from-address amit_glue_hive_demo \
--to-client-type glue \
--to-address amit_glue_hive_demo_glue_test_branch \
--branch glue_test_branch
copy amit_glue_hive_demo -> amit_glue_hive_demo_glue_test_branch
got empty schema or host wile parsing location url, location should be schema://host/path
```

**Comment by itaiad200** [comment]
I'm able to reproduce it with the same parameters. Something with the location of the database `file:/tmp/spark-warehouse/amit_glue_hive_demo.db` doesn't work (we expect `file://...`). Continue to look at this

**Comment by itaiad200** [comment]
@kesarwam Have you tried it with a DB in glue with location in S3 instead of a temp file?

**Comment by kesarwam** [comment]
I just tried with a DB in glue with location in S3 (`s3://amit-glue/`). Now I get a different error:
```
ak@Amits-MacBook-Pro lakeFS-samples % lakectl metastore copy-schema \
--from-client-type glue \
--from-schema amit_glue_hive_demo \
--to-client-type glue \
--to-schema amit_glue_hive_demo_glue_test_branch \
--to-branch glue_test_branch
copy amit_glue_hive_demo -> amit_glue_hive_demo_glue_test_branch
failed to replace branch name with location: 's3://amit-glue/' and branch: 'glue_test_branch': encoded path is malformed
Error executing command.
```

```
ak@Amits-MacBook-Pro lakeFS-samples % lakectl metastore copy-all \
--from-client-type glue \
--from-address amit_glue_hive_demo \
--to-client-type glue \
--to-address amit_glue_hive_demo_glue_test_branch \
--branch glue_test_branch
copy amit_glue_hive_demo -> amit_glue_hive_demo_glue_test_branch
encoded path is malformed
Error executing command.
```

**Comment by kesarwam** [comment]
I changed S3 location `s3://amit-glue` (without / at the end) then `lakectl metastore copy-schema` command works. But `lakectl metastore copy-all` still fails because it is trying to copy to same schema:

```
ak@Amits-MacBook-Pro lakeFS-samples % lakectl metastore copy-all \
--from-client-type glue \
--from-address amit_glue_hive_demo \
--to-client-type glue \
--to-address amit_glue_hive_demo_glue_test_branch \
--branch glue_test_branch
copy amit_glue_hive_demo -> amit_glue_hive_demo_glue_test_branch
table amit_glue_hive_demo.customers -> amit_glue_hive_demo.customers
table amit_glue_hive_demo.orders -> amit_glue_hive_demo.orders
table amit_glue_trino_demo.customers -> amit_glue_trino_demo.customers
got empty schema or host wile parsing location url, location should be schema://host/path
```

**Comment by guy-har** [comment]
Hi @kesarwam, 
the `--from-address` and `--to-address` fields in `lakectl metastore copy-all` might be confusing.
They are used only when the type is `hive`.
The `copy all` command should be used to copy all data between different metastores, that is (`hive` -> `glue`, `glue` -> `hive`, `hive:address1` -> `hive:address2`)

It seems like there are two things to fix to make things clear:
1. Don't allow providing  `--from-address` or `--to-address` when the type is `glue`
2. when running `copy-all` on the same metastore return "copy-all can't be done within the same metastore"

**Comment by kesarwam** [comment]
Can we fix the doc: https://docs.lakefs.io/integrations/glue_hive_metastore.html#glue
Key should be catalog_id instead of catalog-id (underscore instead of dash) in .lakectl.yaml.

**Comment by itaiad200** [comment]
Closing - doc improvements are under #6459
