### ISSUE TITLE
[Bug]: Quickstart is broken in v0.106.0

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6400]
### What happened?

1. Go to https://docs.lakefs.io/quickstart/launch.html
2. As instructed, run 
```
$ docker run --name lakefs --pull always \
             --rm --publish 8000:8000 \
             treeverse/lakefs:latest \
             run --quickstart
```

3. Fails:

```
latest: Pulling from treeverse/lakefs
Digest: sha256:c54ee0daaa98dd0e673de791551221c70616a3f733a7ada883bf93a75374bd8d
Status: Image is up to date for treeverse/lakefs:latest

WARNING!

Using quickstart parameters configuration. This is suitable only for testing! It is NOT SUPPORTED for production.
quickstart mode can only run with local settings

$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ 
```

😢 

### Expected behavior

Docker container should launch successfully

### lakeFS version

v0.106.0

**Comment by rmoff** [comment]
A separate issue to log: `quickstart mode can only run with local settings` isn't clear that it's a fatal error and should be.

**Comment by rmoff** [comment]
https://github.com/treeverse/lakeFS/blob/master/README.md#getting-started is also broken

**Comment by rmoff** [comment]
The error's being thrown [here](https://github.com/treeverse/lakeFS/blob/master/cmd/lakefs/cmd/root.go#L51-L54) but I'm not clear why. The [database](https://github.com/treeverse/lakeFS/blob/master/pkg/config/defaults.go#L26) and [blockstore](https://github.com/treeverse/lakeFS/blob/master/pkg/config/defaults.go#L28) are both set [here](https://github.com/treeverse/lakeFS/blob/master/pkg/config/defaults.go#L22C23-L22C23). 

The logic was added as part of #6217 — @N-o-Z can you help here?

**Comment by N-o-Z** [comment]
> The error's being thrown [here](https://github.com/treeverse/lakeFS/blob/master/cmd/lakefs/cmd/root.go#L51-L54) but I'm not clear why. The [database](https://github.com/treeverse/lakeFS/blob/master/pkg/config/defaults.go#L26) and [blockstore](https://github.com/treeverse/lakeFS/blob/master/pkg/config/defaults.go#L28) are both set [here](https://github.com/treeverse/lakeFS/blob/master/pkg/config/defaults.go#L22C23-L22C23).
> 
> The logic was added as part of #6217 — @N-o-Z can you help here?

@rmoff  I see the error. It's an emberrasing  logical condition bug. 🤦🏽 
I'll open a PR for it in a minute
