### ISSUE TITLE
local clone should not leave an empty-but-not-empty folder if it fails

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6413]
This behaviour is confusing for the user

```
➜  ~ ~/git/lakeFS/lakectl local clone  lakefs://quickstart/main/images ./images2
download duckdb-editor-02.png failed: Get "http://minio:9000/quickstart/data/glpo6pv3chgc777qq2q0/cjdnv7f3chgc777qq2ug?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=mi
nioadmin%2F20230815%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230815T165437Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=a7c743b4467e4b297ace94566d1a8741
1d70305e0f0a5ea75c607e5903c385ba": dial tcp: lookup minio: no such host
Error executing command.

➜  ~ ~/git/lakeFS/lakectl local clone  lakefs://quickstart/main/images ./images2
directory '/Users/rmoff/images2' exists and is not empty
Error executing command.
```

How can it fail (I got an error) but not fail (it's not re-runnable because the failed checkout left a not-empty folder) ?

(rhetorical question - I *know* why, but it's confusing nonetheless)

Suggestion: if an action fails it should rollback so that it can be re-run by the user. 
Leaving a bunch of zero-byte files around locally is no help to man nor beast

**Comment by N-o-Z** [comment]
@rmoff the clone operation is composed from an init and pull steps.
If the pull fails we are left with an init'ed directory (contains the lakefs index file). To fix this state you can either pull force or checkout the directory.
Regarding rollback - this is a larger issue than just clone, it pertains to all sync operations and can be complex to implement and prone to bugs. In my opinion we should not try to handle these states but rather let the user decide how to proceed using the their knowledge of the previous, current and desired state and with the help of the local commands.
There's an [issue](https://github.com/treeverse/lakeFS/issues/6409) discussing how we can "invalidate" a directory in case of a failure mid flow

**Comment by rmoff** [comment]
Thanks for the explanation of how it works. 

BTW I looked for force but couldn't see it as an option

```
$ lakectl local clone --help
Clone a path from a lakeFS repository into a new directory.

Usage:
  lakectl local clone <path uri> [directory] [flags]

Flags:
      --gitignore         Update .gitignore file when working in a git repository context (default true)
  -h, --help              help for clone
  -p, --parallelism int   Max concurrent operations to perform (default 25)
      --pre-sign          Use pre-signed URLs when downloading/uploading data (recommended) (default true)

Global Flags:
      --base-uri string      base URI used for lakeFS address parse
  -c, --config string        config file (default is $HOME/.lakectl.yaml)
      --log-format string    set logging output format
      --log-level string     set logging level (default "none")
      --log-output strings   set logging output(s)
      --no-color             don't use fancy output colors (default when not attached to an interactive terminal)
      --verbose              run in verbose mode
```

**Comment by N-o-Z** [comment]
Clone doesn't support a force flag. Only pull. Once the folder already went through init there's no need to clone again. Either pull (force) or checkout will do
