### ISSUE TITLE
Uploading a folder with many objects in results in duplication of folder in web UI object list

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6417]
1. Run https://github.com/treeverse/lakeFS-samples/blob/main/docker-compose.yml
2. Create sample repo
3. Upload `data` folder from https://github.com/treeverse/lakeFS-samples/ through web UI
4. Wait for upload to complete
5. Puzzle over repeated `data` folders listed in the web UI each with the same contents
    <img width="1484" alt="image" src="https://github.com/treeverse/lakeFS/assets/3671582/cf771ca2-da44-439e-b98b-4b208382d85a">

🎥 Screencap: https://img.rmoff.net/4qvXwFPS

lakeFS v0.106.0

**Comment by rmoff** [comment]
If I upload the objects to a `dev` branch and merge it into `main` the web UI then looks just fine

<img width="1490" alt="CleanShot_2023-08-16_at_11 21 36@2x" src="https://github.com/treeverse/lakeFS/assets/3671582/11ef0558-4190-428e-9726-fd5e3d4a98cd">

**Comment by nopcoder** [comment]
This was fixed in a newer version of lakefs
