### ISSUE TITLE
`lakectl local commit` failed: upload to backing store: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6421]
I am using https://github.com/treeverse/lakeFS-samples/blob/main/docker-compose.yml along with `lakectl` run locally from the Docker host machine, connecting to lakeFS on Docker which in turn is using MinIO for its object store (also on Docker).  

When I do a `commit` the upload fails: 

```
failed: upload to backing store: MissingRegion: could not find region configuration
```

---

Steps to reproduce

1. Run https://github.com/treeverse/lakeFS-samples/blob/main/docker-compose.yml
2. Configure local `lakectl` for connecting to & auth for lakeFS in Docker container
3. Manually upload the contents of the `/data` folder in the samples github repo to a lakeFS repo called `quickstart`
4. Clone a path into local `orion` folder

    ```
    $ lakectl local clone lakefs://quickstart/main/data/OrionStar/ orion --pre-sign=false
    ```
5. Switch to dev branch

    ```
    $ lakectl local checkout . --ref dev
    ```

6. Create a `RATINGS.csv` file locally, and delete some files `rm -v EMPLOYEE_*`

7. Check status

    ```
    $ lakectl local status
    
    diff 'local:///Users/rmoff/work/orion' <--> 'lakefs://quickstart/7eaeafd3fb90df419ca26eca69ba2b153eae13bd3dccf80ba47cbed1260cb0c1/data/OrionStar/'...
    diff 'lakefs://quickstart/7eaeafd3fb90df419ca26eca69ba2b153eae13bd3dccf80ba47cbed1260cb0c1/data/OrionStar/' <--> 'lakefs://quickstart/main/data/OrionStar/'...
    
    ╔════════╦═════════╦═══════════════════════════╗
    ║ SOURCE ║ CHANGE  ║ PATH                      ║
    ╠════════╬═════════╬═══════════════════════════╣
    ║ local  ║ removed ║ EMPLOYEE_ADDRESSES.csv    ║
    ║ local  ║ removed ║ EMPLOYEE_DONATIONS.csv    ║
    ║ local  ║ removed ║ EMPLOYEE_ORGANIZATION.csv ║
    ║ local  ║ removed ║ EMPLOYEE_PAYROLL.csv      ║
    ║ local  ║ added   ║ RATINGS.csv               ║
    ╚════════╩═════════╩═══════════════════════════╝
    ```

8. Try to commit the changes 
    
    ```
    $ lakectl local commit . -m "Remove employee data and add ratings information" --pre-sign=false
    
    Getting branch: main
    
    diff 'local:///Users/rmoff/work/orion' <--> 'lakefs://quickstart/7eaeafd3fb90df419ca26eca69ba2b153eae13bd3dccf80ba47cbed1260cb0c1/data/OrionStar/'...
    
    diff 'lakefs://quickstart/38df1480d835fe52dc6db31b87ef35b78403d0c9c621c74a6d032c686551abc5/data/OrionStar/' <--> 'lakefs://quickstart/main/data/OrionStar/'...
    delete remote path: EMPLOYEE_ADDRESSES.~ ... fail! [%0 in 8ms]
    delete remote path: EMPLOYEE_ORGANIZATI~ ... fail! [%0 in 8ms]
    delete remote path: EMPLOYEE_DONATIONS.~ ... fail! [%0 in 8ms]
    delete remote path: EMPLOYEE_PAYROLL.csv ... fail! [%0 in 8ms]
    upload RATINGS.csv                       ... done! [6.86KB in 6ms]
    upload RATINGS.csv failed: upload to backing store: MissingRegion: could not find region configuration
    Error executing command.
    ```

**Comment by N-o-Z** [comment]
The issue is this - and it impacts more than just the local commands:

When uploading files, whether using `fs upload` with --direct flag or indirectly by a `local commit` command we create an S3 adapter which uses the default AWS configuration. Some things are taken from env variables (such as the region) and some are using default parameters (endpoint url). The problem is that lakectl currently does not have block adapter configuration parameters.
Bottom line is - we currently support the `direct` operations only on **AWS S3**.
The problem is more severe in `local` since we must use the direct approach to add the `x-client-mtime` metadata to the uploaded object otherwise we will continue to see changes between server and local.
One WA I can think of is to sync back after every commit - to align the mtime but this is very inefficient - it will mean we will have to download everything we uploaded again and will be very confusing to the user

**Comment by ozkatz** [comment]
So from what I understand we currently do not support committing to local storage at all?

**Comment by ozkatz** [comment]
I would suggest a "fix-then-really-fix" approach here:
1. short term fix: if local storage, upload by using the S3 gateway (`PutObject` [respects metadata headers](https://github.com/treeverse/lakeFS/blob/master/pkg/gateway/operations/putobject.go#L269)). We already have all the required info (access key and secret, as well as endpoint).
2. long term fix: allow setting metadata fields in OpenAPI's Put Object. I'd suggest doing this now but currently adding an optional parameter to existing endpoints breaks the Java generated client as it is not forwards compatible.

WDYT?

**Comment by N-o-Z** [comment]
> I would suggest a "fix-then-really-fix" approach here:
> 
> 1. short term fix: if local storage, upload by using the S3 gateway (`PutObject` [respects metadata headers](https://github.com/treeverse/lakeFS/blob/master/pkg/gateway/operations/putobject.go#L269)). We already have all the required info (access key and secret, as well as endpoint).
> 2. long term fix: allow setting metadata fields in OpenAPI's Put Object. I'd suggest doing this now but currently adding an optional parameter to existing endpoints breaks the Java generated client as it is not forwards compatible.
> 
> WDYT?

1. We need to use this approach for all block adapters (maybe except for S3) when using --direct flag
2. Sounds good

**Comment by N-o-Z** [comment]
Thanks @nopcoder, per the discussion will proceed with no.2
