### ISSUE TITLE
Catalog export hooks

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#6461]
## Goals

Working with External Catalogs (or systems that rely soley on an external catalog) is a current point of friction.
There are several well known formats that exist today that could help export existing tables in lakeFS into a "native" object store representation
which don't require copying the data outside of lakeFS.

Since these are metadata representations, they could be applied using hooks to automate the process and reduce the friction.

## Catalogs and query engines to support (by order of importance)

* Unity Catalog (+ Databricks SQL Warehouses)
* Glue Catalog (+ Athena)
* Snowflake
* BigQuery
* Redshift

## High Level Design

Tables in lakeFS are already declared using a [standard mechanism]().

## Extractors

Extractors take a declared table and map it into the following structure:

1. Schema (using names and types as declared in Parquet)
1. Partition Spec (columns and their values)
1. list of files in the form of `[](partition, []physical_address{path, size, *stats})`

Such an extractor will be implemented for any type of table supported by lakeFS (`HiveExtractor`, `DeltaExtractor`, `IcebergExtractor`, ...)

## Exporters

Take the output of an [Extractor](#extractors) and write it in a given format

* `SymlinkExporter` - Writes metadata for the table using Hive's [`SymlinkTextInputFormat`](https://svn.apache.org/repos/infra/websites/production/hive/content/javadocs/r2.1.1/api/org/apache/hadoop/hive/ql/io/SymlinkTextInputFormat.html)
* `DeltaExporter` - Writes a "table" with a single log entry with the schema and one "add" entry per underlying object (+its metadata)
* `IcebergExporter` - Writes a "table" with a single metadata file & single manifest list, with manifests pointing to the data files

## Hook Wrappers

Each extractor & exporter will be exposed as a set of lua functions that will allow writing reusable hooks to connect various types of tables to different catalogs:

## Flow

```mermaid
sequenceDiagram
    Lua Hook->>Exporter: export request
    Exporter->>Extractor: Extract table
    Extractor->>Table Registry: Read table metadata
    Extractor->>Exporter: return translated table structure
    Exporter->>Object Store: materialize an exported table
    Exporter->>Catalog: register object store location
    Query Engine-->Catalog: Query
    Query Engine-->Object Store: Query
```

### symlink_exporter.lua

Read extracted table, and output a symlink structure in the following hieraracy:

```text
${storageNamespace}
    _lakefs/
        exported/
            ${ref}/
                ${commitId}/
                    ${tableName}/
                        p1=v1/symlink.txt
                        p1=v2/symlink.txt
                        p1=v3/symlink.txt
                        ...
```
Each `symlink.txt` will include the absolute URI on the underlying object store for each parquet file.

### glue_exporter.lua

Runs the same logic as `symlink_exporter` and Register the symlink table in Glue:

```sql
CREATE OR REPLACE EXTERNAL TABLE `branch_or_tag`.`t1_<commit_id>` (
    -- schema from extracted table
) PARTITIONED BY (
    -- partition columns from extracted table
) ROW FORMAT SERDE 'parquet.hive.serde.ParquetHiveSerDe'
  STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
  LOCATION '${storageNamespace}/_lakefs/exported/main/abc123/t1/';

ALTER TABLE `branch_or_tag`.`t1_<commit_id>` RENAME TO `branch_or_tag`.`t1`;
```

***Note:** Athena does [support the Delta protocol](https://docs.aws.amazon.com/athena/latest/ug/delta-lake-tables.html), however, upstream Trino has an [open issue](https://github.com/trinodb/trino/issues/17011) about absolute URIs not being supported for Delta tables, with an [outstanding PR](https://github.com/trinodb/trino/pull/17038) to fix that, but we'll have to wait for it to be merged and upstreamed and released into Athena.. could be a while!*

This bug also appears to break Glue Crawler's [ability to generate symlinks from Delta tables](https://aws.amazon.com/blogs/big-data/crawl-delta-lake-tables-using-aws-glue-crawlers/), as it also breaks absolute URLs.

### bigquery_exporter.lua

Runs the same logic as `symlink_exporter` and Register the symlink table in [BigQuery](https://cloud.google.com/blog/products/data-analytics/bigquery-manifest-file-support-for-open-table-format-queries/):

```sql
CREATE EXTERNAL TABLE IF NOT EXISTS `my-project.<branch>.t1`
WITH PARTITION COLUMNS (p string)
WITH CONNECTION `my-project.us.bl_connection`
OPTIONS (
    hive_partition_uri_prefix = "${storageNamespace}/_lakefs/exported/main/abc123/t1/",
    uris = ['${storageNamespace}/_lakefs/exported/main/abc123/t1/*/symlink.txt'],
    file_set_spec_type = 'NEW_LINE_DELIMITED_MANIFEST',
    format="PARQUET"
);
```

### delta_exporter.lua

Read extracted table, and output a "dummy" delta table as the following file:

```text
${storageNamespace}/_lakefs/exported/${ref}/${commitId}/${tableName}/_delta_log/00000000000000000000.json
```
This file will include the schema of the extracted table, and a set of `"add" {}` declartions that describe the underlying objects, their metadata (size, stats) and partition columns they belong to.

### unity_exporter.lua

Runs the same logic as `delta_exporter.lua` and Register the table in Unity:

```sql
CREATE TABLE my-project.<branch>.t1 USING delta LOCATION "${storageNamespace}/_lakefs/exported/t1/<commit_id>";
```

### Example Hook:

```yaml
---
name: DeltaToGlue
description: Export tables to Glue
on:
  post-commit:
  post-create-branch:
  post-create-tag:
hooks:
  - id: glue_exporter
    type: lua
    properties:
      script_path: scripts/glue_exporter.lua
      args:
        tables: "*" # default
        schema_pattern: "${branch_or_tag}"
        table_pattern: "${escaped_table_name}"
```

## User Experience

Once hooks are set up, querying lakeFS data from e.g. Athena, Trino and other catalog-dependant tools looks like this:

```sql
use main;
use my_branch; -- any branch
use v101; -- or tag

SELECT * FROM users 
INNER JOIN events 
ON users.id = events.user_id; -- SQL stays the same, branch or tag exist as schema
```

## Open questions

1. Cleanup of old commits?
1. Limitations?
1. Alternative designs?

**Comment by TinoSM** [comment]
Adding some challenges I'm facing/worried about regarding naming convention:

1. How to name schemas/databases with multiple repositories? (i.e. what if I want to have a single Hive/Glue catalog which allows to query all tables in my datalake on the main branch)
2. How to map special characters in branch names with SQL-supported database names (in Spark only "_" and alphanum), same with tablenames
2.1. Can we limit which characters can be used to create branches or folders
2.2 How to map word-separators and folder-separators to sql-supported separators ("_"?)
3. How to limit the export (i.e. maybe only export when branches are named X, or just don't export commits).

Sharing a little bit of my own proposal:
1. Adding repository name upfront as part of the schema (like "${repoName}__ ${branchName}")
2.1. Add a "regexp" configuration (customizable) which Admins ("data governance") can use to limit repository and branch (and folder?) names in LakeFS.
2.2. Replace "-" with "_" and folder/repo+branch separators with "__". This is an idea, but it needs to be consistent so users who use both LakeFS and Tables can correlate them easily. <-- Can we make this customizable in the hook?

**Comment by ozkatz** [comment]
Thanks @TinoSM ! Good questions.
Regarding 1 - Agree, there should be a way to include the repository ID in the schema name!
Regarding 2 - This is already possible using a `pre-create-branch` and `pre-create-tag` hook:

```yaml
# _lakefs_actions/validate_branch_name.yaml
name: validate-lower-case-branches 
on:
  pre-create-branch:
hooks:
  - id: check_branch_id
    type: lua
    properties:
      script: |
        regexp = require("regexp")
        if not regexp.match("^[a-z0-9\\_\\-]+$", action.branch_id) then
          error("branches must be lower case, invalid branch ID: " .. action.branch_id)
        end
```

This lives under `_lakefs_actions/` inside a repository, so you could always set an RBAC policy to only allow admins/ops to configure that. Does that make sense?
We can always add simple transformations in the hook definition to allow replacing specific chars.

**Comment by TinoSM** [comment]
Yup, didn't think on actions, but it does solve the issue :). Although it would be handy as a server-level configuration/feature imo (for corporate world).

**Comment by Isan-Rivkin** [comment]
> Tables in lakeFS are already declared using a [standard mechanism](https://github.com/treeverse/lakeFS/issues/6461).
@ozkatz i think you used incorrect link here ^

**Comment by Isan-Rivkin** [comment]
@ozkatz I looked at the [s3_hive_manifest_exporter.lua](https://github.com/treeverse/lakeFS/blob/master/examples/hooks/s3_hive_manifest_exporter.lua) script you  wrote, that helps understand even better the design.

Let's take Glue Catalog for example: 
It seems to me that the script almost get the job done for Glue, minus the table creations but mostly get it done. 
Let's assume we add we add a glue library to our Lua runtime and then be able to complete the flow still, it's not standardized and seems very low level for end users. 
Instead, if we had a library embedded into our Lua VM for exporter and importer logic would it be better? ("Pseudo lua") Is this directionally correct? 

```lua
-- For simplicity reasons ignoring configuration params (i.e AWS creds, glue metadata). 
exporter = require("catalog-export")
--- Internally will call the Symlink Extractor, context is abstraction of all the required lakeFS inputs
table = exporter.extract_table("symlinks", args.context)
--- Put the Symlinks in S3 
exporter.materialize_table(table)
--- Call SQL query or API's to update the new table / version in Glue 
exporter.register_glue_table_location(table)
```

**Comment by Isan-Rivkin** [comment]
Created initial issues, can be filtered with [export-hooks](https://github.com/treeverse/lakeFS/issues?q=is%3Aissue+is%3Aopen+label%3Aexport-hooks) label.

When the current issues are done we will have Table definition (_lakefs_tables/), Symlink Exporter, Glue Exporter and a repeatable way to keep adding exporters (Unity, Delta, Snowflake etc). 

- https://github.com/treeverse/lakeFS/issues/6573
- https://github.com/treeverse/lakeFS/issues/6574
- https://github.com/treeverse/lakeFS/issues/6575

(CC @itaiad200 , @arielshaqed )

**Comment by Tahasadiki** [comment]
This looks great! @ozkatz

A few comments I have are:

1. I think it's important to provide a way to de-register schemas and tables when the corresponding branch or table declaration is removed, similar to how we register them on new branches or tags.
2. With the catalog exporters relying on lakefs actions, improving the user experience (UX) becomes even more important. Specifically, two areas that would be extremely helpful to improve are:
    a. UI: Add the ability to filter the list of Action runs by "status" and "branch," and order them by dates.
    b. Alerting: We should be alerted when an Action fails. Currently, we use another hook that runs on `if: failure()` to send alerts to PagerDuty. However, this setup feels a bit clunky, and there have been instances where the hook failed to send alerts due to transient issues. There is an opportunity to provide a built-in way to listen to Action failure events and send notifications to specified destinations like PagerDuty or Email.
4. Regarding the point raised by @TinoSM about naming conventions, it's worth noting that identifiers (e.g., schema names) in Unity Catalog are case-insensitive, while LakeFS branch names are case-sensitive. This means that we could create two branches in LakeFS: "my_branch" and "MY_BRANCH," which would end up pointing to the same schema in Unity. We need to find a way to handle this collision. One approach could be using a hook to only consider certain types of branches (e.g., only branches in lowercase).
