### ISSUE TITLE
UI should indicate that a security advisory was published

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6467]
The current indication is not very informative on the risks involved in running an obsolete version: 
![Image](https://github.com/treeverse/lakeFS/assets/9861474/6b6fda5c-75c3-4c22-a099-2cb3d6a0e116)

**Comment by Isan-Rivkin** [comment]
@itaiad200 for some context, since version [v0.98.0](https://github.com/treeverse/lakeFS/blob/master/CHANGELOG.md#v0980) we show a notification badge when upgrade is recommended introduced in PR #5608.
So in terms of visibility that's better, we can of course add more.

**Comment by itaiad200** [comment]
Right - it actually looks like this for newer versions:


![Image](https://github.com/treeverse/lakeFS/assets/9861474/c2d84096-acd8-49ca-a043-a92fc85fba5b)

**Comment by itaiad200** [comment]
I think we should at least link to the security advisories:
https://github.com/advisories?query=lakefs

**Comment by itaiad200** [comment]
@ozkatz is this better?


![Image](https://github.com/treeverse/lakeFS/assets/9861474/35aa269f-e9c0-45f2-944e-62bf553b1477)
