### ISSUE TITLE
UI: When using local settings pressing on Create Sample Repository button does nothing

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#6470]
Under the hood we get a 400 response:
![image](https://github.com/treeverse/lakeFS/assets/3787958/c9dd7e81-ecc0-423b-8977-ab81b89374ee)

**We are able** to create a sample repo from the create repository view
![image](https://github.com/treeverse/lakeFS/assets/3787958/e9ecedce-bb58-49c7-b6f7-39bee0f9f428)

**Comment by nopcoder** [comment]
I assume that the local directory exists and the server retruns an error, right?

**Comment by N-o-Z** [comment]
> I assume that the local directory exists and the server retruns an error, right?

Not sure I understand your question.
When pressing on the button nothing happens. When creating the repository with the Add sample data checkbox checked - it creates the sample data as expected
