### ISSUE TITLE
 lakectl - Add default endpoint_url 

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#649]
currently, lakectl uses the endpoint_url set in the lakectl config file(~/.lakectl.yaml)
In case it is not set we receive an error 
 For example:
```console
user@MacBook-Pro ~ % lakectl repo list
Error executing command: Get "https:///api/v1/repositories?amount=-1": http: no Host in request URL
```

The default host should be `http://127.0.0.1:8000`

**Comment by abraham-john-paul** [comment]
HI can i work on this issue?

**Comment by YaelRiv** [comment]
All yours! Thanks for your help.

**Comment by YaelRiv** [comment]
@abraham-john-paul Assigned to you! Let us know if you need any help. 

Many thanks!

**Comment by eylonronen** [comment]
Hi, I know it's assigned to @abraham-john-paul but I have actually solved it a week ago, and just been on holydays so I couldn't fix the required changes in the PR. I have now reopened it so you are welcome to use it :)

**Comment by YaelRiv** [comment]
Thanks @eylonronen - we are reviewing. 

@abraham-john-paul apologies for our confusion here. Somehow we missed it. Happy to help find another good issue to work on.

**Comment by abraham-john-paul** [comment]
Sure , no problem 🙂
