### ISSUE TITLE
[Bug]: pdf cat not preview after Version 0.106.0

### ISSUE THREAD

**Issue by yinggoga** [treeverse/lakeFS#6517]
### What happened?

pdf cat not preview after Version 0.106.0
      
![image](https://github.com/treeverse/lakeFS/assets/27919234/2069efbc-5cc0-4b23-af35-bdb6b55a29ad)

### lakeFS version

0.106.0

### How lakeFS is installed

docker

### Relevant log output

```shell
lakeFS 0.106.0 - Up and running (^C to shutdown)...


     ██╗      █████╗ ██╗  ██╗███████╗███████╗███████╗
     ██║     ██╔══██╗██║ ██╔╝██╔════╝██╔════╝██╔════╝
     ██║     ███████║█████╔╝ █████╗  █████╗  ███████╗
     ██║     ██╔══██║██╔═██╗ ██╔══╝  ██╔══╝  ╚════██║
     ███████╗██║  ██║██║  ██╗███████╗██║     ███████║
     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝

│
│ If you're running lakeFS locally for the first time,
│     complete the setup process at http://127.0.0.1:8000/setup
│
│
│ For more information on how to use lakeFS,
│     check out the docs at https://docs.lakefs.io/quickstart/
│

│
│ For support or any other question,                            >(.＿.)<
│     join our Slack channel https://docs.lakefs.io/slack         (  )_
│

Version 0.106.0
```

**Comment by yinggoga** [comment]
Version 0.105.0 can preview pdf file
![image](https://github.com/treeverse/lakeFS/assets/27919234/b4b98179-7ade-46cb-b2b1-4f76a2042464)

**Comment by nopcoder** [comment]
Thanks for submitting the issue, the issue is related to a header returned by the server that prevents from the UI to render the content. X-Frame-Options DENY.

**Comment by yinggoga** [comment]
> Thanks for submitting the issue, the issue is related to a header returned by the server that prevents from the UI to render the content. X-Frame-Options DENY.

Thanks!
