### ISSUE TITLE
Replace alert in UI with nice modal in case of delete

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#653]
Currently, all the delete actions in the UI (such as delete object, revert, delete group, remove user, etc...) are followed by a confirmation message that is showed by an alert.

We would like to change them with a nice modal.

**Comment by shamikakumar** [comment]
Hey I would like to tackle this issue for the upcoming hacktoberfest. Do assign this to me, thanks!

**Comment by Dikshapurswani** [comment]
@guy-har Could you please assign this to me?

**Comment by arielshaqed** [comment]
@shamikakumar do you want to proceed with this, or would you prefer that I re-assign to @Dikshapurswani ?

**Comment by shamikakumar** [comment]
@arielshaqed I've started working on it so I would like to proceed, thanks!

**Comment by Dikshapurswani** [comment]
Any other issue I could work on?

**Comment by arielshaqed** [comment]
/@shamikakumar :
> @arielshaqed I've started working on it so I would like to proceed, thanks!

Great, looking forward to the PR!

@Dikshapurswani :
> Any other issue I could work on?

Sure, please look at any of these [issues with the hacktoberfest label](https://github.com/treeverse/lakeFS/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).  Yesterday we noticed that it was a bit hard to discover, so now it's even on [the front page](https://github.com/treeverse/lakeFS).

Thanks!

**Comment by Dikshapurswani** [comment]
Okay!
Thank you!
