### ISSUE TITLE
lakectl autocomplete nouns

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#654]
Have the completions code complete our "nouns" when relevant.
Example:
```
lakectl fs upload --source <tab> // should suggest files
lakectl repo delete <tab> // should suggest repositories names
```

**Comment by kichloo** [comment]
@nopcoder Though I am beginner in this, I can complete it with some help. So, I would like to take this issue.

**Comment by nopcoder** [comment]
Sure, let me know if you have questions about the issue or the code.

**Comment by kichloo** [comment]
Yes, kindly help me regarding it!

**Comment by nopcoder** [comment]
@kichloo we are using Cobra, here you can find information about the current completion - https://github.com/spf13/cobra/blob/master/shell_completions.md
There you can also find information on how to add "Completion of nouns" to each command we mapped.
Our documentation https://docs.lakefs.io/reference/commands.html#commands-cli-reference holds the reference of all the command, but you can also find the same in the standard project structure based on Cobra.

**Comment by avats-dev** [comment]
@kichloo are you still working on this one? Let me know, I want to try this one.

**Comment by johnnyaug** [comment]
Hey @kichloo, still working on this?

**Comment by kichloo** [comment]
The issue is now open!

**Comment by fumblehool** [comment]
Hi, I can work on this if nobody is currently working on it.

**Comment by nopcoder** [comment]
@fumblehool still interested?

**Comment by fumblehool** [comment]
@nopcoder Unfortunately, I'm unable to work on it right now.

**Comment by whoAbhishekSah** [comment]
Hello @nopcoder I would like to work on this issue. Can you assign it to me?
