### ISSUE TITLE
WebUI delete losing focus on refresh

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#655]
Delete refresh updates the UI and focus back at the top of the listing.
When you have to scroll to locate your item, the delete operation will trigger a refresh that will get you back to the top of the list.

**Comment by hi-18-K** [comment]
I can solve this issue! Could you assign it to me?

**Comment by arielshaqed** [comment]
> I can solve this issue! Could you assign it to me?

Cool, thanks!  Let us know if you need help.  And (of course) looking forward to your PRs.

**Comment by iamRishabh07** [comment]
Hi, I would like to work on this issue,

**Comment by YaelRiv** [comment]
Hey @iamRishabh07! Thanks for your interest and willingness to help. 
This is already assigned to @hi-18-K.

Let us know if you need help finding another suitable issue :)

**Comment by hi-18-K** [comment]
sir/mam, I have tried a solution of saving the scroll position on click of delete button and trigrring a scrollTo() method after a time lag(ie after refresh is done after deleting an object) . I have done this on my js file hosted locally. I am trying to install lakefs via docker with the help of given tutorial on youtube(having installed docker and pulling official lakefs image).But it is showing this error:-
![Screenshot from 2020-10-03 13-06-50](https://user-images.githubusercontent.com/46860508/94986090-68a8b280-0579-11eb-948d-8cada73655bd.png)

**Comment by hi-18-K** [comment]
I am first time using docker so please explain in a bit simple way what should I do..

**Comment by johnnyaug** [comment]
Hey @hi-18-K, still working on this?

**Comment by hi-18-K** [comment]
Yes sir, actually I had a project submission pending(on 11th oct), initially I tried using js scrollTo which I need to modify a bit, also this is my first open source contribution in full scale project that's why it took so much time... I will submit this work on or before 17th oct.

**Comment by johnnyaug** [comment]
No worries :slightly_smiling_face:, take your time, join our Slack if you need some help

**Comment by nopcoder** [comment]
@hi-18-K why updates or partial work related to this issue that you have?

**Comment by hi-18-K** [comment]
I have created PR. Was much confused how and where to place code. I have changed webui -> src -> actions -> objects.js.
The code is running well on my webpage in localhost environment, please let me know if it is doing something wrong in LakeFS.
I was confused about where to place the snippet and how to test...which is why it took so much time.
