### ISSUE TITLE
Skip building and pushing docker image for existing tags

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#656]
In Nessie Github workflow, docker image is always built (tagged with git sha) and pushed to ECR.
It should be avoided when that image already exists. It's causing failures when workflows are rerun for the same tag.

**Comment by indhupriya** [comment]
Hi @itaiad200 Can I work on this issue?

**Comment by YaelRiv** [comment]
All yours @indhupriya!

Thanks for giving us a hand. We're here if you need any assistance.

**Comment by indhupriya** [comment]
I plan to use describe-image to check if the image tag exists, if it doesnt then build and push the image
```
describe_image="$( aws ecr describe-images --repository-name=<repository_name> --image-ids=imageTag=<tag> 2> /dev/null )"
if [[ $? == 0 ]]; then
    #build and push docker image
fi
```

Is this okay?

**Comment by itaiad200** [comment]
Sounds like a plan! Let us know if you need any assistance.

**Comment by indhupriya** [comment]
Hi @itaiad200 @YaelRiv  is there an easier way to test my solution instead of having to create a PR every time to test it out?

**Comment by itaiad200** [comment]
Hey @indhupriya, you can try [this](https://github.com/nektos/act) project for running github actions locally. However, having experiencing with it a bit I'm afraid that the quickest way is creating a PR and updating it with new commits. Notice you don't need to create a PR for each commit.

**Comment by indhupriya** [comment]
@itaiad200 when the action runs, I get an error at "Configure AWS Credentials" stage saying `Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers` am I supposed to pass any parameters explicitly?

**Comment by itaiad200** [comment]
@indhupriya Unfortunately Github actions have a limitation of accessing secrets for PRs originated from forked repos. I went ahead and created a draft [PR](https://github.com/treeverse/lakeFS/pull/757) in the original repo so that the actions can run. If all goes well, we can merge your PR and close mine. 
I know it's not the easiest way of testing your changes. Maybe try running your bash commands with a repo you have access to?

**Comment by indhupriya** [comment]
HI @itaiad200 My PR has new changes. Could you try it out on your PR? I have tested it on my local repository and have verified that it works.
