### ISSUE TITLE
Auth system test

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#657]
The current system tests use the default admin user for all requests.

The auth test should create users with less privileges and check actions are passing or blocked according to the permissions.

**Comment by khushijindal** [comment]
Hey @itaiad200! I want to work on this issue but can you please provide me with more details and guide me for the issue as I am new to open source.

**Comment by itaiad200** [comment]
Hey @khushijindal , thanks for helping out!

We check our system with tests with every PR/push to master. You can find examples to the current tests here: https://github.com/treeverse/lakeFS/tree/master/nessie.
Notice that none of the tests use any user other than the admin user.
The goal of the test is to create less privileged users with the API, and check that their permissions are enforced by lakeFS app. API: https://github.com/treeverse/lakeFS/blob/2501b5c70808d3d33922caff715c37b533b3c7c0/swagger.yml#L1.

P.S There are currently some limitations to running the system-tests for fork repos. However you can test your changes locally by running lakeFS and executing the tests against it. Refer to the quickstart section for running lakeFS instructions.

**Comment by AnshMishra2001** [comment]
Can I also work on this issue?

**Comment by itaiad200** [comment]
Hey @khushijindal ! I didn't hear back from you in the last week, any progress made on this issue?

**Comment by khushijindal** [comment]
@itaiad200 Sorry, I was somewhat busy lately. If @AnshMishra2001 wants to work too on this issue, he may please.

**Comment by itaiad200** [comment]
Thanks @khushijindal . @AnshMishra2001 it's yours! You can follow the instructions in previous comments. Feel free to reach out if you have any questions.

**Comment by itaiad200** [comment]
@AnshMishra2001 Are you still working on it?

**Comment by itaiad200** [comment]
@AnshMishra2001 ? Are you actively working on it or should I unassigned you?

**Comment by AnshMishra2001** [comment]
Yes. I got busy lately due tom exams.
