### ISSUE TITLE
[Bug]: lakectl fs upload pdf file can not be previewed

### ISSUE THREAD

**Issue by yinggoga** [treeverse/lakeFS#6578]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1.lakectl fs upload -s ./abc.pdf lakefs://myrepo/origin_corpus/abc.pdf
Path: origin_corpus/abc.pdf
Modified Time: 2023-09-11 11:03:22 +0800 CST
Size: 1722807 bytes
Human Size: 1.7 MB
Physical Address: s3://myrepo/data/gl888ejmc5vul9ff4rcg/cjv86ujmc5vul9ff4rfg
Checksum: 8219e0d2e6d7bc1537a2a352a44e6972
Content-Type: application/octet-stream
2.login webUI and preview pdf, failed，an object was downloaded
![image](https://github.com/treeverse/lakeFS/assets/27919234/a23bd11f-fdfd-4208-afcc-df4c64f8e7ef)
3.Re-upload the pdf after deleting it in webui，preview succeed
![image](https://github.com/treeverse/lakeFS/assets/27919234/9436ef6d-ac21-453b-ab30-2de565fb62ae)
![image](https://github.com/treeverse/lakeFS/assets/27919234/c2119436-1ee2-4496-9406-2e6ee0478cf7)
![image](https://github.com/treeverse/lakeFS/assets/27919234/e669179e-a109-47d2-916d-f16bdc381cca)
![image](https://github.com/treeverse/lakeFS/assets/27919234/c7fb491e-62ab-435c-8dfb-67708e080408)

### Expected behavior

lakectl fs upload pdf file can be previewed

### lakeFS version

0.109.0

### How lakeFS is installed

docker

### Relevant log output

```shell
time="2023-09-11T02:43:24Z" level=info msg="starting HTTP server" func=cmd/lakefs/cmd.glob..func8 file="cmd/run.go:328" listen_address="0.0.0.0:8000"

lakeFS 0.109.0 - Up and running (^C to shutdown)...


     ██╗      █████╗ ██╗  ██╗███████╗███████╗███████╗
     ██║     ██╔══██╗██║ ██╔╝██╔════╝██╔════╝██╔════╝
     ██║     ███████║█████╔╝ █████╗  █████╗  ███████╗
     ██║     ██╔══██║██╔═██╗ ██╔══╝  ██╔══╝  ╚════██║
     ███████╗██║  ██║██║  ██╗███████╗██║     ███████║
     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝

│
│ If you're running lakeFS locally for the first time,
│     complete the setup process at http://127.0.0.1:8000/setup
│
│
│ For more information on how to use lakeFS,
│     check out the docs at https://docs.lakefs.io/quickstart/
│

│
│ For support or any other question,                            >(.＿.)<
│     join our Slack channel https://docs.lakefs.io/slack         (  )_
│

Version 0.109.0
```

**Comment by nopcoder** [comment]
Unlike the web browser, when uploading a file using `lakectl` it doesn't perform content detection. No content type is treated as "application/octet-stream", and this is why clicking on it will download the object.

You can set the content type while uploading the file using lakectl:

```sh
lakectl fs upload -s ./abc.pdf --content-type "application/pdf" lakefs://myrepo/origin_corpus/abc.pdf
```

**Comment by yinggoga** [comment]
> 

ok，Thanks！Are there any other content types？

**Comment by nopcoder** [comment]
Yes, there are more - here you can see some common: https://github.com/nginx/nginx/blob/master/conf/mime.types

Currently `lakectl local` doesn't support upload with content type.
If it is something you required I suggest open an issue to capture the need and to discuss how we can support this capability.

**Comment by yinggoga** [comment]
Thanks
