### ISSUE TITLE
Schema under response shouldn't have a description (swagger)

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#658]
https://github.com/treeverse/lakeFS/blob/209ee80ccd151e65116c0866f25bebae47259dd0/swagger.yml#L392
Description should be deleted/moved to avoid swagger errors.

**Comment by knaveenr** [comment]
I would like to work on this issue, can I take this?

**Comment by Viswalahiri** [comment]
I'd like to work on this issue, can I take this up please?

**Comment by YaelRiv** [comment]
> I'd like to work on this issue, can I take this up please?

This one is already taken -there are other interesting issues under the Hactoberfest label that could be interesting. 

Let us know if you need any help.

**Comment by knaveenr** [comment]
@YaelRiv, looks like @kzuri is already up for the task, Please reassign issue to @kzuri
