### ISSUE TITLE
Import should not accept a path starting with /

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#6600]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Click on import
2. on the destiation either enter `/` or anything that start with `/`such us `/test`
3. This will create an empty `/` direcoty for example -` lakefs://iddo-import-test2/main//test/` which is confusing and prevents some functionality (like lakectl local) from working. 

### Expected behavior

We should not allow input of a path that starts with a `/`

### lakeFS version

0.107

### How lakeFS is installed

anywhere

### Contact details

iddo.avneri@treeverse.io

**Comment by nopcoder** [comment]
The improved import dialog by @johnnyaug makes reduce the risk that that use will add extra '/' to the destination as it is very clear that we render the full path under the branch while the address holds '/' after the branch name.

<img width="801" alt="image" src="https://github.com/treeverse/lakeFS/assets/8110/8a10c448-add1-455b-bc95-3ce544dc2258">

**Comment by nopcoder** [comment]
Trying to beat stale bot... @iddoavn do you think the above is enough or we like to do more than the new UI?

**Comment by iddoavn** [comment]
It’s good IMO
