### ISSUE TITLE
UI: Create Branch from Commit

### ISSUE THREAD

**Issue by clintonmonk** [treeverse/lakeFS#6615]
Currently, the LakeFS UI only supports creating new branches from either branches or tags. On occasion, we need to create branches from commits. We would like the LakeFS UI to also support creating a branch from a user-provided commit ID. This is already supported through the LakeFS API, so only the UI would need to be updated.

Additional background: In our data pipeline, each data processing step produces a LakeFS commit. We test changes to the data pipeline by running these data processing steps on a separate LakeFS branch from production. While testing, we might find that we need to re-run some of those steps but not all of them. To do this, we create a new LakeFS branch from an earlier commit on the current testing branch (to contain commits that we want to reuse but not contain commits for steps we want to re-run). Currently, we have to perform this using the LakeFS API or lakectl. It would be nice if we could create the branch from a given commit ID in the LakeFS UI, as that is where we tend to go to perform most of our manual actions.

**Comment by iddoavn** [comment]
Does this do what you are looking for?
![BranchFromCommit](https://github.com/treeverse/lakeFS/assets/87393827/7aadfc50-b102-4f08-a85c-a2c37ae266d7)

**Comment by clintonmonk** [comment]
Yes! I must have missed this. Thank you!
