### ISSUE TITLE
Can blockstore(s3) credentials be dynamically applied to each user?

### ISSUE THREAD

**Issue by sjkim2322** [treeverse/lakeFS#6638]
Hi,
I am considering applying lakefs to MinIO that I am already using.

The MinIO side we are using already divides credentials for each user and manages permissions. (access rights to specific buckets, etc.)

However, LakeFS seems to use only one static credential when deploying the server.
```
-e LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID="<minio_access_key>" \
-e LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY="<minio_secret_key>" \
```
<img width="766" alt="스크린샷 2023-09-21 오후 5 10 06" src="https://github.com/treeverse/lakeFS/assets/21153782/db2a8a4d-ed2c-4e8b-a0f5-faf0c21c0ef3">

Is there a way to use minio credentials for each lakefs user?

**Comment by itaiad200** [comment]
Hey @sjkim2322 I'll try to answer that. First, allow me to share the specifics of lakeFS requirements and usage of the underlying object store, in this case MinIO.
lakeFS repository has a storage namespace, which is basically the root of everything the user/lakeFS stores in the object store. For example, repo `repo1` storage namespace can be `s3://bucket1/foo` in MinIO. Everything the user uploads to lakeFS get stored under the storage namespace, e.g. the object `lakefs://repo1/main/bla.txt` may be mapped to `s3://bucket1/foo/data/<nanoid1>/<nanoid2>` in MinIO. Notice there's no correlation between the user which uploaded the file, or even the lakeFS path itself, to the physical path of the object. lakeFS commits metadata will be saved under `s3://bucket1/foo/_lakefs/`.
When a user runs lakeFS, object store credentials should be given, just like in the example you shared with MinIO. lakeFS needs access to the entire storage namespace (namespaces in case of multi-repos). Hence we should tie the creds given to lakeFS to the storage namespaces, not the permissions of any user of a lakeFS repo.

But how can an admin of a lakeFS installation manage the users access? Using lakeFS Authorization: [ACLs](https://docs.lakefs.io/reference/security/access-control-lists.html#access-control-lists-acls) for the OSS version, [RBAC](https://docs.lakefs.io/reference/security/rbac.html#role-based-access-control-rbac) for the Enterprise and Cloud versions.

**Comment by sjkim2322** [comment]
@itaiad200 

Thank you for answer
Let me explain my situation in more detail.

At my company, I am running MinIO (currently not using lakeFS).

Team members who want to use MinIO apply for use through a separate process, create a bucket and credential, and share the credential with team members.

for example,
```
User A`s bucket: s3://user_a/**
User A`s access key: user_a
User A`s secret Key: secret

User B`s bucket: s3://user_b/**
User B`s access key: user_b
User B`s secret Key: secret
```

If we consider the case of operating LakeFS in front of MinIO, LakeFS also uses credential as you explained.
(A total of 2 credentials must be operated)

Is there a way to use the existing MinIO side credentail on LakeFS side as well?

**Comment by arielshaqed** [comment]
Hi @sjkim2322 ,

Thanks for the explanation!  I do not believe that lakeFS currently has this capability.  But let me see that I understand what exactly you need.  There are two different possibilities here and I am not sure which you would like.

## (1) Allow lakeFS to use different credentials to access different buckets

In this scenario:

- User A gets bucket_A and credentials to access bucket_A from IT
- User A adds a repository "A" to lakeFS that uses bucket_A as its backing store, and provides lakeFS with their credentials on MinIO to access bucket_A.
- Users (A, B, and C) each have their credentials from lakeFS, and they use those to  access lakeFS and all buckets.

This is not currently possible: we configure the S3 block adaptor with a single set of credentials, and it uses those credentials for all repositories.  Changing this would make for a very difficult configuration experience, even just for getting and using a suitable secrets store to hold all these credentials, or to be able to assume-role for each bucket.

Also note that access-key-ID and secret-access-key are generally not preferred authentication solutions.

## (2) Allow lakeFS to use credentials from MinIO to identify users

In this scenario:

- Users A, B, C get their bucket_A, bucket_B, bucket_C and credentials to access those buckets.
- lakeFS uses its own credentials that allow it to access all buckets whose names start with prefix "`bucket_`".
- lakeFS knows about the credentials for users A, B, C and can use them to authenticate.
- Users A, B, C create repositories A, B, C on lakeFS using their credentials (same credentials on lakeFS and on MinIO!)

This is not currently possible if you use MinIO Internal IDP: I do not know of an interface that MinIO provides that lakeFS could use to verify identities.  However if your MinIO uses OIDC or LDAP then these are also supported on both lakeFS Enterprise or lakeFS Cloud, and it should be possible to configure something.  In this scenario both lakeFS and MinIO use the same IDP.

Hope this helps!

**Comment by arielshaqed** [comment]
[+ @sjkim2322, waiting on a reply from them]

**Comment by arielshaqed** [comment]
Closing due to no traction.  @sjkim2322 if you can, _please_ re-open stating if you need (1) or (2).
