### ISSUE TITLE
Azure pre-signed URLs sometimes use expired credentials

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#6643]
I managed to get 2-day-old credentials, with a correspondingly out-of-date
pre-signed URL.

## How to reproduce

You can literally _see_ this: take my old lakeFS that has not been doing
much, generate a pre-signed URL using `fs stat --pre-sign` on some object,
and then look for the expiry times on the returned "Physical Address".  I
get things like `ske=2023-09-19T...` and `skt=<similar>`.  Not pasting
presigned URLs in here because, well, they're somewhat secret.

Validate this by getting the URL, yielding results like:

``` xml
<Error>
  <Code>AuthenticationFailed</Code>
  <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:15d872dd-201e-0031-027d-ec09e3000000
Time:2023-09-21T11:19:38.6455372Z</Message>
  <AuthenticationErrorDetail>Signed expiry time [Thu, 21 Sep 2023 11:18:48 GMT] must be after signed start time [Thu, 21 Sep 2023 11:19:38 GMT]</AuthenticationErrorDetail>
</Error>
```

(the actual quoted times are _not even close_ to those of the URL, but also in the past).

**Comment by N-o-Z** [comment]
This happens only on Azure because we cache the User Delegation Credentials for reuse, to prevent redundant requests to the backend.
The problem is caused by a bug in the lru cache package (https://github.com/treeverse/lakeFS/pull/6651) we use which doesn't expire the entries.

**Comment by arielshaqed** [comment]
> This happens only on Azure because we cache the User Delegation Credentials for reuse, to prevent redundant requests to the backend. The problem is caused by a bug in the lru cache package (#6651) we use which doesn't expire the entries.

Cool, @nopcoder and I missed that 🙀 !  Can you link the issue here, please?

One odd thing about caching there is that this apparently we added yet _another_ cache system to lakeFS.  We already have pkg/cache/cache.go, which wraps the same golang-lru library. Using it will avoid multiple concurrent get-credential requests, which the current Azure implementation does exhibit.  And AFAIR we _did_ see expiry when using this implementation; it has definitely seen extensive usage in lakeFS.

We also use the ristretto library in Pyramid (tier_fs), but TBH I don't think that we need something like that just to hold caches

**Comment by N-o-Z** [comment]
> > This happens only on Azure because we cache the User Delegation Credentials for reuse, to prevent redundant requests to the backend. The problem is caused by a bug in the lru cache package (#6651) we use which doesn't expire the entries.
> 
> Cool, @nopcoder and I missed that 🙀 ! Can you link the issue here, please?
> 
> One odd thing about caching there is that this apparently we added yet _another_ cache system to lakeFS. We already have pkg/cache/cache.go, which wraps the same golang-lru library. Using it will avoid multiple concurrent get-credential requests, which the current Azure implementation does exhibit. And AFAIR we _did_ see expiry when using this implementation; it has definitely seen extensive usage in lakeFS.
> 
> We also use the ristretto library in Pyramid (tier_fs), but TBH I don't think that we need something like that just to hold caches

The cache/cache.go has the exact same problem and we need to address it in https://github.com/treeverse/lakeFS/issues/6652.
The reason it doesn't happen in `cache/cache.go` is because there we use the `lru.Cache` implementation and not the `lru.ARCCache` implementation which has the bug. In any case we should probably stop using this packaged as it is buggy and un-maintained.

**Comment by nopcoder** [comment]
Missed that. I was sure it was a case when we access data from different accounts. The cache in that flow gets invalidated.
