### ISSUE TITLE
[Bug]: Colons in tags not allowed

### ISSUE THREAD

**Issue by dsgibbons** [treeverse/lakeFS#6694]
### What happened?

The [docs](https://docs.lakefs.io/understand/model.html#tags) indicate that we can use the colon character `:` in tags. The docs use the example of `dev:jane-before-v2.3-merge`. If we try to add this tag via either the web UI or `lakectl` we get `argument tagID: tag id: invalid value: validation error`. Removing the colon character fixes this error.
        
Steps to Reproduce:

```bash
lakectl tag create lakefs://myrepo/dev:jane-before-v2.3-merge lakefs://myrepo/<commit-id>
```

### Expected behavior

Support for the colon character in lakeFS tags.

### lakeFS version

0.110.0

### How lakeFS is installed

Locally

### Affected clients

0.110.0

### Relevant log output

```shell
argument tagID: tag id: invalid value: validation error
```

**Comment by eladlachmi** [comment]
[Tag validation](https://github.com/treeverse/lakeFS/blob/master/pkg/graveler/validate.go#L71) indeed doesn't allow for `:` ([aligned with Gif ref formatting rules](https://git-scm.com/docs/git-check-ref-format)). Docs should be updated to reflect this. A reference to the Git ref format rules might also be useful.

**Comment by arielshaqed** [comment]
@eladlachmi did we fix docs?

**Comment by eladlachmi** [comment]
> @eladlachmi did we fix docs?

@arielshaqed I checked just now and they were not. I'll take care of it.
