### ISSUE TITLE
[Bug]: Copy Presigned URL doesn't work properly

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#6702]
### What happened?

Steps to Reproduce:
1. Click on object's gear icon
2. Click on Copy Presigned UR
3. Paste

### Expected behavior

Get presigned URL

### lakeFS version

0.111.1

**Comment by idanovo** [comment]
Checked with Azure

**Comment by nopcoder** [comment]
This issue is when presigned UI is disabled - the button copy the object information, so we are getting the physical address and not presigned working URL.
