### ISSUE TITLE
[docs] Hard to understand how to import additional data into an existing destination

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#6704]
### What happened?

Today, when you import data into a location, whatever exists in that location is being overwritten.
In scenarios where this is ONLY additional data and not the existing data (with additional data), this is problematic.

Examples we run into this so far:
ML use cases where data scientists import a subset of files from different origins.
Multiple teams feeding data from multiple places to a single location.

The workaround we suggest today is to create an empty ingest branch (possible only when creating the repo in the first time), and import the data into that branch. Should be documented better. 

### Expected behavior

Better documentation until a better solution is provided.

### lakeFS version

All

**Comment by itaiad200** [comment]
Import Docs and blogs have changed to include this use case
