### ISSUE TITLE
API: update spec for all relevant API to support StatusTooManyRequests status code

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6710]
Using StatusTooManyRequests(429) the server can report on throttle / rate issue for the clients.
This way our SDK can support backoff while using the lakefs's API

**Comment by arielshaqed** [comment]
This is for 1.0.0, unfortunately, right?
If so then we should decide on the desired format of the response. Two main possible response types are:
- "back off for [duration]".
- "[this kind of request] limited to [requests per second]".

At the very least, we can return a 429 with a response body of type SlowDown that will initially have no fields. Then we can add optional features ields later.

As another alternative, we might respond with a plain 429, and later on add an optional response field header "[request type] has [number of slots] free in bucket". An advantage of this is that it allows clients to slow down before everything shuts down on them. That's often useful, too.

**Comment by itaiad200** [comment]
I don't understand why we went with `420` status code and why we had to add it to every api operation we have (`setupCommunicationPreferences`)?

**Comment by arielshaqed** [comment]
> I don't understand why we went with `420` status code and why we had to add it to every api operation we have (`setupCommunicationPreferences`)?

In addition it *must* have somewhere we can put optional parameters later on. Can we at least add an empty body type TooManyRequests *now*? Otherwise  adding some response fields later will be difficult and require a breaking change.
