### ISSUE TITLE
[Bug]: Unexpected error from gw -> get_object for small objects deleted from underlaying storage 

### ISSUE THREAD

**Issue by eladlachmi** [treeverse/lakeFS#6718]
### What happened?

When calling get_object through S3 gw on a small (or empty) object that has been deleted from the underlying storage, an unexpected `Internal Server Error` is returned.

### Expected behavior

Should return HTTP Status Code 410 (Gone)

### Relevant log output

```shell
2023-10-06T07:12:35.199793485Z time="2023-10-06T07:12:35Z" level=error msg="encoding response failed" func="pkg/gateway/operations.(*PathOperation).EncodeError" file="build/pkg/gateway/operations/base.go:210" error="http: wrote more than the declared Content-Length"
```

**Comment by mhtrinh** [comment]
Do you know which release will include this bug fix ?

**Comment by eladlachmi** [comment]
> Do you know which release will include this bug fix ?

@mhtrinh Version 0.113.0 includes the fix. Could you let me know if you are seeing the same error? Are you still seeing different errors for empty/non-empty files?

**Comment by mhtrinh** [comment]
I can confirm the bug is still there with lakefs server 0.113.0 and lakefs-client 0.113.0.1
```
ClientError: An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again.
```

**Comment by mhtrinh** [comment]
@eladlachmi  Can you please re-open the bug

**Comment by eladlachmi** [comment]
@mhtrinh As far as I can recall, the original client-side error was different, right?   
It still seems not to be behaving as expected, but this might be a different yet related issue.

**Comment by mhtrinh** [comment]
The error on client side: 
```
ClientError                               Traceback (most recent call last)
File /data/deleteme/venv/lib64/python3.10/site-packages/s3fs/core.py:113, in _error_wrapper(func, args, kwargs, retries)
    112 try:
--> 113     return await func(*args, **kwargs)
    114 except S3_RETRYABLE_ERRORS as e:

File /data/deleteme/venv/lib64/python3.10/site-packages/aiobotocore/client.py:383, in AioBaseClient._make_api_call(self, operation_name, api_params)
    382     error_class = self.exceptions.from_code(error_code)
--> 383     raise error_class(parsed_response, operation_name)
    384 else:

ClientError: An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again.
```

The debug log from server side:
[query_data_sorted.csv](https://github.com/treeverse/lakeFS/files/13034446/query_data_sorted.csv)

commit2 is the folder that were deleted. the debug message status code==500 while the commit1 is the folder that is normal and seem to have status code==200
