### ISSUE TITLE
change min_commit uncommitted indicator

### ISSUE THREAD

**Issue by tzahij** [treeverse/lakeFS#672]
currently an un-committed entry is marked by min_commit = 0
This complicates finding the active entry when reading the branch current state, which includes uncommitted entries. after reading the first row, we need to read all other entries until the last entry of that path. only then we will know if there is an uncommitted entry that overrides the top entry.
Th change is to set min_commit to MaxCommitID when it is uncommitted. now when an entry is uncomitted - it is the first one in the index order. so we immediatly know that the active entry is the first one we get.

**Comment by haardikdharma10** [comment]
Hey @tzahij, I'd like to help in solving this issue. Can you help me with the files I need to change?

**Comment by nopcoder** [comment]
Hi @haardikdharma10 assigned this task to tzahij as this change touches a lot of the groundwork he introduced to the project.  
I suggest any "good first issue" labeled first, I can help if you have questions now to address the problem and contribute.

**Comment by ozkatz** [comment]
as we're changing data model, I'm closing this in the meantime. Please reopen if relevant.
