### ISSUE TITLE
GC update SDK for lakeFS v1

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6724]
Part of moving to SDK v1 some of the APIs used by GC were updated.
The newer version of lakeFS SDK should be used as part of GC.

**Comment by arielshaqed** [comment]
## Rough guide for someone picking this up as a first issue

This is a great first issue!  The Spark metadata and GC codes use the lakeFS API, so naturally we want to update them to use the new SDK.  They're written in Scala and run on the JVM, the new Maven coordinates to use are io.lakefs:sdk.

The task is to change clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala to use this SDK.  Calls have changed, especially the _style_ of the call.  You can look at [recent changes to LakeFSFileSystem.java](https://github.com/treeverse/lakeFS/commit/e6a8e4a01509aa50a10b0f5356cebb7c02cd8368#diff-4c50b9ac3bf6bfc05e3b6ff0fbe2fd3214f31afb5b449732d90efe5f97f67167R457) to see how we did it in Java.  The Scala changes will be very similar.
