### ISSUE TITLE
Release lakeFSFS v1.0.0

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#6727]
After releasing lakeFS 1.0.0, release lakeFSFS 1.0.0.  This package follows a separate release train so this is a different activity.

## Things we need to decide before we can call it 1.0.0:

* [ ] Names of all configuration options.
* [ ] Defaults of all configuration options.  For instance, do we want to be presigned by default?
* [ ] Which Hadoop version we support, in the sense of which Hadoop version do we use for the Hadoop fs spec test.

## Checklist for releasing (add here!):

* [ ] It should depend on io.lakefs:sdk:1.0.0 (or later)
* [ ] It should have version number 1.0.0
  _However_ the version numbers will remain separated in two trains.  This release exemplifies that we cannot in fact release server and a dependent lakeFSFS revision in the same release, as lakeFSFS will (probably) depend on a newly-published SDK.
* [ ] #6725 includes a recommended changelog comment for this release: it drops support for lakeFS server versions < 0.108.0.

**Comment by nopcoder** [comment]
@arielshaqed think we can close this one - also think we got it right ;)

**Comment by nopcoder** [comment]
Closing things we did in the past.

**Comment by arielshaqed** [comment]
Ummm..., I don't think we published 1.0.0 😱

**Comment by arielshaqed** [comment]
[Latest is 0.2.1](https://github.com/treeverse/lakeFS/actions/runs/6637660308/job/18032424168#step:10:74).

Re-opening, I think all of the decisions about configuration are still open.

**Comment by nopcoder** [comment]
can we change the title to be relevant?
