### ISSUE TITLE
Align checksum in azure for upload response between pre-signed and not pre-signed

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#6745]
### Description

in lakectl: uploading using pre-signed resolves with different checksum than uploading without pre-signed

This is the difference between the results in lakectl

```bash
➜  echo "this" | ./lakectl fs upload lakefs://one/main/other2 --pre-sign  -s -
Path: other2
Modified Time: 2023-10-10 12:20:08 +0300 IDT
Size: 5 bytes
Human Size: 5 B
Physical Address: data/gkkunea8tio0kuuanl30/ckihehq8tio0kuuanl3g
Checksum: 0x8DBC97218C1C40D
Content-Type: application/octet-stream
➜  echo "this" | ./lakectl fs upload lakefs://one/main/other2   -s -
Path: other2
Modified Time: 2023-10-10 12:20:15 +0300 IDT
Size: 5 bytes
Human Size: 5 B
Physical Address: https://mystorage.blob.core.windows.net/some/path/data/gkkunea8tio0kuuanl30/ckihejq8tio0kuuanl40
Checksum: 9e7b964750cf0bb08ee960fce356b6d6
Content-Type: application/octet-stream
```

In the case without pre-signed we get `9e7b964750cf0bb08ee960fce356b6d6` which is an md5 calculated by lakeFS
In the case with pre-signed, we get `0x8DBC97218C1C40D` which is the Etag returned by Azure 

We should align the results to be the same
We should also validate that this doesn't happen in other places such as lakeFSFS and generated clients

**Comment by arielshaqed** [comment]
0x8DBC97218C1C40D seems incorrect!  Those are merely 15 hex digits, 60 bits, not enough to distinguish between objects.  Is this ETag reproducible across uploads?  Does Azure really use 16-bit ETags?

**Comment by arielshaqed** [comment]
> 0x8DBC97218C1C40D seems incorrect! Those are merely 15 hex digits, 60 bits, not enough to distinguish between objects. Is this ETag reproducible across uploads? Does Azure really use 16-bit ETags?

Well, [this SDK link](https://github.com/Azure/azure-sdk-for-net/issues/16920) _also_ has such tiny ETags.  Also I read it as saying ETags are sometimes with and sometimes without quotation marks.
