### ISSUE TITLE
On repo creation from the UI, storage namespace placeholder hint should match lakeFS blockstore type

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#676]
When creating a repository from the lakeFS UI, you need to specify a "storage namespace". This is the URI pointing to where the data will actually be stored.

Currently the hint always starts with "s3://...". However, since lakeFS can operate with various backing storage services, the hint should be suitable to the current storage type.
e.g. when using Google Storage, the hint should begin with "gs://..." etc.

Related to #502

**Comment by eylonronen** [comment]
Hi, thinking of looking into this...
mind assigning to me?

**Comment by YaelRiv** [comment]
All yours @eylonronen! 

Feel free to ask questions on the slack. 

Many thanks,
Yael

**Comment by eylonronen** [comment]
The block store type is stored in the config file, and as I see its only use is when setting up the adapter.
I plan on adding a new request handler in api_controller that will return the config value to GET requests to the uri: "/config/blockstore_type", and then fetching it accordingly from the UI
Should I do it in any other way?
