### ISSUE TITLE
UI object info with presigned support show presigned URL as physical address

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6769]
Expected behaviour to show the entry physical address and not a presigned URL.

**Comment by idanovo** [comment]
@nopcoder isn't it a duplication of [this](https://github.com/treeverse/lakeFS/issues/6702)?

**Comment by nopcoder** [comment]
> @nopcoder isn't it a duplication of [this](https://github.com/treeverse/lakeFS/issues/6702)?

No, this one issue is related to what we disable on object information, while we request for object stat.
The issue #6702 copy presigned - should always request for presigned url or use the presigned information from the object list.
