### ISSUE TITLE
Replace "i.e." with "e.g." where needed

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#677]
In some places (docs, UI and other text files) we use the abbreviation "i.e." where "e.g." actually makes more sense.
"e.g." means "For example", while "i.e." means "That is".

Find all places where we use "i.e." and replace it (only if applicable)

Clarification edit: the issue here is to find the places where "i.e." appears *by mistake*, not all of its appearances.

**Comment by boradakash** [comment]
Can I take this up?

**Comment by gokulkannan7** [comment]
@johnnyaug can I tackle this issue?

**Comment by johnnyaug** [comment]
Hi @gokulkannan7, welcome!
Sure thing, assigning you.

**Comment by RishabhDevbanshi** [comment]
Can I also work on this issue?

**Comment by sharmakeshav10** [comment]
I'd like to work on this issue. @johnnyaug

**Comment by Ameenrehman** [comment]
@johnnyaug hello, can i work on this issue?

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue.

**Comment by imanishbarnwal** [comment]
Hello @johnnyaug, I would like to work on this issue if it's still available.

**Comment by nishithgadhiya** [comment]
Hi @johnnyaug  If it is still open I would to work on this issue

**Comment by Yashs911** [comment]
Hi, @johnnyaug I would Like to work on this.

**Comment by Sumindar** [comment]
Hi @johnnyaug 
Can I please contribute.
Thanks

**Comment by galahad42** [comment]
Hi [@johnnyuag](https://github.com/johnnyaug), if this issue is still open I'd like to work one it

**Comment by thrix04** [comment]
Hi @johnnyaug , can i work on this issue. This is first hacktoberfest, want to make most of it.

**Comment by swapniljha001** [comment]
Is this issue already resolved?
