### ISSUE TITLE
lakeFS v1 Python SDK changes

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#6796]
Update the lakeFS V1.0 document with the Python SDK changes to apply in order to use it.

**Comment by nopcoder** [comment]
Note also the changes related to upload_object content - the fact that it is no longer support IOBase.
Thanks @arielshaqed.

**Comment by nopcoder** [comment]
@Jonathan-Rosenberg can we close this one?
