### ISSUE TITLE
Dark theme feature

### ISSUE THREAD

**Issue by Ritwik880** [treeverse/lakeFS#683]
before adding dark theme:
![Screenshot from 2020-09-30 20-33-05](https://user-images.githubusercontent.com/54446880/94703226-4259fb80-035c-11eb-8776-e52344155ba9.png)

After adding dark theme:
![Screenshot from 2020-09-30 20-32-47](https://user-images.githubusercontent.com/54446880/94703268-4be36380-035c-11eb-9807-4e9c94b7d3ce.png)

**Comment by Harshal0902** [comment]
Can I work on this Issue?

**Comment by iamRishabh07** [comment]
Hi @Ritwik880 I would like to work on this issue.
