### ISSUE TITLE
Lua: lakeFS GC rules API

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#6835]
Add an API to the lakeFS object in the Lua action to set and get garbage collection rules.

### Motivation: 
Before or after creating a branch, set a `pre/post-create-branch` hook that will specify GC rule for that branch.
When deleting the branch, set a `post-delete-branch` hook to remove the branch's GC rule.

**Comment by itaiad200** [comment]
This has the potential of bloating the GC rules. I don't think it was ever tested with thousands of rules.
Can you share more about the specific use-case that's hidden here? Like what's the required branch strategy and GC policies?
