### ISSUE TITLE
Higher level python SDK Wrapper

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6874]
#### Tasks Breakdown (by priority):
1. [Client and IO classes](https://github.com/treeverse/lakeFS/issues/6947)
2. [Repo Class](https://github.com/treeverse/lakeFS/issues/6950)
3. [Reference, Tag Classes](https://github.com/treeverse/lakeFS/issues/6960)
4. [Branch Class](https://github.com/treeverse/lakeFS/issues/6969)
5. [Object Class](https://github.com/treeverse/lakeFS/issues/7007)
6. Managers: Repos, Branches, Tags, Objects
   1. https://github.com/treeverse/lakeFS/issues/7055
   2. https://github.com/treeverse/lakeFS/issues/7054

7. [Transactions](https://github.com/treeverse/lakeFS/issues/7154)
8. [Imports](https://github.com/treeverse/lakeFS/issues/7077)

### Additional tasks:
1. [Documentation generator](https://github.com/treeverse/lakeFS/issues/7016)
3. System tests
   - [Python Wrapper: System Tests Base](https://github.com/treeverse/lakeFS/issues/6951#top)
4. [Release workflow and packaging](https://github.com/treeverse/lakeFS/issues/6996)
5. ~Client compatibility tests?~ Covered by integration tests
6. [Metrics](https://github.com/treeverse/lakeFS/issues/7000)
7. [Tech debts (filter issues by label)](https://github.com/treeverse/lakeFS/labels/python-wrapper)

**Comment by N-o-Z** [comment]
Closing as completed all major milestones
