### ISSUE TITLE
[Bug]: Import gets stuck sometimes

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6878]
### What happened?

When I am using lakeFS Cloud and import files from S3 then sometime process gets stuck and never completes.
        
Steps to Reproduce:
1. Run "Import" process (last cell in the the attached notebook) multiple times. 

Import process sometime gets stuck. When I call `lakefs.import_api.import_status`, it returns same number of images imported and import process never finishes. So, I manually interrupt the process.

[import-multiple-buckets-issue1.ipynb.zip](https://github.com/treeverse/lakeFS/files/13171035/import-multiple-buckets-issue1.ipynb.zip)

### lakeFS version

1.0.0

### How lakeFS is installed

lakeFS Cloud

### Contact details

amit.kesarwani@treeverse.io

**Comment by nopcoder** [comment]
I've used the following code, didn't managed to reproduce the issue:

```python
#!/usr/bin/env python3

import json
import time

import lakefs_client
from pprint import pprint
from lakefs_client.models import *
from lakefs_client.client import LakeFSClient

configuration = lakefs_client.Configuration(
        username=<LAKEFS_KEY>,
        password=<LAKEFS_SECRET>,
        host=<LAKEFS_ENDPOINT>)
lakefs = LakeFSClient(configuration)

repo = <REPO>
branch = "main"
paths=[
    ImportLocation(type="common_prefix", path="s3://ds-vino", destination=""),
    ImportLocation(type="common_prefix", path="s3://sample-dog-images", destination=""),
    ImportLocation(type="common_prefix", path="s3://amit-labelbox-geospatial-vessel-detection", destination="")
]
print("==> Starting import")
import_resp = lakefs.import_api.import_start(repo, branch, ImportCreation(paths, CommitCreation(message="Test import functionality")))
print("Import id: {}".format(import_resp.id))

# Wait for import to finish
while True:
    time.sleep(2)
    status_resp = lakefs.import_api.import_status(repo, branch, import_resp.id)
    print("==> Import status")
    pprint(status_resp)
    if status_resp.completed:
        break
````

@kesarwam can you capture when it happens the output, also if it happens inside the notebook.
Want to see if the status update time is updated.

Note that currently we do not handle the case of lakeFS restart where the instance that process the request no longer available - in this case we can define stale import and status will report an error which will require re-run import flow.
In case it is running on our cloud solution - slack so we can check if the specific organization isolake had any update or errors in the logs.

**Comment by kesarwam** [comment]
Yes, it happens inside the notebook. I didn't try from outside the notebook.

Yes, I am using lakeFS Cloud. So, I will Slack when it happens again. I have noticed this many times so I will be able to reproduce.
