### ISSUE TITLE
Import API of Python Client: "type" field for ImportLocation is not explained

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6880]
### What happened?

Types in `ImportLocation` are either `common_prefix` or `object` but it is not explained in any documentation. If I use `object` to import a single object by using following ImportLocation then it creates a blank file name:

ImportLocation(type="object", path="s3://sample-dog-images/Annotations/n02085620-Chihuahua/n02085620_10074", destination="json/")

While Import UI doesn't have this `type` option.

### lakeFS version

1.0.0

### How lakeFS is installed

lakeFS Cloud

### Contact details

amit.kesarwani@treeverse.io

**Comment by itaiad200** [comment]
I think the second item issue here ("While Import UI doesn't have this `type` option.") is covered by https://github.com/treeverse/lakeFS/issues/5886

**Comment by N-o-Z** [comment]
Currently UI and lakectl support only common_prefix and we might want to mention that in the docs

**Comment by kesarwam** [comment]
and change this doc also: https://github.com/treeverse/lakeFS/blob/master/clients/python/docs/ImportLocation.md
