### ISSUE TITLE
[Bug]: "lakectl local commit" response doesn't show count of Removed files

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6881]
### What happened?

Steps to Reproduce:
1. Clone a branch locally by using `lakectl local clone`
2. Delete few files locally.
3. Now commit your changes: `lakectl local commit`
4. Commit Sync summary shows "Removed: 0"

### lakeFS version

1.0.0

### How lakeFS is installed

lakeFS Cloud

### Contact details

amit.kesarwani@treeverse.io

**Comment by N-o-Z** [comment]
@kesarwam This was fixed in previous versions of lakectl - which client version are you using?
Ran the scenario on latest:
```
± % lakectl local commit -m "bla" /tmp/data                                                                                     !10232

Getting branch: main

diff 'local:///tmp/data' <--> 'lakefs://quickstart/a6f8f70f2baabeedcee73948b7af42171ab7da14a70d2ad56bad024f6e688f86/'...
delete remote path: lakes.parquet        ... done!

Sync Summary:

Downloaded: 0
Uploaded: 0
Removed: 1

Finished syncing changes. Perform commit on branch...

```

**Comment by kesarwam** [comment]
Thanks. I was using `v0.107.0` and I just upgraded to latest `v1.1.0`. Issue got resolved.
