### ISSUE TITLE
Allow adding commit message and metadata to merge commits in CLI, UI

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#6883]
The OpenAPI endpoint allows setting a commit message and adding commit metadata keys to a merge operation. This is currently not available in the UI and CLI.

Proposed solution:

1. for `lakectl merge` add the same `--message` and `--meta` flags that exist in `lakectl commit`
1. for the UI, add the same message and metadata fields from the commit dialog to the merge dialog (which now allows setting only a merge strategy).

**Comment by N-o-Z** [comment]
Done
