### ISSUE TITLE
Add session ID to lakeFS request

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#6901]
Adding a session ID to lakeFS requests might be useful so it will be easier to track flows by reading lakeFS logs.
LakeFS will search for a session ID in the request header. If it finds one, it will use it and send it back to the client in the response. If it doesn't find one, it will generate a new session ID and return it to the client in the response.

**Comment by arielshaqed** [comment]
I believe this already exists as a "request-id" field?

**Comment by idanovo** [comment]
The request-id field serves a different purpose than the session-id field. Clients use unique request-ids but may use the same session-id for different requests.

**Comment by arielshaqed** [comment]
Cool, thanks for explaining!  IIRC back in Correlix we sniffed some traffic that would engineer their Request-Ids to share a prefix.  I think that might be a workaround:
```http
Request-Id: <SESSION_ID>::<REQUEST_ID>
```
But if users want it, or if we need to use full-field searching of logs for some reason... who am I to stop it?
