### ISSUE TITLE
Import a single object for local blockstore

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6913]

**Comment by Isan-Rivkin** [comment]
Need to remember update the docs when done: 
https://docs.lakefs.io/howto/import.html#notes

**Comment by kesarwam** [comment]
I tested importing single object from `local` storage and it works fine. Also, bug # [6879](https://github.com/treeverse/lakeFS/issues/6879) is an issue with S3 storage only. It works fine for `local` storage.
