### ISSUE TITLE
lakectl: revert a non existing commit succeeds and creates a commit with no changes

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#6917]
Executing lakectl branch revert with a reference which does not exist on the branch results in a commit with no changes

![image](https://github.com/treeverse/lakeFS/assets/3787958/49e5e31d-bab0-42bd-bf35-7926bad1252e)

![image](https://github.com/treeverse/lakeFS/assets/3787958/2ee1c870-db35-4b0d-9a72-b192bf404f29)

**Comment by sullyvannunes** [comment]
Hi folks! I would like to work on it. Do you mind assigning me to this issue?

**Comment by nopcoder** [comment]
Hi @ sullyvannunes - assigned, let me know if you need any help?

**Comment by N-o-Z** [comment]
@sullyvannunes, since there's no update on the corresponding PR - we're taking you off the issue.
Since this is a high visibility bug, we are committed to our users to resolve it as quickly as possible.
If you do manage to address the PR comments soon - please let us know
