### ISSUE TITLE
Discovery: Branch rollback

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#6919]
The ability to "reset" a branch to a previous state referenced by a commit or tag on that branch.
Today this is possible by performing a branch "revert" command and providing all references leading up to the desired commit.
Another existing alternative is creating a new branch using the desired commit as source reference.
The purpose of this issue is to understand the user use cases for this operation and suggest an "atomic" operation for that.

**Comment by arielshaqed** [comment]
Ideally we could phrase this as the Git operation.  I believe that this is the same as `git reset --hard <ref>`?

**Comment by N-o-Z** [comment]
> Ideally we could phrase this as the Git operation. I believe that this is the same as `git reset --hard <ref>`?

Yes, I tried to refrain from using the comparison to the `git reset` command as our `reset` behaves a bit differently than git

**Comment by N-o-Z** [comment]
Closing in favour of continuing the discussion in #2343
