### ISSUE TITLE
[S3 gw] put-object-tagging runs put-object

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#6930]
The S3 gw does _not_ [support put-object-tagging](https://docs.lakefs.io/reference/s3.html).  Running put-object-tagging _should_ fail.  Instead it runs put-object.

## Expected behaviour

Fail with "unsupported operation".

## Observed behaviour

put-object

**Comment by arielshaqed** [comment]
A brief examination of the code suggests that `*BasedOperationID` funcs look at the HTTP method but no further.

**Comment by arielshaqed** [comment]
## Workaround

It is not possible to place S3 tags on lakeFS objects. However you can use object-level user metadata. In practice most uses require metadata not tags.

* more [about metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata)
* more [about tags](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html)

**Comment by itaiad200** [comment]
@ozkatz to prioritize
