### ISSUE TITLE
Remove deprecation from UploadObject API

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6956]
Revert the decision to mark if-none-match parameter for upload as deprecated.

We've decided to retract the deprecation notice for the if-none-match argument. Initially, we believed that our future needs could be met through alternative capabilities, but upon further consideration, we've recognized its necessity.

**Comment by arielshaqed** [comment]
Evil bot closed bugs that are in actual current implementation requirement.

Samples:
#7378 
#7479

**Comment by N-o-Z** [comment]
Superseded by: https://github.com/treeverse/lakeFS/issues/7479
