### ISSUE TITLE
Configurable metadata for Commits

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6989]
For the Commit Changes popup (see the screenshot below) where you can type in the message and add metadata, can we configure the metadata inputs?

As typing, especially keys can be problematic and easy to mistype, is there a way of having a default set of keys for metadata fields already populated?

Another idea would be also to be able to have other types of input for value - for example a list (like you have already in merge), or date-type fields etc.

Use case is that basically for each of the newly added files to a repo, or changes that are going to happen them thereafter, user needs to attach more information apart from commit message. Which can be later used/exposed for compliance, reporting, auditing etc.

![image](https://github.com/treeverse/lakeFS/assets/93291915/e80a01b0-199e-47cc-b2f1-657c1dd52bcb)

**Comment by itaiad200** [comment]
@treeverse/product to prioritize
