### ISSUE TITLE
Python Wrapper: Should we remove the max_amount param from generators?

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7004]
Pros:
- Simplifying user interface

Cons:
- Might cause confusion and create a strange behavior when providing additional listing args

From discussions:
https://github.com/treeverse/lakeFS/pull/6992#discussion_r1395340315

**Comment by N-o-Z** [comment]
@nopcoder FYI

**Comment by nopcoder** [comment]
Thanks @N-o-Z

**Comment by nopcoder** [comment]
@ozkatz will like your input on this one as the current implementation do not leverage anything from the server I think we should drop it from the interface or use the information while calling the server.

**Comment by ozkatz** [comment]
@nopcoder I would assume that if `max_amount` < page size, the client would request only `max_amount` results. If that's the case I prefer to keep it - as an optional parameter.

**Comment by nopcoder** [comment]
agree, @N-o-Z can we use the value in order to optimize the calls to the server?
@arielshaqed suggested passing the max value, and each call reduces the amount we accepted. 
Also, there is a special case for branch log where we like to pass the server limit=true, in order not to cause the server to go over the full comment tree while requesting a small number of commits (blame takes 1). We can defer this one but it is related to max items and specific to the logs.

**Comment by N-o-Z** [comment]
> agree, @N-o-Z can we use the value in order to optimize the calls to the server? @arielshaqed suggested passing the max value, and each call reduces the amount we accepted. Also, there is a special case for branch log where we like to pass the server limit=true, in order not to cause the server to go over the full comment tree while requesting a small number of commits (blame takes 1). We can defer this one but it is related to max items and specific to the logs.

Thanks,

We already set limit = True on in the log operation if max_amount is not None. Regarding passing max_value as amount, unfortunately we validate the amount param to be in the range of [-1, 1000]. I prefer not hardcoding these numbers in the SDK wrapper. I suggest that advanced users should know how to pass the `amount` parameter as part of the kwargs in the request

**Comment by N-o-Z** [comment]
Restating due to https://github.com/treeverse/lakeFS/issues/7037
limit and any other custom flags can be passed to the wrapper as part of the kwargs. Advanced users should understand that setting limit = True will override max_amount settings
