### ISSUE TITLE
Python Wrapper: Release Blocker: support writer 

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7033]
We need to rethink the `create` method.
Either:
1. Return a writer from the create method which implements the IO interface
2. Use the open method with write modes to return an ObjectWriter
3. Other?

**Comment by ozkatz** [comment]
Some more context:

Many Python libraries do serialization by **accepting** a file-like object (as opposed to `create(data=...)` that currently requires the caller to **provide** a file-like object that we read from.

Examples:

1. Standard library
    1. [`pickle.dump(fp, data)`](https://docs.python.org/3/library/pickle.html#pickle.dumps)
    2. [`json.dump(fp, data)`](https://docs.python.org/3/library/json.html#json.dump)
    3. [`csv.writer(f)`](https://docs.python.org/3/library/csv.html#writer-objects)
1. PIL - [`Image.save()`](https://www.geeksforgeeks.org/python-pil-image-save-method/)
4. PyYAML - [`yaml.dump()`](https://pyyaml.org/wiki/PyYAMLDocumentation)
5. Pandas - [`pandas.DataFrame.to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) (and all other `DataFrame.to_*` methods)

Many other Python libraries seem to behave this way.

Using the current design, this would require setting up an intermediate buffer (`io.BytesIO`, write to that object, and pass it back to `create()`. This means we lose the benefits of being able to stream.

**Comment by ozkatz** [comment]
My suggestion:

1. replace `create` with an `upload(data=..)` leaving the interface as-is.
2. expose an additional `writer()` context manager and object:

```python
with branch.object('foo.csv').writer() as f:
    yaml.dump(f)

# or without the context manager:
f = branch.object('foo.csv').writer():
yaml.dump(f)
f.flush() # or f.close()

```

Looking for thoughts/feedback on this, of course.

**Comment by N-o-Z** [comment]
> My suggestion:
> 
> 1. rename `create` to `upload` leaving the arguments as-is.
> 2. expose an additional `writer()` context manager and object:
> 
> ```python
> with branch.object('foo.csv').writer() as f:
>     yaml.dump(f)
> 
> # or without the context manager:
> f = branch.object('foo.csv').writer():
> yaml.dump(f)
> f.flush() # or f.close()
> ```
> 
> Looking for thoughts/feedback on this, of course.

If providing the writer context - why not provide it in the context of `open` and add the appropriate write modes?
Also suggest in that case to limit the `upload` functionality to either file names / explicit strings bytes

**Comment by ozkatz** [comment]
fine with both. The reasoning to differentiate open() from create() is @arielshaqed's [comment on the original proposal](https://github.com/treeverse/lakeFS/pull/6821#discussion_r1371465131) which still holds true IMO.

Another design option to separate the two and perhaps remove some ambiguity, is to replace open() with `reader(mode: Literal['r', 'rb'] = 'rb')` and `writer(mode: Literal['w', 'wb', 'x', 'xb'] = 'wb')`. 

Example:

```python

with branch.object('foo.yaml').reader() as fr:
    data = yaml.load(fr)

with branch.object('foo.yaml').writer() as fw:
    yaml.dump(fw, data)

```

With that, we can optionally also provide an `upload(data: bytes | string = "")` and perhaps at some later point `upload_file(path: str | os.PathLike[str] = "")`.

WDYT? @N-o-Z @arielshaqed

**Comment by ozkatz** [comment]
> Seems like a good solution. Just to make sure:
> 
> 1. Will reader / writer support modes (as was with open and create including 'x', 'xb')?

Yes, see above.

> 2. Will upload also accept the same writer modes?

I would suggest so, for consistency

> 3. Is the writer RW or write only?

write-only.

> 4. How do you suggest handling write buffering (we can't rely on access to disk)

I think we can start with a reasonable hard-coded value (1MiB?) and later make it configurable on the Client object (including DefaultClient). WDYT?

> 5. Should we support write after flush?

Why not? as long as we haven't closed, flush should empty the buffer into the HTTP connection. `close()` becomes important here - not calling it when in pre-signed mode means data was uploaded into the void..

Again, opinions and suggestions welcome.

**Comment by nopcoder** [comment]
As currently we don't support multipart upload, suggest to hold no more than 32MB of data before we switch to use tmp file to hold the content.
Love zero abstractions, can pay for some abstractions, but sometimes when it is too expensive I prefer to just document and enable fast upload using filename/bytes.

**Comment by N-o-Z** [comment]
@guy-har Note the changes required in the interface
