### ISSUE TITLE
[Bug]: Error: Invalid Input Error: No magic bytes found at end of file 'lakefs://test-repo/main/lakes.parquet' after merge in tutorial

### ISSUE THREAD

**Issue by rhprasad0** [treeverse/lakeFS#7074]
### What happened?

What actually happened, including error codes if applies. 

See conversation on slack. AWS setup: EC2, S3, Postgres on RDS freebie. After merge of lakes-denmark and main branches, lakes.parquet in main branch cannot be read. Followed tutorial to the T. lakes-denmark branch works as intended.
        

### Expected behavior

Lakes.parquet was to be queriable after merge in tutorial.

### lakeFS version

1.2.0

### How lakeFS is installed

AWS EC2, RDS, S3

### Affected clients

Web UI

### Relevant log output

```shell
Error: Invalid Input Error: No magic bytes found at end of file 'lakefs://test-repo/main/lakes.parquet'
```

### Contact details

rhprasad@outlook.com

**Comment by N-o-Z** [comment]
![image](https://github.com/treeverse/lakeFS/assets/3787958/52fcd9a0-fb31-4851-b3c3-86bbeba1a211)

**Comment by arielshaqed** [comment]
Also [this conversation](https://lakefs.slack.com/archives/C016726JLJW/p1701784925601769) on Slack might refer to the same issue.

**Comment by arielshaqed** [comment]
A user report is that 1.2.0 does not display this issue but 1.3.0 does.

**Comment by nopcoder** [comment]
After delete the service worker running in the chrome application I cloud not reproduce the bug.
I'll keep trying to reproduce it for couple of more days - and return to planned in case I fail.

**Comment by nopcoder** [comment]
Failed to reproduce - moving back to Planned

**Comment by johnnyaug** [comment]
## How to reproduce
1. Start from the sample repository, and in the lakeFS UI open the `lakefs.parquet` file to reach the DuckDB console.

2. Create a table from the parquet file:
   ```
   CREATE OR REPLACE TABLE lakes AS 
    SELECT * FROM READ_PARQUET('lakefs://example-repo/main/lakes.parquet');
   ```
3. Now make a change to the table:
   ```
    DELETE FROM lakes WHERE Country != 'Denmark';
   ```

4. Now commit the changes, and query the table:
   ```
   SELECT * FROM lakes LIMIT 100;
   ```

5. You can now use the following lakectl command to revert the last commit to the one before:
   ```
   lakectl branch revert lakefs://example-repo/main $(./lakectl log lakefs://example-repo/main --amount 1 | grep "ID:" | sed s'/ID:[[:space:]]*//') -y
   ```
   Run this command and execute the query again. Repeat this until the bug is reproduced.

**Comment by nopcoder** [comment]
DuckDB Wasm discord response - suggest to use cache break while requesting the s3 resources to bypass the browser's cache. Need to validate this solution - understand if it solves also the internal cache that duckdb manages.
