### ISSUE TITLE
Adding stale bot GitHub action

### ISSUE THREAD

**Issue by iamrajiv** [treeverse/lakeFS#708]

**Comment by iamrajiv** [comment]
@YaelRiv I want to work on this.

**Comment by arielshaqed** [comment]
Hi @iamrajiv ,

Thanks!  Could you add some details to the issue description, e.g. a link to the action, and possibly how it would help us?  I am not familiar with the "stale bot" GitHub action.

**Comment by iamrajiv** [comment]
@arielshaqed Added the description.

**Comment by arielshaqed** [comment]
Thanks for clarifying!

I am not sure that we want this: I am not sure that we have this problem.

**Comment by iamrajiv** [comment]
@arielshaqed Maybe not now but in future, this will be helpful. I do not think adding this will cause any problem instead it will give a proper workflow to lakeFS.

**Comment by arielshaqed** [comment]
> @arielshaqed Maybe not now but in future, this will be helpful. I do not think adding this will cause any problem instead it will give a proper workflow to lakeFS.

Cool, I understand better.  There are (at least) 2 ways of using GitHub actions:
1. As a list of actions that we are committed to perform.  AFAIU the proposed workflow helps manage this category.
1. As a backlog of known issues, some of which we will handle.  The proposed workflow is relevant for marking untriaged issues for handling, but it less suitable for closing issues.

This issue exposes that we have never discussed which one we want :-) -- thanks!  I've opened a discussion on https://lakefs.slack.com/archives/C01APUNTSGH/p1601794722011700.

**Comment by arielshaqed** [comment]
Hi @iamrajiv !
Discussion is silent on https://lakefs.slack.com/archives/C01APUNTSGH/p1601794722011700.  Given the silence here and there, I am not sure that this PR should go in.  Please post here or there why we should do this.

Thanks!

**Comment by arielshaqed** [comment]
Closing due to lack of discussion.  Let's revisit this when inactive issues and PRs become a larger issue.  

![close a stale issue to add a bot that closes stale issues: we need to dig deeper](https://user-images.githubusercontent.com/7802932/99357651-eff57f80-28b4-11eb-9efe-08c474b61298.png)


Thanks!
