### ISSUE TITLE
High-level Python SDK: add an option to list repositories

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#7085]
Add the ability to list repositories to the [lakeFS Python SDK](https://pydocs-lakefs.lakefs.io/index.html). 

Use cases - 
* Build applications that require repos browsing. 
* Programmatically manage lakeFS infra.

**Comment by mhtrinh** [comment]
Me too

We divide our data into repos but for some workload we would like to be able to scan all of our data, across repos. Having to maintain a list of repo in a text file is kind of ugly ! Especially if the Web UI can list them. Git allow you to list repo right ;-)
