### ISSUE TITLE
[BUG]: Python SDK create tag returns conflict error

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7103]
"The code that is giving me issues is:"

```
tag_creation=client.models.tag_creation.TagCreation(id='commit_id',ref='ref_example')
thread=client.tags_api.create_tag("repo-name",tag_creation)
```

**Comment by N-o-Z** [comment]
Waiting for more information from user

**Comment by arielshaqed** [comment]
## Current plan

_Document_ fields of `TagCreation` better.  It may be hard to understand what `id` and `ref` mean.

**Comment by jamslaugh** [comment]
Hi, when I try to run the code posted above it raises an HTTP error (403) due to a conflict with the id put.

**Comment by arielshaqed** [comment]
Sorry, this was confusing to a user.  So waiting for user feedback.

**Comment by arielshaqed** [comment]
> Hi, when I try to run the code posted above, it raises an HTTP error (403) due to a conflict with the id put.

Hi @jamslaugh ,

I guess the documentation fix is not good enough. Could you please give the exact parameters that you pass?

The reason that I merely changed the docs was that it seems like a mixup between the two parameters. There are reasons not to change the parameter names - OpenAPI is not forward-compatible or backward: compatible to such changes. So ideally we'd phrase the docs to make it clear which parameter is which.

**Comment by arielshaqed** [comment]
Hi again @jamslaugh ,

I am not sure what further to do with this issue.  I believe that this is a documentation issue: the field names "id" and "ref" are probably not that obvious, but  I do not know a way to alias field names in OpenAPI.  Instead I improved their documentation.

I am closing this issue.  But if you have a suggestion for how we could improve documentation, or even believe that we _could_, please re-open.

Thanks!
