### ISSUE TITLE
[Bug]: Can't run lakeFS Python Client on a Databricks cluster - compatibility issue between lakeFS 1.0 and urllib3

### ISSUE THREAD

**Issue by iddoavn** [treeverse/lakeFS#7169]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. I set up [this cluster](https://cz3k804.na1.hs-sales-engage.com/Ctc/RI+23284/cZ3k804/JjT4YGXpW50kH_H6lZ3nsW1GZRcf8PKZ2XW6c1hLB2RCkR5VBmyD21D7xWVW2840tK6H1ZcLMtkBBymv44fW92508-4WrVNgN3fCDyKBYjTZV_nVh85RyljfW1pTQ4N3pYFc6W329nml5P6-RpW6wPLVP5kq00KW6ZgQv78GflQgVg7zkh3500jSW8ZnThd2YDJgCW2qn10j2TqsFVW5DDSCS3DgZ0YW5Z7MNb6kByjRW3_sLxp1Jb4V5W1YDyTh84rFc5W13R1Pk1_D0yrW5CPxpr2q2-r1W2rDvz86_yrgWW6NWsM711qdBgW9gCmpL981kyVW792gTd3fcVHGW7MWFFb3zpd-8N8_TXmVFB2trW6_sVSl2vjMn4W3QrGrW5bCKfPW1gXRGP4yFPZpW5jb40b50pW0ZW89XK-365r9QTf14B8z404) to test this.  

2. Run a simple command [here](https://cz3k804.na1.hs-sales-engage.com/Ctc/RI+23284/cZ3k804/JjT4YGXpW50kH_H6lZ3kVW2CRKl97b3kCgW8f8MqV1MS6dCN74QgCBgp0F1N90trWVbbbWWW54Shpw3R7yfyW43YC1x7pyFwHW4L2kRr14CD_WW8GN1V98_CnPcW4cGbh94fplCxN5Zbr57xzHG6W9hqmMW8S9RmlW8YTYtC43Gvg_V6fP2x8MYtnVW713z7j1rhds_W5qhK-n7Vl8JkW8rSq8W9kwDGlW5BgZZj5PxxtMVYLnwp7wGtJ0N701VxwsFPX2W6mB4PY4xQJf6W3Nq4K22dxbdyW2VM0bQ8JSmbSVPg06_8_1KGfW52vvjf7CTJlwW5f20vR83c4QfW4Y0Cg-8xBrJDVxw-tv2_jJMNN8sH69JlbktbW5s4QX83wgS7bW4PfQkZ7rLGTcN8vnXWgqB3mbW4bnldw2XnByMf7vXCYx04)

`import lakefs`
Will cause:
`ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3' (/databricks/python/lib/python3.9/site-packages/urllib3/__init__.py)`

`BaseHTTPResponse` was added in `urllib3 v2.0.4 `while Databricks cluster v12.2 installs older `urllib3 v1.26.9`. 

Another comment from @kesarwam that might be relevant in this issue:
Also BaseHTTPResponse is part of response in urllib3. So, “from urllib3 import BaseHTTPResponse” statement in lakefs/exceptions.py may not work. 

### Expected behavior

Need to be able to run the new lakeFS Python client on a databricks cluster.

### Affected clients

lakefs==0.1.1

### Contact details

iddo.avneri@treeverse.io

**Comment by iddoavn** [comment]
Full stack trace:

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File <command-3047610880313563>:1
----> 1 import lakefs
      2 from lakefs.client import Client
      4 client = Client(
      5     host=lakefsEndPoint,
      6     username=lakefsAccessKey,
      7     password=lakefsSecretKey
      8 )

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/lakefs/__init__.py:5
      1 """
      2 Allow importing of models from package root
      3 """
----> 5 from lakefs.repository import Repository, repositories
      6 from lakefs.reference import Reference
      7 from lakefs.models import (
      8     Commit,
      9     Change,
   (...)
     14     RepositoryProperties
     15 )

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/lakefs/repository.py:12
      9 import lakefs_sdk
     11 from lakefs.models import RepositoryProperties
---> 12 from lakefs.tag import Tag
     13 from lakefs.branch import Branch
     14 from lakefs.client import Client, _BaseLakeFSObject

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/lakefs/tag.py:10
      6 from typing import Optional
      8 import lakefs_sdk
---> 10 from lakefs.exceptions import api_exception_handler, LakeFSException, ConflictException
     11 from lakefs.reference import Reference
     14 class Tag(Reference):

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/lakefs/exceptions.py:9
      6 from typing import Optional, Callable
      8 import lakefs_sdk.exceptions
----> 9 from urllib3 import BaseHTTPResponse
     12 class LakeFSException(Exception):
     13     """
     14     Base exception for all SDK exceptions
     15     """`

**Comment by N-o-Z** [comment]
@iddoavn did not understand @kesarwam comment. Can you please explain

**Comment by kesarwam** [comment]
I see 2 issues:

1. BaseHTTPResponse was added in urllib3 v2.0.4 while Databricks cluster v12.2 installs older urllib3 v1.26.9. Even latest Databricks cluster v13.3 installs urllib3 v1.26.11. So, all Databricks users will face this issue. So, we should consider using something else e.g. HTTPResponse instead of BaseHTTPResponse.
2. Also, BaseHTTPResponse is part of response in urllib3. So, “from urllib3 import BaseHTTPResponse” statement in lakefs/exceptions.py may not work. So, this might be a bug also.

**Comment by N-o-Z** [comment]
1. I'll change to class used
BUT - as a WA for now can you just upgrade the urllib3 package in the notebook / cluster?

> “from urllib3 import BaseHTTPResponse” statement in lakefs/exceptions.py may not work.
What do you mean may not work? It either works or it doesn't. In what scenario is this not going to work??
