### ISSUE TITLE
Delta export: Support Azure and GCP

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#7199]
Add Lua support for Azure and GCP such that it will be possible to export Delta Lake tables to the cloud providers' storage solutions.

**Comment by felipeff** [comment]
Is this not planned anymore? The issue was closed

**Comment by felipeff** [comment]
I see other tasks about azure support. The documentation is pointing to this closed task: https://docs.lakefs.io/integrations/unity-catalog.html

**Comment by itaiad200** [comment]
Hey @felipeff , you're right. We do support Azure for Delta Exports. I opened #7841 to close the documentation gap.
