### ISSUE TITLE
[Bug]: Python HL SDK -  transaction branches not deleted if no modifications made

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#7214]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. create a transaction
2. use it to read data, but don't write anything
3. let the transaction end.

### Expected behavior

The underlying transaction branch should be removed since there was no error during the processing of the transaction. 

Example:

```python
with branch.transact(commit_message='remove expired data') as tx:
    expired_objects = json.load(tx.object('manifest.json').reader())
    if expired_objects.get('should_delete'):
        tx.delete_objects(expired_objects.get('paths'))
```

This transaction has a condition inside it that might result in no modifications. As expected, there's no error and no exception is thrown, however - the transaction branch is not deleted once the transaction is complete.

### lakeFS version

1.4

### How lakeFS is installed

locally, cloud

### Affected clients

Python: lakefs==0.2.0

**Comment by N-o-Z** [comment]
The beauty of Python indentation 😆
