### ISSUE TITLE
When downloading a file using presigned URLs, set the actual filename

### ISSUE THREAD

**Issue by stevewillard** [treeverse/lakeFS#7251]
Hi there.

Currently I'm calling `stat` on a file:
```
const { data } = await client.get(
    `/repositories/${repositoryName}/refs/${ref}/objects/stat`,
    {
      params: {
        presign: true,
        path
      }
    }
  )
```

and downloading the file from S3 using the `physical_address` returned field. The filename, however, seems to be an internal LakeFS identifier. Is there a way to set the downloaded file name to the "real" name?

From my understanding if the S3 object had this header:
```
Content-Disposition: attachment; filename="foo.bar"
```

it would work. Thanks!

**Comment by ozkatz** [comment]
This seems to be possible using a [`response-content-disposition`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax) query parameter that could be added when constructing the pre-signed URL returned to the client
