### ISSUE TITLE
[Bug]: Linux system binaries are failing with arm64 docker images

### ISSUE THREAD

**Issue by fxp0** [treeverse/lakeFS#7257]
### What happened?

Using `arm64` docker images (`1.2`, `1.3`, `1.4`, `1.5`, `1.6`, `1.7` and versions before), most/any system binaries execution is failing inside of the container with error:
```
exec /bin/sh: exec format error
```
Therefore there is no way to get into a running container with `docker` or `kubectl` `exec` command.

```
$ uname -a
Linux ip-172-30-40-50 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:03 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

$ docker run -ti --rm --entrypoint=sh --platform=linux/arm64 treeverse/lakefs:1.5
exec /bin/sh: exec format error

$ docker run -ti --rm --entrypoint=pwd --platform=linux/arm64 treeverse/lakefs:1.5.0
exec /bin/pwd: exec format error

$ docker run -ti --rm --entrypoint=ls --platform=linux/arm64 treeverse/lakefs:1.5.0
exec /bin/ls: exec format error

$ docker inspect treeverse/lakefs:1.5 | grep Architecture
        "Architecture": "arm64",
```

I suppose the base image in use is for `x86_64` architecture, seems like it's not a problem for `lakefs` `go` binary entrypoint as this command is still running fine, and there is no issue as long as you don't need to use platform dependant binaries.

There is no such issue on `amd64` machine running `amd64` docker image.

Steps to Reproduce:
1. On `arm64` machine run:
```
docker run -ti --rm --entrypoint=sh --platform=linux/arm64 treeverse/lakefs:1.5
```

### Expected behavior

The `/bin/sh` command should be executed without errors inside `arm64` docker image.

### lakeFS version

1.5.0

### How lakeFS is installed

Docker and Kubernetes

**Comment by fxp0** [comment]
To build fully platform-specific docker images the `Dockerfile` should be changed.
String 
```
FROM --platform=$BUILDPLATFORM alpine:3.18 AS lakefs-plugins
``` 
should be changed to:
```
FROM --platform=$TARGETPLATFORM alpine:3.18 AS lakefs-plugins
```

**Comment by nopcoder** [comment]
Thanks @fxp0 for reporting this issue. Was using https://docs.docker.com/build/guide/multi-platform/ guide to build the the cross compile image and tested the lakefs/lakectl is running, while missing the verify that the OS (sh included) is working.

Looking into fixing it for the next release - will update here.
