### ISSUE TITLE
[Bug]: Example in PyDocs for Python Wrapper is wrong

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#7264]
### What happened?

Import statement in this [example](https://pydocs-lakefs.lakefs.io/lakefs.client.html) is wrong. It should be `from lakefs.client import Client` instead of `from lakefs import Client`

### Affected clients

python lakefs 0.2.0

### Contact details

amit.kesarwani@treeverse.io

**Comment by N-o-Z** [comment]
I think the fix should be in the code, not example. The solution is to add the Client class into the package's __init__

**Comment by N-o-Z** [comment]
@kesarwam, opened: https://github.com/treeverse/lakeFS/issues/7274
