### ISSUE TITLE
[Bug]: Branch Diff missing in Python Wrapper

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#7265]
### What happened?

Branch Diff (equivalent to https://pydocs.lakefs.io/v1.7/docs/BranchesApi.html#diff_branch in lakefs_client) is missing in new [Python Wrapper](https://pydocs-lakefs.lakefs.io/lakefs.html).

I use Branch Diff to find any uncommitted changes in a branch. This is not the same as Ref Diff.

### Affected clients

python lakefs 0.2.0

### Contact details

amit.kesarwani@treeverse.io

**Comment by ozkatz** [comment]
see [`branch.uncommitted()`](https://docs.lakefs.io/integrations/python.html#uncommitted-changes).

**Comment by N-o-Z** [comment]
Superseded by https://github.com/treeverse/lakeFS/issues/7276
