### ISSUE TITLE
[Hi-lvl Python SDK] Expose version in the top-level `lakefs` module

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#7273]
This is done for the `lakefs_sdk` package, but not for `lakefs`.

https://github.com/treeverse/lakeFS/blob/c9d5eb7625cb93c0e341a6c58ceece98d56505dd/clients/python/lakefs_sdk/__init__.py#L18

I'm only using this for a debug print in pytest though, so it's not urgent.

**Comment by N-o-Z** [comment]
@nicholasjng You can use the importlib metadata module:
```
In [4]: print(importlib.metadata.version('lakefs'))
0.2.1

```

**Comment by nicholasjng** [comment]
Yep, that's what I'm currently doing - I just brought this up as a convenience to save the `importlib.metadata` import ;)

**Comment by N-o-Z** [comment]
@nicholasjng you can leave the issue open if you like.
Since you have a WA, we'll put this in our backlog and wait for me use cases
