### ISSUE TITLE
HL Python Wrapper: add delete_objects method

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#7276]
Can delete_objects equivalent to this(https://github.com/treeverse/lakeFS/blob/master/clients/python/docs/ObjectsApi.md#delete_objects) be added?

**Comment by N-o-Z** [comment]
@kesarwam You already have a delete_objects method on the branch object.
I will use this issue to fix the documentation

**Comment by N-o-Z** [comment]
Branch documentation is fixed
