### ISSUE TITLE
Unity catalog exporter: Exported tables should retain original table field documentation

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#7302]
databricks users can add comments to tables in Unity Catalog and to their columns for documentation purposes. 
[Table-level comments](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-comment.html) can be added after table creation, but [column-level comments](https://docs.delta.io/1.1.0/api/java/io/delta/tables/DeltaTableBuilder.html#comment-java.lang.String-) can be added on table creation. 

Currently, table and column comments don't survive the export process to Unity Catalog. 

### Requirements 

* Retain Delta Lake tables comments on their export to Unity 
* Retain Delta Lake columns comments on their export to Unity

**Comment by itaiad200** [comment]
Why is this a bug for exported tables only? AFAICT @kesarwam opened the issue before we exported the tables

**Comment by talSofer** [comment]
@itaiad200 this is not a bug, this is an enhancement request. 
The way I see this, we should not support this for Unity delta sharing solution (against which #6322 was opened) but include it in our recommended delta + unity solution which is the exporter. Makes sense?

**Comment by Jonathan-Rosenberg** [comment]
Column comments are already supported:
![Image](https://github.com/treeverse/lakeFS/assets/96974219/dbae0778-e6bc-40c3-a9dc-7396fb1febf9)

**Comment by Jonathan-Rosenberg** [comment]
So currently Delta table comments (both on table and column) are exported. 
When running:
1. `DESCRIBE DETAIL <catalog>.<schema>.<table>;` you'll get the table comment (although you can't see it in the Unity GUI).
2. `DESCRIBE TABLE <catalog>.<schema>.<table>;` you'll get the column comments (you can also see it in the Unity GUI).

LMK if you wish me to keep working on that @talSofer @ozkatz

**Comment by talSofer** [comment]
Great news @Jonathan-Rosenberg!
Do you know what effort does it take to make table documentation appear in the Unity catalog UI?

**Comment by Jonathan-Rosenberg** [comment]
not much... Just wanted to know that it's indeed necessary
