### ISSUE TITLE
[Hi-lvl Python SDK] Add `Branch.cherry_pick()`

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#7346]
It would be cool if I could cherry-pick commits from a branch in the lakeFS Python wrapper.

Maybe like this:

```py
import lakefs

b = lakefs.Branch("repo", "my-branch")
# I have some data on a branch named "previous" at HEAD.
b.cherry_pick("previous")
```

If this is feasible, its signature would probably be determined by the API. Input ref should be a `ReferenceType`, i.e., strs for ref expressions, proper `lakefs.Reference`s, and `Commit`s.

Also, on success, it should return the new commit on b (that is actually returned by the API as far as I can see, https://pydocs-sdk.lakefs.io/docs/BranchesApi.html#cherry_pick).

**Comment by nicholasjng** [comment]
PS: Happy to take this on myself if you like.

**Comment by itaiad200** [comment]
@treeverse/product

**Comment by itaiad200** [comment]
@nicholasjng Thank you. I assigned this to you, feel free to reach out if you need any assistance
