### ISSUE TITLE
put-if-absent support

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#7378]
### Created at

2023-11-09T10:33:00.000Z

### Priority

p2

### Feature Definition

Useful for the python wrapper (`open(mode='x')`) as well as a LogStore for Delta (as discussed with Databricks). Requires un-deprecating the `If-None-Match` param from uploadObject, and supporting it in linkPhysicalAddress.

### T-shirt size

M

**Comment by N-o-Z** [comment]
Removed deprecation in: https://github.com/treeverse/lakeFS/issues/7479

**Comment by N-o-Z** [comment]
If this task doesn't involve also adding support in the HL SDK, then yes

**Comment by ozkatz** [comment]
I'll open a seperate issue for that (however, **not currently prioritized**)

**Comment by ozkatz** [comment]
Closing this issue, python enhancement tracked in #7505
