### ISSUE TITLE
Lua Hooks: lakefs.delete_branch operation

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#7388]
### Created at

2023-11-09T12:57:25.000Z

### Priority

p3

### PRD

https://github.com/treeverse/lakeFS/issues/6884

### T-shirt size

S

### Related feature requests

https://github.com/treeverse/product/issues/86

**Comment by N-o-Z** [comment]
@talSofer this looks like a duplicate of https://github.com/treeverse/lakeFS/issues/6884
Can we close it?

**Comment by talSofer** [comment]
@N-o-Z yes, closing it 
deplicates https://github.com/treeverse/lakeFS/issues/6884
