### ISSUE TITLE
Give an option to hide merge commits in a branch view in the UI

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#7441]
Similarly to GitHub metrics I guess. We switched our transaction model to a merge of an ephemeral branch, which creates merge commits on success. When going through a branch history, these commits clutter the view, so it would be great to have a filtered view where we can focus on the actual additions.

cc @maxmynter

**Comment by talSofer** [comment]
Thanks for opening this request @nicholasjng! Are you using lakectl or the lakeFS UI to view the commit history? 

If you had a `--no-merges` flag as part of the `lakectl log` command, would that solve your case?

**Comment by nicholasjng** [comment]
I'm viewing it in the UI. `--no-merges` sounds like a good idea (assuming it means everything with maximum 1 parent, like in git log), for a UI view of commits, should not be difficult to filter by that condition, then.

**Comment by arielshaqed** [comment]
Also the same filtering is equally possible in the UI.
