### ISSUE TITLE
Add an option to ignore/override dummy file when creating a lakeFS repository

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#7448]
When creating a new lakeFS repository, we check for a dummy file in the path we try to create the repository at.
If it exists, we fail.
I would like to have the option to ignore the existence of this file or override it.

**Comment by arielshaqed** [comment]
I think it makes sense to do this when creating a read-only repository - will that be sufficient?

**Comment by idanovo** [comment]
> I think it makes sense to do this when creating a read-only repository - will that be sufficient?

@arielshaqed I think it should be a flag that we can pass in the CreateRepository request, no?
