### ISSUE TITLE
[Bug]: Delta table export: can't read exported data if any delta partition name includes spaces

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#7460]
### What happened?

If a Delta table, which is imported into lakeFS, has a space in the table partition name e.g. "professional athlete" (in the below example) then I can't read exported Delta table directly from S3.
        
Steps to Reproduce:
1. Create a Delta table directly on S3 e.g.
```
data = [
   ('James','Bond','England','intelligence'),
   ('Robbie','Williams','England','music'),
   ('Hulk','Hogan','USA','entertainment'),
   ('Mister','T','USA','entertainment'),
   ('Rafael','Nadal','Spain','professional athlete'),
   ('Paul','Haver','Belgium','music'),
]
columns = ["firstname", "lastname", "country", "category"]
df = spark.createDataFrame(data=data, schema = columns)
df.write.format("delta").mode("overwrite").partitionBy("category", "country").save(f"s3://bucket/test/famous_people")
df.show()
```
2. Import Delta table created in previous step into a lakeFS repo
3. Export this Delta table via Hook
4. Read exported Delta table directly from S3 (where 66857e is commit_id)
```
df = spark.read.format("delta").load(f"s3://repo-bucket/repo-name/_lakefs/exported/main/66857e/famous_people")
df.show()
```
I get following error:
```
Caused by: java.net.URISyntaxException: Illegal character in path at index 52: s3://bucket/test/famous_people/category=professional athlete/country=Spain/part-00003-a8056a9b-483f-48c3-bfdb-2e4a87d7da74.c000.snappy.parquet
```

### lakeFS version

1.9.1

### How lakeFS is installed

lakeFS Cloud

### Affected clients

Python lakefs==0.2.1

### Contact details

amit.kesarwani@treeverse.io

**Comment by N-o-Z** [comment]
Root cause is addition of query_unescape on path in https://github.com/treeverse/lakeFS/pull/7204
I need @Jonathan-Rosenberg for context on why this was added, maybe @guy-har has some insight
