### ISSUE TITLE
Bug: Escape path on imported objects

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7474]
We're missing path escaping when writing object entry during import process.
This resulted in: https://github.com/treeverse/lakeFS/issues/7460

Fix:
Add path escaping to the `Address` in this function in `walk_entry_iterator.go`:
```golang
func objectStoreEntryToEntryRecord(e block.ObjectStoreEntry, path string) EntryRecord {
	return EntryRecord{
		Path: Path(path),
		Entry: &Entry{
			Address:      e.Address,
			LastModified: timestamppb.New(e.Mtime),
			Size:         e.Size,
			ETag:         e.ETag,
			AddressType:  Entry_FULL,
		},
	}
}
```

**Comment by itaiad200** [comment]
We don't escape paths in lakeFS system regardless of import. #7460 root cause was the failure to escape the paths when they are written to delta log, or unescape when they are read from it.
