### ISSUE TITLE
Improving the styling for the FAQ section

### ISSUE THREAD

**Issue by ymrmmm** [treeverse/lakeFS#749]
In the current design, the Questions and Answers share the same styling which is not having a good User experience.
Some suggestions:
* Making the text of the questions bold.
* Changing the font of the questions or answers.
* Making a separation between two questions.

Please provide more suggestions if any.

![image](https://user-images.githubusercontent.com/61229047/94894518-24e57880-04a7-11eb-9ab6-8a7c0be27fa2.png)

**Comment by ymrmmm** [comment]
I am interested in working on this.

**Comment by YaelRiv** [comment]
Thanks for suggestion @ymrmmm! We will stick with the original.
