### ISSUE TITLE
Add a Compaction Sensor

### ISSUE THREAD

**Issue by Isan-Rivkin** [treeverse/lakeFS#7497]
See design #7442

**D.O.D**

We have a sensor that triggers a callback due to number of deletions.

**The sensor** 

- It will count deleted entries and trigger a callback based on a threshold number. 
- Deleted entires should count only if they required a [tombstone](https://github.com/treeverse/lakeFS/blob/master/pkg/graveler/graveler.go#L1855). 
- The sensor should be updated by push from `graveler` whenever Delete / DeleteBatch operations are called. The counter should be increased. e.g graveler will call `sensor.UpdateDeletion()`. 
- A compromise on the counter correctness: The sensor will not be updated if the same file will be added to the staging area after it was removed. This will simplify the implementation and should not trigger false compactions because the threshold should be a larger number (i.e 1000 deletions). 

**The sensor callback v1 - stats (implement now):** 
- The sensor callback should be called once the threshold is met (i.e new 1000 tombstones) and decide what action to take based on that. 
- Before we have the compactor implemented we can start with a stats callback before the compaction is ready that will only log stats. 

**The sensor callback v2 - call compaction (implement in another task) :** 
- The callback should be responsible for validating with KV if the compactor should run, run it and update once it's finished. 
- Before deciding to compact it it will check if branch's `CompactionStartTime` is not within the last x<TBD> minutes using and potentially some `CoolDownTimeStamp`.
- The callback shouldn’t do any compaction logic it should only call compact, the decision to compact or not will be done by the compaction method, to avoid implementing this in many places, e.g compaction API endpoint. The callback will probably need to know how to handle ErrTooEarly (or something like that) returned from the compaction method

**Implementation considerations / questions**
- Thread safety: Should the updates in the sensor be via a channel? 
- The counter: Should it be Atomic (if not using channels)? 
- Sensor reset: When should we reset the counter incase of a successful commit / compaction?

**Comment by Isan-Rivkin** [comment]
@guy-har please take a look.

**Comment by itaiad200** [comment]
Looks good. I didn't see a reference to 2 important characteristics of the Sensor:
1. It is per branch.
2. Replications. Do we have a single instance for each lakeFS replica? How do they keep track of the changes seperately?
