### ISSUE TITLE
BUG: lakeFSFS creates directory markers even when path is not empty on delete

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7509]

**Comment by itaiad200** [comment]
Why is this a bug? It creates an empty directory marker if it doesn't exist. It saves a listing operation for each call, when multiplied by the number of calls this could really add up. Moreover, empty directory markers are often a way to synchronize multiple writers/readers, are you sure you're not effecting any flow?

**Comment by N-o-Z** [comment]
> Why is this a bug? It creates an empty directory marker if it doesn't exist. It saves a listing operation for each call, when multiplied by the number of calls this could really add up. Moreover, empty directory markers are often a way to synchronize multiple writers/readers, are you sure you're not effecting any flow?

The directory marker is used to keep the directory when we removed all the objects from it.
In case the directory is not empty after the delete operation there's no need to create a marker since it still exists.
This does not change any existing behavior

**Comment by itaiad200** [comment]
It does add a listing operation for each call, that's my concern.
