### ISSUE TITLE
Verify SSL False not applying - Python SDK

### ISSUE THREAD

**Issue by ion-elgreco** [treeverse/lakeFS#7513]
### What happened?

At the moment I need to use Lakefs with SSL verification disabled, however this does not seem to work:

 ```python
import lakefs
 from lakefs.client import Client
 
 clt = Client(
     host="http://localhost:8000",
     username="",
     password="",
 )
 clt.config.verify_ssl= False
 
 repo = lakefs.Repository("example-repo", client=clt).create(storage_namespace="s3://storage-bucket/repos/example-repo")
 
```

For some reason it's still trying to verify SSL but since the compute I am using doesn't have the root certificate yet, it will fail

### lakeFS version

1.12

### Affected clients

Latest high level python sdk

**Comment by ion-elgreco** [comment]
This is the error:

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<redacted>', port=443): Max retries exceeded with url: /api/v1/repositories/bronze/branches (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))`

**Comment by N-o-Z** [comment]
@ion-elgreco Found the issue - I'll send a PR for a fix today
