### ISSUE TITLE
merge_into ignore when no changes

### ISSUE THREAD

**Issue by sverbruggen** [treeverse/lakeFS#7528]
In the merge_into method defined in [lakeFS](https://github.com/treeverse/lakeFS/tree/master)/[clients](https://github.com/treeverse/lakeFS/tree/master/clients)/[python-wrapper](https://github.com/treeverse/lakeFS/tree/master/clients/python-wrapper)/[lakefs](https://github.com/treeverse/lakeFS/tree/master/clients/python-wrapper/lakefs)
/reference.py please add a parameter that will ignore the merge if there are no changes. As it is, the merge will fail with a bad request error.

**Comment by itaigilo** [comment]
Will be solved in a more general manner, by issue #7797.

**Comment by sverbruggen** [comment]
@itaigilo yes that's great, thank you!
