### ISSUE TITLE
Example of how to deploy lakeFS to Google App Engine Standard if possible.

### ISSUE THREAD

**Issue by jarrodhroberson** [treeverse/lakeFS#753]
I am trying to figure out if it is even possible to deploy this to Google App Engine Standard.

This is a great abstraction layer over Google Cloud Store. If it can be deployed as part of my application instead of a Docker container it would be perfect.

If it is possible, can someone add how to do it to the "deployment" documentation?

**Comment by upedd** [comment]
Maybe I could do it?

**Comment by arielshaqed** [comment]
> Maybe I could do it?

Please do!  I am not particularly familiar with AppEngine, I had no idea you could run your own servers inside it.

**Comment by avats-dev** [comment]
@jarrodhroberson I can do this for Google compute engine, I've not used app engine much that's why. What do you think?

**Comment by itaiad200** [comment]
We have a working documented solution with Google compute engine and GKE. Closing this one until more information is provided for the need of app engine as well.
