### ISSUE TITLE
[Bug]: diff generator empty even when there are committed changes

### ISSUE THREAD

**Issue by sverbruggen** [treeverse/lakeFS#7534]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Created a branch in LakeFS
2. Wrote and committed changes to it which can be seen on the branch in the GUI
3. Called 
```
repository.branch(step_branch_name).diff(
                    source_branch_name
                ).__next__()
```
4. Received StopIteration exception indicating an empty generator

### Expected behavior

Expected the generator to not be empty

### lakeFS version

1.12.0

### How lakeFS is installed

locally & in docker

### Affected clients

 lakefs==0.4.1 lakefs-sdk==1.12.1

### Contact details

stefan.verbruggen@asml.com

**Comment by itaiad200** [comment]
Hey @sverbruggen - I think the first branch is the destination and the second is the source. So trying to merge `source_branch_name ` into `step_branch_name ` should yield no results. Could you try switching the two and see if there are the changes are apparent?

**Comment by sverbruggen** [comment]
Hi there, thanks for the quick help. You were right, I had simply put them in the wrong order, and it works now! Sorry for the bother.

**Comment by itaiad200** [comment]
No worries, happy to help
