### ISSUE TITLE
abortPresignMultipartUpload uses unsupported HTTP method starting with OpenAPI 3.1

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#7538]
Starting with OpenAPI 3.1 apparently, we are no longer allowed to use the HTTP DELETE verb with a body.  (Apparently GET with a body is also right out...).

Fortunately this API is still experimental.  So I suppose we will have to change it to be a PUT method.  Better sooner than later - once it moves out of "experimental", we will have to support it until at least 2.0!

Discovered as part of #7493.

[3.1-no-delete-body]:  https://github.com/swagger-api/swagger-ui/issues/4425#issuecomment-440478854

**Comment by N-o-Z** [comment]
@arielshaqed I'm wondering what's the advantage of changing it into a `PUT` rather than passing the "body" (physical_address) in the query params?

**Comment by arielshaqed** [comment]
> @arielshaqed I'm wondering what's the advantage of changing it into a `PUT` rather than passing the "body" (physical_address) in the query params?

You're right, I completely misunderstood "physical_address" and therefore _assumed_ that it was repeated.  (Hint: it's an S3 upload_id for the entire multipart upload, not a physical address of any kind; probably named "physical" to indicate that this is _not_ the lakeFS upload ID!)  I am not sure why it is in the body.

This does not change b/c considerations AFAICT.

**Comment by Jonathan-Rosenberg** [comment]
Could you specify where you found the source for this issue?
The comment you've referred to is from 2018, and reading the spec of [OpenAPI 3.1](https://spec.openapis.org/oas/v3.1.0#operation-object), it's mentioned that:

> The request body applicable for this operation. The requestBody is fully supported in HTTP methods where the HTTP 1.1 specification [[RFC7231](https://spec.openapis.org/oas/v3.1.0#bib-RFC7231)] has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague (such as [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1), [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2) and [DELETE](https://tools.ietf.org/html/rfc7231#section-4.3.5)), requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible.

So should be avoided, yet supported?

**Comment by Jonathan-Rosenberg** [comment]
Closing the issue since the problem wan't with the DELETE request's body but rather with the templates location that has changed between the versions.
This [draft PR](https://github.com/treeverse/lakeFS/pull/7532) includes the correct template location, and it will be merged as part of it.
