### ISSUE TITLE
Valid Apple developer ID for Notarization our macOS binaries 

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#755]
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution#3087722

**Comment by ozkatz** [comment]
is this a dupe of #439 ? if so, @nopcoder can we close?

**Comment by nopcoder** [comment]
> is this a dupe of #439 ? if so, @nopcoder can we close?

yes, closing.

Duplicate of #439
