### ISSUE TITLE
Azure Databricks Unity Catalog Integration issue: how to config SQL Warehouse to store blob Storage Account Key

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#7552]
### What happened?

Got following error when reading data from Delta table via Unity Catalog:
Your request failed with status FAILED: [BAD_REQUEST] Error while reading file abfss:REDACTED_LOCAL_PART@lakefsdemo.dfs.core.windows.net/unity-catalog-demo/data/ghejp7gqhgls73dj1q7g/cnosqvgqhgls73dj1qn0. shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.contracts.exceptions.KeyProviderException

Added following configuration in Compute cluster to resolve the issue:
spark.hadoop.fs.azure.account.key.<storage account name>.dfs.core.windows.net <storage account key>

How do I add this configuration to SQL Warehouse so SQL to select data from Delta table will work?

### Contact details

amit.kesarwani@treeverse.io

**Comment by itaiad200** [comment]
@kesarwam , per @N-o-Z this is not lakeFS related (more like a general Azure Databricks thing), right?

**Comment by kesarwam** [comment]
Right, this is for tracking purpose only.
