### ISSUE TITLE
Delta exporter: support export of delta log files with abfss scheme to support unity catalog external tables

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7553]
While working on https://github.com/treeverse/lakeFS/issues/7551 and trying to enable unity exporter on Azure we discovered that in addition to providing the external location as an abfss scheme, we also need to export the delta logs so that the paths are format using this scheme instead of https.

We need to add a flag for the exporter, when using with Azure to decide the format in which to write the paths in the delta log when exporting from lakeFS

**Comment by ozkatz** [comment]
@N-o-Z can’t this be inferred from the storage namespace/external location?

**Comment by N-o-Z** [comment]
If we translate the path to abfss as a rule we will lose support for delta export for Azure Blob Storage accounts that are not ADLS gen2.I think we need to provide the user the option to choose how to save the paths. AFAIU abfss is a scheme supported only by [ADLS Gen2 storage accounts](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver)

**Comment by ozkatz** [comment]
so this is orthogonal to the scheme defined in the repository’s storage namespace?
