### ISSUE TITLE
Fuzzy search across repositories

### ISSUE THREAD

**Issue by dsgibbons** [treeverse/lakeFS#7596]
The search bar in the UI currently searches by exact string matches from the beginning of the repository name. Fuzzy matching would make it easier to find repositories through the UI. This is especially useful when we have hundreds of repositories.

![image](https://github.com/user-attachments/assets/02614fe8-3dcd-4da8-8276-2ec31c41409b)

Resource:
https://staging.us-east-1.lakefscloud.ninja/api/v1/repositories?prefix=nada&after=&amount=100

**Comment by hoac4** [comment]
The following search fields would also benefit from the ability to fuzzy search:
- Administration > Groups > [Select Group] > Group Memberships > Add Members > Find User
- Administration > Groups > [Select Group] > Attached Policies > Attach Policy > Find Policies

**Comment by nadavsteindler** [comment]
I'd like to sanity test this a bit in staging...

**Comment by arielshaqed** [comment]
To be explicit: We implemented _substring_ search.  We do not have current plans to perform a "fuzzy" search.
