### ISSUE TITLE
S3 GW DDB SlowDown propagation

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#7597]

**Comment by guy-har** [comment]
Issue #7685 causes lakeFS to propagate DynamoDB slowdowns by returning a 503 status when DynamoDB encounters slowdown issues. By default, lakeFS initializes the DynamoDB client with 10 retries.

During this task, I investigated the impact of reducing the retry count to 1, thereby fully propagating the slowdown without additional retries. My tests revealed that lakeFS, when configured with 10 DynamoDB retries, is significantly more efficient than with just 1 retry.

Here’s a summary of the test setup and findings:

Read a 50 MB parquet table from lakeFS.
Rewrote the table to a new path, repartitioning it into 1000 parts.
Applied stress to the lakeFS S3 gateway with varying W/RCU levels on DynamoDB (initially set at 10, also tested at 50 and 100).
The main observation was that throttling by provisioned W/RCU (as opposed to the partition's hard limit) and directly propagating this slowdown to the client noticeably decreased performance:

With 10 W/RCU, the operation lasted 04:30; it was much slower at 01:10:00 and was ultimately canceled after completing 999 of 1000 operations.
With 50 W/RCU, it took 04:00 compared to 08:00, suggesting that increasing capacity had little impact on improving response times.
