### ISSUE TITLE
Document how to use custom SSL certificate with Python SDK

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#7610]
See https://github.com/treeverse/product/issues/222

**Comment by itaiad200** [comment]
@N-o-Z can you add reference to the part of the docs where this is mentioned?

**Comment by N-o-Z** [comment]
> I can see this [here](https://docs.lakefs.io/integrations/python.html#initializing):
> 
> > Optionally, to enable communication via proxies, simply set the proxy configuration:
> > ```python
> > clt = Client(
> >     host="http://localhost:8000",
> >     username="AKIAIOSFODNN7EXAMPLE",
> >     password="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
> >     ssl_ca_cert="<path to a file of concatenated CA certificates in PEM format>",  # Set this to customize the certificate file to verify the peer
> >     proxy="<proxy server URL>",
> > )
> > ```
> 
> I will move this text outside of the context of a "proxy". OK, everyone? (@talSofer , @N-o-Z , @itaiad200 )

I'm not sure it's necessary wince we have explicit instructions on how to do it in our documentation

**Comment by itaiad200** [comment]
Closing this as Done. Feel free to open if you feel differently.

**Comment by arielshaqed** [comment]
I also opened #7652 that cleans this up.  @itaiad200 would you prefer that I re-open this and pull that, or shall I just close it?

**Comment by N-o-Z** [comment]
> I also opened #7652 that cleans this up. @itaiad200 would you prefer that I re-open this and pull that, or shall I just close it?

I think the improvement you did is with adding
