### ISSUE TITLE
[UI] Onboarding "service" slows down main screen until everything is set up

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#7674]
[Seen at a user installation]

The repo onboarding service _always_ looks for:
- GC configuration, by fetching settings/gc_rules
- Branch protection, by fetching settings/branch_protection
- Hooks, by listing `_lakefs_actions/`
- The lakefs.parquet object, to determine whether this is a sample repo

This slows everything down in the GUI until the user has "completed" onboarding.  Given that sopme users do not need GC rules or actions, they will always pay for it in the GUI.  The user never actually sees this, it's hidden behind the "Start here" panel.  I don't know how often this is actually used.

* settings/gc_rules is _additionally_ called to show the "No garbage collection rules configured" warning panel.  So it is loaded _again_ per page, but this one appears to be cached by repo ID.  The steps are not really 
* settings/branch_protection also ends up being loaded _twice_ per page, not sure why.

Anyway this slows down everything in the GUI.

**Comment by talSofer** [comment]
I opened https://github.com/treeverse/lakeFS/issues/7691 to remove the progress bar

**Comment by eladlachmi** [comment]
This UI feature has been removed.
