### ISSUE TITLE
[Bug]: `lakectl local commit` commits staged changes outside of its directory

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#7687]
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Ensure lakefs://repo/main is _dirty_ but has no "directory" path `xyzzy`.
1. `lakectl local init lakefs://repo/main/xyzzy`
1. `touch x`
1. `lakectl local commit --message 'add xyzzy for lulz'`
1. `lakectl diff lakefs://repo/main{~,}`:

   ```
   Left ref: lakefs://ariels-repo/main~
   Right ref: lakefs://ariels-repo/main
   + added .hidden-foo
   + added foofoo
   + added xyzzy/x
   ```

These 2 files were added by `lakectl local` because _I added them elsewhere_.

### Expected behavior

`lakectl commit` should fail with an error about the branch being dirty, or lakectl should be more like Git LFS and not hide changes from me.

**Comment by N-o-Z** [comment]
Requires @treeverse/product specification

**Comment by talSofer** [comment]
### Expected behavior 

* Fail the commit
* Print an error message: 
```bash
error: The branch you are trying to commit to contains uncommitted changes outside the lakeFS path your local directory '<DIR_NAME>' is synced with.
To proceed, use the --force option.
```
* add a --force -f flag lakectl local commit

**Comment by N-o-Z** [comment]
@eladlachmi @arielshaqed @talSofer making sure we understand the implications of this since it is a breaking change.
