### ISSUE TITLE
[webui] Investigate removing Redux in favour of React contexts and hooks

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#771]
I wondered about using your async reducer, but because I believe that since React 16.3 (and the arrival of Context API) redux is not necessary and is actually just overheads.
However, some store mechanism should be used since the entire app might need the config. If you want me to rewrite with a 
context I'd be happy to. It'll take about 5 minutes and will be much neater. Just tell me what you prefer

_Originally posted by @eylonronen in https://github.com/treeverse/lakeFS/pull/751#issuecomment-703215962_

**Comment by arielshaqed** [comment]
@nopcoder @ozkatz @johnnyaug do we want to try to drop Redux?

**Comment by ozkatz** [comment]
my 2 cents on this: I'd rather not support both hooks/context and redux going forward. If we decide to move from Redux to something else, by all means let's do it - but the definition of done should be a complete migration from one to the other.

If that's the case, I'm OK with it, even if it takes a while to complete - we'll need to add it to our roadmap as a low priority item to make that clear.

**Comment by nopcoder** [comment]
Also in favor to reduce complexity

**Comment by ozkatz** [comment]
Closed by #1766 - Moved to context and hooks
