### ISSUE TITLE
Add duckdb_delta to LakeFS duckdb wasm

### ISSUE THREAD

**Issue by ion-elgreco** [treeverse/lakeFS#7771]
Being able to read deltalake directly in LakeFS with duckdb wasm would be awesome, recently this extension got released 

https://github.com/duckdb/duckdb_delta

**Comment by ozkatz** [comment]
Currently DuckDB is being used to explore the contents of a file. 
There's no planned support to allow querying whole tables/datasets through the lakeFS UI.
