### ISSUE TITLE
Underscores in variable names stored as metadata

### ISSUE THREAD

**Issue by offirc2** [treeverse/lakeFS#7782]
### What happened?

I managed to create a Minimal Working Example of the Error. While creating it the error appeared as soon as I used the actual Metadata from our internal script (thus I include it in the mwe), before that the metadata was uploaded correctly, when using different information.

Upon investigation, we’ve identified that the issue lies with underscores in variable names stored as metadata. Currently, this results in silent failures during storage, processing, and display—something we’d like to avoid. We hope a fix for this issue rather than having to modify the variable names in our code.

[mwe.txt](https://github.com/treeverse/lakeFS/files/15376050/mwe.txt)

### Contact details

sebastian.haugg@gi-de.com

**Comment by N-o-Z** [comment]
Closing this issue as this seems like an environment issue
