### ISSUE TITLE
[Bug]: Add to group screen doesn't display user's friendly names

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#7861]
### What happened?

When trying to add users to a group using the UI, the Add To Group screen displays the user's IDs instead of the user's friendly name.
![image](https://github.com/treeverse/lakeFS/assets/43949240/d2dfb4c2-8fb8-4bf9-8ba2-5412db04e28c)

### lakeFS version

1.25.0

**Comment by talSofer** [comment]
duplicate of https://github.com/treeverse/product/issues/373
