### ISSUE TITLE
Update everest mount docs

### ISSUE THREAD

**Issue by Isan-Rivkin** [treeverse/lakeFS#7888]
- Update `--presign true` is now the default 
- Add F&Q about `.gitignore`
Closes #7888

**Comment by Isan-Rivkin** [comment]
@talSofer I have no idea how to remove the issue from "product backlog" in projects 👀

**Comment by ozkatz** [comment]
so this means that presign is enabled by default but only when the server supports it? (i.e. will gracefully use non-presigned mode when deployed on non supporting storage)?

**Comment by Isan-Rivkin** [comment]
@ozkatz 

> only when the server supports it?

No, that's a very good point I missed that functionality of "checking if its supported" - I'll update everest to fetch dynamically  and ping you again!
