### ISSUE TITLE
Reference page having height issues

### ISSUE THREAD

**Issue by ymrmmm** [treeverse/lakeFS#793]
On the API reference page, when collapsing the sections (setup, auth, etc) the height of the page remains the same when the sections are expanded and thus having a big empty space between the footer and the main content.

![image](https://user-images.githubusercontent.com/61229047/95652698-91e4b800-0b10-11eb-941d-78b34ef94020.png)

Click on the arrows for collapsing the section.

Go to the bottom of the page and see the effect (the empty space)

**Comment by ymrmmm** [comment]
I am interested in working on this.

**Comment by arielshaqed** [comment]
> I am interested in working on this.

Ouch, thanks for picking that up, that's really painful!  Please do -- I'm gladly assigning to you.

**Comment by arielshaqed** [comment]
Verified page on website.  Looks great.

Thanks, @ymrmmm , for opening this issue!
