### ISSUE TITLE
[Bug]: S3 Copy doesn't allow overwrite user metadata

### ISSUE THREAD

**Issue by itaigilo** [treeverse/lakeFS#8070]
### What happened?

Using the S3 Gateway to copy an object doesn't copy the user metadata.
     
Steps to Reproduce:
1. Upload an object without metadata.
2. Copy the object to the same exact location, passing the metadata headers.
3. Metadata does not show up on the object.

### Expected behavior

Metadata should show up on the object.

### lakeFS version

1.31.1

**Comment by DnOberon** [comment]
I need to clarify this a little, or add my use case.

Steps to reproduce:

1. Upload an object _without_ metadata
2. Copy the object to the same exact location, passing the metadata headers
3. Metadata does not show up on object.

**Comment by itaigilo** [comment]
> I need to clarify this a little, or add my use case.
> 
> Steps to reproduce:
> 
> 1. Upload an object _without_ metadata
> 2. Copy the object to the same exact location, passing the metadata headers
> 3. Metadata does not show up on object.

@DnOberon Thanks for clarifying!

Updated the issue's description.

**Comment by offirc2** [comment]
@talSofer Where does this stand?
