### ISSUE TITLE
Default storage namespace

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#808]
I want to be able to start lakeFS with a "default storage namespace", where the data for new repositories will be stored by default. This will be provided through the lakeFS configuration.

In the UI, when creating a repo, the default storage namespace will be entered in the create dialog.

In the CLI, the repo will be created under the default namespace unless a namespace flag is explicitly provided.

Note that the storage namespace is still part of the repository once it is created. If tomorrow someone starts lakeFS with a different default storage namespace, a previously created repository should still point to the storage namespace it was created with.

Consider adding a suffix of "<REPO_NAME>/" to the default namespace for each repository.

**Comment by shamikakumar** [comment]
is this issue open to work on ?

**Comment by johnnyaug** [comment]
Yes, you are welcome to work on it.

**Comment by shamikakumar** [comment]
sorry for the real late response, I'm not familiar with Go, and I see this requires some changes there. I think I'm going to pass this up and pick up other UI issues that I'd be more comfortable with, thanks anyway!
