### ISSUE TITLE
Basic Authentication in Reverse Proxy before LakeFS Auth

### ISSUE THREAD

**Issue by lgcCerti** [treeverse/lakeFS#8085]
Hello, the following is the enterprise architecture suggestion for LakeFS:

![image](https://github.com/user-attachments/assets/c8d5a341-4626-4e78-996c-75a1bf24a794)

If we were to add basic authentication to the reverse proxy, would the current LakeFS client support headers for authenticating on both the proxy and the API Server? I have not managed to find a solution that doesn't hack the library open.

Thanks.

**Comment by iddoavn** [comment]
Thank you so much for your question Since this is a lakeFS Enterprise question, GitHub is not the right channel. 

Feel free to contact us at [hello@treeverse.io](mailto:hello@treeverse.io) of with your Customer Success representative.

**Comment by lgcCerti** [comment]
> Thank you so much for your question Since this is a lakeFS Enterprise question, GitHub is not the right channel.
> 
> Feel free to contact us at [hello@treeverse.io](mailto:hello@treeverse.io) of with your Customer Success representative.

In that regard I may have worded it poorly; this is not about the enterprise, I just used the diagram as an example.

As far as I'm aware, the only enterprise related object in that diagram is Fluffy, otherwise this issue question pertains architecture for any LakeFS deployment.

**Comment by lgcCerti** [comment]
@iddoavn I believe this was closed prematurely, please consider reopening.

**Comment by itaiad200** [comment]
Hey @lgcCerti, could you share a bit more about your use case? What exactly are you trying to achieve with dual authentication?

**Comment by lgcCerti** [comment]
> Hey @lgcCerti, could you share a bit more about your use case? What exactly are you trying to achieve with dual authentication?

Hello. Currently it'd be a reverse proxy that requires authentication to use (thus handles any and all garbage that may bother an application server) before lakeFS can be authenticated to.

I see lakeFS uses urllib3 and sets the header directly which coincidentally enables it to authenticate with one such proxy through basic auth. However, it will not manage to retrieve a token and thus fail to use the API server itself; the only solution so far is to make the proxy either unsecure and forward directly to the lakeFS server (which could be troublesome) or allow only some fixed IPs to take it.

This issue is more of a question than a feature request. I have not found a native way to go through protected reverse proxies using the library.

**Comment by itaiad200** [comment]
So to make sure I understand correctly, your concern is with DDOS attacks on lakeFS servers?

**Comment by lgcCerti** [comment]
> So to make sure I understand correctly, your concern is with DDOS attacks on lakeFS servers?

A crude form of defense for a self-hosted instance, yes. Additionally, it also hides what the application is and a potential troublemaker won't know what the application behind the proxy is.

**Comment by itaiad200** [comment]
Got it. So indeed it's less of an Enterprise question or a lakeFS question tbh. lakeFS doesn't have anything builtin for this case, I don't think it really needs to. Whichever proxy you use, there should be a way to limit traffic by ip range or VPCs, alter http response by status code (for example, 403 body should be empty and with no response headers), etc. 
lakeFS will continue to ignore request headers that it's not familiar with and respect those with lakeFS context, authentication wise or anything else.

I'm closing this for now, let me know if you feel this is something specific to lakeFS that we should address.
