### ISSUE TITLE
Docs: Python integration doc needs update

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#8095]
[https://docs.lakefs.io/integrations/python.html](https://docs.lakefs.io/integrations/python.html#upload)

Due to code changes, we need to go over the guide and update the code snippets.
One example:

```
branch1 = lakefs.repository("example-repo").branch("experiment1").create(source_reference_id="main")
```

For branch creation parameter name was changed from `source_reference_id` to `source_reference`.

**Comment by ozkatz** [comment]
closed by @N-o-Z in https://github.com/treeverse/lakeFS/pull/8273
