### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [treeverse/lakeFS#811]
@nopcoder / @arielshaqed 

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

I would like to work on this issue.

**Comment by arielshaqed** [comment]
Hi @ng29 ,

Thanks for suggesting to improve our documentation!  Not sure whether you mean the README or the proper docs.  The former I think is a bit too short to need a ToC, the latter actually gets a really nice ToC when you read it on https://lakefs.io.

@YaelRiv do we have any user request to improve navigation on either of these?

Will close on Wednesday if I hear nothing.

**Comment by ng29** [comment]
> Hi @ng29 ,
> 
> Thanks for suggesting to improve our documentation! Not sure whether you mean the README or the proper docs. The former I think is a bit too short to need a ToC, the latter actually gets a really nice ToC when you read it on https://lakefs.io.
> 
> @YaelRiv do we have any user request to improve navigation on either of these?
> 
> Will close on Wednesday if I hear nothing.

Yes i was talking about readme as it helps the user to hop into the information easily and avoids unnecessary scrolling.
