### ISSUE TITLE
Circular dependency between fluffy and lakeFS

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#8123]
Using fluffy as the auth service for lakeFS CI testing creates a circular dependency.
Since Hagrid is also using lakeFS to run fluffy tests, we find ourselves in a situation that we must break one service in order to perform breaking changes in either one

**Comment by arielshaqed** [comment]
Ouch, sorry, I opened a dupe as #8128!  I'm closing this one in favour of that one, because that one is longer 🤷🏽 .
