### ISSUE TITLE
BUG: Catalog CreateBranch uses store.GetTag to verify branch exists

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#8188]

**Comment by itaiad200** [comment]
What happens if a tag and a branch have the same name?
I believe we do that do avoid inconsistent reference.

**Comment by N-o-Z** [comment]
I see - so we might want to document it so there will be no future confusion

**Comment by N-o-Z** [comment]
@itaiad200 why did we close it?
