### ISSUE TITLE
Cancel legacy Java SDK client api-client

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#8193]
## What

1. [x] Publish the next release of io.lakefs:api-client with a changed
   description.  Instead of "lakeFS OpenAPI Java client legacy SDK", state
   "[EOL] Do NOT use: lakeFS OpenAPI Java client legacy SDK". (#8368)
1. [x] Remove support from the lakeFS and stop publishing new versions of
   io.lakefs:api-client. (#8389)

## Why

This is the pre-1.0 Java SDK.  It shows very low usage.  Indeed, the [code
migration guide][java-code-migration] mistakenly says that this is the
`io.lakefs:lakefs-client` package.  In fact it is `io.lakefs:api-client`.
We have seen no complaints even about this.

Supporting this legacy implementation requires some real work.  In
particular, we do not want to upgrade the OpenAPI release we use to build
this client, and it has occasional low-threat CVEs.  I would rather dedicate
this work to tasks that bring real value to users and to customers.

[java-code-migration]:  https://docs.lakefs.io/project/code-migrate-1.0-sdk.html#migrating-sdk-code-for-java-and-jvm-based-languages

**Comment by yonipeleg33** [comment]
> Remove support from the lakeFS and stop publishing new versions of
io.lakefs:api-client.

@arielshaqed can you please elaborate on what that means technically? Should we remove the source code / just the maven package from the maven repository...?

**Comment by arielshaqed** [comment]
- WAIT until we finish verifying that  we can actually remove support.
- Remove `clients/java-legacy` from source code and from Makefile, build processes, etc.
- Do _**NOT**_ remove the Maven package from the repository - it did nothing wrong!

I believe that we do not need to publish something like [this announcement](https://docs.lakefs.io/posts/deprecate-py-legacy.html) for the legacy Java client.
- It is barely used.
- We marked it deprecated around 1.0.
