### ISSUE TITLE
Cancel legacy Python SDK client lakefs-client

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#8194]
## What

1. [ ] Publish the next release of lakefs-client with a changed description.
	   Instead of "lakeFS HTTP API", state somewhere "[EOL] Do NOT use:
	   lakeFS OpenAPI Python client legacy SDK", and refer to the [code
	   migration guide] [python-code-migration] guide.
1. [ ] Wait for a while.  Longer than #8193 (Java) - this change is
       currently not well publicized on PyPI.
1. [ ] Remove support from the lakeFS and stop publishing new versions of
	   lakefs-client.

## When

This is the pre-1.0 Python SDK.  We _did_ state to use it in [lakeFS SDK in
1.0][lakefs-towards-1.0], but updating the generated client proved more
difficult -- and I cannot find an indication on PyPI that clearly states to
prefer lakefs-sdk.  We do see some real usage of these clients.  Some of
these may be due to higher-level packages, of course.  So this change will
require a longer lead time after announcing that #8193.

I would like to publish the changed description shortly in a next release of
lakeFS, so that we can kick off this process.

## Why

Supporting this legacy implementation requires some real work.  In
particular, we do not want to upgrade the OpenAPI release we use to build
this client, and it has occasional low-threat CVEs.  I would rather dedicate
this work to tasks that bring real value to users and to customers.

[python-code-migration]: https://docs.lakefs.io/project/code-migrate-1.0-sdk.html#migrating-sdk-code-for-python
[lakefs-towards-1.0]:  https://docs.lakefs.io/understand/towards-1.0-sdk.html

**Comment by AhmadMahmoodRana** [comment]
install this

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by AbdullahSK03** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by kesarwam** [comment]
Our Kubeflow integration page still uses legacy Python client: https://docs.lakefs.io/integrations/kubeflow.html
It should be updated.
