### ISSUE TITLE
[UI] Allow to tag a specific Commit and not only the head of the branch

### ISSUE THREAD

**Issue by mickaellcr** [treeverse/lakeFS#8199]
Hello everyone!

From the UI we can only TAG the last commit of a branch. It will be nice to
* tag an old commit either from the search bar of the Tag windows, 
* or when we go to the Commits tab, having a Tag button next to the other quick action
* or when we are inside a specific commit

Why? Sometimes we missed the opportunity to tag the right commit and from the UI it's not possible to go back in time.

Do you think it's possible?

Thank you very much!

**Comment by talSofer** [comment]
Hi @mickaellcr! This feature is supported in lakeFS 
If you click the arrow highlighted in the following screenshot, you can pick the commit you'd like to create the tag from 
![Image](https://github.com/user-attachments/assets/60026b78-2e9e-42d6-b78b-8efa31dea1bc)
