### ISSUE TITLE
There is no lakectl command to check current user

### ISSUE THREAD

**Issue by nadavsteindler** [treeverse/lakeFS#8313]
This is an API that we lack that @arielshaqed suggested- both he and I ran into this missing functionality

### Story
Basically, when you run lakectl, it looks at your access key and determines what user you are based on that. That user's authorization policies are applied. It is very common that users make a mistake and specify the wrong access key and it takes a lot of effort to debug.

### Feature Request
It would be nice if we had a lakectl command. Something similar perhaps to https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sts/get-caller-identity.html

**Comment by arielshaqed** [comment]
AWS have this (never mind the UX),  e.g.
```sh
❯ aws sts get-caller-identity
```
```json
{
    "UserId": "AROAR3RFY3EGTFAMROWCR:ariels@treeverse.io",
    "Account": "127854500109",
    "Arn": "arn:aws:sts::127854500109:assumed-role/JumpCloudDeveloper/ariels@treeverse.io"
}
```
