### ISSUE TITLE
Wrong UI error when repo name contains underscore (on repo creation)

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#833]

**Comment by Sufiyan1997** [comment]
@itaiad200 I would like to work on this.

**Comment by itaiad200** [comment]
@Sufiyan1997 assigned. Feel free to reach out on slack if you need any help.

**Comment by Sufiyan1997** [comment]
Do I need to change the regex to allow underscores in repository names or just change the error message?

**Comment by itaiad200** [comment]
Underscores should not be allowed. We should validate the repo name in the UI and display a proper error message before sending the request to the server.

**Comment by Sufiyan1997** [comment]
I have added client side validation for all 3 fields while creating repository.
Are this validation messages and UI correct?
![Screenshot_2020-10-27 lakeFS App](https://user-images.githubusercontent.com/22118049/97331621-97c3f280-189f-11eb-8fd1-a79d692be32e.png)

**Comment by itaiad200** [comment]
Almost :) It's easiest to point you to the validation on the server side to avoid mismatches.
1. Swagger file: https://github.com/treeverse/lakeFS/blob/00d3eb2f03b5a20f6ed6a6439820049e4b7e5907/swagger.yml#L86

2. On the actual creation: https://github.com/treeverse/lakeFS/blob/00d3eb2f03b5a20f6ed6a6439820049e4b7e5907/catalog/cataloger_create_repository.go#L17

Let me know if something is unclear.
