### ISSUE TITLE
Commits tab should allow committing files

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#834]
Or at least link to the 'Objects' tab where you can commit.

**Comment by jolo-dev** [comment]
Hi @itaiad200,

Maybe I can support this.
But I would like to clarify the workflow:

* User clicks on the "commit tabs"
* User clicks on a button "commit" but only when changes
* Modal windows pop-ups
* User types commit message

Is it similar to the "changes" tab?

**Comment by itaiad200** [comment]
Hey @jolo-dev. I think it can be simpler than that.

- User clicks on "Commits" tab.
- If there are any uncommitted changes, a text line (highlighted green) will appear between the branch drop-down list and the commits list.
- The line will say something like "There are uncommitted changes for branch [branch-name]. You can commit them in the [Link Changes-Tab]"

**Comment by jolo-dev** [comment]
Hi @itaiad200 
Thanks for your reply.
I will give it a shot and in case of having troubles, I'll let you know.
