### ISSUE TITLE
When uploading file, the path in the repo should be visible

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#835]
It currently contains just the file name. It's not clear that it's reachable under repo and branch, and that you can edit the file path.

**Comment by yashinde** [comment]
can I explain more?

**Comment by itaiad200** [comment]
Sure - When you upload an object, you always upload it under a specific branch.
The path under that branch is editable. In the example below, we upload "dump" file, but it would be reachable under "<Bucket_path>/<branch>/dump". The UI should reflect the entire path while keeping just the last part editable.

![image](https://user-images.githubusercontent.com/9861474/96477017-ae829d80-123e-11eb-9d03-f03bcd358b68.png)

**Comment by shamikakumar** [comment]
Hey I'd like to take this up..could you assign this to me

**Comment by itaiad200** [comment]
@shamikakumar It's yours. Feel free to join our slack and ask for clarifications if necessary.
