### ISSUE TITLE
Enhance stats, repository identifier 

### ISSUE THREAD

**Issue by ItamarYuran** [treeverse/lakeFS#8442]
Currently, the oss stats that are received by callhome (event scheme) do not contain repository identifier.
Those stats can be extremely helpful for some cases, and provide useful information about our installations behavior.
For cloud installation, this information does exist.
There is of course no need for the repo's name, but a unique identifier could be very helpful.

**Comment by itaiad200** [comment]
We won't add this to the OSS.
