### ISSUE TITLE
[BI] Exclude Katacoda stats from dashboard and queries in redash

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#849]
all Katacoda stats are sent from a fixed installation ID 
`781ce7c6-ebe0-42a8-b558-be780251b83a`
connected to company `katacoda`

we need to exclude that data from all dashboards and queries.

**Comment by johnnyaug** [comment]
I see this installation id still appears in: downloads graph, MAU/WAU/DAU graph, and also appears as a trial from time to time.
