### ISSUE TITLE
Docker Build Failing

### ISSUE THREAD

**Issue by kaushalag29** [treeverse/lakeFS#853]
Steps to Reproduce:
1. Go to lakeFS Dir
2. Run `docker build --tag lakefs:1.0 .`
[Failed Logs.txt](https://github.com/treeverse/lakeFS/files/5413616/Failed.Logs.txt)
[go.mod.txt](https://github.com/treeverse/lakeFS/files/5413645/go.mod.txt)
[go.sum.txt](https://github.com/treeverse/lakeFS/files/5413646/go.sum.txt)

We can try to fix docker build from clean env.

**Comment by arielshaqed** [comment]
Could you try to `make build-docker` and see if that works?  AFAIU we build most of the files *outside* of Docker, we do not have a 2-phase Dockerfile for the build (yet...).

**Comment by kaushalag29** [comment]
@arielshaqed actually we have a discussion in slack channel, we know that it will work after executing `make build` and then build docker image. But we want to have it in a single phase. People are/will face problem while setting up the environment like I faced.
