### ISSUE TITLE
optimization issue in lineage scanner

### ISSUE THREAD

**Issue by tzahij** [treeverse/lakeFS#858]
when scanning a lineage, the ancestors retrieved are filtered by the max commit the child branch is aware of.
A performance problem happens when:

1. the ancestor branch is very large (many millions)
2. The lineage defines that the child branch can not "see" the content of the ancestor branch

the branch scanner of the ancestor issues a select command to fill it's buffer with entries that fit the commit restrictions. but since the commits do not fit - it may scan GBs if index, until it reaches a not found status.
To solve this issue, we add an index by min_commit to catalog_entries. and add a condition in the branch select statement to take only entries where the min_commit fits one of the branches commit. when planning the query, the optimizer will check the number of entries with those commitIDs. and if the number is small - it will go via that index, and not scan GBs in the branch,path index.
THIS SOLUTION MAY STOP WORKING IF A BRANCH HAS MORE THAN 1000 COMMITS. IF THE NUMBER  OF ENTRIES ON THOSE 1000+ COMMITS IS SMALL COMPARED TO THE REPOSITORY - WE MAY BE BACK TO SCANNING THE INDEX.
THERE IS A REASONABLE CHANCE THIS IS A THEORETICAL PROBLEM ( 1000 COMMITS WITH FEW ENTRIES IS AN EXTREME CONDITION) BUT IT SHOULD BE CHECKED IN LARGE PRODUCTION ENVIRONMENTS.

**Comment by ozkatz** [comment]
As we're changing data model, I'm not sure we want to optimize this further. Closing for now. If you see a need, please reopen
