### ISSUE TITLE
Verify MultipartTest content match 

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#888]
We currently only upload the file and read it without asserting on content mismatch.

**Comment by Sufiyan1997** [comment]
I would like to work on this. But need more details

**Comment by itaiad200** [comment]
Hey @Sufiyan1997 - assigned it to you.
Notice [this](https://github.com/treeverse/lakeFS/blob/0f3084a0f5424dfd76880f84c0b5766c158890da/nessie/multipart_test.go#L23) test which is part of our system testing. Notice how we multipart-upload an object to lakeFS, complete the multipart upload and GETting the object. However, we do not compare the returned object with the uploaded parts. That's the part which is missing.
