### ISSUE TITLE
[parade] - add error signals

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#900]
add the option to send failures to dependent task

**Comment by arielshaqed** [comment]
I think I already added this in 08c9a5c1d, it's now a [field in OwnedTaskData](https://github.com/treeverse/lakeFS/blob/f1d3a1a39457a8dc41ad66a70b1f65649bd2b6d9/parade/ddl.go#L205).  Please reopen (with explanation) if I am wrong, and I shall add whatever is missing.

**Comment by arielshaqed** [comment]
/
