### ISSUE TITLE
[research] Publishing lakeFS to Bitnami application catalog

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#936]
Bitnami is an application catalog trusted by developers around the world. For every app, it allows the developer to install it directly on their cloud or on container-based environments like Docker / Kubernetes.

Appearing there is seen by developers as a sign of following security rules and other best practices. 

In order to appear there, we need to follow some guidelines and contact Bitnami. Research what these guidelines are and what else is necessary, and decide if it's worth the effort.

**Comment by guy-har** [comment]
Closing for now, will open again once it's relevant
