### ISSUE TITLE
Delete branch button is missing

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#956]

**Comment by shamikakumar** [comment]
I'd like to work on this issue, could I have more information..

**Comment by itaiad200** [comment]
Sure - assigned. Under the branches tab, each non-default branch should have the delete button.
After the user clicked, an approval pop-up appears which warns about the branch deletion.
When the actions is approved, a deletion request is sent.
![image](https://user-images.githubusercontent.com/9861474/100538394-32657780-3238-11eb-84a5-f2d1d12970cd.png)

**Comment by shamikakumar** [comment]
@itaiad200 I finished the UI part, where I added a delete button for the non-default branches and an approval pop up for branch deletion. However I didn't do the delete call request as I believe it requires code changes in Go that I'm not familiar with..

**Comment by itaiad200** [comment]
@shamikakumar Delete branch is already supported by the api, so no Go code changes are needed. However The call is missing from the UI, an appropriate place for it would be alongside other branch operation calls, [here](https://github.com/treeverse/lakeFS/blob/4f89db99305189b6b55026316a517d1f3f18e402/webui/src/actions/api.js#L384).

**Comment by shamikakumar** [comment]
@itaiad200 I've implemented it, do review and let me know
