### ISSUE TITLE
"Content-Type" response header should be "application/xml"

### ISSUE THREAD

**Issue by keimoon** [treeverse/lakeFS#987]
The `Content-Type` header for S3 compatible API is currently set to `text/xml charset=utf-8`. While this is fine with awscli, some strict clients like https://github.com/akka/alpakka only accepts `application/xml`. The real S3 API also returns `application/xml` so I think we should stick to that.

**Comment by arielshaqed** [comment]
Thanks!
This looks like a bug in the alpakka client.  Specifically, [RFC 7303](https://tools.ietf.org/html/rfc7303#page-21) registers both application/xml and text/xml and states that
>  The registration information for text/xml is in all respects the same
>  as that given for application/xml above (Section 9.1), except that
>  the "Type name" is "text".
Clearly this argument cuts both ways.  The incumbent `text/xml` has the advantage that it works with all our current clients; the proposed `application/xml` has the advantage that it works with another client.  I shall see what I can do.

**Comment by arielshaqed** [comment]
Here's what I can do: perform content negotiation on the [`Accept:`` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept).  So _if_ the client explicitly asks for either of `text/xml` or `application/xml` lakefs will return that type.
In order for this to work, your S3 client will need to send an appropriate header.  Is there a compiled client (hopefully CLI) that I could use on my system to capture headers and see whether that would work?
The effect on boto should be nil, it does not appear to send an `Accept` header.

**Comment by ozkatz** [comment]
Seems like S3 returns `Content-Type: application/xml` even if passing `Accept: text/xml` in the request.

**Comment by ozkatz** [comment]
@arielshaqed I think this is fixed by tge linked PR, no?

**Comment by arielshaqed** [comment]
> @arielshaqed I think this is fixed by tge linked PR, no?

No customer {dis,}approval, so I guess you're right. Closing... and can always reopen if not good.
